PandoraMonitoring: PandoraMonitoringApi Class Reference
PandoraMonitoringApi Class Reference
PandoraMonitoringApi class.
#include <PandoraMonitoringApi.h>
Public Types
typedef std::map< int, float > PdgCodeToEnergyMap
Static Public Member Functions
template<typename T >
static void SetTreeVariable (const pandora::Pandora &pandora, const std::string &treeName, const std::string &variableName, T t)
Set a variable in a tree (create the tree and the branch if not yet existing)
static void FillTree (const pandora::Pandora &pandora, const std::string &treeName)
Fill the tree with the variables which have been set before with SetTreeVariable.
static void PrintTree (const pandora::Pandora &pandora, const std::string &treeName)
Print the tree.
static void ScanTree (const pandora::Pandora &pandora, const std::string &treeName)
Scan the tree (print a list of all values of all branches)
static void SaveTree (const pandora::Pandora &pandora, const std::string &treeName, const std::string &fileName, const std::string &fileOptions)
Save the tree to a file.
template<typename T >
static void DrawPandoraHistogram (const pandora::Pandora &pandora, const T &t)
Draw a pandora histogram.
template<typename T >
static void DrawPandoraHistogram (const pandora::Pandora &pandora, const T &t, const std::string &options)
Draw a pandora histogram.
static void SetEveDisplayParameters (const pandora::Pandora &pandora, const bool showDetectors=true, const DetectorView detectorView=DETECTOR_VIEW_DEFAULT, const float transparencyThresholdE=-1.f, const float energyScaleThresholdE=-1.f, const float scalingFactor=0.1f)
Set TEve display parameters.
static void VisualizeMCParticles (const pandora::Pandora &pandora, const pandora::MCParticleList *const pMCParticleList, const std::string &name, const Color color, const PdgCodeToEnergyMap *pParticleSuppressionMap=NULL)
Add MCParticles to the Eve event-display.
static void VisualizeTracks (const pandora::Pandora &pandora, const pandora::TrackList *const pTrackList, const std::string &name, const Color color)
Add Tracks to the Eve event-display.
static void VisualizeCaloHits (const pandora::Pandora &pandora, const pandora::CaloHitList *const pCaloHitList, const std::string &name, const Color color)
Add CaloHits to the Eve event-display.
static void VisualizeClusters (const pandora::Pandora &pandora, const pandora::ClusterList *const pClusterList, const std::string &name, const Color color, bool showAssociatedTracks=false)
Add Clusters to the Eve event-display.
static void VisualizeParticleFlowObjects (const pandora::Pandora &pandora, const pandora::PfoList *const pPfoList, const std::string &name, const Color color, bool showVertices=true, bool displayPfoHierarchy=true)
Add Particle flow objects to the Eve event-display.
static void VisualizeVertices (const pandora::Pandora &pandora, const pandora::VertexList *const pVertexList, const std::string &name, const Color color)
Add Vertices to the Eve event-display.
static void AddMarkerToVisualization (const pandora::Pandora &pandora, const pandora::CartesianVector *const pMarkerPoint, const std::string &name, const Color color, const unsigned int markerSize)
Add marker to visualization.
static void ViewEvent (const pandora::Pandora &pandora)
Show the Eve Event-display and pause.
static void Pause (const pandora::Pandora &pandora)
Pause thread until user enters 'return'.
static void Create (const pandora::Pandora &pandora)
Create monitoring instance, with its associated ROOT TApplication.
static void Delete (const pandora::Pandora &pandora)
Delete monitoring instance, terminating its associated ROOT TApplication (unless it is in use by another instance)
Detailed Description
PandoraMonitoringApi class.
Member Function Documentation
void PandoraMonitoringApi::AddMarkerToVisualization (const pandora::Pandora & pandora, const pandora::CartesianVector *const pMarkerPoint, const std::string & name, const Color color, const unsigned int markerSize) static
Add marker to visualization.
Parameters
pandora the calling pandora instance
pMarkerPoint address of the marker point
name of the marker
color the marker color
showAssociatedTracks draw the tracks associated to the cluster
References pandora_monitoring::PandoraMonitoring::AddMarkerToVisualization(), and pandora_monitoring::PandoraMonitoring::GetInstance().
void PandoraMonitoringApi::Create (const pandora::Pandora & pandora) static
Create monitoring instance, with its associated ROOT TApplication.
Parameters
pandora the calling pandora instance
References pandora_monitoring::PandoraMonitoring::GetInstance().
void PandoraMonitoringApi::Delete (const pandora::Pandora & pandora) static
Delete monitoring instance, terminating its associated ROOT TApplication (unless it is in use by another instance)
Parameters
pandora the calling pandora instance
References pandora_monitoring::PandoraMonitoring::DeleteInstance(), and pandora_monitoring::PandoraMonitoring::GetInstance().
template<typename T > void PandoraMonitoringApi::DrawPandoraHistogram (const pandora::Pandora & pandora, const T & t) static
Draw a pandora histogram.
Parameters
pandora the calling pandora instance
t the pandora histogram
References pandora_monitoring::PandoraMonitoring::DrawPandoraHistogram(), and pandora_monitoring::PandoraMonitoring::GetInstance().
template<typename T > void PandoraMonitoringApi::DrawPandoraHistogram (const pandora::Pandora & pandora, const T & t, const std::string & options) static
Draw a pandora histogram.
Parameters
pandora the calling pandora instance
t the pandora histogram
options the drawing options
References pandora_monitoring::PandoraMonitoring::DrawPandoraHistogram(), and pandora_monitoring::PandoraMonitoring::GetInstance().
void PandoraMonitoringApi::FillTree (const pandora::Pandora & pandora, const std::string & treeName) static
Fill the tree with the variables which have been set before with SetTreeVariable.
Parameters
pandora the calling pandora instance
treeName name of the tree to be filled
References pandora_monitoring::PandoraMonitoring::FillTree(), and pandora_monitoring::PandoraMonitoring::GetInstance().
void PandoraMonitoringApi::Pause (const pandora::Pandora & pandora) static
Pause thread until user enters 'return'.
Parameters
pandora the calling pandora instance
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::Pause().
void PandoraMonitoringApi::PrintTree (const pandora::Pandora & pandora, const std::string & treeName) static
Print the tree.
Parameters
pandora the calling pandora instance
treeName name of the tree to be printed
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::PrintTree().
void PandoraMonitoringApi::SaveTree (const pandora::Pandora & pandora, const std::string & treeName, const std::string & fileName, const std::string & fileOptions) static
Save the tree to a file.
Parameters
pandora the calling pandora instance
fileName the file name under which to save the histogram
fileOptions the options associated with opening/recreating a file
treeName name of the tree to be written to a file
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::SaveTree().
void PandoraMonitoringApi::ScanTree (const pandora::Pandora & pandora, const std::string & treeName) static
Scan the tree (print a list of all values of all branches)
Parameters
pandora the calling pandora instance
treeName name of the tree to be scanned
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::ScanTree().
void PandoraMonitoringApi::SetEveDisplayParameters (const pandora::Pandora & pandora, const bool showDetectors = true, const DetectorView detectorView = DETECTOR_VIEW_DEFAULT, const float transparencyThresholdE = -1.f, const float energyScaleThresholdE = -1.f, const float scalingFactor = 0.1f) static
Set TEve display parameters.
Parameters
pandora the calling pandora instance
showDetectors turns the visibility of the detector geometry on or off
detectorView the detector view
transparencyThresholdE cell energy for which transparency is saturated (0%, fully opaque)
energyScaleThresholdE cell energy for which color is at top end of continous color palette
scalingFactor TEve works with [cm], Pandora works with [mm] (unless user has decided to use alternative units)
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::SetEveDisplayParameters().
template<typename T > template void PandoraMonitoringApi::SetTreeVariable (const pandora::Pandora & pandora, const std::string & treeName, const std::string & variableName, T t) static
Set a variable in a tree (create the tree and the branch if not yet existing)
Parameters
pandora the calling pandora instance
treeName name of the tree (is created if it does not exist yet)
variableName name of the branch in the tree (the branch is created if it does not exist yet)
t sets value of the variable (permitted types are float/double/int and std::vector<float>*,std::vector<double>*,std::vector<int>*
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::SetTreeVariable().
void PandoraMonitoringApi::ViewEvent (const pandora::Pandora & pandora) static
Show the Eve Event-display and pause.
Parameters
pandora the calling pandora instance
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::ViewEvent().
void PandoraMonitoringApi::VisualizeCaloHits (const pandora::Pandora & pandora, const pandora::CaloHitList *const pCaloHitList, const std::string & name, const Color color) static
Add CaloHits to the Eve event-display.
Parameters
pandora the calling pandora instance
pCaloHitList list of calohits to be added to the event display
name of the calohit list
color The color the cluster elements are drawn with
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::VisualizeCaloHits().
void PandoraMonitoringApi::VisualizeClusters (const pandora::Pandora & pandora, const pandora::ClusterList *const pClusterList, const std::string & name, const Color color, bool showAssociatedTracks = false) static
Add Clusters to the Eve event-display.
Parameters
pandora the calling pandora instance
pClusterList list of clusters to be added to the event display
name of the cluster list
color The color the cluster elements are drawn with
showAssociatedTracks draw the tracks associated to the cluster
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::VisualizeClusters().
void PandoraMonitoringApi::VisualizeMCParticles (const pandora::Pandora & pandora, const pandora::MCParticleList *const pMCParticleList, const std::string & name, const Color color, const PdgCodeToEnergyMap * pParticleSuppressionMap = NULL) static
Add MCParticles to the Eve event-display.
Parameters
pandora the calling pandora instance
pMCParticleList list of MC particles to be added to the event display
name of the MC particle list
color The color the track elements are drawn with
pParticleSuppressionMap map from pdg-codes to energy for suppression of particles types below specific energies
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::VisualizeMCParticles().
void PandoraMonitoringApi::VisualizeParticleFlowObjects (const pandora::Pandora & pandora, const pandora::PfoList *const pPfoList, const std::string & name, const Color color, bool showVertices = true, bool displayPfoHierarchy = true) static
Add Particle flow objects to the Eve event-display.
Parameters
pandora the calling pandora instance
pPfoList list of particle flow objects to be added to the event display
name of the pfo list
parent pointer to the parent TEveElement. If NULL, the cluster will be parent element
color The color the cluster elements are drawn with
showAssociatedTracks draw the tracks associated to the cluster
showVertices whether to draw markers to represent the pfo vertices
displayPfoHierarchy whether to draw daughter particles (only) within parent elements
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::VisualizeParticleFlowObjects().
void PandoraMonitoringApi::VisualizeTracks (const pandora::Pandora & pandora, const pandora::TrackList *const pTrackList, const std::string & name, const Color color) static
Add Tracks to the Eve event-display.
Parameters
pandora the calling pandora instance
pTrackList list of tracks to be added to the event display
name of the track list
color The color the track elements are drawn with
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::VisualizeTracks().
void PandoraMonitoringApi::VisualizeVertices (const pandora::Pandora & pandora, const pandora::VertexList *const pVertexList, const std::string & name, const Color color) static
Add Vertices to the Eve event-display.
Parameters
pandora the calling pandora instance
pVertexList list of vertices to be added to the event display
name of the vertex list
color The color the cluster elements are drawn with
References pandora_monitoring::PandoraMonitoring::GetInstance(), and pandora_monitoring::PandoraMonitoring::VisualizeVertices().
The documentation for this class was generated from the following files:
PandoraMonitoringApi.h
PandoraMonitoringApi.cc