ArborContent: arbor_content::CaloHitHelper Class Reference
arbor_content::CaloHitHelper Class Reference
CaloHitHelper class.
#include <CaloHitHelper.h>
Static Public Member Functions
static pandora::StatusCode RemoveCurrentConnections (const pandora::Algorithm &algorithm)
Remove the connections of the current calo hit list.
static pandora::StatusCode RemoveConnections (const pandora::CaloHitList *const pCaloHitList)
Remove the connections of the calo hit list.
static pandora::StatusCode ExtractCurrentSeedCaloHitList (const pandora::Algorithm &algorithm, pandora::CaloHitList &seedCaloHitList, bool discriminateLeafHits=false)
Extract the calo hit seed list from the current calo hit list.
static pandora::StatusCode ExtractSeedCaloHitList (const pandora::CaloHitList *const pCaloHitList, pandora::CaloHitList &seedCaloHitList, bool discriminateLeafHits=false)
Extract the calo hit seed list from the calo hit list.
static pandora::StatusCode ExtractCurrentLeafCaloHitList (const pandora::Algorithm &algorithm, pandora::CaloHitList &leafCaloHitList, bool discriminateSeedHits=false)
Extract the calo hit leaf list from the current calo hit list.
static pandora::StatusCode ExtractLeafCaloHitList (const pandora::CaloHitList *const pCaloHitList, pandora::CaloHitList &leafCaloHitList, bool discriminateSeedHits=false)
Extract the calo hit leaf list from the calo hit list.
static pandora::StatusCode BuildCaloHitList (const CaloHit *const pCaloHit, ConnectorDirection direction, pandora::CaloHitList &calohitList)
Build the calo hit list starting from a calo hit by looking recursively in the connector list (forward or backward)
static pandora::StatusCode BuildCaloHitList (const CaloHit *const pCaloHit, ConnectorDirection direction, pandora::CaloHitList &calohitList, unsigned int connectionLimit, unsigned int pseudoLayerLimit)
Build the calo hit list starting from a calo hit by looking recursively in the connector list (forward or backward).
static pandora::StatusCode GetMeanDirection (const CaloHit *const pCaloHit, ConnectorDirection connectorDirection, pandora::CartesianVector &direction, unsigned int depth)
Get the mean direction of the calo hit in a given direction.
static bool CanConnect (const CaloHit *const pCaloHit1, const CaloHit *const pCaloHit2, const pandora::CartesianVector &expectedDirection, const float normaleMaxAngle, const float normaleMaxDistance, const float transverseMaxAngle, const float transverseMaxDistance)
Whether the two calo hits can be connected.
static bool CanConnect (const pandora::Track *const pTrack, const CaloHit *const pCaloHit, const float normaleMaxAngle, const float normaleMaxDistance, const float transverseMaxAngle, const float transverseMaxDistance)
Whether the track and the calo hit can be connected.
static bool IsInRegionOfInterest (const pandora::CartesianVector &startRegionPosition, const pandora::CartesianVector &testPosition, const pandora::CartesianVector &expectedDirection, const pandora::CartesianVector &normaleVector, const float normaleMaxAngle, const float normaleMaxDistance, const float transverseMaxAngle, const float transverseMaxDistance)
Whether the tested position is in the region of interest.
Detailed Description
CaloHitHelper class.
Definition at line 46 of file CaloHitHelper.h.
Member Function Documentation
pandora::StatusCode arbor_content::CaloHitHelper::BuildCaloHitList (const CaloHit *const pCaloHit, ConnectorDirection direction, pandora::CaloHitList & calohitList) static
Build the calo hit list starting from a calo hit by looking recursively in the connector list (forward or backward)
Parameters
pCaloHit the calo hit to start from
direction the direction to look recursively for
caloHitList the calo hit list recursively built to receive
Definition at line 133 of file CaloHitHelper.cc.
References arbor_content::Connector::Get(), and ArborContentApi::GetConnectorList().
Referenced by BuildCaloHitList(), arbor_content::ArborClusteringAlgorithm::CreateClusters(), arbor_content::ClusterFragmentMergingAlgorithm::Run(), arbor_content::ReclusterHelper::SplitClusterIntoTreeClusters(), and arbor_content::ReclusterHelper::SplitTreeFromCluster().
   {
     const ConnectorList &connectorList(ArborContentApi::GetConnectorList(pCaloHit, direction));
     for(ConnectorList::const_iterator iter = connectorList.begin(), endIter = connectorList.end() ;
         endIter != iter ; ++iter)
     {
       const Connector *const pConnector = *iter;
       const CaloHit *const pConnectedCaloHit = pConnector->Get(direction);
       if(!calohitList.insert(pConnectedCaloHit).second)
         return pandora::STATUS_CODE_FAILURE;
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, CaloHitHelper::BuildCaloHitList(pConnectedCaloHit, direction, calohitList));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::CaloHitHelper::BuildCaloHitList (const CaloHit *const pCaloHit, ConnectorDirection direction, pandora::CaloHitList & calohitList, unsigned int connectionLimit, unsigned int pseudoLayerLimit) static
Build the calo hit list starting from a calo hit by looking recursively in the connector list (forward or backward).
Stops after n recursive steps from the initial calo hit or after reaching a pseudo layer limit
Parameters
pCaloHit the calo hit to start from
direction the direction to look recursively for
caloHitList the calo hit list recursively built to receive
connectionLimit the maximum number of recursive steps from the initial calo hit
pseudoLayerLimit the pseudo layer limit to reach for stopping the recursive list building
Definition at line 157 of file CaloHitHelper.cc.
References BuildCaloHitList(), arbor_content::Connector::Get(), and ArborContentApi::GetConnectorList().
   {
     const ConnectorList &connectorList(ArborContentApi::GetConnectorList(pCaloHit, direction));
     if(0 == connectionDepthLimit)
       return pandora::STATUS_CODE_SUCCESS;
     for(ConnectorList::const_iterator iter = connectorList.begin(), endIter = connectorList.end() ;
         endIter != iter ; ++iter)
     {
       const Connector *const pConnector = *iter;
       const CaloHit *const pConnectedCaloHit = pConnector->Get(direction);
       const unsigned int pseudoLayerDifference =
           std::max(pConnectedCaloHit->GetPseudoLayer(), pCaloHit->GetPseudoLayer()) - std::min(pConnectedCaloHit->GetPseudoLayer(), pCaloHit->GetPseudoLayer());
       if(pseudoLayerDifference > pseudoLayerLimit)
         continue;
       if(!calohitList.insert(pConnectedCaloHit).second)
         return pandora::STATUS_CODE_FAILURE;
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, CaloHitHelper::BuildCaloHitList(pConnectedCaloHit, direction, calohitList, connectionDepthLimit-1, pseudoLayerLimit-pseudoLayerDifference));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
bool arbor_content::CaloHitHelper::CanConnect (const CaloHit *const pCaloHit1, const CaloHit *const pCaloHit2, const pandora::CartesianVector & expectedDirection, const float normaleMaxAngle, const float normaleMaxDistance, const float transverseMaxAngle, const float transverseMaxDistance) static
Whether the two calo hits can be connected.
The valid region to connect two hits is contained within a cone
Parameters
pCaloHit1 a backward calo hit to connect
pCaloHit2 a forward calo hit to connect
exceptedDirection the expected of the shower development from pCaloHit1
normaleMaxAngle the maximum angle between the two hits when the expected direction is colinear to the cell direction of pCaloHit1
normaleMaxDistance the maximum distance between the two hits when the expected direction is colinear to the cell direction of pCaloHit1
transverseMaxAngle the maximum angle between the two hits when the expected direction is perpendicular to the cell direction of pCaloHit1
transverseMaxDistance the maximum distance between the two hits when the expected direction is perpendicular to the cell direction of pCaloHit1
Definition at line 224 of file CaloHitHelper.cc.
References IsInRegionOfInterest().
   {
     if(NULL == pCaloHit1 || NULL == pCaloHit2)
       return false;
     if(pCaloHit1 == pCaloHit2)
       return false;
     if(pCaloHit2->GetPseudoLayer() < pCaloHit1->GetPseudoLayer())
       return false;
     const pandora::CartesianVector &cellNormaleVector(pCaloHit1->GetCellNormalVector());
     return CaloHitHelper::IsInRegionOfInterest(pCaloHit1->GetPositionVector(), pCaloHit2->GetPositionVector(),
         expectedDirection, cellNormaleVector, normaleMaxAngle, normaleMaxDistance, transverseMaxAngle, transverseMaxDistance);
   }
bool arbor_content::CaloHitHelper::CanConnect (const pandora::Track *const pTrack, const CaloHit *const pCaloHit, const float normaleMaxAngle, const float normaleMaxDistance, const float transverseMaxAngle, const float transverseMaxDistance) static
Whether the track and the calo hit can be connected.
The valid region is contained within a cone
Parameters
pTrack a track with a valid calorimeter projection
pCaloHit a forward calo hit to connect
normaleMaxAngle the maximum angle between the two hits when the expected direction is colinear to the cell direction of pCaloHit1
normaleMaxDistance the maximum distance between the two hits when the expected direction is colinear to the cell direction of pCaloHit1
transverseMaxAngle the maximum angle between the two hits when the expected direction is perpendicular to the cell direction of pCaloHit1
transverseMaxDistance the maximum distance between the two hits when the expected direction is perpendicular to the cell direction of pCaloHit1
Definition at line 245 of file CaloHitHelper.cc.
References IsInRegionOfInterest().
   {
     if(NULL == pTrack || NULL == pCaloHit)
       return false;
     const pandora::CartesianVector &cellNormaleVector(pCaloHit->GetCellNormalVector());
     return CaloHitHelper::IsInRegionOfInterest(pTrack->GetTrackStateAtCalorimeter().GetPosition(), pCaloHit->GetPositionVector(),
         pTrack->GetTrackStateAtCalorimeter().GetMomentum(), cellNormaleVector, normaleMaxAngle, normaleMaxDistance, transverseMaxAngle, transverseMaxDistance);
   }
pandora::StatusCode arbor_content::CaloHitHelper::ExtractCurrentLeafCaloHitList (const pandora::Algorithm & algorithm, pandora::CaloHitList & leafCaloHitList, bool discriminateSeedHits = false) static
Extract the calo hit leaf list from the current calo hit list.
Parameters
algorithm the algorithm to access the content
leafCaloHitList the calo hit leaf list to receive
discriminateLeafHits whether the leaf/seed hits have to be put in the extracted list
Definition at line 102 of file CaloHitHelper.cc.
References ExtractLeafCaloHitList().
   {
     const pandora::CaloHitList *pCaloHitList = NULL;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(algorithm, pCaloHitList));
     return CaloHitHelper::ExtractLeafCaloHitList(pCaloHitList, leafCaloHitList, discriminateSeedHits);
   }
pandora::StatusCode arbor_content::CaloHitHelper::ExtractCurrentSeedCaloHitList (const pandora::Algorithm & algorithm, pandora::CaloHitList & seedCaloHitList, bool discriminateLeafHits = false) static
Extract the calo hit seed list from the current calo hit list.
Parameters
algorithm the algorithm to access the content
seedCaloHitList the calo hit seed list to receive
discriminateLeafHits whether the leaf/seed hits have to be put in the extracted list
Definition at line 71 of file CaloHitHelper.cc.
References ExtractSeedCaloHitList().
Referenced by arbor_content::ArborClusteringAlgorithm::CreateClusters().
   {
     const pandora::CaloHitList *pCaloHitList = NULL;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(algorithm, pCaloHitList));
     return CaloHitHelper::ExtractSeedCaloHitList(pCaloHitList, seedCaloHitList, discriminateLeafHits);
   }
pandora::StatusCode arbor_content::CaloHitHelper::ExtractLeafCaloHitList (const pandora::CaloHitList *const pCaloHitList, pandora::CaloHitList & leafCaloHitList, bool discriminateSeedHits = false) static
Extract the calo hit leaf list from the calo hit list.
Parameters
pCaloHitList the list to extract the sub calo hit leaf list
leafCaloHitList the calo hit leaf list to receive
discriminateLeafHits whether the leaf/seed hits have to be put in the extracted list
Definition at line 113 of file CaloHitHelper.cc.
References ArborContentApi::IsLeaf(), and ArborContentApi::IsSeed().
Referenced by ExtractCurrentLeafCaloHitList(), and arbor_content::ClusterFragmentMergingAlgorithm::Run().
   {
     for(pandora::CaloHitList::const_iterator iter = pCaloHitList->begin(), endIter = pCaloHitList->end() ;
         endIter != iter ; ++iter)
     {
       const CaloHit *const pCaloHit = dynamic_cast<const CaloHit *const>(*iter);
       if(NULL == pCaloHit)
         continue;
       if(ArborContentApi::IsLeaf(pCaloHit) && !(discriminateSeedHits && !ArborContentApi::IsSeed(pCaloHit)))
         leafCaloHitList.insert(pCaloHit);
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::CaloHitHelper::ExtractSeedCaloHitList (const pandora::CaloHitList *const pCaloHitList, pandora::CaloHitList & seedCaloHitList, bool discriminateLeafHits = false) static
Extract the calo hit seed list from the calo hit list.
Parameters
pCaloHitList the list to extract the sub calo hit seed list
seedCaloHitList the calo hit seed list to receive
discriminateLeafHits whether the leaf/seed hits have to be put in the extracted list
Definition at line 82 of file CaloHitHelper.cc.
References ArborContentApi::IsLeaf(), and ArborContentApi::IsSeed().
Referenced by ExtractCurrentSeedCaloHitList(), arbor_content::ClosebySeedMergingAlgorithm::FindMergeCandidateClusters(), arbor_content::ClusterHelper::GetNCaloHitSeeds(), arbor_content::ReclusterHelper::SplitClusterIntoTreeClusters(), and arbor_content::ReclusterHelper::SplitTreeFromCluster().
   {
     for(pandora::CaloHitList::const_iterator iter = pCaloHitList->begin(), endIter = pCaloHitList->end() ;
         endIter != iter ; ++iter)
     {
       const CaloHit *const pCaloHit = dynamic_cast<const CaloHit *const>(*iter);
       if(NULL == pCaloHit)
         continue;
       if(ArborContentApi::IsSeed(pCaloHit) && !(ArborContentApi::IsLeaf(pCaloHit) && discriminateLeafHits))
         seedCaloHitList.insert(pCaloHit);
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::CaloHitHelper::GetMeanDirection (const CaloHit *const pCaloHit, ConnectorDirection connectorDirection, pandora::CartesianVector & direction, unsigned int depth) static
Get the mean direction of the calo hit in a given direction.
Parameters
pCaloHit the calo hit to evaluate the mean direction
connectorDirection the connector direction to evaluate the mean direction
direction the mean direction to receive
depth the maximum connector depth to reach for the direction evaluation
Definition at line 189 of file CaloHitHelper.cc.
References arbor_content::Connector::Get(), and ArborContentApi::GetConnectorList().
Referenced by arbor_content::ConnectorCleaningTool::GetReferenceVector().
   {
     if(NULL == pCaloHit)
       return pandora::STATUS_CODE_FAILURE;
     if(0 == depth)
       return pandora::STATUS_CODE_SUCCESS;
     const ConnectorList &connectorList(ArborContentApi::GetConnectorList(pCaloHit, connectorDirection));
     if(connectorList.empty())
       return pandora::STATUS_CODE_SUCCESS;
     const pandora::CartesianVector &positionVector(pCaloHit->GetPositionVector());
     for(ConnectorList::const_iterator iter = connectorList.begin() , endIter = connectorList.end() ;
         endIter != iter ; ++iter)
     {
       const Connector *const pConnector = *iter;
       const CaloHit *const pConnectedCaloHit = pConnector->Get(connectorDirection);
       pandora::CartesianVector differencePosition(pConnectedCaloHit->GetPositionVector() - positionVector);
       const float normalizationWeight = 1.f / (differencePosition.GetMagnitudeSquared());
       direction += (differencePosition * normalizationWeight);
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, CaloHitHelper::GetMeanDirection(pConnectedCaloHit, connectorDirection,
           direction, depth-1));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
bool arbor_content::CaloHitHelper::IsInRegionOfInterest (const pandora::CartesianVector & startRegionPosition, const pandora::CartesianVector & testPosition, const pandora::CartesianVector & expectedDirection, const pandora::CartesianVector & normaleVector, const float normaleMaxAngle, const float normaleMaxDistance, const float transverseMaxAngle, const float transverseMaxDistance) static
Whether the tested position is in the region of interest.
The valid region is contained within a cone
Parameters
startRegionPosition the position where the region of interest starts
testPosition the position to test inside the region of interest
exceptedDirection the expected of the shower development from startRegionPosition
normaleMaxAngle the maximum angle between the two hits when the expected direction is colinear to the cell direction of startRegionPosition
normaleMaxDistance the maximum distance between the two hits when the expected direction is colinear to the cell direction of startRegionPosition
transverseMaxAngle the maximum angle between the two hits when the expected direction is perpendicular to the cell direction of startRegionPosition
transverseMaxDistance the maximum distance between the two hits when the expected direction is perpendicular to the cell direction of startRegionPosition
Definition at line 260 of file CaloHitHelper.cc.
Referenced by CanConnect().
   {
     const float expectedAngle = normaleVector.GetOpeningAngle(expectedDirection);
     if(normaleMaxAngle <= transverseMaxAngle || normaleMaxDistance >= transverseMaxDistance)
       return false;
     const float maxDistance = (normaleMaxDistance - transverseMaxDistance)*std::cos(expectedAngle) + transverseMaxDistance;
     const float maxAngle = (normaleMaxAngle - transverseMaxAngle)*std::cos(expectedAngle) + transverseMaxAngle;
     const pandora::CartesianVector differenceVector = testPosition - startRegionPosition;
     const float angle = differenceVector.GetOpeningAngle(expectedDirection);
     const float distance = differenceVector.GetMagnitude();
     if(angle > maxAngle || distance > maxDistance)
       return false;
     return true;
   }
pandora::StatusCode arbor_content::CaloHitHelper::RemoveConnections (const pandora::CaloHitList *const pCaloHitList) static
Remove the connections of the calo hit list.
Parameters
pCaloHitList the calo hit list to remove the connections
Definition at line 53 of file CaloHitHelper.cc.
References ArborContentApi::RemoveAndDeleteAllConnections().
Referenced by arbor_content::FragmentRemovalAlgorithm::RemoveClusterFragments(), RemoveCurrentConnections(), and arbor_content::SplitTrackReclusteringAlgorithm::Run().
   {
     for(pandora::CaloHitList::const_iterator iter = pCaloHitList->begin(), endIter = pCaloHitList->end() ;
         endIter != iter ; ++iter)
     {
       const CaloHit *const pCaloHit = dynamic_cast<const CaloHit *const>(*iter);
       if(NULL == pCaloHit)
         continue;
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::RemoveAndDeleteAllConnections(pCaloHit));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::CaloHitHelper::RemoveCurrentConnections (const pandora::Algorithm & algorithm) static
Remove the connections of the current calo hit list.
Parameters
algorithm the algorithm to access the content
Definition at line 43 of file CaloHitHelper.cc.
References RemoveConnections().
   {
     const pandora::CaloHitList *pCaloHitList = NULL;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(algorithm, pCaloHitList));
     return CaloHitHelper::RemoveConnections(pCaloHitList);
   }
The documentation for this class was generated from the following files:
CaloHitHelper.h
CaloHitHelper.cc