ArborContent: arbor_content::ArborPseudoLayerPlugin Class Reference
arbor_content::ArborPseudoLayerPlugin Class Reference
ArborPseudoLayerPlugin class.
#include <ArborPseudoLayerPlugin.h>
Public Member Functions
ArborPseudoLayerPlugin ()
Default constructor.
unsigned int GetPseudoLayer (const pandora::CartesianVector &positionVector) const
unsigned int GetPseudoLayerAtIp () const
Private Types
typedef std::vector< float > LayerPositionList
typedef std::vector< std::pair
< float, float > > AngleVector
Private Member Functions
pandora::StatusCode Initialize ()
pandora::StatusCode GetPseudoLayer (const float rCoordinate, const float zCoordinate, const float rCorrection, const float zCorrection, const float barrelInnerR, const float endCapInnerZ, unsigned int &pseudoLayer) const
Get the appropriate pseudolayer for a specified parameters.
pandora::StatusCode FindMatchingLayer (const float position, const LayerPositionList &layerPositionList, unsigned int &layer) const
Find the layer number corresponding to a specified position, via reference to a specified layer position list.
void StoreLayerPositions ()
Store all revelevant barrel and endcap layer positions upon initialization.
void StoreLayerPositions (const pandora::SubDetector &subDetector, LayerPositionList &LayerPositionList)
Store subdetector layer positions upon initialization.
void StoreDetectorOuterEdge ()
Store positions of barrel and endcap outer edges upon initialization.
void StorePolygonAngles ()
Store sine and cosine of angles used to project hit positions onto polygonal calorimeter surfaces upon initialization.
void StoreOverlapCorrectionDetails ()
Store all details revelevant to barrel/endcap overlap corrections upon initialization.
float GetMaximumRadius (const AngleVector &angleVector, const float x, const float y) const
Get the maximum polygon radius, with reference to cached sine/cosine values for relevant polygon angles.
void FillAngleVector (const unsigned int symmetryOrder, const float phi0, AngleVector &angleVector) const
Fill a vector with sine/cosine values for relevant polygon angles.
pandora::StatusCode ReadSettings (const pandora::TiXmlHandle xmlHandle)
Private Attributes
LayerPositionList m_barrelLayerPositions
List of barrel layer positions.
LayerPositionList m_endCapLayerPositions
List of endcap layer positions.
AngleVector m_eCalBarrelAngleVector
The ecal barrel angle vector.
AngleVector m_muonBarrelAngleVector
The muon barrel angle vector.
float m_barrelInnerR
Barrel inner radius.
float m_endCapInnerZ
Endcap inner z position.
float m_barrelInnerRMuon
Muon barrel inner radius.
float m_endCapInnerZMuon
Muon endcap inner z position.
float m_rCorrection
Barrel/endcap overlap r correction.
float m_zCorrection
Barrel/endcap overlap z correction.
float m_rCorrectionMuon
Muon barrel/endcap overlap r correction.
float m_zCorrectionMuon
Muon barrel/endcap overlap z correction.
float m_barrelEdgeR
Extremal barrel r coordinate.
float m_endCapEdgeZ
Extremal endcap z coordinate.
bool m_useCoordinateCorrections
Whether to use coordinate correction in intermediate regions.
Detailed Description
ArborPseudoLayerPlugin class.
Definition at line 41 of file ArborPseudoLayerPlugin.h.
Member Typedef Documentation
typedef std::vector< std::pair<float, float> > arbor_content::ArborPseudoLayerPlugin::AngleVector private
Definition at line 108 of file ArborPseudoLayerPlugin.h.
typedef std::vector<float> arbor_content::ArborPseudoLayerPlugin::LayerPositionList private
Definition at line 69 of file ArborPseudoLayerPlugin.h.
Constructor & Destructor Documentation
arbor_content::ArborPseudoLayerPlugin::ArborPseudoLayerPlugin ()
Default constructor.
Definition at line 34 of file ArborPseudoLayerPlugin.cc.
                                                  :
       m_barrelInnerR(0.f),
       m_endCapInnerZ(0.f),
       m_barrelInnerRMuon(0.f),
       m_endCapInnerZMuon(0.f),
       m_rCorrection(0.f),
       m_zCorrection(0.f),
       m_rCorrectionMuon(0.f),
       m_zCorrectionMuon(0.f),
       m_barrelEdgeR(0.f),
       m_endCapEdgeZ(0.f),
       m_useCoordinateCorrections(false)
   {
   }
Member Function Documentation
void arbor_content::ArborPseudoLayerPlugin::FillAngleVector (const unsigned int symmetryOrder, const float phi0, AngleVector & angleVector) const private
Fill a vector with sine/cosine values for relevant polygon angles.
Parameters
symmetryOrder the polygon symmetry order
phi0 the polygon cylindrical polar phi coordinate
angleVector the vector to fill with sine/cosine values for relevant polygon angles
Definition at line 302 of file ArborPseudoLayerPlugin.cc.
Referenced by StorePolygonAngles().
   {
     const float twoPi = static_cast<float>(2. * std::acos(-1.));
     angleVector.clear();
     for (unsigned int iSymmetry = 0; iSymmetry < symmetryOrder; ++iSymmetry)
     {
       const float phi = phi0 + ((twoPi * static_cast<float>(iSymmetry)) / static_cast<float>(symmetryOrder));
       angleVector.push_back(std::make_pair(std::cos(phi), std::sin(phi)));
     }
   }
pandora::StatusCode arbor_content::ArborPseudoLayerPlugin::FindMatchingLayer (const float position, const LayerPositionList & layerPositionList, unsigned int & layer) const private
Find the layer number corresponding to a specified position, via reference to a specified layer position list.
Parameters
position the specified position
layerPositionList the specified layer position list
layer to receive the layer number
Definition at line 141 of file ArborPseudoLayerPlugin.cc.
Referenced by GetPseudoLayer().
   {
     LayerPositionList::const_iterator upperIter = std::upper_bound(layerPositionList.begin(), layerPositionList.end(), position);
     if (layerPositionList.end() == upperIter)
     {
       return pandora::STATUS_CODE_NOT_FOUND;
     }
     if (layerPositionList.begin() == upperIter)
     {
       layer = 0;
       return pandora::STATUS_CODE_SUCCESS;
     }
     LayerPositionList::const_iterator lowerIter = upperIter - 1;
     if (std::fabs(position - *lowerIter) < std::fabs(position - *upperIter))
     {
       layer = std::distance(layerPositionList.begin(), lowerIter);
     }
     else
     {
       layer = std::distance(layerPositionList.begin(), upperIter);
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
float arbor_content::ArborPseudoLayerPlugin::GetMaximumRadius (const AngleVector & angleVector, const float x, const float y) const private
Get the maximum polygon radius, with reference to cached sine/cosine values for relevant polygon angles.
Parameters
angleVector vector containing cached sine/cosine values
x the cartesian x coordinate
y the cartesian y coordinate
Returns
the maximum radius
Definition at line 283 of file ArborPseudoLayerPlugin.cc.
Referenced by GetPseudoLayer().
   {
     if (angleVector.size() <= 2)
       return std::sqrt((x * x) + (y * y));
     float maxRadius(0.);
     for (AngleVector::const_iterator iter = angleVector.begin(), iterEnd = angleVector.end(); iter != iterEnd; ++iter)
     {
       const float radius((x * iter->first) + (y * iter->second));
       if (radius > maxRadius)
         maxRadius = radius;
     }
     return maxRadius;
   }
unsigned int arbor_content::ArborPseudoLayerPlugin::GetPseudoLayer (const pandora::CartesianVector & positionVector) const
Definition at line 71 of file ArborPseudoLayerPlugin.cc.
References GetMaximumRadius(), m_barrelEdgeR, m_barrelInnerR, m_barrelInnerRMuon, m_eCalBarrelAngleVector, m_endCapEdgeZ, m_endCapInnerZ, m_endCapInnerZMuon, m_muonBarrelAngleVector, m_rCorrection, m_rCorrectionMuon, m_zCorrection, and m_zCorrectionMuon.
Referenced by GetPseudoLayerAtIp().
   {
     const float zCoordinate(std::fabs(positionVector.GetZ()));
     if (zCoordinate > m_endCapEdgeZ)
       throw pandora::StatusCodeException(pandora::STATUS_CODE_NOT_FOUND);
     const float rCoordinate(this->GetMaximumRadius(m_eCalBarrelAngleVector, positionVector.GetX(), positionVector.GetY()));
     const float rCoordinateMuon(this->GetMaximumRadius(m_muonBarrelAngleVector, positionVector.GetX(), positionVector.GetY()));
     if ((rCoordinateMuon > m_barrelEdgeR) || (rCoordinate > m_barrelEdgeR))
       throw pandora::StatusCodeException(pandora::STATUS_CODE_NOT_FOUND);
     unsigned int pseudoLayer;
     if ((zCoordinate < m_endCapInnerZMuon) && (rCoordinateMuon < m_barrelInnerRMuon))
     {
       const pandora::StatusCode statusCode(this->GetPseudoLayer(rCoordinate, zCoordinate, m_rCorrection, m_zCorrection, m_barrelInnerR,
           m_endCapInnerZ, pseudoLayer));
       if (pandora::STATUS_CODE_SUCCESS != statusCode)
         throw pandora::StatusCodeException(statusCode);
     }
     else
     {
       const pandora::StatusCode statusCode(this->GetPseudoLayer(rCoordinateMuon, zCoordinate, m_rCorrectionMuon, m_zCorrectionMuon,
           m_barrelInnerRMuon, m_endCapInnerZMuon, pseudoLayer));
       if (pandora::STATUS_CODE_SUCCESS != statusCode)
         throw pandora::StatusCodeException(statusCode);
     }
     // Reserve a pseudo layer for track projections, etc.
     return (1 + pseudoLayer);
   }
pandora::StatusCode arbor_content::ArborPseudoLayerPlugin::GetPseudoLayer (const float rCoordinate, const float zCoordinate, const float rCorrection, const float zCorrection, const float barrelInnerR, const float endCapInnerZ, unsigned int & pseudoLayer) const private
Get the appropriate pseudolayer for a specified parameters.
Parameters
rCoordinate the radial coordinate
zCoordinate the z coordinate
rCorrection the barrel/endcap overlap r correction
zCorrection the barrel/endcap overlap z correction
barrelInnerR the barrel inner r coordinate
endCapInnerZ the endcap inner z coordinate
pseudoLayer to receive the appropriate pseudolayer
Definition at line 109 of file ArborPseudoLayerPlugin.cc.
References FindMatchingLayer(), m_barrelLayerPositions, m_endCapLayerPositions, and m_useCoordinateCorrections.
   {
     if (zCoordinate < endCapInnerZ)
     {
       return this->FindMatchingLayer(rCoordinate, m_barrelLayerPositions, pseudoLayer);
     }
     else if (rCoordinate < barrelInnerR)
     {
       return this->FindMatchingLayer(zCoordinate, m_endCapLayerPositions, pseudoLayer);
     }
     else
     {
       const float correctedRCoordinate = m_useCoordinateCorrections ? rCoordinate - rCorrection : rCoordinate;
       const float correctedZCoordinate = m_useCoordinateCorrections ? zCoordinate - zCorrection : zCoordinate;
       unsigned int bestBarrelLayer(0);
       const pandora::StatusCode barrelStatusCode(this->FindMatchingLayer(correctedRCoordinate, m_barrelLayerPositions, bestBarrelLayer));
       unsigned int bestEndCapLayer(0);
       const pandora::StatusCode endCapStatusCode(this->FindMatchingLayer(correctedZCoordinate, m_endCapLayerPositions, bestEndCapLayer));
       if ((pandora::STATUS_CODE_SUCCESS != barrelStatusCode) && (pandora::STATUS_CODE_SUCCESS != endCapStatusCode))
         return pandora::STATUS_CODE_NOT_FOUND;
       pseudoLayer = std::max(bestBarrelLayer, bestEndCapLayer);
       return pandora::STATUS_CODE_SUCCESS;
     }
   }
unsigned int arbor_content::ArborPseudoLayerPlugin::GetPseudoLayerAtIp () const inline
Definition at line 156 of file ArborPseudoLayerPlugin.h.
References GetPseudoLayer().
 {
     const unsigned int pseudoLayerAtIp(this->GetPseudoLayer(pandora::CartesianVector(0.f, 0.f, 0.f)));
     return pseudoLayerAtIp;
 }
pandora::StatusCode arbor_content::ArborPseudoLayerPlugin::Initialize () private
Definition at line 51 of file ArborPseudoLayerPlugin.cc.
References StoreDetectorOuterEdge(), StoreLayerPositions(), StoreOverlapCorrectionDetails(), and StorePolygonAngles().
   {
     try
     {
       this->StoreLayerPositions();
       this->StoreDetectorOuterEdge();
       this->StorePolygonAngles();
       this->StoreOverlapCorrectionDetails();
     }
     catch (pandora::StatusCodeException &statusCodeException)
     {
       std::cout << "ArborPseudoLayerPlugin: Incomplete geometry - consider using a different PseudoLayerCalculator." << std::endl;
       return statusCodeException.GetStatusCode();
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ArborPseudoLayerPlugin::ReadSettings (const pandora::TiXmlHandle xmlHandle) private
Definition at line 316 of file ArborPseudoLayerPlugin.cc.
References m_useCoordinateCorrections.
   {
     m_useCoordinateCorrections = false;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "UseCoordinateCorrections", m_useCoordinateCorrections));
     return pandora::STATUS_CODE_SUCCESS;
   }
void arbor_content::ArborPseudoLayerPlugin::StoreDetectorOuterEdge () private
Store positions of barrel and endcap outer edges upon initialization.
Definition at line 222 of file ArborPseudoLayerPlugin.cc.
References m_barrelEdgeR, m_barrelLayerPositions, m_endCapEdgeZ, and m_endCapLayerPositions.
Referenced by Initialize().
   {
     const pandora::GeometryManager *const pGeometryManager(this->GetPandora().GetGeometry());
     m_barrelEdgeR = (std::max(pGeometryManager->GetSubDetector(pandora::ECAL_BARREL).GetOuterRCoordinate(), std::max(
         pGeometryManager->GetSubDetector(pandora::HCAL_BARREL).GetOuterRCoordinate(),
         pGeometryManager->GetSubDetector(pandora::MUON_BARREL).GetOuterRCoordinate()) ));
     m_endCapEdgeZ = (std::max(std::fabs(pGeometryManager->GetSubDetector(pandora::ECAL_ENDCAP).GetOuterZCoordinate()), std::max(
         std::fabs(pGeometryManager->GetSubDetector(pandora::HCAL_ENDCAP).GetOuterZCoordinate()),
         std::fabs(pGeometryManager->GetSubDetector(pandora::MUON_ENDCAP).GetOuterZCoordinate())) ));
     if ((m_barrelLayerPositions.end() != std::upper_bound(m_barrelLayerPositions.begin(), m_barrelLayerPositions.end(), m_barrelEdgeR)) ||
         (m_endCapLayerPositions.end() != std::upper_bound(m_endCapLayerPositions.begin(), m_endCapLayerPositions.end(), m_endCapEdgeZ)))
     {
       std::cout << "ArborPseudoLayerPlugin: Layers specified outside detector edge." << std::endl;
       throw pandora::StatusCodeException(pandora::STATUS_CODE_FAILURE);
     }
     m_barrelLayerPositions.push_back(m_barrelEdgeR);
     m_endCapLayerPositions.push_back(m_endCapEdgeZ);
   }
void arbor_content::ArborPseudoLayerPlugin::StoreLayerPositions () private
Store all revelevant barrel and endcap layer positions upon initialization.
Definition at line 173 of file ArborPseudoLayerPlugin.cc.
References m_barrelLayerPositions, and m_endCapLayerPositions.
Referenced by Initialize().
   {
     const pandora::GeometryManager *const pGeometryManager(this->GetPandora().GetGeometry());
     this->StoreLayerPositions(pGeometryManager->GetSubDetector(pandora::ECAL_BARREL), m_barrelLayerPositions);
     this->StoreLayerPositions(pGeometryManager->GetSubDetector(pandora::ECAL_ENDCAP), m_endCapLayerPositions);
     this->StoreLayerPositions(pGeometryManager->GetSubDetector(pandora::HCAL_BARREL), m_barrelLayerPositions);
     this->StoreLayerPositions(pGeometryManager->GetSubDetector(pandora::HCAL_ENDCAP), m_endCapLayerPositions);
     this->StoreLayerPositions(pGeometryManager->GetSubDetector(pandora::MUON_BARREL), m_barrelLayerPositions);
     this->StoreLayerPositions(pGeometryManager->GetSubDetector(pandora::MUON_ENDCAP), m_endCapLayerPositions);
     if (m_barrelLayerPositions.empty() || m_endCapLayerPositions.empty())
     {
       std::cout << "ArborPseudoLayerPlugin: No layer positions specified." << std::endl;
       throw pandora::StatusCodeException(pandora::STATUS_CODE_NOT_INITIALIZED);
     }
     std::sort(m_barrelLayerPositions.begin(), m_barrelLayerPositions.end());
     std::sort(m_endCapLayerPositions.begin(), m_endCapLayerPositions.end());
     LayerPositionList::const_iterator barrelIter = std::unique(m_barrelLayerPositions.begin(), m_barrelLayerPositions.end());
     LayerPositionList::const_iterator endcapIter = std::unique(m_endCapLayerPositions.begin(), m_endCapLayerPositions.end());
     if ((m_barrelLayerPositions.end() != barrelIter) || (m_endCapLayerPositions.end() != endcapIter))
     {
       std::cout << "ArborPseudoLayerPlugin: Duplicate layer position detected." << std::endl;
       throw pandora::StatusCodeException(pandora::STATUS_CODE_FAILURE);
     }
   }
void arbor_content::ArborPseudoLayerPlugin::StoreLayerPositions (const pandora::SubDetector & subDetector, LayerPositionList & LayerPositionList) private
Store subdetector layer positions upon initialization.
Parameters
subDetector the sub detector
layerParametersList the layer parameters list
Definition at line 204 of file ArborPseudoLayerPlugin.cc.
   {
     if (!subDetector.IsMirroredInZ())
     {
       std::cout << "ArborPseudoLayerPlugin: Error, detector must be symmetrical about z=0 plane." << std::endl;
       throw pandora::StatusCodeException(pandora::STATUS_CODE_INVALID_PARAMETER);
     }
     const pandora::SubDetector::SubDetectorLayerList &subDetectorLayerList(subDetector.GetSubDetectorLayerList());
     for (pandora::SubDetector::SubDetectorLayerList::const_iterator iter = subDetectorLayerList.begin(), iterEnd = subDetectorLayerList.end(); iter != iterEnd; ++iter)
     {
       layerPositionList.push_back(iter->GetClosestDistanceToIp());
     }
   }
void arbor_content::ArborPseudoLayerPlugin::StoreOverlapCorrectionDetails () private
Store all details revelevant to barrel/endcap overlap corrections upon initialization.
Definition at line 260 of file ArborPseudoLayerPlugin.cc.
References m_barrelInnerR, m_barrelInnerRMuon, m_endCapInnerZ, m_endCapInnerZMuon, m_rCorrection, m_rCorrectionMuon, m_zCorrection, and m_zCorrectionMuon.
Referenced by Initialize().
   {
     const pandora::GeometryManager *const pGeometryManager(this->GetPandora().GetGeometry());
     m_barrelInnerR = pGeometryManager->GetSubDetector(pandora::ECAL_BARREL).GetInnerRCoordinate();
     m_endCapInnerZ = std::fabs(pGeometryManager->GetSubDetector(pandora::ECAL_ENDCAP).GetInnerZCoordinate());
     m_barrelInnerRMuon = pGeometryManager->GetSubDetector(pandora::MUON_BARREL).GetInnerRCoordinate();
     m_endCapInnerZMuon = std::fabs(pGeometryManager->GetSubDetector(pandora::MUON_ENDCAP).GetInnerZCoordinate());
     const float barrelOuterZ = std::fabs(pGeometryManager->GetSubDetector(pandora::ECAL_BARREL).GetOuterZCoordinate());
     const float endCapOuterR = pGeometryManager->GetSubDetector(pandora::ECAL_ENDCAP).GetOuterRCoordinate();
     const float barrelOuterZMuon = std::fabs(pGeometryManager->GetSubDetector(pandora::MUON_BARREL).GetOuterZCoordinate());
     const float endCapOuterRMuon = pGeometryManager->GetSubDetector(pandora::MUON_ENDCAP).GetOuterRCoordinate();
     const bool IsEnclosingEndCap(endCapOuterR > m_barrelInnerR); // true for ILD !
     m_rCorrection = ((!IsEnclosingEndCap) ? 0.f : m_barrelInnerR * ((m_endCapInnerZ / barrelOuterZ) - 1.f));
     m_zCorrection = ((IsEnclosingEndCap) ? 0.f : m_endCapInnerZ * ((m_barrelInnerR / endCapOuterR) - 1.f));
     m_rCorrectionMuon = ((!IsEnclosingEndCap) ? 0.f : m_barrelInnerRMuon * ((m_endCapInnerZMuon / barrelOuterZMuon) - 1.f));
     m_zCorrectionMuon = ((IsEnclosingEndCap) ? 0.f : m_endCapInnerZMuon * ((m_barrelInnerRMuon / endCapOuterRMuon) - 1.f));
   }
void arbor_content::ArborPseudoLayerPlugin::StorePolygonAngles () private
Store sine and cosine of angles used to project hit positions onto polygonal calorimeter surfaces upon initialization.
Definition at line 247 of file ArborPseudoLayerPlugin.cc.
References FillAngleVector(), m_eCalBarrelAngleVector, and m_muonBarrelAngleVector.
Referenced by Initialize().
   {
     const pandora::GeometryManager *const pGeometryManager(this->GetPandora().GetGeometry());
     this->FillAngleVector(pGeometryManager->GetSubDetector(pandora::ECAL_BARREL).GetInnerSymmetryOrder(),
         pGeometryManager->GetSubDetector(pandora::ECAL_BARREL).GetInnerPhiCoordinate(), m_eCalBarrelAngleVector);
     this->FillAngleVector(pGeometryManager->GetSubDetector(pandora::MUON_BARREL).GetInnerSymmetryOrder(),
         pGeometryManager->GetSubDetector(pandora::MUON_BARREL).GetInnerPhiCoordinate(), m_muonBarrelAngleVector);
   }
Member Data Documentation
float arbor_content::ArborPseudoLayerPlugin::m_barrelEdgeR private
Extremal barrel r coordinate.
Definition at line 148 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StoreDetectorOuterEdge().
float arbor_content::ArborPseudoLayerPlugin::m_barrelInnerR private
Barrel inner radius.
Definition at line 138 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StoreOverlapCorrectionDetails().
float arbor_content::ArborPseudoLayerPlugin::m_barrelInnerRMuon private
Muon barrel inner radius.
Definition at line 140 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StoreOverlapCorrectionDetails().
LayerPositionList arbor_content::ArborPseudoLayerPlugin::m_barrelLayerPositions private
List of barrel layer positions.
Definition at line 133 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), StoreDetectorOuterEdge(), and StoreLayerPositions().
AngleVector arbor_content::ArborPseudoLayerPlugin::m_eCalBarrelAngleVector private
The ecal barrel angle vector.
Definition at line 135 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StorePolygonAngles().
float arbor_content::ArborPseudoLayerPlugin::m_endCapEdgeZ private
Extremal endcap z coordinate.
Definition at line 149 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StoreDetectorOuterEdge().
float arbor_content::ArborPseudoLayerPlugin::m_endCapInnerZ private
Endcap inner z position.
Definition at line 139 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StoreOverlapCorrectionDetails().
float arbor_content::ArborPseudoLayerPlugin::m_endCapInnerZMuon private
Muon endcap inner z position.
Definition at line 141 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StoreOverlapCorrectionDetails().
LayerPositionList arbor_content::ArborPseudoLayerPlugin::m_endCapLayerPositions private
List of endcap layer positions.
Definition at line 134 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), StoreDetectorOuterEdge(), and StoreLayerPositions().
AngleVector arbor_content::ArborPseudoLayerPlugin::m_muonBarrelAngleVector private
The muon barrel angle vector.
Definition at line 136 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StorePolygonAngles().
float arbor_content::ArborPseudoLayerPlugin::m_rCorrection private
Barrel/endcap overlap r correction.
Definition at line 143 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StoreOverlapCorrectionDetails().
float arbor_content::ArborPseudoLayerPlugin::m_rCorrectionMuon private
Muon barrel/endcap overlap r correction.
Definition at line 145 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StoreOverlapCorrectionDetails().
bool arbor_content::ArborPseudoLayerPlugin::m_useCoordinateCorrections private
Whether to use coordinate correction in intermediate regions.
Definition at line 151 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and ReadSettings().
float arbor_content::ArborPseudoLayerPlugin::m_zCorrection private
Barrel/endcap overlap z correction.
Definition at line 144 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StoreOverlapCorrectionDetails().
float arbor_content::ArborPseudoLayerPlugin::m_zCorrectionMuon private
Muon barrel/endcap overlap z correction.
Definition at line 146 of file ArborPseudoLayerPlugin.h.
Referenced by GetPseudoLayer(), and StoreOverlapCorrectionDetails().
The documentation for this class was generated from the following files:
ArborPseudoLayerPlugin.h
ArborPseudoLayerPlugin.cc