ArborContent: arbor_content::TrackClusterAssociationAlgorithm Class Reference
arbor_content::TrackClusterAssociationAlgorithm Class Reference
TrackClusterAssociationAlgorithm class.
#include <TrackClusterAssociationAlgorithm.h>
Classes
struct AssociationConstraints
AssociationConstraints struct.
class Factory
Factory class for instantiating algorithm.
Private Types
typedef std::vector
< AssociationConstraints > AssociationConstraintsVector
typedef std::map< const
pandora::Track
*, AssociationConstraintsVector > AssociationConstraintsMap
typedef std::map< const
pandora::Track *, const
pandora::Cluster * > AssociationMap
typedef std::map< const
pandora::Cluster *, const
pandora::Track * > MultiAssociationMap
Private Member Functions
pandora::StatusCode Run ()
pandora::StatusCode ReadSettings (const pandora::TiXmlHandle xmlHandle)
pandora::StatusCode ExtractAssociationLists (pandora::ClusterList &clusterList, pandora::TrackList &trackList)
Extract the cluster and track lists eligible for track-cluster associations.
pandora::StatusCode BuildPossibleAssociations (const pandora::ClusterList &clusterList, const pandora::TrackList &trackList, AssociationMap &associationMap)
Build the possible track-cluster associations.
pandora::StatusCode PerformAssociations (const AssociationMap &associationMap)
Perform the track-cluster association.
pandora::StatusCode ComputeInnerCentroid (const pandora::Cluster *const pCluster, const pandora::Track *const pTrack, pandora::CartesianVector &innerCentroid) const
bool PassesInitialCuts (const pandora::Cluster *const pCluster, const pandora::Track *const pTrack) const
Whether the track-cluster pair passes simple cuts for a possible association.
pandora::StatusCode CalculateAssociationConstraints (const pandora::Cluster *const pCluster, const pandora::Track *const pTrack, AssociationConstraints &constraints)
Calculate the track-cluster association constraints for a possible association.
bool FitConstraints (const AssociationConstraints &constraints) const
Whether the set of constraints passes the final cuts for an association.
Static Private Member Functions
static bool SortByBestCompatibility (const AssociationConstraints &lhs, const AssociationConstraints &rhs)
Sort association constraints by compatibility (std::sort)
Private Attributes
unsigned int m_maxClusterInnerPseudoLayer
The maximum cluster inner pseudo layer cut.
unsigned int m_nFirstClusterPseudoLayer
The number of cluster pseudo layers for the inner centroid evaluation.
float m_maxDistanceToHelix
The maximum distance between a track helix and the cluster inner centroid.
float m_maxTrackClusterAngle
The maximum angle between the track projection and the cluster inner centroid.
bool m_allowMultiAssociations
Whether to allow multi track associations for a single cluster.
bool m_useEnergyCompatibility
Whether to use energy information for association.
Detailed Description
TrackClusterAssociationAlgorithm class.
Definition at line 40 of file TrackClusterAssociationAlgorithm.h.
Member Typedef Documentation
typedef std::map<const pandora::Track*, AssociationConstraintsVector> arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraintsMap private
Definition at line 69 of file TrackClusterAssociationAlgorithm.h.
typedef std::vector<AssociationConstraints> arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraintsVector private
Definition at line 68 of file TrackClusterAssociationAlgorithm.h.
typedef std::map<const pandora::Track*, const pandora::Cluster*> arbor_content::TrackClusterAssociationAlgorithm::AssociationMap private
Definition at line 70 of file TrackClusterAssociationAlgorithm.h.
typedef std::map<const pandora::Cluster*, const pandora::Track*> arbor_content::TrackClusterAssociationAlgorithm::MultiAssociationMap private
Definition at line 71 of file TrackClusterAssociationAlgorithm.h.
Member Function Documentation
pandora::StatusCode arbor_content::TrackClusterAssociationAlgorithm::BuildPossibleAssociations (const pandora::ClusterList & clusterList, const pandora::TrackList & trackList, AssociationMap & associationMap) private
Build the possible track-cluster associations.
Parameters
clusterList the input cluster list
trackList the input track list
associationMap the association map to receive
Definition at line 108 of file TrackClusterAssociationAlgorithm.cc.
References CalculateAssociationConstraints(), FitConstraints(), arbor_content::ReclusterHelper::GetTrackClusterCompatibility(), m_allowMultiAssociations, arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraints::m_compatibility, and PassesInitialCuts().
Referenced by Run().
   {
     AssociationConstraintsMap contraintsMap;
     MultiAssociationMap multiAssociationMap;
     for(pandora::TrackList::const_iterator trackIter = trackList.begin() , trackEndIter = trackList.end() ;
         trackEndIter != trackIter ; ++trackIter)
     {
       const pandora::Track *const pTrack = *trackIter;
       const pandora::Cluster *pBestCluster = NULL;
       float bestCompatibility(std::numeric_limits<float>::max());
       AssociationConstraints bestConstraints;
       for(pandora::ClusterList::const_iterator iter = clusterList.begin() , endIter = clusterList.end() ;
           endIter != iter ; ++iter)
       {
         const pandora::Cluster *const pCluster = *iter;
         if( ! this->PassesInitialCuts(pCluster, pTrack) )
           continue;
         AssociationConstraints constraints;
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->CalculateAssociationConstraints(pCluster, pTrack, constraints));
         if( ! this->FitConstraints(constraints) )
           continue;
         if(constraints.m_compatibility < bestCompatibility)
         {
           bestCompatibility = constraints.m_compatibility;
           bestConstraints = constraints;
           pBestCluster = pCluster;
         }
       }
       if(NULL != pBestCluster)
       {
         if(m_allowMultiAssociations)
         {
           associationMap[pTrack] = pBestCluster;
           continue;
         }
         MultiAssociationMap::iterator iter = multiAssociationMap.find(pBestCluster);
         if(multiAssociationMap.end() != iter)
         {
           AssociationMap::iterator iter2 = associationMap.find(iter->second);
           if(iter2 == associationMap.end())
           {
             associationMap[pTrack] = pBestCluster;
             multiAssociationMap[pBestCluster] = pTrack;
             continue;
           }
           pandora::TrackList chiTrackList, newChiTrackList;
           chiTrackList.insert(iter->second);
           newChiTrackList.insert(pTrack);
           const float chi = ReclusterHelper::GetTrackClusterCompatibility(this->GetPandora(), pBestCluster, chiTrackList);
           const float newChi = ReclusterHelper::GetTrackClusterCompatibility(this->GetPandora(), pBestCluster, newChiTrackList);
           if(chi*chi > newChi*newChi)
           {
             multiAssociationMap[pBestCluster] = pTrack;
             associationMap.erase(iter2);
             associationMap[pTrack] = pBestCluster;
           }
         }
         else
         {
           associationMap[pTrack] = pBestCluster;
           multiAssociationMap[pBestCluster] = pTrack;
         }
       }
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::TrackClusterAssociationAlgorithm::CalculateAssociationConstraints (const pandora::Cluster *const pCluster, const pandora::Track *const pTrack, AssociationConstraints & constraints) private
Calculate the track-cluster association constraints for a possible association.
Parameters
pCluster the input cluster
pTrack the input track
constraints the track-cluster association constraints
Definition at line 284 of file TrackClusterAssociationAlgorithm.cc.
References ComputeInnerCentroid(), arbor_content::ReclusterHelper::GetTrackClusterCompatibility(), arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraints::m_chi2, arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraints::m_compatibility, arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraints::m_distanceToHelix, m_maxDistanceToHelix, arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraints::m_pCluster, arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraints::m_trackClusterAngle, and m_useEnergyCompatibility.
Referenced by BuildPossibleAssociations().
   {
     if( NULL == pCluster || NULL == pTrack)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     const pandora::CartesianVector trackMomentum(pTrack->GetTrackStateAtCalorimeter().GetMomentum());
     const pandora::CartesianVector trackProjection(pTrack->GetTrackStateAtCalorimeter().GetPosition());
     pandora::CartesianVector innerCentroid(0.f, 0.f, 0.f);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->ComputeInnerCentroid(pCluster, pTrack, innerCentroid));
     // get b field and track helix
     const float bField(PandoraContentApi::GetPlugins(*this)->GetBFieldPlugin()->GetBField(pandora::CartesianVector(0.f, 0.f, 0.f)));
     const pandora::Helix helix(trackProjection, trackMomentum, pTrack->GetCharge(), bField);
     pandora::CartesianVector distanceToHelix(0.f, 0.f, 0.f);
     helix.GetDistanceToPoint(innerCentroid, distanceToHelix);
     pandora::TrackList trackList;
     trackList.insert(pTrack);
     const float openingAngle(trackMomentum.GetOpeningAngle(innerCentroid - trackProjection));
     const float chi = ReclusterHelper::GetTrackClusterCompatibility(this->GetPandora(), pCluster, trackList);
     const float energyCompatibility( m_useEnergyCompatibility ? chi*chi : 1.f );
     const float distanceCompatibility( distanceToHelix.GetZ() / m_maxDistanceToHelix );
     // compatibility as a distance to helix combined with energy information
     const float compatibility( energyCompatibility * distanceCompatibility );
     constraints.m_pCluster = pCluster;
     constraints.m_chi2 = chi*chi;
     constraints.m_trackClusterAngle = openingAngle;
     constraints.m_distanceToHelix = distanceToHelix.GetZ();
     constraints.m_compatibility = compatibility;
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::TrackClusterAssociationAlgorithm::ComputeInnerCentroid (const pandora::Cluster *const pCluster, const pandora::Track *const pTrack, pandora::CartesianVector & innerCentroid) const private
Definition at line 212 of file TrackClusterAssociationAlgorithm.cc.
References m_maxTrackClusterAngle, and m_nFirstClusterPseudoLayer.
Referenced by CalculateAssociationConstraints(), and PassesInitialCuts().
   {
     const unsigned int innerPseudoLayer(pCluster->GetInnerPseudoLayer());
     const pandora::CartesianVector trackMomentum(pTrack->GetTrackStateAtCalorimeter().GetMomentum());
     const pandora::CartesianVector trackProjection(pTrack->GetTrackStateAtCalorimeter().GetPosition());
     const pandora::OrderedCaloHitList &orderedCaloHitList(pCluster->GetOrderedCaloHitList());
     unsigned int nDof(0);
     for(pandora::OrderedCaloHitList::const_iterator iter = orderedCaloHitList.begin(), endIter = orderedCaloHitList.end() ; endIter != iter ; ++iter)
     {
       if( ( iter->first - innerPseudoLayer ) > m_nFirstClusterPseudoLayer )
         break;
       for(pandora::CaloHitList::const_iterator hiter = iter->second->begin(), endhiter = iter->second->end() ; endhiter != hiter ; ++hiter)
       {
         const pandora::CaloHit *const pCaloHit(*hiter);
         const float openingAngle(trackMomentum.GetOpeningAngle(pCaloHit->GetPositionVector() - trackProjection));
         if(openingAngle > m_maxTrackClusterAngle)
           continue;
         ++nDof;
         innerCentroid += pCaloHit->GetPositionVector();
       }
     }
     //  std::cout << " ==> nDof = " << nDof <<  std::endl;
     if(0 == nDof)
       return pandora::STATUS_CODE_FAILURE;
     innerCentroid *= (1.f / nDof);
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::TrackClusterAssociationAlgorithm::ExtractAssociationLists (pandora::ClusterList & clusterList, pandora::TrackList & trackList) private
Extract the cluster and track lists eligible for track-cluster associations.
Parameters
clusterList the cluster list to receive
trackList the track list to receive
Definition at line 57 of file TrackClusterAssociationAlgorithm.cc.
References m_maxClusterInnerPseudoLayer.
Referenced by Run().
   {
     const pandora::TrackList *pTrackList = NULL;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(*this, pTrackList));
     const pandora::ClusterList *pClusterList = NULL;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(*this, pClusterList));
     if(pTrackList->empty() || pClusterList->empty())
       return pandora::STATUS_CODE_SUCCESS;
     // filter clusters
     for(pandora::ClusterList::const_iterator iter = pClusterList->begin() , endIter = pClusterList->end() ;
         endIter != iter ; ++iter)
     {
       const pandora::Cluster *const pCluster = *iter;
       if( ! PandoraContentApi::IsAvailable(*this, pCluster) )
         continue;
       const unsigned int innerPseudoLayer(pCluster->GetInnerPseudoLayer());
       if( innerPseudoLayer > m_maxClusterInnerPseudoLayer )
         continue;
       clusterList.insert(pCluster);
     }
     // filter tracks
     for(pandora::TrackList::const_iterator trackIter = pTrackList->begin() , trackEndIter = pTrackList->end() ;
         trackEndIter != trackIter ; ++trackIter)
     {
       const pandora::Track *const pTrack = *trackIter;
       if(!PandoraContentApi::IsAvailable(*this, pTrack))
         continue;
       if(!pTrack->ReachesCalorimeter())
         continue;
       if(!pTrack->CanFormPfo())
         continue;
       trackList.insert(pTrack);
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
bool arbor_content::TrackClusterAssociationAlgorithm::FitConstraints (const AssociationConstraints & constraints) const private
Whether the set of constraints passes the final cuts for an association.
Parameters
constraints the constraints to check
Definition at line 325 of file TrackClusterAssociationAlgorithm.cc.
References arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraints::m_distanceToHelix, m_maxDistanceToHelix, m_maxTrackClusterAngle, and arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraints::m_trackClusterAngle.
Referenced by BuildPossibleAssociations().
   {
     if( constraints.m_distanceToHelix > m_maxDistanceToHelix )
       return false;
     if( constraints.m_trackClusterAngle > m_maxTrackClusterAngle )
       return false;
     return true;
   }
bool arbor_content::TrackClusterAssociationAlgorithm::PassesInitialCuts (const pandora::Cluster *const pCluster, const pandora::Track *const pTrack) const private
Whether the track-cluster pair passes simple cuts for a possible association.
Parameters
pCluster the input cluster
pTrack the input track
Definition at line 251 of file TrackClusterAssociationAlgorithm.cc.
References ComputeInnerCentroid(), and m_maxDistanceToHelix.
Referenced by BuildPossibleAssociations().
   {
     if( NULL == pCluster || NULL == pTrack)
       return false;
     const pandora::CartesianVector trackMomentum(pTrack->GetTrackStateAtCalorimeter().GetMomentum());
     const pandora::CartesianVector trackProjection(pTrack->GetTrackStateAtCalorimeter().GetPosition());
     pandora::CartesianVector innerCentroid(0.f, 0.f, 0.f);
     if(pandora::STATUS_CODE_SUCCESS != this->ComputeInnerCentroid(pCluster, pTrack, innerCentroid))
       return false;
     // get b field and track helix
     const float bField(PandoraContentApi::GetPlugins(*this)->GetBFieldPlugin()->GetBField(pandora::CartesianVector(0.f, 0.f, 0.f)));
     const pandora::Helix helix(trackProjection, trackMomentum, pTrack->GetCharge(), bField);
     //  pandora::CartesianVector projectionOnHelix(0.f, 0.f, 0.f);
     //
     //  if(pandora::STATUS_CODE_SUCCESS != GeometryHelper::GetProjectionOnHelix(helix, innerCentroid, projectionOnHelix))
     //    return false;
     pandora::CartesianVector distanceToHelix(0.f, 0.f, 0.f);
     helix.GetDistanceToPoint(innerCentroid, distanceToHelix);
     if( distanceToHelix.GetZ() > m_maxDistanceToHelix )
       return false;
     return true;
   }
pandora::StatusCode arbor_content::TrackClusterAssociationAlgorithm::PerformAssociations (const AssociationMap & associationMap) private
Perform the track-cluster association.
Parameters
associationMap the input association map
Definition at line 193 of file TrackClusterAssociationAlgorithm.cc.
Referenced by Run().
   {
     for(AssociationMap::const_iterator iter = associationMap.begin() , endIter = associationMap.end() ;
         endIter != iter ; ++iter)
     {
       const pandora::Track *const pTrack(iter->first);
       const pandora::Cluster *const pCluster(iter->second);
       if((NULL == pTrack) || (NULL == pCluster))
         continue;
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::AddTrackClusterAssociation(*this, pTrack, pCluster));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::TrackClusterAssociationAlgorithm::ReadSettings (const pandora::TiXmlHandle xmlHandle) private
Definition at line 345 of file TrackClusterAssociationAlgorithm.cc.
References m_allowMultiAssociations, m_maxClusterInnerPseudoLayer, m_maxDistanceToHelix, m_maxTrackClusterAngle, m_nFirstClusterPseudoLayer, and m_useEnergyCompatibility.
   {
     m_maxClusterInnerPseudoLayer = 3;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxClusterInnerPseudoLayer", m_maxClusterInnerPseudoLayer));
     m_nFirstClusterPseudoLayer = 4;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "NFirstClusterPseudoLayer", m_nFirstClusterPseudoLayer));
     m_maxDistanceToHelix = 25.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxDistanceToHelix", m_maxDistanceToHelix));
     m_maxTrackClusterAngle = 0.6f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxTrackClusterAngle", m_maxTrackClusterAngle));
     m_allowMultiAssociations = true;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "AllowMultiAssociations", m_allowMultiAssociations));
     m_useEnergyCompatibility = false;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "UseEnergyCompatibility", m_useEnergyCompatibility));
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::TrackClusterAssociationAlgorithm::Run () private
Definition at line 36 of file TrackClusterAssociationAlgorithm.cc.
References BuildPossibleAssociations(), ExtractAssociationLists(), and PerformAssociations().
   {
     // extract tracks and clusters eligible for track-cluster associations
     pandora::TrackList trackList; pandora::ClusterList clusterList;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->ExtractAssociationLists(clusterList, trackList));
     if(trackList.empty() || clusterList.empty())
       return pandora::STATUS_CODE_SUCCESS;
     // reset the track-cluster associations
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::RemoveCurrentTrackClusterAssociations(*this));
     AssociationMap associationMap;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->BuildPossibleAssociations(clusterList, trackList, associationMap));
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->PerformAssociations(associationMap));
     return pandora::STATUS_CODE_SUCCESS;
   }
bool arbor_content::TrackClusterAssociationAlgorithm::SortByBestCompatibility (const AssociationConstraints & lhs, const AssociationConstraints & rhs) static private
Sort association constraints by compatibility (std::sort)
Definition at line 338 of file TrackClusterAssociationAlgorithm.cc.
References arbor_content::TrackClusterAssociationAlgorithm::AssociationConstraints::m_compatibility.
   {
     return lhs.m_compatibility > rhs.m_compatibility;
   }
Member Data Documentation
bool arbor_content::TrackClusterAssociationAlgorithm::m_allowMultiAssociations private
Whether to allow multi track associations for a single cluster.
Definition at line 139 of file TrackClusterAssociationAlgorithm.h.
Referenced by BuildPossibleAssociations(), and ReadSettings().
unsigned int arbor_content::TrackClusterAssociationAlgorithm::m_maxClusterInnerPseudoLayer private
The maximum cluster inner pseudo layer cut.
Definition at line 133 of file TrackClusterAssociationAlgorithm.h.
Referenced by ExtractAssociationLists(), and ReadSettings().
float arbor_content::TrackClusterAssociationAlgorithm::m_maxDistanceToHelix private
The maximum distance between a track helix and the cluster inner centroid.
Definition at line 136 of file TrackClusterAssociationAlgorithm.h.
Referenced by CalculateAssociationConstraints(), FitConstraints(), PassesInitialCuts(), and ReadSettings().
float arbor_content::TrackClusterAssociationAlgorithm::m_maxTrackClusterAngle private
The maximum angle between the track projection and the cluster inner centroid.
Definition at line 137 of file TrackClusterAssociationAlgorithm.h.
Referenced by ComputeInnerCentroid(), FitConstraints(), and ReadSettings().
unsigned int arbor_content::TrackClusterAssociationAlgorithm::m_nFirstClusterPseudoLayer private
The number of cluster pseudo layers for the inner centroid evaluation.
Definition at line 134 of file TrackClusterAssociationAlgorithm.h.
Referenced by ComputeInnerCentroid(), and ReadSettings().
bool arbor_content::TrackClusterAssociationAlgorithm::m_useEnergyCompatibility private
Whether to use energy information for association.
Definition at line 140 of file TrackClusterAssociationAlgorithm.h.
Referenced by CalculateAssociationConstraints(), and ReadSettings().
The documentation for this class was generated from the following files:
TrackClusterAssociationAlgorithm.h
TrackClusterAssociationAlgorithm.cc