ArborContent: arbor_content::Branch Class Reference
arbor_content::Branch Class Reference
Branch class.
#include <Branch.h>
Public Types
typedef std::vector< const
CaloHit * > List
typedef List::value_type value_type
typedef List::iterator iterator
typedef List::const_iterator const_iterator
typedef List::reverse_iterator reverse_iterator
typedef
List::const_reverse_iterator const_reverse_iterator
Public Member Functions
Branch ()
Default constructor.
Branch (const_iterator first, const_iterator last)
Constructor with iterators on a branch.
Branch (const Branch &branch)
Copy constructor.
virtual ~Branch ()
Destructor.
pandora::StatusCode BuildFromCaloHit (const CaloHit *const pCaloHit)
Build-up a branch from the calo hit by looking a UNIQUE backward connection.
iterator begin ()
Returns an begin iterator on branch.
const_iterator begin () const
Returns an begin iterator on branch.
iterator end ()
Returns an end iterator on branch.
const_iterator end () const
Returns an end iterator on branch.
reverse_iterator rbegin ()
Returns a begin reverse iterator on branch.
const_reverse_iterator rbegin () const
Returns a begin reverse iterator on branch.
reverse_iterator rend ()
Returns an end reverse iterator on branch.
const_reverse_iterator rend () const
Returns an end reverse iterator on branch.
void clear ()
Clear the branch content.
size_t size () const
Returns the size of the branch (n calo hits)
pandora::StatusCode push_back (const CaloHit *const pCaloHit)
Add a calo hit to the branch (outermost calo hit).
pandora::StatusCode push_front (const CaloHit *const pCaloHit)
Add a calo hit to the branch (innermost calo hit).
pandora::StatusCode Cut (iterator position, bool keepForwardPart=true)
Cut the branch and keep only a part of the branch including the calo hit of the iterator.
bool IsValid () const
Whether the branch is still valid in terms of connected calo hits.
Branch & operator= (const Branch &branch)
Assignment operator.
Private Attributes
std::vector< const CaloHit * > m_caloHitList
Detailed Description
Branch class.
Definition at line 42 of file Branch.h.
Member Typedef Documentation
typedef List::const_iterator arbor_content::Branch::const_iterator
Definition at line 48 of file Branch.h.
typedef List::const_reverse_iterator arbor_content::Branch::const_reverse_iterator
Definition at line 50 of file Branch.h.
typedef List::iterator arbor_content::Branch::iterator
Definition at line 47 of file Branch.h.
typedef std::vector<const CaloHit *> arbor_content::Branch::List
Definition at line 45 of file Branch.h.
typedef List::reverse_iterator arbor_content::Branch::reverse_iterator
Definition at line 49 of file Branch.h.
typedef List::value_type arbor_content::Branch::value_type
Definition at line 46 of file Branch.h.
Constructor & Destructor Documentation
arbor_content::Branch::Branch () inline
Default constructor.
Definition at line 177 of file Branch.h.
 {
 }
arbor_content::Branch::Branch (const_iterator first, const_iterator last)
Constructor with iterators on a branch.
Parameters
first the starting iterator of the branch
last the ending iterator of the branch
Definition at line 36 of file Branch.cc.
References clear(), and IsValid().
                                                           :
     m_caloHitList(first, last)
   {
     if(!IsValid())
     {
       this->clear();
       throw pandora::StatusCodeException(pandora::STATUS_CODE_FAILURE);
     }
   }
arbor_content::Branch::Branch (const Branch & branch)
Copy constructor.
Definition at line 48 of file Branch.cc.
References clear(), and IsValid().
   {
     *this = branch;
     if(!IsValid())
     {
       clear();
       throw pandora::StatusCodeException(pandora::STATUS_CODE_FAILURE);
     }
   }
arbor_content::Branch::~Branch () inline virtual
Destructor.
Definition at line 183 of file Branch.h.
References clear().
 {
   clear();
 }
Member Function Documentation
Branch::iterator arbor_content::Branch::begin () inline
Returns an begin iterator on branch.
Definition at line 190 of file Branch.h.
References m_caloHitList.
Referenced by IsValid().
 {
   return m_caloHitList.begin();
 }
Branch::const_iterator arbor_content::Branch::begin () const inline
Returns an begin iterator on branch.
Definition at line 197 of file Branch.h.
References m_caloHitList.
 {
   return m_caloHitList.begin();
 }
pandora::StatusCode arbor_content::Branch::BuildFromCaloHit (const CaloHit *const pCaloHit)
Build-up a branch from the calo hit by looking a UNIQUE backward connection.
Stops when no connection is found.
Parameters
pCaloHit the calo hit to start with
Definition at line 61 of file Branch.cc.
References arbor_content::BACKWARD_DIRECTION, clear(), ArborContentApi::GetConnectorList(), and m_caloHitList.
   {
     if(NULL == pCaloHit)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     clear();
     const CaloHit *pCurrentCaloHit = pCaloHit;
     m_caloHitList.push_back(pCurrentCaloHit);
     while(pCurrentCaloHit)
     {
       const ConnectorList &backwardConnectorList(ArborContentApi::GetConnectorList(pCurrentCaloHit, BACKWARD_DIRECTION));
       if(backwardConnectorList.empty())
         return pandora::STATUS_CODE_SUCCESS;
       if(backwardConnectorList.size() != 1)
       {
         clear();
         return pandora::STATUS_CODE_FAILURE;
       }
       const Connector *const pConnector(*backwardConnectorList.begin());
       pCurrentCaloHit = pConnector->GetFrom();
       m_caloHitList.insert(m_caloHitList.begin(), pCurrentCaloHit);
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
void arbor_content::Branch::clear () inline
Clear the branch content.
Definition at line 246 of file Branch.h.
References m_caloHitList.
Referenced by Branch(), BuildFromCaloHit(), and ~Branch().
 {
   return m_caloHitList.clear();
 }
pandora::StatusCode arbor_content::Branch::Cut (iterator position, bool keepForwardPart = true)
Cut the branch and keep only a part of the branch including the calo hit of the iterator.
Parameters
position an iterator pointing on the calo hit from/to which the branch has to be cut
keepForwardPart whether to keep the forward part of the branch
Definition at line 142 of file Branch.cc.
References m_caloHitList.
   {
     if(m_caloHitList.end() == position || m_caloHitList.end() == position+1)
       return pandora::STATUS_CODE_SUCCESS;
     if(keepForwardPart)
     {
       m_caloHitList.erase(m_caloHitList.begin(), position);
     }
     else
     {
       m_caloHitList.erase(position+1, m_caloHitList.end());
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
Branch::iterator arbor_content::Branch::end () inline
Returns an end iterator on branch.
Definition at line 204 of file Branch.h.
References m_caloHitList.
Referenced by IsValid().
 {
   return m_caloHitList.end();
 }
Branch::const_iterator arbor_content::Branch::end () const inline
Returns an end iterator on branch.
Definition at line 211 of file Branch.h.
References m_caloHitList.
 {
   return m_caloHitList.end();
 }
bool arbor_content::Branch::IsValid () const
Whether the branch is still valid in terms of connected calo hits.
Returns true if the structure still follow a branch structure and false if the branch structure is broken (some connections removed)
Definition at line 161 of file Branch.cc.
References begin(), end(), arbor_content::FORWARD_DIRECTION, ArborContentApi::IsConnected(), and m_caloHitList.
Referenced by Branch().
   {
     if(m_caloHitList.size() <= 1)
       return true;
     for(const_iterator iter = this->begin(), endIter = this->end() ; endIter != iter ; ++iter)
     {
       const CaloHit *const pCaloHit = *iter;
       if(iter+1 == this->end())
         break;
       const CaloHit*const pNextCaloHit = *(iter+1);
       if(!ArborContentApi::IsConnected(pCaloHit, pNextCaloHit, FORWARD_DIRECTION))
         return false;
     }
     return true;
   }
Branch & arbor_content::Branch::operator= (const Branch & branch)
Assignment operator.
Definition at line 184 of file Branch.cc.
References m_caloHitList.
   {
     m_caloHitList.insert(m_caloHitList.begin(), branch.m_caloHitList.begin(), branch.m_caloHitList.end());
     return *this;
   }
pandora::StatusCode arbor_content::Branch::push_back (const CaloHit *const pCaloHit)
Add a calo hit to the branch (outermost calo hit).
A check is performed to test whether the calo hit is connected with the last calo hit
Parameters
pCaloHit the calo hit to add
Definition at line 94 of file Branch.cc.
References arbor_content::BACKWARD_DIRECTION, ArborContentApi::IsConnected(), and m_caloHitList.
   {
     if(NULL == pCaloHit)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     if(m_caloHitList.empty())
     {
       m_caloHitList.push_back(pCaloHit);
     }
     else
     {
       const CaloHit *const pOuterCaloHit(m_caloHitList.back());
       if(!ArborContentApi::IsConnected(pCaloHit, pOuterCaloHit, BACKWARD_DIRECTION))
         return pandora::STATUS_CODE_FAILURE;
       m_caloHitList.push_back(pCaloHit);
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::Branch::push_front (const CaloHit *const pCaloHit)
Add a calo hit to the branch (innermost calo hit).
A check is performed to test whether the calo hit is connected with the first calo hit
Parameters
pCaloHit the calo hit to add
Definition at line 118 of file Branch.cc.
References arbor_content::FORWARD_DIRECTION, ArborContentApi::IsConnected(), and m_caloHitList.
   {
     if(NULL == pCaloHit)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     if(m_caloHitList.empty())
     {
       m_caloHitList.push_back(pCaloHit);
     }
     else
     {
       const CaloHit *const pInnerCaloHit(m_caloHitList.front());
       if(!ArborContentApi::IsConnected(pCaloHit, pInnerCaloHit, FORWARD_DIRECTION))
         return pandora::STATUS_CODE_FAILURE;
       m_caloHitList.insert(m_caloHitList.begin(), pCaloHit);
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
Branch::reverse_iterator arbor_content::Branch::rbegin () inline
Returns a begin reverse iterator on branch.
Definition at line 218 of file Branch.h.
References m_caloHitList.
 {
   return m_caloHitList.rbegin();
 }
Branch::const_reverse_iterator arbor_content::Branch::rbegin () const inline
Returns a begin reverse iterator on branch.
Definition at line 225 of file Branch.h.
References m_caloHitList.
 {
   return m_caloHitList.rbegin();
 }
Branch::reverse_iterator arbor_content::Branch::rend () inline
Returns an end reverse iterator on branch.
Definition at line 232 of file Branch.h.
References m_caloHitList.
 {
   return m_caloHitList.rend();
 }
Branch::const_reverse_iterator arbor_content::Branch::rend () const inline
Returns an end reverse iterator on branch.
Definition at line 239 of file Branch.h.
References m_caloHitList.
 {
   return m_caloHitList.rend();
 }
size_t arbor_content::Branch::size () const inline
Returns the size of the branch (n calo hits)
Definition at line 253 of file Branch.h.
References m_caloHitList.
Referenced by arbor_content::SortingHelper::SortBranchesBySize().
 {
   return m_caloHitList.size();
 }
Member Data Documentation
std::vector<const CaloHit *> arbor_content::Branch::m_caloHitList private
Definition at line 171 of file Branch.h.
Referenced by begin(), BuildFromCaloHit(), clear(), Cut(), end(), IsValid(), operator=(), push_back(), push_front(), rbegin(), rend(), and size().
The documentation for this class was generated from the following files:
Branch.h
Branch.cc