ArborContent: arbor_content::ParticleIdHelper Class Reference
arbor_content::ParticleIdHelper Class Reference
ParticleIdHelper class.
#include <ParticleIdPlugins.h>
Classes
class StartingLayerSettings
StartingLayerSettings class.
Static Public Member Functions
static pandora::StatusCode GetStartingPseudoLayer (const pandora::Pandora &pandora, const pandora::Cluster *const pCluster, const StartingLayerSettings &settings, unsigned int &startingPseudoLayer)
Get the starting pseudo layer of the target cluster.
Detailed Description
ParticleIdHelper class.
Definition at line 40 of file ParticleIdPlugins.h.
Member Function Documentation
pandora::StatusCode arbor_content::ParticleIdHelper::GetStartingPseudoLayer (const pandora::Pandora & pandora, const pandora::Cluster *const pCluster, const StartingLayerSettings & settings, unsigned int & startingPseudoLayer) static
Get the starting pseudo layer of the target cluster.
Parameters
pandora the pandora instance to access content
pCluster the target cluster address
settings the input settings to calculate the starting pseudo layer
startingPseudoLayer the starting pseudo layer to receive
Definition at line 51 of file ParticleIdPlugins.cc.
References arbor_content::ClusterHelper::ContainsHitType(), arbor_content::ClusterHelper::GetCentroid(), arbor_content::GeometryHelper::GetClosestDistanceToLine(), arbor_content::GeometryHelper::GetDistanceToHelix(), arbor_content::ParticleIdHelper::StartingLayerSettings::m_lowEnergyClusterCut, arbor_content::ParticleIdHelper::StartingLayerSettings::m_maxForwardPseudoLayer, arbor_content::ParticleIdHelper::StartingLayerSettings::m_minFitHitDistanceCoarse, arbor_content::ParticleIdHelper::StartingLayerSettings::m_minFitHitDistanceFine, arbor_content::ParticleIdHelper::StartingLayerSettings::m_minNInteractingLayers, and arbor_content::ParticleIdHelper::StartingLayerSettings::m_minPseudoLayerNHits.
Referenced by arbor_content::ArborEmShowerId::IsMatch(), and arbor_content::ThetaEnergyFunction::MakeEnergyCorrections().
   {
     startingPseudoLayer = std::numeric_limits<unsigned int>::max();
     if(pCluster->GetNCaloHits() == 0)
       return pandora::STATUS_CODE_FAILURE;
     pandora::CaloHitList clusterCaloHitList, nonIsolatedCaloHitList;
     pCluster->GetOrderedCaloHitList().GetCaloHitList(clusterCaloHitList);
     pandora::ClusterFitPointList clusterFitPointList;
     unsigned int innerPseudoLayer(std::numeric_limits<unsigned int>::max());
     for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
         endIter != iter ; ++iter)
     {
       const pandora::CaloHit *const pCaloHit(*iter);
       if(pCaloHit->IsIsolated())
         continue;
       nonIsolatedCaloHitList.insert(pCaloHit);
       clusterFitPointList.push_back(pandora::ClusterFitPoint(pCaloHit));
       if(pCaloHit->GetPseudoLayer() < innerPseudoLayer)
         innerPseudoLayer = pCaloHit->GetPseudoLayer();
     }
     if(clusterFitPointList.empty())
     {
 //      std::cout << "ParticleIdHelper::GetStartingPseudoLayer: non isolated hit list empty " << std::endl;
       return pandora::STATUS_CODE_FAILURE;
     }
     bool lowEnergyEmCluster(pCluster->GetElectromagneticEnergy() < settings.m_lowEnergyClusterCut.Get()
         && !ClusterHelper::ContainsHitType(pCluster, pandora::HCAL)
     && pCluster->GetAssociatedTrackList().empty());
     if(lowEnergyEmCluster)
     {
       startingPseudoLayer = innerPseudoLayer;
 //      std::cout << "ParticleIdHelper::GetStartingPseudoLayer: (low) starting pseudo layer = " << startingPseudoLayer << std::endl;
       return pandora::STATUS_CODE_SUCCESS;
     }
     const pandora::OrderedCaloHitList &orderedCaloHitList(pCluster->GetOrderedCaloHitList());
     pandora::CartesianVector centroid(0.f, 0.f, 0.f);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));
     pandora::ClusterFitResult fitResult;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pandora::ClusterFitHelper::FitPoints(clusterFitPointList, fitResult));
     if(!fitResult.IsFitSuccessful())
     {
       std::cout << "ParticleIdHelper::GetStartingPseudoLayer: invalid fit" << std::endl;
       return pandora::STATUS_CODE_FAILURE;
     }
     bool chargedCluster(pCluster->GetAssociatedTrackList().size() == 1);
     pandora::Helix *pHelix(NULL);
     const float bField(pandora.GetPlugins()->GetBFieldPlugin()->GetBField(pandora::CartesianVector(0.f, 0.f, 0.f)));
     if(chargedCluster)
     {
       const pandora::Track *const pTrack(*pCluster->GetAssociatedTrackList().begin());
       const pandora::CartesianVector trackMomentum(pTrack->GetTrackStateAtCalorimeter().GetMomentum());
       const pandora::CartesianVector trackProjection(pTrack->GetTrackStateAtCalorimeter().GetPosition());
       const int trackCharge(pTrack->GetCharge());
       pHelix = new pandora::Helix(trackProjection, trackMomentum, trackCharge, bField);
     }
     const pandora::CartesianVector clusterDirection(fitResult.GetDirection());
     bool startingLayerFound(false);
     const pandora::GeometryManager *const pGeometryManager(pandora.GetGeometry());
     try
     {
       // walk along the ordered calo hit list and find the shower start layer
       for(pandora::OrderedCaloHitList::const_iterator layerIter = orderedCaloHitList.begin(), layerEndIter = orderedCaloHitList.end() ;
           layerEndIter != layerIter ; ++layerIter)
       {
         const unsigned int pseudoLayer(layerIter->first);
         unsigned int nInteractionLayers(0);
         for(pandora::OrderedCaloHitList::const_iterator layerIter2 = layerIter, layerEndIter2 = orderedCaloHitList.end() ;
             layerEndIter2 != layerIter2 ; ++layerIter2)
         {
           const unsigned int pseudoLayer2(layerIter2->first);
           if(pseudoLayer == pseudoLayer2)
             continue;
           if(pseudoLayer2 > pseudoLayer + settings.m_maxForwardPseudoLayer.Get())
             break;
           unsigned int nPseudoLayerHits(0);
           for(pandora::CaloHitList::const_iterator iter = layerIter2->second->begin(), endIter = layerIter2->second->end() ;
               endIter != iter ; ++iter)
           {
             const pandora::CaloHit *const pCaloHit(*iter);
             float distanceToFit(std::numeric_limits<float>::max());
             const pandora::Granularity granularity(pGeometryManager->GetHitTypeGranularity(pCaloHit->GetHitType()));
             const float minFitHitDistance(granularity <= pandora::FINE ?
                 settings.m_minFitHitDistanceFine.Get() : settings.m_minFitHitDistanceCoarse.Get());
             if(pHelix)
             {
               if(pandora::STATUS_CODE_SUCCESS != GeometryHelper::GetDistanceToHelix(*pHelix, pCaloHit->GetPositionVector(), distanceToFit))
                 continue;
             }
             else
             {
               if(pandora::STATUS_CODE_SUCCESS != GeometryHelper::GetClosestDistanceToLine(centroid, clusterDirection, pCaloHit->GetPositionVector(), distanceToFit))
                 continue;
             }
             if(distanceToFit > minFitHitDistance)
               continue;
             ++nPseudoLayerHits;
           }
           if(nPseudoLayerHits > settings.m_minPseudoLayerNHits.Get())
             ++nInteractionLayers;
         }
         //        std::cout << "    => Pseudo layer " << pseudoLayer << ", n interacting layers = " << nInteractionLayers << std::endl;
         if(nInteractionLayers > settings.m_minNInteractingLayers.Get())
         {
           startingPseudoLayer = pseudoLayer;
           startingLayerFound = true;
           break;
         }
       }
     }
     catch(const pandora::StatusCodeException &exception)
     {
       if(pHelix) delete pHelix;
       std::cout << "ParticleIdHelper::GetStartingPseudoLayer: caught exception in loop : " << exception.ToString() << std::endl;
       return exception.GetStatusCode();
     }
     if(pHelix) delete pHelix;
     if(!startingLayerFound)
     {
 //      std::cout << "ParticleIdHelper::GetStartingPseudoLayer: starting layer not found !" << std::endl;
       return pandora::STATUS_CODE_NOT_FOUND;
     }
 //    std::cout << "ParticleIdHelper::GetStartingPseudoLayer: starting pseudo layer = " << startingPseudoLayer << std::endl;
     return pandora::STATUS_CODE_SUCCESS;
   }
The documentation for this class was generated from the following files:
ParticleIdPlugins.h
ParticleIdPlugins.cc