ArborContent: ArborContentApi Class Reference
ArborContentApi Class Reference
ArborContentApi class.
#include <ArborContentApi.h>
Classes
class CaloHitMetadata
CaloHitMetadata class.
Static Public Member Functions
static pandora::StatusCode AlterMetadata (const pandora::Algorithm &algorithm, const arbor_content::CaloHit *const pCaloHit, const CaloHitMetadata &caloHitMetadata)
Alter calo hit meta data.
static bool IsConnected (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2)
Whether the two calo hits are connected (backward or forward directions)
static bool IsConnected (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2, arbor_content::ConnectorDirection direction)
Whether the two calo hits are connected in the given direction.
static pandora::StatusCode FindConnector (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2, const arbor_content::Connector *&pConnector)
Find a connector that links the two calo hits.
static pandora::StatusCode FindConnector (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2, arbor_content::ConnectorDirection direction, const arbor_content::Connector *&pConnector)
Find a connector that links the two calo hits in a given direction.
static bool HasAnyConnection (const arbor_content::CaloHit *const pCaloHit)
Whether the calo hit has at least one connection.
static const
arbor_content::ConnectorList & GetConnectorList (const arbor_content::CaloHit *const pCaloHit)
Get the global connector list (backward and forward) of the calo hit.
static const
arbor_content::ConnectorList & GetConnectorList (const arbor_content::CaloHit *const pCaloHit, arbor_content::ConnectorDirection direction)
Get the connector list of a calo hit for a given direction.
static bool IsSeed (const arbor_content::CaloHit *const pCaloHit)
Whether the calo hit is a seed calo hit in the tree.
static bool IsLeaf (const arbor_content::CaloHit *const pCaloHit)
Whether the calo hit is a leaf calo hit in the tree.
static pandora::StatusCode Connect (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2, arbor_content::ConnectorDirection direction, float referenceLength=1.f)
Connect the two calo hits in a given direction.
static pandora::StatusCode Connect (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2, arbor_content::ConnectorDirection direction, const arbor_content::Connector *&pConnector, float referenceLength=1.f)
Connect the two calo hits in a given direction.
static pandora::StatusCode RemoveConnectionBetween (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2)
.
static pandora::StatusCode RemoveAndDeleteConnector (const arbor_content::Connector *const pConnector)
.
static pandora::StatusCode RemoveAndDeleteAllConnections (const arbor_content::CaloHit *const pCaloHit)
Remove and delete all the connections of the calo hit.
static pandora::StatusCode Tag (const arbor_content::CaloHit *const pCaloHit, arbor_content::HitTag tag, bool value)
Set the calo hit tag.
static bool IsTagged (const arbor_content::CaloHit *const pCaloHit, arbor_content::HitTag tag)
Whether the calo hit has been tagged.
static pandora::StatusCode ResetTags (const arbor_content::CaloHit *const pCaloHit)
Reset the calo hit tags.
static pandora::StatusCode InitializeReclustering (const pandora::Algorithm &algorithm, const pandora::TrackList &inputTrackList, const pandora::ClusterList &inputClusterList, std::string &originalClustersListName)
Initialize Arbor re-clustering.
static pandora::StatusCode RunReclusteringAlgorithm (const pandora::Algorithm &algorithm, const std::string &clusteringAlgorithmName, const pandora::ClusterList *&pNewClusterList, std::string &newClusterListName)
Run a re-clustering algorithm.
static pandora::StatusCode PostRunReclusteringAlgorithm (const pandora::Algorithm &algorithm, const std::string &clusterListName)
Function to call just after a re-clustering algorithm and potential association algorithms.
static pandora::StatusCode EndReclustering (const pandora::Algorithm &algorithm, const std::string &selectedClusterListName)
End the re-clustering procedure.
Static Private Member Functions
static pandora::StatusCode RemoveConnector (const arbor_content::Connector *const pConnector)
.
template<typename T >
static T * Modifiable (const T *const pT)
Alter the object (const_cast<T*>) for internal modification through the API.
Detailed Description
ArborContentApi class.
Definition at line 44 of file ArborContentApi.h.
Member Function Documentation
pandora::StatusCode ArborContentApi::AlterMetadata (const pandora::Algorithm & algorithm, const arbor_content::CaloHit *const pCaloHit, const CaloHitMetadata & caloHitMetadata) static
Alter calo hit meta data.
Parameters
algorithm to access internal content
pCaloHit to modify
caloHitMetadata the input meta data
Definition at line 37 of file ArborContentApi.cc.
References ArborContentApi::CaloHitMetadata::m_density, ArborContentApi::CaloHitMetadata::m_surroundingEnergy, and Modifiable().
Referenced by arbor_content::CaloHitPreparationAlgorithm::Run().
 {
   // alter pandora calo hit meta data
   const pandora::CaloHit *const pPandoraCaloHit(pCaloHit);
   const PandoraContentApi::CaloHit::Metadata pandoraCaloHitMetadata(caloHitMetadata);
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::AlterMetadata(algorithm, pPandoraCaloHit, pandoraCaloHitMetadata));
   if(caloHitMetadata.m_surroundingEnergy.IsInitialized())
     ArborContentApi::Modifiable(pCaloHit)->m_surroundingEnergy = caloHitMetadata.m_surroundingEnergy.Get();
   if(caloHitMetadata.m_density.IsInitialized())
     ArborContentApi::Modifiable(pCaloHit)->m_density = caloHitMetadata.m_density.Get();
   return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode ArborContentApi::Connect (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2, arbor_content::ConnectorDirection direction, float referenceLength = 1.f) static
Connect the two calo hits in a given direction.
Parameters
pCaloHit1 the first calo hit to connect
pCaloHit2 the second calo hit to connect
direction the direction of the connection (FORWARD_DIRECTION means that pCaloHit1 will be the "from")
referenceLength the reference length assigned to the connector
Definition at line 120 of file ArborContentApi.cc.
Referenced by arbor_content::ConnectorAlignmentTool::ConnectBackward(), arbor_content::TrackDrivenSeedingTool::ConnectCaloHits(), arbor_content::ConnectorAlignmentTool::ConnectForward(), and arbor_content::ConnectorSeedingTool::Process().
 {
   const arbor_content::Connector *pConnector = NULL;
   return ArborContentApi::Connect(pCaloHit1, pCaloHit2, direction, pConnector, referenceLength);
 }
pandora::StatusCode ArborContentApi::Connect (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2, arbor_content::ConnectorDirection direction, const arbor_content::Connector *& pConnector, float referenceLength = 1.f) static
Connect the two calo hits in a given direction.
Parameters
pCaloHit1 the first calo hit to connect
pCaloHit2 the second calo hit to connect
direction the direction of the connection (FORWARD_DIRECTION means that pCaloHit1 will be the "from")
pConnector the connector address to receive
referenceLength the reference length assigned to the connector
Definition at line 129 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::AddConnector(), arbor_content::BACKWARD_DIRECTION, arbor_content::FORWARD_DIRECTION, arbor_content::CaloHit::m_pCaloHitMetaData, and Modifiable().
 {
   pConnector = NULL;
   arbor_content::CaloHit *const pCaloHitFrom = direction == arbor_content::BACKWARD_DIRECTION ? ArborContentApi::Modifiable(pCaloHit2) : ArborContentApi::Modifiable(pCaloHit1);
   arbor_content::CaloHit *const pCaloHitTo = direction == arbor_content::BACKWARD_DIRECTION ? ArborContentApi::Modifiable(pCaloHit1) : ArborContentApi::Modifiable(pCaloHit2);
   pConnector = new arbor_content::Connector(pCaloHitFrom, pCaloHitTo, referenceLength);
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pCaloHitFrom->m_pCaloHitMetaData->AddConnector(pConnector, arbor_content::FORWARD_DIRECTION));
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pCaloHitTo->m_pCaloHitMetaData->AddConnector(pConnector, arbor_content::BACKWARD_DIRECTION));
   return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode ArborContentApi::EndReclustering (const pandora::Algorithm & algorithm, const std::string & selectedClusterListName) static
End the re-clustering procedure.
Parameters
algorithm the parent algorithm that run the re-clustering
selectedClusterListName the name of the selected cluster list
Definition at line 294 of file ArborContentApi.cc.
References Modifiable().
Referenced by arbor_content::EnergyExcessReclusteringAlgorithm::Run(), and arbor_content::MissingEnergyReclusteringAlgorithm::Run().
 {
   const pandora::CaloHitList *pCaloHitList = NULL;
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(algorithm, pCaloHitList));
   for(pandora::CaloHitList::const_iterator iter = pCaloHitList->begin(), endIter = pCaloHitList->end() ;
       endIter != iter ; ++iter)
   {
     const arbor_content::CaloHit *const pCaloHit = dynamic_cast<const arbor_content::CaloHit *const>(*iter);
     if(NULL == pCaloHit)
       return pandora::STATUS_CODE_FAILURE;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::Modifiable(pCaloHit)->EndReclustering(selectedClusterListName));
   }
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::EndReclustering(algorithm, selectedClusterListName));
   return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode ArborContentApi::FindConnector (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2, const arbor_content::Connector *& pConnector) static
Find a connector that links the two calo hits.
Parameters
pCaloHit1 the first calo hit
pCaloHit2 the second calo hit
pConnector the connector address to receive
Definition at line 70 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::FindConnector(), and arbor_content::CaloHit::m_pCaloHitMetaData.
 {
   return pCaloHit1->m_pCaloHitMetaData->FindConnector(pCaloHit2, pConnector);
 }
pandora::StatusCode ArborContentApi::FindConnector (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2, arbor_content::ConnectorDirection direction, const arbor_content::Connector *& pConnector) static
Find a connector that links the two calo hits in a given direction.
Parameters
pCaloHit1 the first calo hit
pCaloHit2 the second calo hit
direction the direction in which the two calo hits are connected
pConnector the connector address to receive
Definition at line 77 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::FindConnector(), and arbor_content::CaloHit::m_pCaloHitMetaData.
 {
   return pCaloHit1->m_pCaloHitMetaData->FindConnector(pCaloHit2, direction, pConnector);
 }
const arbor_content::ConnectorList & ArborContentApi::GetConnectorList (const arbor_content::CaloHit *const pCaloHit) static
Get the global connector list (backward and forward) of the calo hit.
Parameters
pCaloHit the calo hit to get the connector list
Returns
ConnectorList the connector list (std::set<const Connector*>)
Definition at line 92 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::GetConnectorList(), and arbor_content::CaloHit::m_pCaloHitMetaData.
Referenced by arbor_content::CaloHitHelper::BuildCaloHitList(), arbor_content::Branch::BuildFromCaloHit(), arbor_content::ConnectorCleaningTool::CleanCaloHits(), arbor_content::ConnectorAlignmentTool::GetConnectorList(), arbor_content::CaloHitHelper::GetMeanDirection(), and arbor_content::ConnectorSeedingTool::Process().
 {
   return pCaloHit->m_pCaloHitMetaData->GetConnectorList();
 }
const arbor_content::ConnectorList & ArborContentApi::GetConnectorList (const arbor_content::CaloHit *const pCaloHit, arbor_content::ConnectorDirection direction) static
Get the connector list of a calo hit for a given direction.
Parameters
pCaloHit the calo hit to get the connector list
direction the direction of the connector list
Returns
ConnectorList the connector list (std::set<const Connector*>)
Definition at line 99 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::GetConnectorList(), and arbor_content::CaloHit::m_pCaloHitMetaData.
 {
   return pCaloHit->m_pCaloHitMetaData->GetConnectorList(direction);
 }
bool ArborContentApi::HasAnyConnection (const arbor_content::CaloHit *const pCaloHit) static
Whether the calo hit has at least one connection.
Parameters
pCaloHit the calo hit to test
Returns
boolean
Definition at line 85 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::HasAnyConnection(), and arbor_content::CaloHit::m_pCaloHitMetaData.
 {
   return pCaloHit->m_pCaloHitMetaData->HasAnyConnection();
 }
pandora::StatusCode ArborContentApi::InitializeReclustering (const pandora::Algorithm & algorithm, const pandora::TrackList & inputTrackList, const pandora::ClusterList & inputClusterList, std::string & originalClustersListName) static
Initialize Arbor re-clustering.
Save calo hit meta data and create a new one for each calo hit
Parameters
algorithm the parent algorithm that initializes the re-clustering
inputTrackList the list of tracks used for re-clustering
inputClusterList the list of cluster used for re-clustering
originalClustersListName the list of the original cluster to receive
Definition at line 234 of file ArborContentApi.cc.
References Modifiable().
Referenced by arbor_content::EnergyExcessReclusteringAlgorithm::Run(), and arbor_content::MissingEnergyReclusteringAlgorithm::Run().
 {
   // Initialize re-clustering within pandora
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::InitializeReclustering(algorithm, inputTrackList, inputClusterList, originalClustersListName));
   // Current calo hit list here is the one for re-clustering
   // Get it, save and create new meta data for each
   const pandora::CaloHitList *pCaloHitList = NULL;
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(algorithm, pCaloHitList));
   for(pandora::CaloHitList::const_iterator iter = pCaloHitList->begin(), endIter = pCaloHitList->end() ;
       endIter != iter ; ++iter)
   {
     const arbor_content::CaloHit *const pCaloHit = dynamic_cast<const arbor_content::CaloHit *const>(*iter);
     if(NULL == pCaloHit)
       return pandora::STATUS_CODE_FAILURE;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::Modifiable(pCaloHit)->SaveReclusterMetaData(originalClustersListName));
   }
   return pandora::STATUS_CODE_SUCCESS;
 }
bool ArborContentApi::IsConnected (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2) static
Whether the two calo hits are connected (backward or forward directions)
Parameters
pCaloHit1 the first calo hit
pCaloHit2 the second calo hit
Returns
boolean
Definition at line 56 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::IsConnected(), and arbor_content::CaloHit::m_pCaloHitMetaData.
Referenced by arbor_content::ConnectorAlignmentTool::ConnectBackward(), arbor_content::TrackDrivenSeedingTool::ConnectCaloHits(), arbor_content::ConnectorAlignmentTool::ConnectForward(), arbor_content::Branch::IsValid(), arbor_content::ConnectorSeedingTool::Process(), arbor_content::Branch::push_back(), and arbor_content::Branch::push_front().
 {
   return pCaloHit1->m_pCaloHitMetaData->IsConnected(pCaloHit2);
 }
bool ArborContentApi::IsConnected (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2, arbor_content::ConnectorDirection direction) static
Whether the two calo hits are connected in the given direction.
Parameters
pCaloHit1 the first calo hit
pCaloHit2 the second calo hit
direction the direction in which the calo hits may be connected
Returns
boolean
Definition at line 63 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::IsConnected(), and arbor_content::CaloHit::m_pCaloHitMetaData.
 {
   return pCaloHit1->m_pCaloHitMetaData->IsConnected(pCaloHit2, direction);
 }
bool ArborContentApi::IsLeaf (const arbor_content::CaloHit *const pCaloHit) static
Whether the calo hit is a leaf calo hit in the tree.
Parameters
pCaloHit the calo hit to test
Returns
boolean
Definition at line 113 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::IsLeaf(), and arbor_content::CaloHit::m_pCaloHitMetaData.
Referenced by arbor_content::CaloHitHelper::ExtractLeafCaloHitList(), and arbor_content::CaloHitHelper::ExtractSeedCaloHitList().
 {
   return pCaloHit->m_pCaloHitMetaData->IsLeaf();
 }
bool ArborContentApi::IsSeed (const arbor_content::CaloHit *const pCaloHit) static
Whether the calo hit is a seed calo hit in the tree.
Parameters
pCaloHit the calo hit to test
Returns
boolean
Definition at line 106 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::IsSeed(), and arbor_content::CaloHit::m_pCaloHitMetaData.
Referenced by arbor_content::CaloHitHelper::ExtractLeafCaloHitList(), arbor_content::CaloHitHelper::ExtractSeedCaloHitList(), and arbor_content::ReclusterHelper::SplitTreeFromCluster().
 {
   return pCaloHit->m_pCaloHitMetaData->IsSeed();
 }
bool ArborContentApi::IsTagged (const arbor_content::CaloHit *const pCaloHit, arbor_content::HitTag tag) static
Whether the calo hit has been tagged.
Parameters
pCaloHit the calo hit to test
tag the reconstruction tag to test
Returns
boolean
Definition at line 215 of file ArborContentApi.cc.
References arbor_content::CaloHit::m_hitTagMap.
 {
   return pCaloHit->m_hitTagMap.test(tag);
 }
template<typename T > template arbor_content::Connector * ArborContentApi::Modifiable (const T *const pT) static private
Alter the object (const_cast<T*>) for internal modification through the API.
Parameters
pT the object to alter
Returns
T* the altered object
Definition at line 318 of file ArborContentApi.cc.
Referenced by AlterMetadata(), Connect(), EndReclustering(), InitializeReclustering(), PostRunReclusteringAlgorithm(), RemoveAndDeleteConnector(), RemoveConnector(), ResetTags(), and Tag().
 {
   return const_cast<T*>(pT);
 }
pandora::StatusCode ArborContentApi::PostRunReclusteringAlgorithm (const pandora::Algorithm & algorithm, const std::string & clusterListName) static
Function to call just after a re-clustering algorithm and potential association algorithms.
Parameters
algorithm the parent algorithm that run the re-clustering algorithm
clusterListName the name of the cluster list
Definition at line 271 of file ArborContentApi.cc.
References Modifiable().
Referenced by arbor_content::EnergyExcessReclusteringAlgorithm::Run(), and arbor_content::MissingEnergyReclusteringAlgorithm::Run().
 {
   // Get the current re-clustering calo hit list
   // Save meta data for each calo hit
   const pandora::CaloHitList *pCaloHitList = NULL;
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(algorithm, pCaloHitList));
   for(pandora::CaloHitList::const_iterator iter = pCaloHitList->begin(), endIter = pCaloHitList->end() ;
       endIter != iter ; ++iter)
   {
     const arbor_content::CaloHit *const pCaloHit = dynamic_cast<const arbor_content::CaloHit *const>(*iter);
     if(NULL == pCaloHit)
       return pandora::STATUS_CODE_FAILURE;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::Modifiable(pCaloHit)->SaveReclusterMetaData(clusterListName));
   }
   return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode ArborContentApi::RemoveAndDeleteAllConnections (const arbor_content::CaloHit *const pCaloHit) static
Remove and delete all the connections of the calo hit.
Parameters
pCaloHit the calo hit to remove all connections
Definition at line 183 of file ArborContentApi.cc.
References arbor_content::BACKWARD_DIRECTION, arbor_content::FORWARD_DIRECTION, arbor_content::CaloHitMetaData::GetConnectorList(), arbor_content::CaloHit::m_pCaloHitMetaData, and RemoveAndDeleteConnector().
Referenced by arbor_content::ClusterHelper::CleanAndDeleteCluster(), arbor_content::CaloHitHelper::RemoveConnections(), arbor_content::NearbyTrackPhotonRemovalAlg::RemoveNearbyPhotonHits(), and arbor_content::CaloHit::~CaloHit().
 {
   arbor_content::ConnectorList backwardConnectorList(pCaloHit->m_pCaloHitMetaData->GetConnectorList(arbor_content::BACKWARD_DIRECTION));
   arbor_content::ConnectorList forwardConnectorList(pCaloHit->m_pCaloHitMetaData->GetConnectorList(arbor_content::FORWARD_DIRECTION));
   for(arbor_content::ConnectorList::const_iterator iter = backwardConnectorList.begin(), endIter = backwardConnectorList.end() ;
       endIter != iter ; ++iter)
   {
     const arbor_content::Connector *const pConnector = *iter;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::RemoveAndDeleteConnector(pConnector));
   }
   for(arbor_content::ConnectorList::const_iterator iter = forwardConnectorList.begin(), endIter = forwardConnectorList.end() ;
       endIter != iter ; ++iter)
   {
     const arbor_content::Connector *const pConnector = *iter;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::RemoveAndDeleteConnector(pConnector));
   }
   return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode ArborContentApi::RemoveAndDeleteConnector (const arbor_content::Connector *const pConnector) static
.
Remove the connection between the two calo hits and delete the connector
Parameters
pConnector the connector to remove and delete
Definition at line 173 of file ArborContentApi.cc.
References Modifiable(), and RemoveConnector().
Referenced by RemoveAndDeleteAllConnections(), and RemoveConnectionBetween().
 {
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::RemoveConnector(pConnector));
   delete ArborContentApi::Modifiable(pConnector);
   return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode ArborContentApi::RemoveConnectionBetween (const arbor_content::CaloHit *const pCaloHit1, const arbor_content::CaloHit *const pCaloHit2) static
.
Remove and delete the connection between the two calo hits.
Parameters
pCaloHit1 the first calo hit to disconnect
pCaloHit2 the second calo hit to disconnect
Definition at line 147 of file ArborContentApi.cc.
References arbor_content::CaloHitMetaData::FindConnector(), arbor_content::CaloHit::m_pCaloHitMetaData, and RemoveAndDeleteConnector().
Referenced by arbor_content::ConnectorCleaningTool::CleanCaloHits().
 {
   if(NULL == pCaloHit1 || NULL == pCaloHit2)
     return pandora::STATUS_CODE_INVALID_PARAMETER;
   const arbor_content::Connector *pConnector = NULL;
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pCaloHit1->m_pCaloHitMetaData->FindConnector(pCaloHit2, pConnector));
   return ArborContentApi::RemoveAndDeleteConnector(pConnector);
 }
pandora::StatusCode ArborContentApi::RemoveConnector (const arbor_content::Connector *const pConnector) static private
.
Remove the connection. Destructor not called, the connector responsibility is forwarded to the caller
Parameters
pConnector the connector to remove
Definition at line 160 of file ArborContentApi.cc.
References arbor_content::Connector::GetFrom(), arbor_content::Connector::GetTo(), and Modifiable().
Referenced by RemoveAndDeleteConnector().
 {
   if(NULL == pConnector)
     return pandora::STATUS_CODE_INVALID_PARAMETER;
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::Modifiable(pConnector->GetFrom())->m_pCaloHitMetaData->RemoveConnector(pConnector));
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::Modifiable(pConnector->GetTo())->m_pCaloHitMetaData->RemoveConnector(pConnector));
   return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode ArborContentApi::ResetTags (const arbor_content::CaloHit *const pCaloHit) static
Reset the calo hit tags.
Parameters
pCaloHit the calo hit to reset tags
Definition at line 222 of file ArborContentApi.cc.
References Modifiable().
 {
   if(NULL == pCaloHit)
     return pandora::STATUS_CODE_INVALID_PARAMETER;
   ArborContentApi::Modifiable(pCaloHit)->m_hitTagMap.reset();
   return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode ArborContentApi::RunReclusteringAlgorithm (const pandora::Algorithm & algorithm, const std::string & clusteringAlgorithmName, const pandora::ClusterList *& pNewClusterList, std::string & newClusterListName) static
Run a re-clustering algorithm.
Must be called only to run a clustering algorithm in a re-clustering process
Parameters
algorithm the parent algorithm running the (re)clustering algorithm
clusteringAlgorithmName the name of the clustering algorithm
pNewClusterList the list of created clusters to receive
newClusterListName the cluster list name to receive
Definition at line 261 of file ArborContentApi.cc.
Referenced by arbor_content::EnergyExcessReclusteringAlgorithm::Run(), and arbor_content::MissingEnergyReclusteringAlgorithm::Run().
 {
   PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::RunClusteringAlgorithm(algorithm, clusteringAlgorithmName, pNewClusterList, newClusterListName));
   return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode ArborContentApi::Tag (const arbor_content::CaloHit *const pCaloHit, arbor_content::HitTag tag, bool value) static
Set the calo hit tag.
Parameters
pCaloHit the calo hit to tag
tag the reconstruction tag to apply
value the tag value to assign
Definition at line 207 of file ArborContentApi.cc.
References Modifiable().
 {
   ArborContentApi::Modifiable(pCaloHit)->m_hitTagMap.set(tag, value);
   return pandora::STATUS_CODE_SUCCESS;
 }
The documentation for this class was generated from the following files:
ArborContentApi.h
ArborContentApi.cc