ArborContent: arbor_content::SortingHelper Class Reference
arbor_content::SortingHelper Class Reference
SortingHelper class.
#include <SortingHelper.h>
Classes
class SortByTrackClusterCompatibility
SortByTrackClusterCompatibility class.
class SortClusterByOmegaTracks
SortClusterByOmegaTracks class.
Static Public Member Functions
static bool SortClustersByInnerLayer (const pandora::Cluster *const pLhs, const pandora::Cluster *const pRhs)
Sort clusters by inner layer, and hadronic energy for same layer.
static bool SortBranchesBySize (const Branch &lhs, const Branch &rhs)
Sort branches by size.
static bool SortTracksByEnergy (const pandora::Track *const pLhs, const pandora::Track *const pRhs)
Sort tracks by energy at dca.
Detailed Description
SortingHelper class.
Definition at line 45 of file SortingHelper.h.
Member Function Documentation
bool arbor_content::SortingHelper::SortBranchesBySize (const Branch & lhs, const Branch & rhs) static
Sort branches by size.
Parameters
lhs the left handed branch to compare
rhs the right handed branch to compare
Definition at line 57 of file SortingHelper.cc.
References arbor_content::Branch::size().
   {
     return lhs.size() < rhs.size();
   }
bool arbor_content::SortingHelper::SortClustersByInnerLayer (const pandora::Cluster *const pLhs, const pandora::Cluster *const pRhs) static
Sort clusters by inner layer, and hadronic energy for same layer.
Parameters
pLhs the left handed cluster to compare
pRhs the right handed cluster to compare
Definition at line 40 of file SortingHelper.cc.
Referenced by arbor_content::ClusterFragmentMergingAlgorithm::Run(), arbor_content::MipFragmentMergingAlg::Run(), and arbor_content::PointingClusterAssociationAlgorithm::Run().
   {
     const unsigned int innerLayerLhs(pLhs->GetInnerPseudoLayer()), innerLayerRhs(pRhs->GetInnerPseudoLayer());
     if (innerLayerLhs != innerLayerRhs)
       return (innerLayerLhs < innerLayerRhs);
     const unsigned int nCaloHitsLhs(pLhs->GetNCaloHits()), nCaloHitsRhs(pRhs->GetNCaloHits());
     if (nCaloHitsLhs != nCaloHitsRhs)
       return (nCaloHitsLhs > nCaloHitsRhs);
     return (pLhs->GetHadronicEnergy() > pRhs->GetHadronicEnergy());
   }
bool arbor_content::SortingHelper::SortTracksByEnergy (const pandora::Track *const pLhs, const pandora::Track *const pRhs) static
Sort tracks by energy at dca.
Parameters
pLhs the left handed track to compare
pRhs the right handed track to compare
Definition at line 64 of file SortingHelper.cc.
   {
     return pLhs->GetEnergyAtDca() < pRhs->GetEnergyAtDca();
   }
The documentation for this class was generated from the following files:
SortingHelper.h
SortingHelper.cc