ArborContent: arbor_content::ReclusterResult Class Reference
arbor_content::ReclusterResult Class Reference
ReclusterResult class.
#include <ReclusterHelper.h>
Public Member Functions
float GetChi () const
float GetChi2 () const
float GetChiPerDof () const
float GetChi2PerDof () const
float GetNeutralEnergy () const
float GetChargedEnergy () const
float GetChiWorstAssociation () const
void SetChi (float chi)
void SetChi2 (float chi2)
void SetChiPerDof (float chiPerDof)
void SetChi2PerDof (float chi2PerDof)
void SetNeutralEnergy (float neutralEnergy)
void SetChargedEnergy (float chargedEnergy)
void SetChiWorstAssociation (float chiWorstAssociation)
Private Attributes
float m_chi
float m_chi2
float m_chiPerDof
float m_chi2PerDof
float m_neutralEnergy
float m_chargedEnergy
float m_chiWorstAssociation
Detailed Description
ReclusterResult class.
Definition at line 42 of file ReclusterHelper.h.
Member Function Documentation
float arbor_content::ReclusterResult::GetChargedEnergy () const inline
Definition at line 230 of file ReclusterHelper.h.
References m_chargedEnergy.
 {
   return m_chargedEnergy;
 }
float arbor_content::ReclusterResult::GetChi () const inline
Definition at line 195 of file ReclusterHelper.h.
References m_chi.
Referenced by arbor_content::MissingEnergyReclusteringAlgorithm::Run().
 {
   return m_chi;
 }
float arbor_content::ReclusterResult::GetChi2 () const inline
Definition at line 202 of file ReclusterHelper.h.
References m_chi2.
Referenced by arbor_content::MissingEnergyReclusteringAlgorithm::Run().
 {
   return m_chi2;
 }
float arbor_content::ReclusterResult::GetChi2PerDof () const inline
Definition at line 216 of file ReclusterHelper.h.
References m_chi2PerDof.
 {
   return m_chi2PerDof;
 }
float arbor_content::ReclusterResult::GetChiPerDof () const inline
Definition at line 209 of file ReclusterHelper.h.
References m_chiPerDof.
 {
   return m_chiPerDof;
 }
float arbor_content::ReclusterResult::GetChiWorstAssociation () const inline
Definition at line 237 of file ReclusterHelper.h.
References m_chiWorstAssociation.
 {
   return m_chiWorstAssociation;
 }
float arbor_content::ReclusterResult::GetNeutralEnergy () const inline
Definition at line 223 of file ReclusterHelper.h.
References m_neutralEnergy.
 {
   return m_neutralEnergy;
 }
void arbor_content::ReclusterResult::SetChargedEnergy (float chargedEnergy) inline
Definition at line 279 of file ReclusterHelper.h.
References m_chargedEnergy.
Referenced by arbor_content::ReclusterHelper::ExtractReclusterResults().
 {
   m_chargedEnergy = chargedEnergy;
 }
void arbor_content::ReclusterResult::SetChi (float chi) inline
Definition at line 244 of file ReclusterHelper.h.
References m_chi.
Referenced by arbor_content::ReclusterHelper::ExtractReclusterResults().
 {
   m_chi = chi;
 }
void arbor_content::ReclusterResult::SetChi2 (float chi2) inline
Definition at line 251 of file ReclusterHelper.h.
References m_chi2.
Referenced by arbor_content::ReclusterHelper::ExtractReclusterResults().
 {
   m_chi2 = chi2;
 }
void arbor_content::ReclusterResult::SetChi2PerDof (float chi2PerDof) inline
Definition at line 265 of file ReclusterHelper.h.
References m_chi2PerDof.
Referenced by arbor_content::ReclusterHelper::ExtractReclusterResults().
 {
   m_chi2PerDof = chi2PerDof;
 }
void arbor_content::ReclusterResult::SetChiPerDof (float chiPerDof) inline
Definition at line 258 of file ReclusterHelper.h.
References m_chiPerDof.
Referenced by arbor_content::ReclusterHelper::ExtractReclusterResults().
 {
   m_chiPerDof = chiPerDof;
 }
void arbor_content::ReclusterResult::SetChiWorstAssociation (float chiWorstAssociation) inline
Definition at line 286 of file ReclusterHelper.h.
References m_chiWorstAssociation.
Referenced by arbor_content::ReclusterHelper::ExtractReclusterResults().
 {
   m_chiWorstAssociation = chiWorstAssociation;
 }
void arbor_content::ReclusterResult::SetNeutralEnergy (float neutralEnergy) inline
Definition at line 272 of file ReclusterHelper.h.
References m_neutralEnergy.
Referenced by arbor_content::ReclusterHelper::ExtractReclusterResults().
 {
   m_neutralEnergy = neutralEnergy;
 }
Member Data Documentation
float arbor_content::ReclusterResult::m_chargedEnergy private
Definition at line 121 of file ReclusterHelper.h.
Referenced by GetChargedEnergy(), and SetChargedEnergy().
float arbor_content::ReclusterResult::m_chi private
Definition at line 116 of file ReclusterHelper.h.
Referenced by GetChi(), and SetChi().
float arbor_content::ReclusterResult::m_chi2 private
Definition at line 117 of file ReclusterHelper.h.
Referenced by GetChi2(), and SetChi2().
float arbor_content::ReclusterResult::m_chi2PerDof private
Definition at line 119 of file ReclusterHelper.h.
Referenced by GetChi2PerDof(), and SetChi2PerDof().
float arbor_content::ReclusterResult::m_chiPerDof private
Definition at line 118 of file ReclusterHelper.h.
Referenced by GetChiPerDof(), and SetChiPerDof().
float arbor_content::ReclusterResult::m_chiWorstAssociation private
Definition at line 122 of file ReclusterHelper.h.
Referenced by GetChiWorstAssociation(), and SetChiWorstAssociation().
float arbor_content::ReclusterResult::m_neutralEnergy private
Definition at line 120 of file ReclusterHelper.h.
Referenced by GetNeutralEnergy(), and SetNeutralEnergy().
The documentation for this class was generated from the following file:
ReclusterHelper.h