ArborContent: arbor_content::CaloHitMetaData Class Reference
arbor_content::CaloHitMetaData Class Reference
CaloHitMetaData class.
#include <ArborMetaData.h>
Public Member Functions
CaloHitMetaData (arbor_content::CaloHit *const pCaloHit)
Constructor.
~CaloHitMetaData ()
Destructor.
const arbor_content::CaloHit * GetCaloHit () const
Get the calo hit of this connector meta data.
bool IsConnected (const arbor_content::CaloHit *const pCaloHit) const
Whether the calo hit is connected with another one.
bool IsConnected (const arbor_content::CaloHit *const pCaloHit, ConnectorDirection direction) const
Whether the calo hit is connected with another one in the given direction.
pandora::StatusCode FindConnector (const arbor_content::CaloHit *const pCaloHit, const Connector *&pConnector) const
Find a connector.
pandora::StatusCode FindConnector (const arbor_content::CaloHit *const pCaloHit, ConnectorDirection direction, const Connector *&pConnector) const
Find a connector in a given direction.
bool HasAnyConnection () const
Whether the calo hit has at least one connection.
const ConnectorList & GetConnectorList () const
Get the global connector list (backward and forward)
const ConnectorList & GetConnectorList (ConnectorDirection direction) const
Get the connector list for a given direction.
bool IsSeed () const
Whether the calo hit is a seed calo hit in the tree.
bool IsLeaf () const
Whether the calo hit is a leaf calo hit in the tree.
pandora::StatusCode AddConnector (const Connector *const pConnector, ConnectorDirection direction)
Add an available connector to meta data.
pandora::StatusCode RemoveConnector (const Connector *const pConnector)
Remove the connection with an other calo hit.
pandora::StatusCode RemoveAllConnections ()
Remove all connections.
Private Attributes
arbor_content::CaloHit * m_pCaloHit
The handled arbor calo hit.
ConnectorList m_allConnectorList
All connected calo hits.
ConnectorList m_forwardConnectorList
Forward connected calo hits.
ConnectorList m_backwardConnectorList
Backward connected calo hits.
bool m_isLeaf
Whether the calo hit is a leaf.
bool m_isSeed
Whether the calo hit is a seed.
Friends
class CaloHit
Detailed Description
CaloHitMetaData class.
Definition at line 44 of file ArborMetaData.h.
Constructor & Destructor Documentation
arbor_content::CaloHitMetaData::CaloHitMetaData (arbor_content::CaloHit *const pCaloHit)
Constructor.
Parameters
pCaloHit the calo hit for this meta data
Definition at line 37 of file ArborMetaData.cc.
                                                                        :
     m_pCaloHit(pCaloHit),
     m_isLeaf(true),
     m_isSeed(true)
   {
   }
arbor_content::CaloHitMetaData::~CaloHitMetaData ()
Destructor.
Definition at line 46 of file ArborMetaData.cc.
References RemoveAllConnections().
   {
     PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->RemoveAllConnections());
   }
Member Function Documentation
pandora::StatusCode arbor_content::CaloHitMetaData::AddConnector (const Connector *const pConnector, ConnectorDirection direction)
Add an available connector to meta data.
Parameters
pConnector an unavailable connector to add
direction the connector direction
Definition at line 217 of file ArborMetaData.cc.
References arbor_content::BACKWARD_DIRECTION, m_allConnectorList, m_backwardConnectorList, m_forwardConnectorList, m_isLeaf, and m_isSeed.
Referenced by ArborContentApi::Connect().
   {
     if(!m_allConnectorList.insert(pConnector).second)
       return pandora::STATUS_CODE_FAILURE;
     bool inserted = direction == BACKWARD_DIRECTION ?
         m_backwardConnectorList.insert(pConnector).second : m_forwardConnectorList.insert(pConnector).second;
     if(!inserted)
     {
       m_allConnectorList.erase(pConnector);
       return pandora::STATUS_CODE_FAILURE;
     }
     if(BACKWARD_DIRECTION == direction)
       m_isSeed = false;
     else
       m_isLeaf = false;
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::CaloHitMetaData::FindConnector (const arbor_content::CaloHit *const pCaloHit, const Connector *& pConnector) const
Find a connector.
Parameters
pCaloHit an other calo hit to check for connection
pConnector the connector address to receive
Definition at line 138 of file ArborMetaData.cc.
References m_allConnectorList.
Referenced by ArborContentApi::FindConnector(), and ArborContentApi::RemoveConnectionBetween().
   {
     pConnector = NULL;
     for(ConnectorList::const_iterator iter = m_allConnectorList.begin(), endIter = m_allConnectorList.end() ;
         endIter != iter ; ++iter)
     {
       if((*iter)->GetFrom() == pCaloHit || (*iter)->GetTo() == pCaloHit)
       {
         pConnector = *iter;
         return pandora::STATUS_CODE_SUCCESS;
       }
     }
     return pandora::STATUS_CODE_NOT_FOUND;
   }
pandora::StatusCode arbor_content::CaloHitMetaData::FindConnector (const arbor_content::CaloHit *const pCaloHit, ConnectorDirection direction, const Connector *& pConnector) const
Find a connector in a given direction.
Parameters
pCaloHit an other calo hit to check for connection
direction the connector direction
pConnector the connector address to receive
Definition at line 158 of file ArborMetaData.cc.
References arbor_content::BACKWARD_DIRECTION, m_backwardConnectorList, and m_forwardConnectorList.
   {
     pConnector = NULL;
     ConnectorList::const_iterator beginIterator = BACKWARD_DIRECTION == direction ? m_backwardConnectorList.begin() : m_forwardConnectorList.begin();
     ConnectorList::const_iterator endIterator = BACKWARD_DIRECTION == direction ? m_backwardConnectorList.end() : m_forwardConnectorList.end();
     for(ConnectorList::const_iterator iter = beginIterator, endIter = endIterator ;
         endIter != iter ; ++iter)
     {
       if((*iter)->GetFrom() == pCaloHit || (*iter)->GetTo() == pCaloHit)
       {
         pConnector = *iter;
         return pandora::STATUS_CODE_SUCCESS;
       }
     }
     return pandora::STATUS_CODE_NOT_FOUND;
   }
const arbor_content::CaloHit * arbor_content::CaloHitMetaData::GetCaloHit () const
Get the calo hit of this connector meta data.
Definition at line 53 of file ArborMetaData.cc.
References m_pCaloHit.
   {
     return m_pCaloHit;
   }
const ConnectorList & arbor_content::CaloHitMetaData::GetConnectorList () const
Get the global connector list (backward and forward)
Definition at line 189 of file ArborMetaData.cc.
References m_allConnectorList.
Referenced by ArborContentApi::GetConnectorList(), and ArborContentApi::RemoveAndDeleteAllConnections().
   {
     return m_allConnectorList;
   }
const ConnectorList & arbor_content::CaloHitMetaData::GetConnectorList (ConnectorDirection direction) const
Get the connector list for a given direction.
Parameters
direction the connector direction
Definition at line 196 of file ArborMetaData.cc.
References arbor_content::BACKWARD_DIRECTION, m_backwardConnectorList, and m_forwardConnectorList.
   {
     return BACKWARD_DIRECTION == direction ? m_backwardConnectorList : m_forwardConnectorList;
   }
bool arbor_content::CaloHitMetaData::HasAnyConnection () const
Whether the calo hit has at least one connection.
Definition at line 182 of file ArborMetaData.cc.
References m_allConnectorList.
Referenced by ArborContentApi::HasAnyConnection().
   {
     return !(m_allConnectorList.empty());
   }
bool arbor_content::CaloHitMetaData::IsConnected (const arbor_content::CaloHit *const pCaloHit) const
Whether the calo hit is connected with another one.
Parameters
pCaloHit an other calo hit to check for connection
Definition at line 60 of file ArborMetaData.cc.
References arbor_content::Connector::GetFrom(), arbor_content::Connector::GetTo(), and m_allConnectorList.
Referenced by ArborContentApi::IsConnected().
   {
     for(ConnectorList::const_iterator iter = m_allConnectorList.begin(), endIter = m_allConnectorList.end() ;
         endIter != iter ; ++iter)
     {
       const Connector *const pConnector = *iter;
       if(pConnector->GetFrom() == pCaloHit || pConnector->GetTo() == pCaloHit)
         return true;
     }
     return false;
   }
bool arbor_content::CaloHitMetaData::IsConnected (const arbor_content::CaloHit *const pCaloHit, ConnectorDirection direction) const
Whether the calo hit is connected with another one in the given direction.
Parameters
pCaloHit an other calo hit to check for connection
direction the connector direction
Definition at line 76 of file ArborMetaData.cc.
References arbor_content::BACKWARD_DIRECTION, arbor_content::Connector::GetFrom(), arbor_content::Connector::GetTo(), m_backwardConnectorList, and m_forwardConnectorList.
   {
     ConnectorList::const_iterator beginIterator = BACKWARD_DIRECTION == direction ? m_backwardConnectorList.begin() : m_forwardConnectorList.begin();
     ConnectorList::const_iterator endIterator = BACKWARD_DIRECTION == direction ? m_backwardConnectorList.end() : m_forwardConnectorList.end();
     for(ConnectorList::const_iterator iter = beginIterator, endIter = endIterator ;
         endIter != iter ; ++iter)
     {
       const Connector *const pConnector = *iter;
       if(pConnector->GetFrom() == pCaloHit || pConnector->GetTo() == pCaloHit)
         return true;
     }
     return false;
   }
bool arbor_content::CaloHitMetaData::IsLeaf () const
Whether the calo hit is a leaf calo hit in the tree.
Definition at line 210 of file ArborMetaData.cc.
References m_isLeaf.
Referenced by ArborContentApi::IsLeaf().
   {
     return m_isLeaf;
   }
bool arbor_content::CaloHitMetaData::IsSeed () const
Whether the calo hit is a seed calo hit in the tree.
Definition at line 203 of file ArborMetaData.cc.
References m_isSeed.
Referenced by ArborContentApi::IsSeed().
   {
     return m_isSeed;
   }
pandora::StatusCode arbor_content::CaloHitMetaData::RemoveAllConnections ()
Remove all connections.
Definition at line 125 of file ArborMetaData.cc.
References m_allConnectorList, m_backwardConnectorList, m_forwardConnectorList, m_isLeaf, and m_isSeed.
Referenced by ~CaloHitMetaData().
   {
     m_allConnectorList.clear();
     m_backwardConnectorList.clear();
     m_forwardConnectorList.clear();
     m_isSeed = true;
     m_isLeaf = true;
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::CaloHitMetaData::RemoveConnector (const Connector *const pConnector)
Remove the connection with an other calo hit.
Parameters
pConnector the connector to remove (not deleted)
Definition at line 95 of file ArborMetaData.cc.
References arbor_content::Connector::GetFrom(), arbor_content::Connector::GetTo(), m_allConnectorList, m_backwardConnectorList, m_forwardConnectorList, m_isLeaf, m_isSeed, and m_pCaloHit.
   {
     if(pConnector->GetTo() != m_pCaloHit && pConnector->GetFrom() != m_pCaloHit)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     if(m_allConnectorList.erase(pConnector) != 1)
       return pandora::STATUS_CODE_FAILURE;
     if(pConnector->GetTo() == m_pCaloHit)
     {
       if(m_backwardConnectorList.erase(pConnector) != 1)
         return pandora::STATUS_CODE_FAILURE;
       if(m_backwardConnectorList.empty())
         m_isSeed = true;
     }
     else
     {
       if(m_forwardConnectorList.erase(pConnector) != 1)
         return pandora::STATUS_CODE_FAILURE;
       if(m_forwardConnectorList.empty())
         m_isLeaf = true;
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
Friends And Related Function Documentation
friend class CaloHit friend
Definition at line 154 of file ArborMetaData.h.
Member Data Documentation
ConnectorList arbor_content::CaloHitMetaData::m_allConnectorList private
All connected calo hits.
Definition at line 148 of file ArborMetaData.h.
Referenced by AddConnector(), FindConnector(), GetConnectorList(), HasAnyConnection(), IsConnected(), RemoveAllConnections(), and RemoveConnector().
ConnectorList arbor_content::CaloHitMetaData::m_backwardConnectorList private
Backward connected calo hits.
Definition at line 150 of file ArborMetaData.h.
Referenced by AddConnector(), FindConnector(), GetConnectorList(), IsConnected(), RemoveAllConnections(), and RemoveConnector().
ConnectorList arbor_content::CaloHitMetaData::m_forwardConnectorList private
Forward connected calo hits.
Definition at line 149 of file ArborMetaData.h.
Referenced by AddConnector(), FindConnector(), GetConnectorList(), IsConnected(), RemoveAllConnections(), and RemoveConnector().
bool arbor_content::CaloHitMetaData::m_isLeaf private
Whether the calo hit is a leaf.
Definition at line 151 of file ArborMetaData.h.
Referenced by AddConnector(), IsLeaf(), RemoveAllConnections(), and RemoveConnector().
bool arbor_content::CaloHitMetaData::m_isSeed private
Whether the calo hit is a seed.
Definition at line 152 of file ArborMetaData.h.
Referenced by AddConnector(), IsSeed(), RemoveAllConnections(), and RemoveConnector().
arbor_content::CaloHit* arbor_content::CaloHitMetaData::m_pCaloHit private
The handled arbor calo hit.
Definition at line 147 of file ArborMetaData.h.
Referenced by GetCaloHit(), and RemoveConnector().
The documentation for this class was generated from the following files:
ArborMetaData.h
ArborMetaData.cc