ArborContent: arbor_content::ClusterHelper Class Reference
arbor_content::ClusterHelper Class Reference
ClusterHelper class.
#include <ClusterHelper.h>
Static Public Member Functions
static pandora::StatusCode GetCentroid (const pandora::Cluster *const pCluster, pandora::CartesianVector &centroid)
Get the cluster centroid.
static pandora::StatusCode GetClosestDistanceApproach (const pandora::Cluster *const pCluster, const pandora::CartesianVector &point, float &closestDistance)
Get the closest distance approach between all the hits of the cluster and the given position vector.
static pandora::StatusCode GetCentroidDistance (const pandora::Cluster *const pCluster, const pandora::CartesianVector &point, float &centroidDistance)
Get the distance between the cluster centroid and the given position vector.
static pandora::StatusCode GetClosestDistanceApproach (const pandora::Cluster *const pCluster1, const pandora::Cluster *const pCluster2, float &closestDistance)
Get the closest distance approach between all the hits of the clusters.
static pandora::StatusCode GetNCaloHitSeeds (const pandora::Cluster *const pCluster, unsigned int &nSeeds)
Get the number of calo hit seeds in the cluster.
static bool IsClusterLeavingDetector (const pandora::Pandora &pandora, const pandora::Cluster *const pCluster, unsigned int nOuterLayersToExamine=3, float maxDistanceToDetectorEdge=50.f, unsigned int minNHitsNearEdges=3)
Whether the cluster is leaving the detector.
static bool ContainsHitType (const pandora::Cluster *const pCluster, const pandora::HitType hitType)
Whether the cluster contains at least one hit of target type.
static pandora::StatusCode GetMeanSurroundingEnergy (const pandora::Cluster *const pCluster, float &meanSurroundingEnergy)
Get the mean surrounding energy of the cluster.
static pandora::StatusCode GetMeanDensity (const pandora::Cluster *const pCluster, float &meanDensity)
Get the mean density of the cluster.
static pandora::StatusCode GetChiClusterMerging (const pandora::Pandora &pandora, const pandora::Cluster *const pClusterToEnlarge, const pandora::Cluster *const pClusterToMerge, float &oldChi, float &newChi)
Evaluate the chi before and after to merge the two clusters.
static pandora::StatusCode MergeClusters (const pandora::Algorithm &algorithm, ClusterToClusterMap &clusterToClusterMap)
Perform intelligent merging of clusters (daughter <-> parent relationship management)
static pandora::StatusCode GetTrackClusterDistance (const pandora::Pandora &pandora, const pandora::Cluster *const pCluster, const pandora::Track *const pTrack, const float maxTransverseDistance, float &trackClusterDistance)
Get the track cluster distance.
static bool DoesClusterCrossGapRegion (const pandora::Pandora &pandora, const pandora::Cluster *const pCluster, const unsigned int startLayer, const unsigned int endLayer, const pandora::DetectorGap *&pDetectorGap, const unsigned int nSamplingPoints=50)
Whether a linear fit to a cluster crosses a registered gap region.
static bool DoesFitCrossGapRegion (const pandora::Pandora &pandora, const pandora::ClusterFitResult &clusterFitResult, const pandora::CartesianVector &startPosition, const float propagationDistance, const pandora::DetectorGap *&pDetectorGap, const unsigned int nSamplingPoints=50)
Whether a linear fit crosses a registered gap region.
static pandora::StatusCode GetDistanceToDetectorGap (const pandora::CartesianVector &positionVector, const pandora::DetectorGap *const pDetectorGap, float &distanceToGap)
Get the distance to detector gap.
static pandora::StatusCode GetCaloHitsNearDetectorGaps (const pandora::Pandora &pandora, const pandora::Cluster *const pCluster, const float maxDistanceFine, const float maxDistanceCoarse, pandora::CaloHitList &caloHitList, bool shouldUseIsolatedHits)
Get the calo hit list belonging to the cluster, close to all registered detector gaps.
static pandora::StatusCode GetCaloHitsNearDetectorGap (const pandora::Pandora &pandora, const pandora::Cluster *const pCluster, const pandora::DetectorGap *const pDetectorGap, const float maxDistanceFine, const float maxDistanceCoarse, pandora::CaloHitList &caloHitList, bool shouldUseIsolatedHits)
Get the calo hit list belonging to the cluster, close to all registered detector gaps.
static pandora::StatusCode CleanAndDeleteCluster (const pandora::Algorithm &algorithm, const pandora::Cluster *const pCluster)
static pandora::StatusCode CleanAndDeleteClusters (const pandora::Algorithm &algorithm, const pandora::ClusterList &clusterList)
Detailed Description
ClusterHelper class.
Definition at line 107 of file ClusterHelper.h.
Member Function Documentation
pandora::StatusCode arbor_content::ClusterHelper::CleanAndDeleteCluster (const pandora::Algorithm & algorithm, const pandora::Cluster *const pCluster) static
Definition at line 731 of file ClusterHelper.cc.
References ArborContentApi::RemoveAndDeleteAllConnections().
Referenced by CleanAndDeleteClusters().
   {
     pandora::CaloHitList clusterCaloHitList;
     pCluster->GetOrderedCaloHitList().GetCaloHitList(clusterCaloHitList);
     for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin() , endIter = clusterCaloHitList.end() ;
         endIter != iter ; ++iter)
     {
       const arbor_content::CaloHit *const pCaloHit(dynamic_cast<const arbor_content::CaloHit *const>(*iter));
       if(NULL == pCaloHit)
         continue;
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::RemoveAndDeleteAllConnections(pCaloHit));
     }
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::Delete(algorithm, pCluster));
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::CleanAndDeleteClusters (const pandora::Algorithm & algorithm, const pandora::ClusterList & clusterList) static
Definition at line 754 of file ClusterHelper.cc.
References CleanAndDeleteCluster().
Referenced by arbor_content::PhotonReconstructionAlgorithm::SelectPhotonsAndRemoveOthers().
   {
     for(pandora::ClusterList::const_iterator iter = clusterList.begin(), endIter = clusterList.end() ;
         endIter != iter ; ++iter)
     {
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::CleanAndDeleteCluster(algorithm, *iter));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
bool arbor_content::ClusterHelper::ContainsHitType (const pandora::Cluster *const pCluster, const pandora::HitType hitType) static
Whether the cluster contains at least one hit of target type.
Parameters
pCluster to check
hitType the hit type to look for
Definition at line 329 of file ClusterHelper.cc.
Referenced by arbor_content::FragmentRemovalAlgorithm::FindClusterFragments(), arbor_content::ParticleIdHelper::GetStartingPseudoLayer(), IsClusterLeavingDetector(), and arbor_content::ArborEmShowerId::IsMatch().
   {
     const pandora::OrderedCaloHitList &orderedCaloHitList(pCluster->GetOrderedCaloHitList());
     for (pandora::OrderedCaloHitList::const_reverse_iterator iter = orderedCaloHitList.rbegin(), iterEnd = orderedCaloHitList.rend(); iter != iterEnd; ++iter)
     {
       for (pandora::CaloHitList::const_iterator hIter = iter->second->begin(), hIterEnd = iter->second->end(); hIter != hIterEnd; ++hIter)
       {
         const pandora::CaloHit *const pCaloHit(*hIter);
         if (hitType == pCaloHit->GetHitType())
           return true;
       }
     }
     return false;
   }
bool arbor_content::ClusterHelper::DoesClusterCrossGapRegion (const pandora::Pandora & pandora, const pandora::Cluster *const pCluster, const unsigned int startLayer, const unsigned int endLayer, const pandora::DetectorGap *& pDetectorGap, const unsigned int nSamplingPoints = 50) static
Whether a linear fit to a cluster crosses a registered gap region.
Only the region between the startlayer and endlayer is considered in the fit and in the comparison with registered gap regions.
Parameters
pandora the associated pandora instance
pCluster address of the cluster
startLayer the start layer (adjusted to maximum of specified layer and cluster inner layer)
endLayer the end layer (adjusted to minimum of specified layer and cluster outer layer)
pDetectorGap the crossing gap to receive, if any
nSamplingPoints number of points at which to sample the fit within the specified layer region
Returns
boolean
Definition at line 514 of file ClusterHelper.cc.
References DoesFitCrossGapRegion().
   {
     const unsigned int fitStartLayer(std::max(startLayer, pCluster->GetInnerPseudoLayer()));
     const unsigned int fitEndLayer(std::min(endLayer, pCluster->GetOuterPseudoLayer()));
     if (fitStartLayer > fitEndLayer)
       throw pandora::StatusCodeException(pandora::STATUS_CODE_INVALID_PARAMETER);
     pandora::ClusterFitResult fitResult;
     if (pandora::STATUS_CODE_SUCCESS != pandora::ClusterFitHelper::FitLayers(pCluster, fitStartLayer, fitEndLayer, fitResult))
       return false;
     const pandora::CartesianVector startLayerCentroid(pCluster->GetCentroid(fitStartLayer));
     const float propagationDistance((pCluster->GetCentroid(fitEndLayer) - startLayerCentroid).GetDotProduct(fitResult.GetDirection()));
     return ClusterHelper::DoesFitCrossGapRegion(pandora, fitResult, startLayerCentroid, propagationDistance, pDetectorGap, nSamplingPoints);
   }
bool arbor_content::ClusterHelper::DoesFitCrossGapRegion (const pandora::Pandora & pandora, const pandora::ClusterFitResult & clusterFitResult, const pandora::CartesianVector & startPosition, const float propagationDistance, const pandora::DetectorGap *& pDetectorGap, const unsigned int nSamplingPoints = 50) static
Whether a linear fit crosses a registered gap region.
The fit will be propagated through the specified distance from its closest approach to the startPosition. Within this propagation, the fit will be sampled a specified number of times and the resulting position compared with registered gap regions.
Parameters
pandora the associated pandora instance
clusterFitResult the cluster fit result
startPosition the propagation start position (adjusted to closest point on fit trajectory)
propagationDistance the propagation distance, which can be negative for propagation towards the ip
pDetectorGap the detector gap to receive, if any
nSamplingPoints number of points at which to sample the fit within its propagation
Returns
boolean
Definition at line 535 of file ClusterHelper.cc.
Referenced by DoesClusterCrossGapRegion().
   {
     const pandora::CartesianVector &fitDirection(clusterFitResult.GetDirection());
     const pandora::CartesianVector &fitIntercept(clusterFitResult.GetIntercept());
     const float fitStartDistance((startPosition - fitIntercept).GetDotProduct(fitDirection));
     const pandora::CartesianVector fitStartPosition(fitIntercept + (fitDirection * fitStartDistance));
     const pandora::CartesianVector fitPropagation(fitDirection * propagationDistance);
     const pandora::DetectorGapList &detectorGapList(pandora.GetGeometry()->GetDetectorGapList());
     for (unsigned int i = 0; i < nSamplingPoints; ++i)
     {
       const pandora::CartesianVector fitPosition(fitStartPosition + (fitPropagation * (static_cast<float>(i) / static_cast<float>(nSamplingPoints))));
       for (pandora::DetectorGapList::const_iterator iter = detectorGapList.begin(), iterEnd = detectorGapList.end(); iter != iterEnd; ++iter)
       {
         // ATTN Could pass (e.g. inner layer) hit type for cluster, but know that actually need to pass only any 3D hit type (hack)
         if ((*iter)->IsInGap(fitPosition, pandora::ECAL))
         {
           pDetectorGap = *iter;
           return true;
         }
       }
     }
     return false;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetCaloHitsNearDetectorGap (const pandora::Pandora & pandora, const pandora::Cluster *const pCluster, const pandora::DetectorGap *const pDetectorGap, const float maxDistanceFine, const float maxDistanceCoarse, pandora::CaloHitList & caloHitList, bool shouldUseIsolatedHits) static
Get the calo hit list belonging to the cluster, close to all registered detector gaps.
Parameters
pandora the pandora instance to access pandora content
pCluster the input cluster address
pDetectorGap the detector gap to consider
maxDistance the maximum distance between the gap and a calo hit
caloHitList the list of calo hit near a detector gap
shouldUseIsolatedHits whether to consider isolated calo hits from the input cluster
Definition at line 698 of file ClusterHelper.cc.
References GetDistanceToDetectorGap().
Referenced by GetCaloHitsNearDetectorGaps().
   {
     if(0 == pCluster->GetNCaloHits())
       return pandora::STATUS_CODE_SUCCESS;
     pandora::CaloHitList clusterCaloHitList;
     pCluster->GetOrderedCaloHitList().GetCaloHitList(clusterCaloHitList);
     for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin() , endIter = clusterCaloHitList.end() ;
         endIter != iter ; ++iter)
     {
       const pandora::CaloHit *const pCaloHit(*iter);
       if(!shouldUseIsolatedHits && pCaloHit->IsIsolated())
         continue;
       const pandora::Granularity &granularity(pandora.GetGeometry()->GetHitTypeGranularity(pCaloHit->GetHitType()));
       const float maxDistance(granularity <= pandora::FINE ? maxDistanceFine : maxDistanceCoarse);
       float distanceToGap(0.f);
       if(pandora::STATUS_CODE_SUCCESS != ClusterHelper::GetDistanceToDetectorGap(pCaloHit->GetPositionVector(), pDetectorGap, distanceToGap))
         continue;
       if(distanceToGap < maxDistance)
         caloHitList.insert(pCaloHit);
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetCaloHitsNearDetectorGaps (const pandora::Pandora & pandora, const pandora::Cluster *const pCluster, const float maxDistanceFine, const float maxDistanceCoarse, pandora::CaloHitList & caloHitList, bool shouldUseIsolatedHits) static
Get the calo hit list belonging to the cluster, close to all registered detector gaps.
Parameters
pandora the pandora instance to access pandora content
pCluster the input cluster address
maxDistance the maximum distance between the gap and a calo hit
caloHitList the list of calo hit near a detector gap
shouldUseIsolatedHits whether to consider isolated calo hits from the input cluster
Definition at line 682 of file ClusterHelper.cc.
References GetCaloHitsNearDetectorGap().
Referenced by arbor_content::SingleParticleMonitoringAlgorithm::Run().
   {
     const pandora::DetectorGapList &detectorGapList(pandora.GetGeometry()->GetDetectorGapList());
     for (pandora::DetectorGapList::const_iterator iter = detectorGapList.begin(), iterEnd = detectorGapList.end(); iter != iterEnd; ++iter)
     {
       const pandora::DetectorGap *const pDetectorGap(*iter);
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCaloHitsNearDetectorGap(pandora, pCluster, pDetectorGap, maxDistanceFine, maxDistanceCoarse, caloHitList, shouldUseIsolatedHits));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetCentroid (const pandora::Cluster *const pCluster, pandora::CartesianVector & centroid) static
Get the cluster centroid.
Parameters
pCluster the cluster to evaluate the centroid
centroid the centroid to receive
Definition at line 124 of file ClusterHelper.cc.
Referenced by arbor_content::PointingClusterAssociationAlgorithm::FindBestParentCluster(), GetCentroidDistance(), arbor_content::PointingClusterAssociationAlgorithm::GetClusterBackwardDirection(), arbor_content::ThetaEnergyFunction::GetCosTheta(), arbor_content::ParticleIdHelper::GetStartingPseudoLayer(), and arbor_content::MissingEnergyReclusteringAlgorithm::Run().
   {
     const pandora::OrderedCaloHitList &orderedCaloHitList(pCluster->GetOrderedCaloHitList());
     for(pandora::OrderedCaloHitList::const_iterator iter = orderedCaloHitList.begin(), endIter = orderedCaloHitList.end() ;
         endIter != iter ; ++iter)
     {
       centroid += pCluster->GetCentroid(iter->first);
     }
     centroid *= 1.f/(orderedCaloHitList.size());
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetCentroidDistance (const pandora::Cluster *const pCluster, const pandora::CartesianVector & point, float & centroidDistance) static
Get the distance between the cluster centroid and the given position vector.
Parameters
pCluster the cluster to evaluate the closest distance approach
point the position vector
centroidDistance the distance between the point and the cluster centroid, unit mm
Definition at line 170 of file ClusterHelper.cc.
References GetCentroid().
   {
     centroidDistance = std::numeric_limits<float>::max();
     if(NULL == pCluster)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     if(0 == pCluster->GetNCaloHits())
       return pandora::STATUS_CODE_FAILURE;
     pandora::CartesianVector clusterCentroid(0.f, 0.f, 0.f);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, clusterCentroid));
     centroidDistance = (clusterCentroid - point).GetMagnitude();
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetChiClusterMerging (const pandora::Pandora & pandora, const pandora::Cluster *const pClusterToEnlarge, const pandora::Cluster *const pClusterToMerge, float & oldChi, float & newChi) static
Evaluate the chi before and after to merge the two clusters.
Parameters
pandora the pandora instance to access internal content
pClusterToEnlarge the cluster to enlarge
pClusterToMerge the cluster to merge
oldChi the chi of the cluster to enlarge
newChi the chi of the clusters after a potential merging
Definition at line 407 of file ClusterHelper.cc.
References arbor_content::ReclusterHelper::GetTrackClusterCompatibility().
Referenced by arbor_content::PointingClusterAssociationAlgorithm::FindBestParentCluster(), and arbor_content::MipFragmentMergingAlg::FindChargedMipFragments().
   {
     const pandora::TrackList trackList(pClusterToEnlarge->GetAssociatedTrackList());
     pandora::TrackList trackListCombined(pClusterToMerge->GetAssociatedTrackList());
     trackListCombined.insert(trackList.begin(), trackList.end());
     if(trackList.empty())
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     float trackEnergySum(0.f);
     float trackEnergySumCombined(0.f);
     for (pandora::TrackList::const_iterator trackIter = trackList.begin(), trackIterEnd = trackList.end(); trackIter != trackIterEnd; ++trackIter)
       trackEnergySum += (*trackIter)->GetEnergyAtDca();
     for (pandora::TrackList::const_iterator trackIter = trackListCombined.begin(), trackIterEnd = trackListCombined.end(); trackIter != trackIterEnd; ++trackIter)
       trackEnergySumCombined += (*trackIter)->GetEnergyAtDca();
     const float clusterEnergy(pClusterToEnlarge->GetTrackComparisonEnergy(pandora));
     const float clusterEnergyCombined(clusterEnergy + pClusterToMerge->GetTrackComparisonEnergy(pandora));
     oldChi = ReclusterHelper::GetTrackClusterCompatibility(pandora, clusterEnergy, trackEnergySum);
     newChi = ReclusterHelper::GetTrackClusterCompatibility(pandora, clusterEnergyCombined, trackEnergySumCombined);
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetClosestDistanceApproach (const pandora::Cluster *const pCluster, const pandora::CartesianVector & point, float & closestDistance) static
Get the closest distance approach between all the hits of the cluster and the given position vector.
Parameters
pCluster the cluster to evaluate the closest distance approach
point the position vector
closestDistance the closest distance approach between the point and the cluster, unit mm
Definition at line 141 of file ClusterHelper.cc.
Referenced by arbor_content::CaloHitMergingTool::FindCaloHitClusterMerging(), GetClosestDistanceApproach(), and arbor_content::MissingEnergyReclusteringAlgorithm::Run().
   {
     closestDistance = std::numeric_limits<float>::max();
     if(NULL == pCluster)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     if(0 == pCluster->GetNCaloHits())
       return pandora::STATUS_CODE_FAILURE;
     pandora::CaloHitList clusterCaloHitList;
     pCluster->GetOrderedCaloHitList().GetCaloHitList(clusterCaloHitList);
     for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin() , endIter = clusterCaloHitList.end() ;
         endIter != iter ; ++iter)
     {
       const pandora::CaloHit *const pCaloHit = *iter;
       const float distance = (pCaloHit->GetPositionVector() - point).GetMagnitude();
       if(closestDistance > distance)
         closestDistance = distance;
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetClosestDistanceApproach (const pandora::Cluster *const pCluster1, const pandora::Cluster *const pCluster2, float & closestDistance) static
Get the closest distance approach between all the hits of the clusters.
Parameters
pCluster the first cluster
pCluster the second cluster
closestDistance the closest distance approach between the two clusters, unit mm
Definition at line 191 of file ClusterHelper.cc.
References GetClosestDistanceApproach().
   {
     closestDistance = std::numeric_limits<float>::max();
     if(NULL == pCluster1 || NULL == pCluster2)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     if(0 == pCluster1->GetNCaloHits() || 0 == pCluster2->GetNCaloHits())
       return pandora::STATUS_CODE_FAILURE;
     pandora::CaloHitList clusterCaloHitList1;
     pCluster1->GetOrderedCaloHitList().GetCaloHitList(clusterCaloHitList1);
     for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList1.begin() , endIter = clusterCaloHitList1.end() ;
         endIter != iter ; ++iter)
     {
       const pandora::CaloHit *const pCaloHit = *iter;
       float closestHitDistanceApproach(std::numeric_limits<float>::max());
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetClosestDistanceApproach(pCluster2,
           pCaloHit->GetPositionVector(), closestHitDistanceApproach));
       if(closestHitDistanceApproach < closestDistance)
         closestDistance = closestHitDistanceApproach;
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetDistanceToDetectorGap (const pandora::CartesianVector & positionVector, const pandora::DetectorGap *const pDetectorGap, float & distanceToGap) static
Get the distance to detector gap.
Parameters
positionVector the position in space to test
pDetectorGap the detector gap to consider
distanceToGap the distance to detector gap to receive
Definition at line 567 of file ClusterHelper.cc.
Referenced by GetCaloHitsNearDetectorGap().
   {
     distanceToGap = 0.f;
     if(NULL == pDetectorGap)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     if(pDetectorGap->IsInGap(positionVector, pandora::ECAL))
       return pandora::STATUS_CODE_FAILURE;
     const pandora::BoxGap *const pBoxGap(dynamic_cast<const pandora::BoxGap *const>(pDetectorGap));
     if(pBoxGap)
     {
       const pandora::CartesianVector relativePosition(positionVector - pBoxGap->GetVertex());
       const float projection1(relativePosition.GetDotProduct(pBoxGap->GetSide1().GetUnitVector()));
       const float projection2(relativePosition.GetDotProduct(pBoxGap->GetSide2().GetUnitVector()));
       const float projection3(relativePosition.GetDotProduct(pBoxGap->GetSide3().GetUnitVector()));
       distanceToGap = std::min(fabs(projection1), std::min(fabs(projection2), fabs(projection3)));
       return pandora::STATUS_CODE_SUCCESS;
     }
     const pandora::ConcentricGap *const pConcentricGap(dynamic_cast<const pandora::ConcentricGap *const>(pDetectorGap));
     if(pConcentricGap)
     {
       const float z(positionVector.GetZ());
       const float x(positionVector.GetX()), y(positionVector.GetY());
       const float r(std::sqrt(x * x + y * y));
       bool inner(false), outer(false);
       const bool inZ(pConcentricGap->GetMaxZCoordinate() < z && pConcentricGap->GetMinZCoordinate() > z);
       float zDistance(0.f), rInnerDistance(0.f), rOuterDistance(0.f);
       if(pConcentricGap->GetMaxZCoordinate() < z)
       {
         zDistance = fabs(z - pConcentricGap->GetMaxZCoordinate());
       }
       if(pConcentricGap->GetMinZCoordinate() > z)
       {
         zDistance = fabs(z - pConcentricGap->GetMinZCoordinate());
       }
       // inner r case
       for(unsigned int i=0 ; i<pConcentricGap->GetInnerSymmetryOrder()+1 ; i++)
       {
         const float phi = pConcentricGap->GetInnerPhiCoordinate() + 2 * M_PI * (static_cast<float>(i) / static_cast<float>(pConcentricGap->GetInnerSymmetryOrder()));
         const float phiMin = phi - (2 * M_PI / static_cast<float>(pConcentricGap->GetInnerSymmetryOrder())) / 2.f;
         const float phiMax = phi + (2 * M_PI / static_cast<float>(pConcentricGap->GetInnerSymmetryOrder())) / 2.f;
         const float phiPosition(std::atan2(y, x));
         if(phiPosition > phiMin && phiPosition < phiMax)
         {
           const pandora::CartesianVector normaleVector(std::cos(phi), std::sin(phi), 0.f);
           if(r*std::cos(normaleVector.GetOpeningAngle(positionVector)) < pConcentricGap->GetInnerRCoordinate())
           {
             rInnerDistance = fabs(pConcentricGap->GetInnerRCoordinate() - r*std::cos(normaleVector.GetOpeningAngle(positionVector)));
             inner = true;
           }
           break;
         }
       }
       // outer r case
       for(unsigned int i=0 ; i<pConcentricGap->GetOuterSymmetryOrder()+1 ; i++)
       {
         const float phi = pConcentricGap->GetOuterPhiCoordinate() + 2 * M_PI * (static_cast<float>(i) / static_cast<float>(pConcentricGap->GetOuterSymmetryOrder()));
         const float phiMin = phi - (2 * M_PI / static_cast<float>(pConcentricGap->GetOuterSymmetryOrder())) / 2.f;
         const float phiMax = phi + (2 * M_PI / static_cast<float>(pConcentricGap->GetOuterSymmetryOrder())) / 2.f;
         const float phiPosition(std::atan2(y, x));
         if(phiPosition > phiMin && phiPosition < phiMax)
         {
           const pandora::CartesianVector normaleVector(std::cos(phi), std::sin(phi), 0.f);
           if(r*std::cos(normaleVector.GetOpeningAngle(positionVector)) > pConcentricGap->GetOuterRCoordinate())
           {
             rOuterDistance = fabs(r*std::cos(normaleVector.GetOpeningAngle(positionVector)) - pConcentricGap->GetOuterRCoordinate());
             outer = true;
           }
           break;
         }
       }
       if(!inner && !outer)
       {
         distanceToGap = fabs(zDistance);
       }
       else if(inZ)
       {
         if(inner)
           distanceToGap = fabs(rInnerDistance);
         else
           distanceToGap = fabs(rOuterDistance);
       }
       else
       {
         float rDistance(inner ? rInnerDistance : rOuterDistance);
         distanceToGap = std::sqrt(fabs(rDistance)*fabs(rDistance) + fabs(zDistance)*fabs(zDistance));
       }
       return pandora::STATUS_CODE_SUCCESS;
     }
     return pandora::STATUS_CODE_FAILURE;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetMeanDensity (const pandora::Cluster *const pCluster, float & meanDensity) static
Get the mean density of the cluster.
Parameters
pCluster the input cluster
meanDensity the mean density to receive
Definition at line 378 of file ClusterHelper.cc.
References arbor_content::CaloHit::GetDensity().
Referenced by arbor_content::FragmentRemovalAlgorithm::FindClusterFragments().
   {
     if(NULL == pCluster || 0 == pCluster->GetNCaloHits())
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     meanDensity = 0.f;
     const pandora::OrderedCaloHitList &orderedCaloHitList(pCluster->GetOrderedCaloHitList());
     for (pandora::OrderedCaloHitList::const_reverse_iterator iter = orderedCaloHitList.rbegin(), iterEnd = orderedCaloHitList.rend(); iter != iterEnd; ++iter)
     {
       for (pandora::CaloHitList::const_iterator hIter = iter->second->begin(), hIterEnd = iter->second->end(); hIter != hIterEnd; ++hIter)
       {
         const arbor_content::CaloHit *const pCaloHit(dynamic_cast<const arbor_content::CaloHit *const>(*hIter));
         if(NULL == pCaloHit)
           return pandora::STATUS_CODE_INVALID_PARAMETER;
         meanDensity += pCaloHit->GetDensity();
       }
     }
     meanDensity /= pCluster->GetNCaloHits();
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetMeanSurroundingEnergy (const pandora::Cluster *const pCluster, float & meanSurroundingEnergy) static
Get the mean surrounding energy of the cluster.
Parameters
pCluster the input cluster
meanSurroundingEnergy the mean surrounding energy to receive
Definition at line 349 of file ClusterHelper.cc.
References arbor_content::CaloHit::GetSurroundingEnergy().
   {
     if(NULL == pCluster || 0 == pCluster->GetNCaloHits())
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     meanSurroundingEnergy = 0.f;
     const pandora::OrderedCaloHitList &orderedCaloHitList(pCluster->GetOrderedCaloHitList());
     for (pandora::OrderedCaloHitList::const_reverse_iterator iter = orderedCaloHitList.rbegin(), iterEnd = orderedCaloHitList.rend(); iter != iterEnd; ++iter)
     {
       for (pandora::CaloHitList::const_iterator hIter = iter->second->begin(), hIterEnd = iter->second->end(); hIter != hIterEnd; ++hIter)
       {
         const arbor_content::CaloHit *const pCaloHit(dynamic_cast<const arbor_content::CaloHit *const>(*hIter));
         if(NULL == pCaloHit)
           return pandora::STATUS_CODE_INVALID_PARAMETER;
         meanSurroundingEnergy += pCaloHit->GetSurroundingEnergy();
       }
     }
     meanSurroundingEnergy /= pCluster->GetNCaloHits();
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetNCaloHitSeeds (const pandora::Cluster *const pCluster, unsigned int & nSeeds) static
Get the number of calo hit seeds in the cluster.
Parameters
pCluster the cluster to get the number of calo hit seeds
nSeeds the number of seeds to receive
Definition at line 223 of file ClusterHelper.cc.
References arbor_content::CaloHitHelper::ExtractSeedCaloHitList().
   {
     if(NULL == pCluster)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     pandora::CaloHitList clusterCaloHitList;
     pandora::CaloHitList seedsCaloHitList;
     pCluster->GetOrderedCaloHitList().GetCaloHitList(clusterCaloHitList);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, CaloHitHelper::ExtractSeedCaloHitList(&clusterCaloHitList, seedsCaloHitList));
     nSeeds = seedsCaloHitList.size();
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ClusterHelper::GetTrackClusterDistance (const pandora::Pandora & pandora, const pandora::Cluster *const pCluster, const pandora::Track *const pTrack, const float maxTransverseDistance, float & trackClusterDistance) static
Get the track cluster distance.
Parameters
pandora the pandora instance to access internal content
pCluster the input cluster
pTrack the input track
maxTransverseDistance the maximum distance between cluster hits and the track helix
trackClusterDistance the track cluster distance to receive
Definition at line 468 of file ClusterHelper.cc.
References arbor_content::GeometryHelper::GetProjectionOnHelix().
Referenced by arbor_content::UnassociatedTrackRecoveryAlg::PerformPossibleTrackClusterAssociations().
   {
     pandora::CaloHitList clusterCaloHitList;
     pCluster->GetOrderedCaloHitList().GetCaloHitList(clusterCaloHitList);
     const float bField(pandora.GetPlugins()->GetBFieldPlugin()->GetBField(pandora::CartesianVector(0.f, 0.f, 0.f)));
     const pandora::Helix helix(pTrack->GetTrackStateAtCalorimeter().GetPosition(),
         pTrack->GetTrackStateAtCalorimeter().GetMomentum(), pTrack->GetCharge(), bField);
     const pandora::CartesianVector trackProjection(pTrack->GetTrackStateAtCalorimeter().GetPosition());
     unsigned int nNearbyCaloHits(0);
     float distanceToHelix(0.f);
     for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin() , endIter = clusterCaloHitList.end() ;
         endIter != iter ; ++iter)
     {
       const pandora::CaloHit *const pCaloHit(*iter);
       const float trackHitAngle(pCaloHit->GetPositionVector().GetOpeningAngle(trackProjection));
       // cut needed for discriminate track opposite direction
       if(trackHitAngle > (2*M_PI)/3.f)
         continue;
       pandora::CartesianVector projectionOnHelix(0.f, 0.f, 0.f);
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetProjectionOnHelix(helix, pCaloHit->GetPositionVector(), projectionOnHelix));
       const float hitDistanceToHelix((pCaloHit->GetPositionVector()-projectionOnHelix).GetMagnitude());
       if(hitDistanceToHelix < maxTransverseDistance)
       {
         ++nNearbyCaloHits;
         distanceToHelix += hitDistanceToHelix;
       }
     }
     if(0 == nNearbyCaloHits)
       return pandora::STATUS_CODE_NOT_FOUND;
     trackClusterDistance = distanceToHelix / nNearbyCaloHits;
     return pandora::STATUS_CODE_SUCCESS;
   }
bool arbor_content::ClusterHelper::IsClusterLeavingDetector (const pandora::Pandora & pandora, const pandora::Cluster *const pCluster, unsigned int nOuterLayersToExamine = 3, float maxDistanceToDetectorEdge = 50.f, unsigned int minNHitsNearEdges = 3) static
Whether the cluster is leaving the detector.
Parameters
pandora the pandora instance to access internal content
pCluster the cluster address
nOuterLayersToExamine the number of outer layers of the cluster to examine
maxDistanceToDetectorEdge the distance to the detector edge for a target calo hit
minNHitsNearEdges the minimum number of calo hit near the detector edge to consider the cluster as leaving the detector
Definition at line 242 of file ClusterHelper.cc.
References ContainsHitType(), and arbor_content::GeometryHelper::GetOuterNormaleVector().
Referenced by arbor_content::EnergyExcessReclusteringAlgorithm::Run(), and arbor_content::MissingEnergyReclusteringAlgorithm::Run().
   {
     if(NULL == pCluster)
       throw pandora::StatusCodeException(pandora::STATUS_CODE_INVALID_PARAMETER);
     // muons escape detector
     if( abs(pCluster->GetParticleIdFlag()) == 13 || ClusterHelper::ContainsHitType(pCluster, pandora::MUON))
       return true;
     if(pandora::HCAL != pCluster->GetOuterLayerHitType())
       return false;
     const pandora::OrderedCaloHitList &orderedCaloHitList(pCluster->GetOrderedCaloHitList());
     const unsigned int outerPseudoLayer(pCluster->GetOuterPseudoLayer());
     const unsigned int innerPseudoLayer(pCluster->GetInnerPseudoLayer());
     const unsigned int nPseudoLayers(outerPseudoLayer-innerPseudoLayer+1);
     const unsigned int pseudoLayerStart(nPseudoLayers < nOuterLayersToExamine ? innerPseudoLayer : outerPseudoLayer-nOuterLayersToExamine);
     const pandora::GeometryManager *const pGeometry = pandora.GetGeometry();
     const pandora::SubDetector &hcalEndcap(pGeometry->GetSubDetector(pandora::HCAL_ENDCAP));
     const pandora::SubDetector &hcalBarrel(pGeometry->GetSubDetector(pandora::HCAL_BARREL));
     const float hcalEndcapOuterZCoordinate(hcalEndcap.GetOuterZCoordinate());
     const float hcalEndcapOuterRCoordinate(hcalEndcap.GetOuterRCoordinate());
     const float hcalBarrelOuterRCoordinate(hcalBarrel.GetOuterRCoordinate());
     unsigned int nHitsNearbyEdge(0);
     for(unsigned int pl=pseudoLayerStart ; pl<outerPseudoLayer ; ++pl)
     {
       pandora::OrderedCaloHitList::const_iterator iter = orderedCaloHitList.find(pl);
       if(orderedCaloHitList.end() == iter)
         continue;
       for (pandora::CaloHitList::const_iterator hitIter = iter->second->begin(), hitIterEnd = iter->second->end() ;
           hitIter != hitIterEnd; ++hitIter)
       {
         const pandora::CaloHit *const pCaloHit(*hitIter);
         if(pandora::HCAL != pCaloHit->GetHitType())
           continue;
         if(pandora::ENDCAP == pCaloHit->GetHitRegion())
         {
           pandora::CartesianVector outerNormaleVector(0.f, 0.f, 0.f);
           if(pandora::STATUS_CODE_SUCCESS != GeometryHelper::GetOuterNormaleVector(pandora, pandora::HCAL_ENDCAP, (*hitIter)->GetPositionVector(), outerNormaleVector))
             continue;
           const float hitCosAngleNormale(outerNormaleVector.GetCosOpeningAngle(pCaloHit->GetPositionVector()));
           const float hitDistanceToOrigin(pCaloHit->GetPositionVector().GetMagnitude());
           const float hitDistanceToREdge(hcalEndcapOuterRCoordinate - hitDistanceToOrigin*hitCosAngleNormale);
           const float hitDistanceToZEdge(hcalEndcapOuterZCoordinate-fabs(pCaloHit->GetPositionVector().GetZ()));
           if(hitDistanceToREdge < maxDistanceToDetectorEdge)
             ++nHitsNearbyEdge;
           else if(hitDistanceToZEdge < maxDistanceToDetectorEdge)
             ++nHitsNearbyEdge;
         }
         else if(pandora::BARREL == pCaloHit->GetHitRegion())
         {
           pandora::CartesianVector outerNormaleVector(0.f, 0.f, 0.f);
           if(pandora::STATUS_CODE_SUCCESS != GeometryHelper::GetOuterNormaleVector(pandora, pandora::HCAL_BARREL, (*hitIter)->GetPositionVector(), outerNormaleVector))
             continue;
           const float hitCosAngleNormale(outerNormaleVector.GetCosOpeningAngle(pCaloHit->GetPositionVector()));
           const float hitDistanceToOrigin(pCaloHit->GetPositionVector().GetMagnitude());
           const float hitDistanceToEdge(hcalBarrelOuterRCoordinate - hitDistanceToOrigin*hitCosAngleNormale);
           if(hitDistanceToEdge < maxDistanceToDetectorEdge)
             ++nHitsNearbyEdge;
         }
       }
     }
     if(nHitsNearbyEdge >= minNHitsNearEdges)
       return true;
     return false;
   }
pandora::StatusCode arbor_content::ClusterHelper::MergeClusters (const pandora::Algorithm & algorithm, ClusterToClusterMap & clusterToClusterMap) static
Perform intelligent merging of clusters (daughter <-> parent relationship management)
Parameters
algorithm the algorithm that requests the merging
clusterToClusterMap the mapping of clusters to merge (daughter -> parent)
Definition at line 437 of file ClusterHelper.cc.
Referenced by arbor_content::PointingClusterAssociationAlgorithm::Run().
   {
     for(ClusterToClusterMap::iterator iter = clusterToClusterMap.begin(), endIter = clusterToClusterMap.end() ;
         endIter != iter ; ++iter)
     {
       const pandora::Cluster *const pDaughterCluster(iter->first);
       const pandora::Cluster *const pParentCluster(iter->second);
       if((NULL == pDaughterCluster) || (NULL == pParentCluster))
         continue;
       for(ClusterToClusterMap::iterator jter = clusterToClusterMap.begin(), endJter = clusterToClusterMap.end() ;
           endJter != jter ; ++jter)
       {
         if(jter->first == pDaughterCluster)
           continue;
         if(jter->second == pDaughterCluster)
           jter->second = pParentCluster;
       }
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::MergeAndDeleteClusters(algorithm, pParentCluster, pDaughterCluster));
       (iter->second) = NULL;
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
The documentation for this class was generated from the following files:
ClusterHelper.h
ClusterHelper.cc