ArborContent: arbor_content::PerfectClusteringAlgorithm Class Reference
arbor_content::PerfectClusteringAlgorithm Class Reference
PerfectClusteringAlgorithm class.
#include <PerfectClusteringAlgorithm.h>
Classes
class Factory
Factory class for instantiating algorithm.
Public Member Functions
PerfectClusteringAlgorithm ()
Default constructor.
Protected Member Functions
virtual bool SelectMCParticlesForClustering (const pandora::MCParticle *const pMCParticle) const
Private Types
typedef std::map< const
pandora::MCParticle
*, pandora::CaloHitList * > MCParticleToHitListMap
Private Member Functions
pandora::StatusCode Run ()
pandora::StatusCode ReadSettings (const pandora::TiXmlHandle xmlHandle)
void SimpleMCParticleCollection (const pandora::CaloHit *const pCaloHit, MCParticleToHitListMap &mcParticleToHitListMap) const
Simple mc particle collection, using main mc particle associated with each calo hit.
void FullMCParticleCollection (const pandora::CaloHit *const pCaloHit, MCParticleToHitListMap &mcParticleToHitListMap) const
Full mc particle collection, using map of mc particles to hit weights; fragment calo hits where necessary.
void AddToHitListMap (const pandora::CaloHit *const pCaloHitToAdd, const pandora::MCParticle *const pMCParticle, MCParticleToHitListMap &mcParticleToHitListMap) const
Add a calo hit to the mc particle to hit list map.
void CreateClusters (const MCParticleToHitListMap &mcParticleToHitListMap) const
Create clusters based on information in the mc particle to hit list map.
Private Attributes
pandora::IntVector m_particleIdList
list of particle ids of MCPFOs to be selected
bool m_shouldUseOnlyECalHits
Whether to only use ecal hits in the clustering algorithm.
bool m_shouldUseIsolatedHits
Whether to use isolated hits in the clustering algorithm.
bool m_simpleMCParticleCollection
Whether to use simple mc particle collection mechanism, or full mechanism.
float m_minWeightFraction
The minimum mc particle calo hit weight for clustering consideration.
Detailed Description
PerfectClusteringAlgorithm class.
Definition at line 21 of file PerfectClusteringAlgorithm.h.
Member Typedef Documentation
typedef std::map<const pandora::MCParticle*, pandora::CaloHitList*> arbor_content::PerfectClusteringAlgorithm::MCParticleToHitListMap private
Definition at line 45 of file PerfectClusteringAlgorithm.h.
Constructor & Destructor Documentation
arbor_content::PerfectClusteringAlgorithm::PerfectClusteringAlgorithm ()
Default constructor.
Definition at line 20 of file PerfectClusteringAlgorithm.cc.
Referenced by arbor_content::PerfectClusteringAlgorithm::Factory::CreateAlgorithm().
                                                          :
         m_shouldUseOnlyECalHits(false),
         m_shouldUseIsolatedHits(false),
         m_simpleMCParticleCollection(true),
         m_minWeightFraction(0.01f)
   {
   }
Member Function Documentation
void arbor_content::PerfectClusteringAlgorithm::AddToHitListMap (const pandora::CaloHit *const pCaloHitToAdd, const pandora::MCParticle *const pMCParticle, MCParticleToHitListMap & mcParticleToHitListMap) const private
Add a calo hit to the mc particle to hit list map.
Parameters
pCaloHit address of the calo hit
pMCParticle address of the mc particle
mcParticleToHitListMap the mc particle to hit list map
Definition at line 149 of file PerfectClusteringAlgorithm.cc.
Referenced by FullMCParticleCollection(), and SimpleMCParticleCollection().
   {
     MCParticleToHitListMap::iterator iter(mcParticleToHitListMap.find(pMCParticle));
     if (mcParticleToHitListMap.end() == iter)
     {
       CaloHitList *const pCaloHitList = new CaloHitList();
       pCaloHitList->insert(pCaloHitToAdd);
       (void) mcParticleToHitListMap.insert(MCParticleToHitListMap::value_type(pMCParticle, pCaloHitList));
     }
     else
     {
       iter->second->insert(pCaloHitToAdd);
     }
   }
void arbor_content::PerfectClusteringAlgorithm::CreateClusters (const MCParticleToHitListMap & mcParticleToHitListMap) const private
Create clusters based on information in the mc particle to hit list map.
Parameters
mcParticleToHitListMap the mc particle to hit list map
Definition at line 168 of file PerfectClusteringAlgorithm.cc.
Referenced by Run().
   {
     for (MCParticleToHitListMap::const_iterator iter = mcParticleToHitListMap.begin(), iterEnd = mcParticleToHitListMap.end();
         iter != iterEnd; ++iter)
     {
       const MCParticle *const pMCParticle = iter->first;
       CaloHitList *const pCaloHitList = iter->second;
       if (!pCaloHitList->empty())
       {
         const Cluster *pCluster = NULL;
         PandoraContentApi::Cluster::Parameters parameters;
         parameters.m_caloHitList = *pCaloHitList;
         PANDORA_THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, PandoraContentApi::Cluster::Create(*this, parameters, pCluster));
         PandoraContentApi::Cluster::Metadata metadata;
         switch (pMCParticle->GetParticleId())
         {
         case PHOTON:
         case E_PLUS:
         case E_MINUS:
         case MU_PLUS:
         case MU_MINUS:
           metadata.m_particleId = pMCParticle->GetParticleId();
           break;
         default:
           break;
         }
         if (metadata.m_particleId.IsInitialized())
           PANDORA_THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, PandoraContentApi::AlterMetadata(*this, pCluster, metadata));
       }
       delete pCaloHitList;
     }
   }
void arbor_content::PerfectClusteringAlgorithm::FullMCParticleCollection (const pandora::CaloHit *const pCaloHit, MCParticleToHitListMap & mcParticleToHitListMap) const private
Full mc particle collection, using map of mc particles to hit weights; fragment calo hits where necessary.
Parameters
pCaloHit address of the calo hit
mcParticleToHitListMap the mc particle to hit list map
Definition at line 102 of file PerfectClusteringAlgorithm.cc.
References AddToHitListMap(), m_minWeightFraction, SelectMCParticlesForClustering(), and SimpleMCParticleCollection().
Referenced by Run().
   {
     const MCParticleWeightMap mcParticleWeightMap(pCaloHit->GetMCParticleWeightMap());
     if (mcParticleWeightMap.size() < 2)
       return this->SimpleMCParticleCollection(pCaloHit, mcParticleToHitListMap);
     float mcParticleWeightSum(0.f);
     for (MCParticleWeightMap::const_iterator iter = mcParticleWeightMap.begin(), iterEnd = mcParticleWeightMap.end(); iter != iterEnd; ++iter)
       mcParticleWeightSum += iter->second;
     if (mcParticleWeightSum < std::numeric_limits<float>::epsilon())
       throw StatusCodeException(STATUS_CODE_FAILURE);
     const CaloHit *pLocalCaloHit = pCaloHit;
     for (MCParticleWeightMap::const_iterator iter = mcParticleWeightMap.begin(), iterEnd = mcParticleWeightMap.end(); iter != iterEnd; ++iter)
     {
       const MCParticle *const pMCParticle(iter->first);
       const float weight(iter->second);
       if (!this->SelectMCParticlesForClustering(pMCParticle))
         continue;
       const CaloHit *pCaloHitToAdd = pLocalCaloHit;
       if (pCaloHitToAdd->GetWeight() < std::numeric_limits<float>::epsilon())
         throw StatusCodeException(STATUS_CODE_FAILURE);
       const float weightFraction(weight / (mcParticleWeightSum * pCaloHitToAdd->GetWeight()));
       const bool isBelowThreshold((weightFraction - m_minWeightFraction) < std::numeric_limits<float>::epsilon());
       if (isBelowThreshold)
         continue;
       const bool shouldFragment(weightFraction + m_minWeightFraction - 1.f < std::numeric_limits<float>::epsilon());
       if (shouldFragment)
         PANDORA_THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, PandoraContentApi::Fragment(*this, pLocalCaloHit, weightFraction, pCaloHitToAdd, pLocalCaloHit));
       this->AddToHitListMap(pCaloHitToAdd, pMCParticle, mcParticleToHitListMap);
     }
   }
StatusCode arbor_content::PerfectClusteringAlgorithm::ReadSettings (const pandora::TiXmlHandle xmlHandle) private
Definition at line 207 of file PerfectClusteringAlgorithm.cc.
References m_minWeightFraction, m_particleIdList, m_shouldUseIsolatedHits, m_shouldUseOnlyECalHits, and m_simpleMCParticleCollection.
   {
     PANDORA_RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::ReadVectorOfValues(xmlHandle,
         "ParticleIdList", m_particleIdList));
     PANDORA_RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::ReadValue(xmlHandle,
         "ShouldUseOnlyECalHits", m_shouldUseOnlyECalHits));
     PANDORA_RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::ReadValue(xmlHandle,
         "ShouldUseIsolatedHits", m_shouldUseIsolatedHits));
     PANDORA_RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::ReadValue(xmlHandle,
         "SimpleMCParticleCollection", m_simpleMCParticleCollection));
     PANDORA_RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, XmlHelper::ReadValue(xmlHandle,
         "MinWeightFraction", m_minWeightFraction));
     return STATUS_CODE_SUCCESS;
   }
StatusCode arbor_content::PerfectClusteringAlgorithm::Run () private
Definition at line 46 of file PerfectClusteringAlgorithm.cc.
References CreateClusters(), FullMCParticleCollection(), m_shouldUseIsolatedHits, m_shouldUseOnlyECalHits, m_simpleMCParticleCollection, and SimpleMCParticleCollection().
   {
     const CaloHitList *pCaloHitList = NULL;
     PANDORA_RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(*this, pCaloHitList));
     CaloHitList localCaloHitList(pCaloHitList->begin(), pCaloHitList->end());
     MCParticleToHitListMap mcParticleToHitListMap;
     for (CaloHitList::const_iterator hitIter = localCaloHitList.begin(), hitIterEnd = localCaloHitList.end(); hitIter != hitIterEnd; ++hitIter)
     {
       try
       {
         const CaloHit *const pCaloHit = *hitIter;
         if (!PandoraContentApi::IsAvailable(*this, pCaloHit))
           continue;
         if (m_shouldUseOnlyECalHits && (ECAL != pCaloHit->GetHitType()))
           continue;
         if (!m_shouldUseIsolatedHits && pCaloHit->IsIsolated())
           continue;
         if (m_simpleMCParticleCollection)
         {
           this->SimpleMCParticleCollection(pCaloHit, mcParticleToHitListMap);
         }
         else
         {
           this->FullMCParticleCollection(pCaloHit, mcParticleToHitListMap);
         }
       }
       catch (StatusCodeException &)
       {
       }
     }
     this->CreateClusters(mcParticleToHitListMap);
     return STATUS_CODE_SUCCESS;
   }
bool arbor_content::PerfectClusteringAlgorithm::SelectMCParticlesForClustering (const pandora::MCParticle *const pMCParticle) const protected virtual
Definition at line 30 of file PerfectClusteringAlgorithm.cc.
References m_particleIdList.
Referenced by FullMCParticleCollection(), and SimpleMCParticleCollection().
   {
     if (m_particleIdList.empty())
       return true;
     for (IntVector::const_iterator iter = m_particleIdList.begin(), iterEnd = m_particleIdList.end(); iter != iterEnd; ++iter)
     {
       if (pMCParticle->GetParticleId() == *iter)
         return true;
     }
     return false;
   }
void arbor_content::PerfectClusteringAlgorithm::SimpleMCParticleCollection (const pandora::CaloHit *const pCaloHit, MCParticleToHitListMap & mcParticleToHitListMap) const private
Simple mc particle collection, using main mc particle associated with each calo hit.
Parameters
pCaloHit address of the calo hit
mcParticleToHitListMap the mc particle to hit list map
Definition at line 90 of file PerfectClusteringAlgorithm.cc.
References AddToHitListMap(), and SelectMCParticlesForClustering().
Referenced by FullMCParticleCollection(), and Run().
   {
     const MCParticle *const pMCParticle(MCParticleHelper::GetMainMCParticle(pCaloHit));
     if (!this->SelectMCParticlesForClustering(pMCParticle))
       return;
     this->AddToHitListMap(pCaloHit, pMCParticle, mcParticleToHitListMap);
   }
Member Data Documentation
float arbor_content::PerfectClusteringAlgorithm::m_minWeightFraction private
The minimum mc particle calo hit weight for clustering consideration.
Definition at line 83 of file PerfectClusteringAlgorithm.h.
Referenced by FullMCParticleCollection(), and ReadSettings().
pandora::IntVector arbor_content::PerfectClusteringAlgorithm::m_particleIdList private
list of particle ids of MCPFOs to be selected
Definition at line 79 of file PerfectClusteringAlgorithm.h.
Referenced by ReadSettings(), and SelectMCParticlesForClustering().
bool arbor_content::PerfectClusteringAlgorithm::m_shouldUseIsolatedHits private
Whether to use isolated hits in the clustering algorithm.
Definition at line 81 of file PerfectClusteringAlgorithm.h.
Referenced by ReadSettings(), and Run().
bool arbor_content::PerfectClusteringAlgorithm::m_shouldUseOnlyECalHits private
Whether to only use ecal hits in the clustering algorithm.
Definition at line 80 of file PerfectClusteringAlgorithm.h.
Referenced by ReadSettings(), and Run().
bool arbor_content::PerfectClusteringAlgorithm::m_simpleMCParticleCollection private
Whether to use simple mc particle collection mechanism, or full mechanism.
Definition at line 82 of file PerfectClusteringAlgorithm.h.
Referenced by ReadSettings(), and Run().
The documentation for this class was generated from the following files:
PerfectClusteringAlgorithm.h
PerfectClusteringAlgorithm.cc