ArborContent: arbor_content::GeometryHelper Class Reference
arbor_content::GeometryHelper Class Reference
GeometryHelper class.
#include <GeometryHelper.h>
Static Public Member Functions
static pandora::StatusCode GetClosestDistanceBetweenLines (const pandora::CartesianVector &point1, const pandora::CartesianVector &direction1, const pandora::CartesianVector &point2, const pandora::CartesianVector &direction2, float &distance)
Get the closest distance between the two lines.
static pandora::StatusCode GetClosestDistanceToLine (const pandora::CartesianVector &point1, const pandora::CartesianVector &direction1, const pandora::CartesianVector &point2, float &impactParameter)
Get the closest distance between a point and a line.
static pandora::StatusCode GetProjectionOnLine (const pandora::CartesianVector &linePoint, const pandora::CartesianVector &direction, const pandora::CartesianVector &point, pandora::CartesianVector &projection)
Get the projection of a point on the line.
static pandora::StatusCode GetCrossingPointsBetweenLines (const pandora::CartesianVector &point1, const pandora::CartesianVector &direction1, const pandora::CartesianVector &point2, const pandora::CartesianVector &direction2, pandora::CartesianVector &crossingPoint1, pandora::CartesianVector &crossingPoint2)
Get the two crossing points of two lines at the closest distance approach.
static pandora::StatusCode GetLinePlaneCrossingPoint (const pandora::CartesianVector &linePoint, const pandora::CartesianVector &lineDirection, float planeA, float planeB, float planeC, float planeD, pandora::CartesianVector &crossingPoint)
Get the crossing point between a line and a plane in space.
static pandora::StatusCode GetECalHCalEndCapGapSize (const pandora::Pandora &pandora, float &gapSize)
Get the gap size between the ECal end cap and the HCal end cap.
static pandora::StatusCode GetECalHCalBarrelGapSize (const pandora::Pandora &pandora, float &gapSize)
Get the gap size between the ECal barrel and the HCal barrel.
static pandora::StatusCode GetTrackerECalEndCapGapSize (const pandora::Pandora &pandora, float &gapSize)
Get the gap size between the tracker and ECal end cap.
static pandora::StatusCode GetTrackerECalBarrelGapSize (const pandora::Pandora &pandora, float &gapSize)
Get the gap size between the tracker and ECal barrel.
static pandora::StatusCode GetEndcapGapSeparation (const pandora::Pandora &pandora, const pandora::CaloHit *const pEcalCaloHit, const pandora::CaloHit *const pHcalCaloHit, float &gapSeparation)
Get the gap separation in the end cap region between two calo hits.
static pandora::StatusCode GetBarrelGapSeparation (const pandora::Pandora &pandora, const pandora::CaloHit *const pEcalCaloHit, const pandora::CaloHit *const pHcalCaloHit, float &gapSeparation)
Get the gap separation in the barrel region between two calo hits.
static pandora::StatusCode GetOuterNormaleVector (const pandora::Pandora &pandora, pandora::SubDetectorType type, const pandora::CartesianVector &point, pandora::CartesianVector &normaleVector)
Get the normale vector at outer detector face in the phi region where the point is contained.
static pandora::StatusCode GetInnerNormaleVector (const pandora::Pandora &pandora, pandora::SubDetectorType type, const pandora::CartesianVector &point, pandora::CartesianVector &normaleVector)
Get the normale vector at inner detector face in the phi region where the point is contained.
static pandora::StatusCode GetProjectionOnHelix (const pandora::Helix &helix, const pandora::CartesianVector &point, pandora::CartesianVector &projection)
Get the projection of a point on the helix.
static pandora::StatusCode GetDistanceToHelix (const pandora::Helix &helix, const pandora::CartesianVector &point, float &distanceToHelix)
Get the distance between a point and the helix.
Detailed Description
GeometryHelper class.
Definition at line 43 of file GeometryHelper.h.
Member Function Documentation
pandora::StatusCode arbor_content::GeometryHelper::GetBarrelGapSeparation (const pandora::Pandora & pandora, const pandora::CaloHit *const pEcalCaloHit, const pandora::CaloHit *const pHcalCaloHit, float & gapSeparation) static
Get the gap separation in the barrel region between two calo hits.
Parameters
pandora the pandora instance to access geometry parameters
pEcalCaloHit the ecal calo hit address in the barrel region
pHcalCaloHit the hcal calo hit address in the barrel region
gapSeparation the gap separation distance to receive
Definition at line 267 of file GeometryHelper.cc.
References GetInnerNormaleVector(), GetLinePlaneCrossingPoint(), and GetOuterNormaleVector().
   {
     if(pEcalCaloHit->GetHitRegion() != pandora::BARREL || pEcalCaloHit->GetHitType() != pandora::ECAL)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     if(pHcalCaloHit->GetHitRegion() != pandora::BARREL || pHcalCaloHit->GetHitType() != pandora::HCAL)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     const float ecalBarrelOuterRCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::ECAL_BARREL).GetOuterRCoordinate();
     const float hcalBarrelInnerRCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::HCAL_BARREL).GetInnerRCoordinate();
     const pandora::CartesianVector hitsDirection = (pHcalCaloHit->GetPositionVector() - pEcalCaloHit->GetPositionVector()).GetUnitVector();
     // Get normale vectors to ecal and hcal in the gap region
     pandora::CartesianVector ecalBarrelOuterNormaleVector(0.f, 0.f, 0.f);
     pandora::CartesianVector hcalBarrelInnerNormaleVector(0.f, 0.f, 0.f);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetOuterNormaleVector(
         pandora, pandora::ECAL_BARREL, pEcalCaloHit->GetPositionVector(), ecalBarrelOuterNormaleVector));
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetInnerNormaleVector(
         pandora, pandora::HCAL_BARREL, pHcalCaloHit->GetPositionVector(), hcalBarrelInnerNormaleVector));
     // Get the crossing point with ecal and hcal in the gap region
     pandora::CartesianVector ecalFrontFaceCrossingPoint(0.f, 0.f, 0.f);
     pandora::CartesianVector hcalFrontFaceCrossingPoint(0.f, 0.f, 0.f);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetLinePlaneCrossingPoint(
         pEcalCaloHit->GetPositionVector(), hitsDirection,
         ecalBarrelOuterNormaleVector.GetX(), ecalBarrelOuterNormaleVector.GetY(), ecalBarrelOuterNormaleVector.GetZ(),
         -1.f*ecalBarrelOuterRCoordinate, ecalFrontFaceCrossingPoint));
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetLinePlaneCrossingPoint(
         pHcalCaloHit->GetPositionVector(), hitsDirection,
         hcalBarrelInnerNormaleVector.GetX(), hcalBarrelInnerNormaleVector.GetY(), hcalBarrelInnerNormaleVector.GetZ(),
         -1.f*hcalBarrelInnerRCoordinate, hcalFrontFaceCrossingPoint));
     gapSeparation = (ecalFrontFaceCrossingPoint - hcalFrontFaceCrossingPoint).GetMagnitude();
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetClosestDistanceBetweenLines (const pandora::CartesianVector & point1, const pandora::CartesianVector & direction1, const pandora::CartesianVector & point2, const pandora::CartesianVector & direction2, float & distance) static
Get the closest distance between the two lines.
Parameters
point1 on the line 1
direction1 of the line1
point2 on the line 2
direction2 of the line 2
the closest distance to receive
Definition at line 38 of file GeometryHelper.cc.
References GetClosestDistanceToLine().
Referenced by arbor_content::PointingClusterAssociationAlgorithm::FindBestParentCluster().
   {
     distance = 0.f;
     try
     {
       const pandora::CartesianVector unitDirection1 = direction1.GetUnitVector();
       const pandora::CartesianVector unitDirection2 = direction2.GetUnitVector();
       const pandora::CartesianVector w0 = point1 - point2;
       const float b = unitDirection1.GetCosOpeningAngle(unitDirection2);
       const float d = unitDirection1.GetDotProduct(w0);
       const float e = unitDirection2.GetDotProduct(w0);
       const float denom = 1 - b*b;
       // parallel lines
       if(unitDirection1 == unitDirection2)
       {
         // compute the distance from point2 to line1
         return GeometryHelper::GetClosestDistanceToLine(point1, unitDirection1, point2, distance);
       }
       else
       {
         // compute the real impact parameter between the two lines
         const pandora::CartesianVector impactParameterVector = w0 + ( unitDirection1*((b*e - d)/denom) - unitDirection2*((e - b*d)/denom) );
         distance = impactParameterVector.GetMagnitude();
       }
     }
     catch(pandora::StatusCodeException &statusCodeException)
     {
       return statusCodeException.GetStatusCode();
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetClosestDistanceToLine (const pandora::CartesianVector & point1, const pandora::CartesianVector & direction1, const pandora::CartesianVector & point2, float & impactParameter) static
Get the closest distance between a point and a line.
Parameters
point1 on the line
direction1 of the line
point2 in the space
the closest distance between the point and the line to receive
Definition at line 76 of file GeometryHelper.cc.
Referenced by GetClosestDistanceBetweenLines(), and arbor_content::ParticleIdHelper::GetStartingPseudoLayer().
   {
     try
     {
       // compute the distance from point2 to line1
       const pandora::CartesianVector unitDirection1 = direction1.GetUnitVector();
       float k = unitDirection1.GetDotProduct(point2-point1);
       const pandora::CartesianVector normale = point1 + unitDirection1*k - point2;
       distance = normale.GetMagnitude();
     }
     catch(pandora::StatusCodeException &statusCodeException)
     {
       return statusCodeException.GetStatusCode();
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetCrossingPointsBetweenLines (const pandora::CartesianVector & point1, const pandora::CartesianVector & direction1, const pandora::CartesianVector & point2, const pandora::CartesianVector & direction2, pandora::CartesianVector & crossingPoint1, pandora::CartesianVector & crossingPoint2) static
Get the two crossing points of two lines at the closest distance approach.
Parameters
point1 on the line 1
direction1 of the line 1
point2 on the line 2
direction2 of the line 2
crossingPoint1 the crossing point on the line 1 to receive
crossingPoint2 the crossing point on the line 2 to receive
Definition at line 114 of file GeometryHelper.cc.
   {
     try
     {
       // parallel lines never cross
       if(direction1.GetUnitVector() == direction2.GetUnitVector())
         return pandora::STATUS_CODE_INVALID_PARAMETER;
       const pandora::CartesianVector unitDirection1 = direction1.GetUnitVector();
       const pandora::CartesianVector unitDirection2 = direction2.GetUnitVector();
       const pandora::CartesianVector w0 = point1 - point2;
       const float b = unitDirection1.GetCosOpeningAngle(unitDirection2);
       const float d = unitDirection1.GetDotProduct(w0);
       const float e = unitDirection2.GetDotProduct(w0);
       const float denom = 1 - b*b;
       crossingPoint1 = point1 + unitDirection1*(b*e-d)*(1.f/denom);
       crossingPoint2 = point2 + unitDirection2*(e - b*d)*(1.f/denom);
     }
     catch(pandora::StatusCodeException &statusCodeException)
     {
       return statusCodeException.GetStatusCode();
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetDistanceToHelix (const pandora::Helix & helix, const pandora::CartesianVector & point, float & distanceToHelix) static
Get the distance between a point and the helix.
Parameters
helix the helix to consider
point a point in space
distanceToHelix the distance to the helix to receive
Definition at line 412 of file GeometryHelper.cc.
References GetProjectionOnHelix().
Referenced by arbor_content::ParticleIdHelper::GetStartingPseudoLayer(), and arbor_content::SplitTrackReclusteringAlgorithm::Run().
   {
     distanceToHelix = std::numeric_limits<float>::max();
     pandora::CartesianVector projectionOnHelix(0.f, 0.f, 0.f);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetProjectionOnHelix(helix, point, projectionOnHelix));
     distanceToHelix = (point-projectionOnHelix).GetMagnitude();
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetECalHCalBarrelGapSize (const pandora::Pandora & pandora, float & gapSize) static
Get the gap size between the ECal barrel and the HCal barrel.
Parameters
pandora the pandora instance to access geometry parameters
gapSize the gap size to receive
Definition at line 182 of file GeometryHelper.cc.
   {
     const float ecalBarrelOuterRCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::ECAL_BARREL).GetOuterRCoordinate();
     const float hcalBarrelInnerRCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::HCAL_BARREL).GetInnerRCoordinate();
     if(ecalBarrelOuterRCoordinate > hcalBarrelInnerRCoordinate)
       return pandora::STATUS_CODE_FAILURE;
     gapSize = hcalBarrelInnerRCoordinate - ecalBarrelOuterRCoordinate;
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetECalHCalEndCapGapSize (const pandora::Pandora & pandora, float & gapSize) static
Get the gap size between the ECal end cap and the HCal end cap.
Parameters
pandora the pandora instance to access geometry parameters
gapSize the gap size to receive
Definition at line 167 of file GeometryHelper.cc.
   {
     const float ecalEndCapOuterZCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::ECAL_ENDCAP).GetOuterZCoordinate();
     const float hcalEndCapInnerZCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::HCAL_ENDCAP).GetInnerZCoordinate();
     if(ecalEndCapOuterZCoordinate > hcalEndCapInnerZCoordinate)
       return pandora::STATUS_CODE_FAILURE;
     gapSize = hcalEndCapInnerZCoordinate - ecalEndCapOuterZCoordinate;
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetEndcapGapSeparation (const pandora::Pandora & pandora, const pandora::CaloHit *const pEcalCaloHit, const pandora::CaloHit *const pHcalCaloHit, float & gapSeparation) static
Get the gap separation in the end cap region between two calo hits.
Parameters
pandora the pandora instance to access geometry parameters
pEcalCaloHit the ecal calo hit address in the end cap region
pHcalCaloHit the hcal calo hit address in the end cap region
gapSeparation the gap separation distance to receive
Definition at line 227 of file GeometryHelper.cc.
References GetLinePlaneCrossingPoint().
   {
     if(pEcalCaloHit->GetHitRegion() != pandora::ENDCAP || pEcalCaloHit->GetHitType() != pandora::ECAL)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     if(pHcalCaloHit->GetHitRegion() != pandora::ENDCAP || pHcalCaloHit->GetHitType() != pandora::HCAL)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     // same end cap side required
     if(pEcalCaloHit->GetPositionVector().GetZ()*pHcalCaloHit->GetPositionVector().GetZ() < 0)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     const float hcalEndCapInnerZCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::HCAL_ENDCAP).GetInnerZCoordinate();
     const float ecalEndCapOuterZCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::ECAL_ENDCAP).GetOuterZCoordinate();
     const pandora::CartesianVector hitsDirection = (pHcalCaloHit->GetPositionVector() - pEcalCaloHit->GetPositionVector()).GetUnitVector();
     pandora::CartesianVector ecalFrontFaceCrossingPoint(0.f, 0.f, 0.f);
     pandora::CartesianVector hcalFrontFaceCrossingPoint(0.f, 0.f, 0.f);
     int endCapSide = pEcalCaloHit->GetPositionVector().GetZ() > 0 ? 1 : -1;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetLinePlaneCrossingPoint(
         pEcalCaloHit->GetPositionVector(), hitsDirection,
         0.f, 0.f, static_cast<float>(endCapSide), -1.f*endCapSide*ecalEndCapOuterZCoordinate,
         ecalFrontFaceCrossingPoint));
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetLinePlaneCrossingPoint(
         pEcalCaloHit->GetPositionVector(), hitsDirection,
         0.f, 0.f, static_cast<float>(endCapSide), -1.f*endCapSide*hcalEndCapInnerZCoordinate,
         hcalFrontFaceCrossingPoint));
     gapSeparation = (ecalFrontFaceCrossingPoint - hcalFrontFaceCrossingPoint).GetMagnitude();
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetInnerNormaleVector (const pandora::Pandora & pandora, pandora::SubDetectorType type, const pandora::CartesianVector & point, pandora::CartesianVector & normaleVector) static
Get the normale vector at inner detector face in the phi region where the point is contained.
Parameters
pandora the pandora instance to access geometry parameters
type the sub detector type (requires access to inner symmetry order)
point a point in space that fixes the phi region
normaleVector the normal vector at the inner detector face to receive
Definition at line 347 of file GeometryHelper.cc.
Referenced by GetBarrelGapSeparation().
   {
     const unsigned int innerSymmetryOrder = pandora.GetGeometry()->GetSubDetector(type).GetInnerSymmetryOrder();
     if(0 == innerSymmetryOrder)
     {
       normaleVector.SetValues(point.GetX(), point.GetY(), 0.f);
       return pandora::STATUS_CODE_SUCCESS;
     }
     const float rPoint = std::sqrt(point.GetX()*point.GetX() + point.GetY()*point.GetY());
     const float phiPoint = point.GetY() > 0 ?
         std::acos(point.GetX() / rPoint) : std::acos(-point.GetX() / rPoint) + M_PI;
     const float phiShift = (2 * M_PI / static_cast<float>(innerSymmetryOrder)) / 2.f;
     for(unsigned int i=0 ; i<innerSymmetryOrder ; i++)
     {
       const float phi = 2 * M_PI * (static_cast<float>(i) / static_cast<float>(innerSymmetryOrder));
       const float phiMin = phi - phiShift;
       const float phiMax = phi + phiShift;
       if(phiPoint > phiMin && phiPoint < phiMax)
       {
         normaleVector.SetValues(std::cos(phi), std::sin(phi), 0.f);
         break;
       }
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetLinePlaneCrossingPoint (const pandora::CartesianVector & linePoint, const pandora::CartesianVector & lineDirection, float planeA, float planeB, float planeC, float planeD, pandora::CartesianVector & crossingPoint) static
Get the crossing point between a line and a plane in space.
The equation plane is defined as :
P : a*x + b*y + c*z + d = 0
Parameters
linePoint a point on the line
lineDirection the line direction vector
planeA the a component in the plane equation
planeB the b component in the plane equation
planeC the c component in the plane equation
planeD the d component in the plane equation
crossingPoint the crossing point vector position to receive
Definition at line 145 of file GeometryHelper.cc.
Referenced by GetBarrelGapSeparation(), and GetEndcapGapSeparation().
   {
     const float num = planeA*linePoint.GetX() + planeB*linePoint.GetY() + planeC*linePoint.GetZ() + planeD;
     const float denom = planeA*lineDirection.GetX() + planeB*lineDirection.GetY() + planeC*lineDirection.GetZ();
     if(fabs(denom) < std::numeric_limits<float>::epsilon())
       return pandora::STATUS_CODE_FAILURE;
     const float k = num/denom;
     const float xCrossingPoint = linePoint.GetX() + k*lineDirection.GetX();
     const float yCrossingPoint = linePoint.GetY() + k*lineDirection.GetY();
     const float zCrossingPoint = linePoint.GetZ() + k*lineDirection.GetZ();
     crossingPoint.SetValues(xCrossingPoint, yCrossingPoint, zCrossingPoint);
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetOuterNormaleVector (const pandora::Pandora & pandora, pandora::SubDetectorType type, const pandora::CartesianVector & point, pandora::CartesianVector & normaleVector) static
Get the normale vector at outer detector face in the phi region where the point is contained.
Parameters
pandora the pandora instance to access geometry parameters
type the sub detector type (requires access to outer symetry order)
point a point in space that fixes the phi region
normaleVector the normale vector at the outer detector face to receive
Definition at line 312 of file GeometryHelper.cc.
Referenced by GetBarrelGapSeparation(), and arbor_content::ClusterHelper::IsClusterLeavingDetector().
   {
     const unsigned int outerSymmetryOrder = pandora.GetGeometry()->GetSubDetector(type).GetOuterSymmetryOrder();
     if(0 == outerSymmetryOrder)
     {
       normaleVector.SetValues(point.GetX(), point.GetY(), 0.f);
       return pandora::STATUS_CODE_SUCCESS;
     }
     const float rPoint = std::sqrt(point.GetX()*point.GetX() + point.GetY()*point.GetY());
     const float phiPoint = point.GetY() > 0 ?
         std::acos(point.GetX() / rPoint) : std::acos(-point.GetX() / rPoint) + M_PI;
     const float phiShift = (2 * M_PI / static_cast<float>(outerSymmetryOrder)) / 2.f;
     for(unsigned int i=0 ; i<outerSymmetryOrder+1 ; i++)
     {
       const float phi = 2 * M_PI * (static_cast<float>(i) / static_cast<float>(outerSymmetryOrder));
       const float phiMin = phi - phiShift;// + barrelOuterPhiCoordinate;
       const float phiMax = phi + phiShift;// + barrelOuterPhiCoordinate;
       if(phiPoint > phiMin && phiPoint < phiMax)
       {
         normaleVector.SetValues(std::cos(phi), std::sin(phi), 0.f);
         break;
       }
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetProjectionOnHelix (const pandora::Helix & helix, const pandora::CartesianVector & point, pandora::CartesianVector & projection) static
Get the projection of a point on the helix.
Parameters
helix the helix to consider
point the point in space to project on the helix
projection the projection point to receive
Definition at line 382 of file GeometryHelper.cc.
Referenced by arbor_content::TrackDrivenSeedingTool::ConnectCaloHits(), arbor_content::PointingClusterAssociationAlgorithm::FindBestParentCluster(), arbor_content::TrackDrivenSeedingTool::FindInitialCaloHits(), arbor_content::CaloHitPreparationAlgorithm::FlagIsolatedHitsWithTracks(), GetDistanceToHelix(), arbor_content::ClusterHelper::GetTrackClusterDistance(), and arbor_content::NearbyTrackPhotonRemovalAlg::RemoveNearbyPhotonHits().
   {
     pandora::CartesianVector pointInXY(0.f, 0.f, 0.f), pointInZ(0.f, 0.f, 0.f);
     const pandora::StatusCode statusCode1(helix.GetPointInXY(point.GetX(), point.GetY(), point.GetX(), point.GetY(), helix.GetReferencePoint(), pointInXY));
     const pandora::StatusCode statusCode2(helix.GetPointInZ(point.GetZ(), helix.GetReferencePoint(), pointInZ));
     if(pandora::STATUS_CODE_SUCCESS != statusCode1 && pandora::STATUS_CODE_SUCCESS != statusCode2)
       return pandora::STATUS_CODE_NOT_FOUND;
     if(statusCode2 != pandora::STATUS_CODE_SUCCESS)
     {
       projection = pointInXY;
       return pandora::STATUS_CODE_SUCCESS;
     }
     if(statusCode1 != pandora::STATUS_CODE_SUCCESS)
     {
       projection = pointInZ;
       return pandora::STATUS_CODE_SUCCESS;
     }
     const float distanceInXY((pointInXY-point).GetMagnitude()), distanceInZ((pointInZ-point).GetMagnitude());
     projection = distanceInXY < distanceInZ ? pointInXY : pointInZ;
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetProjectionOnLine (const pandora::CartesianVector & linePoint, const pandora::CartesianVector & direction, const pandora::CartesianVector & point, pandora::CartesianVector & projection) static
Get the projection of a point on the line.
Parameters
linePoint on the line
direction1 of the line
point in the space
projection the projection vector on the line to receive
Definition at line 97 of file GeometryHelper.cc.
Referenced by arbor_content::PointingClusterAssociationAlgorithm::FindBestParentCluster(), and arbor_content::PointingClusterAssociationAlgorithm::GetClusterBackwardDirection().
   {
     try
     {
       projection = linePoint + direction.GetUnitVector() * ((point-linePoint).GetMagnitude() * direction.GetCosOpeningAngle(point-linePoint));
     }
     catch(pandora::StatusCodeException &statusCodeException)
     {
       return statusCodeException.GetStatusCode();
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetTrackerECalBarrelGapSize (const pandora::Pandora & pandora, float & gapSize) static
Get the gap size between the tracker and ECal barrel.
Parameters
pandora the pandora instance to access geometry parameters
gapSize the gap size to receive
Definition at line 212 of file GeometryHelper.cc.
   {
     const float ecalBarrelInnerRCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::ECAL_BARREL).GetInnerRCoordinate();
     const float trackerOuterRCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::INNER_TRACKER).GetOuterRCoordinate();
     if(trackerOuterRCoordinate > ecalBarrelInnerRCoordinate)
       return pandora::STATUS_CODE_FAILURE;
     gapSize = ecalBarrelInnerRCoordinate - trackerOuterRCoordinate;
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::GeometryHelper::GetTrackerECalEndCapGapSize (const pandora::Pandora & pandora, float & gapSize) static
Get the gap size between the tracker and ECal end cap.
Parameters
pandora the pandora instance to access geometry parameters
gapSize the gap size to receive
Definition at line 197 of file GeometryHelper.cc.
   {
     const float ecalEndCapInnerZCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::ECAL_ENDCAP).GetInnerZCoordinate();
     const float trackerOuterZCoordinate = pandora.GetGeometry()->GetSubDetector(pandora::INNER_TRACKER).GetOuterZCoordinate();
     if(trackerOuterZCoordinate > ecalEndCapInnerZCoordinate)
       return pandora::STATUS_CODE_FAILURE;
     gapSize = ecalEndCapInnerZCoordinate - trackerOuterZCoordinate;
     return pandora::STATUS_CODE_SUCCESS;
   }
The documentation for this class was generated from the following files:
GeometryHelper.h
GeometryHelper.cc