ArborContent: arbor_content::PointingClusterAssociationAlgorithm Class Reference
arbor_content::PointingClusterAssociationAlgorithm Class Reference
PointingClusterAssociationAlgorithm class.
#include <PointingClusterAssociationAlgorithm.h>
Classes
class Factory
Factory class for instantiating algorithm.
Private Member Functions
pandora::StatusCode Run ()
pandora::StatusCode ReadSettings (const pandora::TiXmlHandle xmlHandle)
pandora::StatusCode GetEligibleClusters (pandora::ClusterVector &clusterVector) const
Get the eligible clusters for parent-daughter association.
pandora::StatusCode FindClustersToMerge (const pandora::ClusterVector &clusterVector, ClusterToClusterMap &clusterToClusterMap) const
Algorithm workhorse, find associations between daughter and parent cluster.
bool CanMergeCluster (const pandora::Cluster *const pCluster) const
Whether the cluster is eligible for association.
pandora::StatusCode FindBestParentCluster (const pandora::Cluster *const pDaughterCluster, const pandora::ClusterVector &clusterVector, const pandora::Cluster *&pBestParentCluster) const
Find the best parent cluster to merge a daughter one.
pandora::StatusCode GetClusterBackwardDirection (const pandora::Cluster *const pCluster, pandora::CartesianVector &backwardDirection, pandora::CartesianVector &innerPosition) const
Get the cluster backward direction and the inner cluster position using a cluster fit of the n first layers.
Private Attributes
bool m_discriminatePhotonPid
Whether to discriminate photons.
bool m_allowNeutralParentMerging
unsigned int m_minNCaloHits
unsigned int m_maxNCaloHits
unsigned int m_minNPseudoLayers
unsigned int m_maxNPseudoLayers
float m_chi2AssociationCut
unsigned int m_nBackwardLayersFit
float m_maxBackwardAngle
float m_maxBackwardDistanceFine
float m_maxBackwardDistanceCoarse
unsigned int m_maxBackwardPseudoLayer
unsigned int m_minParentClusterBackwardNHits
float m_maxClusterFitDca
float m_minClusterCosOpeningAngle
float m_minClusterFitCosOpeningAngle
float m_minClusterFitCosOpeningAngle2
Detailed Description
PointingClusterAssociationAlgorithm class.
Definition at line 44 of file PointingClusterAssociationAlgorithm.h.
Member Function Documentation
bool arbor_content::PointingClusterAssociationAlgorithm::CanMergeCluster (const pandora::Cluster *const pCluster) const private
Whether the cluster is eligible for association.
Parameters
pCluster address of a candidate cluster for association
Returns
boolean
Definition at line 88 of file PointingClusterAssociationAlgorithm.cc.
References m_discriminatePhotonPid, m_maxNCaloHits, m_maxNPseudoLayers, and m_minNCaloHits.
Referenced by GetEligibleClusters().
   {
     if(NULL == pCluster)
       return false;
     if(!PandoraContentApi::IsAvailable(*this, pCluster))
       return false;
     if(pCluster->GetNCaloHits() < m_minNCaloHits || pCluster->GetNCaloHits() > m_maxNCaloHits)
       return false;
     const unsigned int nPseudoLayers(pCluster->GetOrderedCaloHitList().size());
     if(nPseudoLayers < m_minNPseudoLayers || nPseudoLayers >= m_maxNPseudoLayers)
       return false;
     if(m_discriminatePhotonPid && pCluster->IsPhotonFast(this->GetPandora()))
       return false;
     return true;
   }
pandora::StatusCode arbor_content::PointingClusterAssociationAlgorithm::FindBestParentCluster (const pandora::Cluster *const pDaughterCluster, const pandora::ClusterVector & clusterVector, const pandora::Cluster *& pBestParentCluster) const private
Find the best parent cluster to merge a daughter one.
Parameters
pDaughterCluster address of the daughter cluster
clusterVector a cluster vector
pBestParentCluster address of the best parent cluster to receive
Definition at line 141 of file PointingClusterAssociationAlgorithm.cc.
References arbor_content::ClusterHelper::GetCentroid(), arbor_content::ClusterHelper::GetChiClusterMerging(), arbor_content::GeometryHelper::GetClosestDistanceBetweenLines(), GetClusterBackwardDirection(), arbor_content::GeometryHelper::GetProjectionOnHelix(), arbor_content::GeometryHelper::GetProjectionOnLine(), m_chi2AssociationCut, m_maxBackwardDistanceCoarse, m_maxBackwardDistanceFine, m_maxBackwardPseudoLayer, m_minClusterCosOpeningAngle, m_minClusterFitCosOpeningAngle, m_minClusterFitCosOpeningAngle2, and m_nBackwardLayersFit.
Referenced by FindClustersToMerge().
   {
     pBestParentCluster = NULL;
     if(NULL == pDaughterCluster)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     pandora::CartesianVector innerPosition(0.f, 0.f, 0.f), backwardDirection(0.f, 0.f, 0.f);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->GetClusterBackwardDirection(pDaughterCluster, backwardDirection, innerPosition));
     const unsigned int innerPseudoLayer(PandoraContentApi::GetPlugins(*this)->GetPseudoLayerPlugin()->GetPseudoLayer(innerPosition));
     const pandora::Granularity granularity(this->GetPandora().GetGeometry()->GetHitTypeGranularity(pDaughterCluster->GetInnerLayerHitType()));
     const float maxClusterDistance(granularity <= pandora::FINE ? m_maxBackwardDistanceFine : m_maxBackwardDistanceCoarse);
     const unsigned int maxPseudoLayerDifference(m_maxBackwardPseudoLayer);
     float bestClusterCosineAngle(std::numeric_limits<float>::min());
     for(pandora::ClusterVector::const_reverse_iterator jIter = clusterVector.rbegin(), jEndIter = clusterVector.rend() ;
         jEndIter != jIter ; ++jIter)
     {
       const pandora::Cluster *const pCluster(*jIter);
       if(NULL == pCluster)
         continue;
       if(pCluster == pDaughterCluster)
         continue;
       if(pCluster->GetAssociatedTrackList().empty())
         continue;
       const pandora::Track *pTrack((*pCluster->GetAssociatedTrackList().begin()));
       const pandora::CartesianVector trackMomentum(pTrack->GetTrackStateAtCalorimeter().GetMomentum());
       const pandora::CartesianVector trackProjection(pTrack->GetTrackStateAtCalorimeter().GetPosition());
       const float bField(PandoraContentApi::GetPlugins(*this)->GetBFieldPlugin()->GetBField(pandora::CartesianVector(0.f, 0.f, 0.f)));
       const pandora::Helix helix(trackProjection, trackMomentum, pTrack->GetCharge(), bField);
       // compute parent cluster end point using cluster fit
       pandora::CartesianVector centroid(0.f, 0.f, 0.f);
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));
       const pandora::CartesianVector outerCentroid(pCluster->GetCentroid(pCluster->GetOuterPseudoLayer()));
       const unsigned int outerParentPseudoLayer(pCluster->GetOuterPseudoLayer());
       const unsigned int innerParentPseudoLayer(pCluster->GetInnerPseudoLayer());
       const unsigned int clusterPseudoLayerExtension(outerParentPseudoLayer-innerParentPseudoLayer);
       const unsigned int nFitPseudoLayers(clusterPseudoLayerExtension >= m_nBackwardLayersFit ? m_nBackwardLayersFit : clusterPseudoLayerExtension);
       pandora::ClusterFitResult clusterFitResult;
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pandora::ClusterFitHelper::FitEnd(pCluster, nFitPseudoLayers, clusterFitResult));
       const pandora::CartesianVector clusterDirection(clusterFitResult.GetDirection());
       pandora::CartesianVector clusterEndPoint(0.f, 0.f, 0.f);
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetProjectionOnLine(centroid, clusterDirection, outerCentroid, clusterEndPoint));
       pandora::CartesianVector trackEndPointPosition(0.f, 0.f, 0.f), trackEndPointMomentum(0.f, 0.f, 0.f);
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetProjectionOnHelix(helix, clusterEndPoint, trackEndPointPosition));
       trackEndPointMomentum = helix.GetExtrapolatedMomentum(trackEndPointPosition);
       // possible parent if :
       // 1) cluster distance if OK AND angle between fits is ok (cut on cosine)
       // 2) cluster distance if OK AND angle between fits is compatible (cut relaxed) AND dca between fits is OK
       // check pseudo layer cluster separation
       const unsigned int endPseudoLayer(PandoraContentApi::GetPlugins(*this)->GetPseudoLayerPlugin()->GetPseudoLayer(clusterEndPoint));
       const unsigned int pseudoLayerDifference(std::max(innerPseudoLayer, endPseudoLayer) - std::min(innerPseudoLayer, endPseudoLayer));
       if(endPseudoLayer >= innerPseudoLayer || pseudoLayerDifference > maxPseudoLayerDifference)
         continue;
       // distance between clusters
       const pandora::CartesianVector clusterDifferenceDirection(innerPosition-clusterEndPoint);
       const float clusterDistance(clusterDifferenceDirection.GetMagnitude());
       if(clusterDistance > maxClusterDistance)
         continue;
       // compute cluster-to-cluster properties
       const float clusterFitCosineAngle(clusterDirection.GetCosOpeningAngle(backwardDirection * -1.));
       const float clusterCosineAngle(trackEndPointMomentum.GetCosOpeningAngle(clusterDifferenceDirection));
       float clusterFitDca(0.f);
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetClosestDistanceBetweenLines(clusterEndPoint, clusterDirection, innerPosition, backwardDirection, clusterFitDca));
       bool possibleAssociation(false);
       // contained in small angle
       if(clusterFitCosineAngle > m_minClusterFitCosOpeningAngle2 && clusterCosineAngle > m_minClusterCosOpeningAngle)
       {
         possibleAssociation = true;
       }
       // contained in larger angle but short dca
       else if(clusterFitDca < m_maxClusterFitDca && clusterFitCosineAngle > m_minClusterFitCosOpeningAngle && clusterCosineAngle > m_minClusterCosOpeningAngle)
       {
         possibleAssociation = true;
       }
       if(possibleAssociation)
       {
         float oldChi(0.f), newChi(0.f);
         if(pandora::STATUS_CODE_SUCCESS != ClusterHelper::GetChiClusterMerging(this->GetPandora(), pCluster, pDaughterCluster, oldChi, newChi))
           continue;
         const bool angleTightened(clusterCosineAngle > bestClusterCosineAngle);
         const bool chi2Compatible(newChi*newChi < oldChi*oldChi || newChi*newChi < m_chi2AssociationCut);
         if(angleTightened && chi2Compatible)
         {
           bestClusterCosineAngle = clusterCosineAngle;
           pBestParentCluster = pCluster;
         }
       }
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::PointingClusterAssociationAlgorithm::FindClustersToMerge (const pandora::ClusterVector & clusterVector, ClusterToClusterMap & clusterToClusterMap) const private
Algorithm workhorse, find associations between daughter and parent cluster.
Parameters
clusterVector the input cluster vector
clusterToClusterMap the map of daughter to parent cluster to receive
Definition at line 112 of file PointingClusterAssociationAlgorithm.cc.
References FindBestParentCluster().
Referenced by Run().
   {
     for(pandora::ClusterVector::const_iterator iter = clusterVector.begin(), endIter = clusterVector.end() ;
         endIter != iter ; ++iter)
     {
       const pandora::Cluster *const pDaughterCluster = *iter;
       if(NULL == pDaughterCluster)
         continue;
       if( ! pDaughterCluster->GetAssociatedTrackList().empty() )
         continue;
       const pandora::Cluster *pBestParentCluster = NULL;
       if(pandora::STATUS_CODE_SUCCESS != this->FindBestParentCluster(pDaughterCluster, clusterVector, pBestParentCluster))
         continue;
       if(NULL == pBestParentCluster)
         continue;
       clusterToClusterMap[pDaughterCluster] = pBestParentCluster;
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::PointingClusterAssociationAlgorithm::GetClusterBackwardDirection (const pandora::Cluster *const pCluster, pandora::CartesianVector & backwardDirection, pandora::CartesianVector & innerPosition) const private
Get the cluster backward direction and the inner cluster position using a cluster fit of the n first layers.
Parameters
pCluster the input cluster address
backwardDirection the backward direction cartesian vector to receive
innerPosition the inner cluster position to receive
Definition at line 260 of file PointingClusterAssociationAlgorithm.cc.
References arbor_content::ClusterHelper::GetCentroid(), arbor_content::GeometryHelper::GetProjectionOnLine(), and m_nBackwardLayersFit.
Referenced by FindBestParentCluster().
   {
     pandora::CartesianVector centroid(0.f, 0.f, 0.f);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));
     const pandora::CartesianVector innerCentroid(pCluster->GetCentroid(pCluster->GetInnerPseudoLayer()));
     pandora::ClusterFitResult clusterFitResult;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pandora::ClusterFitHelper::FitStart(pCluster, m_nBackwardLayersFit, clusterFitResult));
     const pandora::CartesianVector clusterDirection(clusterFitResult.GetDirection());
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, GeometryHelper::GetProjectionOnLine(centroid, clusterDirection, innerCentroid, innerPosition));
     backwardDirection = clusterDirection * -1.f;
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::PointingClusterAssociationAlgorithm::GetEligibleClusters (pandora::ClusterVector & clusterVector) const private
Get the eligible clusters for parent-daughter association.
Parameters
clusterVector the cluster vector to receive
Definition at line 61 of file PointingClusterAssociationAlgorithm.cc.
References CanMergeCluster(), and m_discriminatePhotonPid.
Referenced by Run().
   {
     const pandora::ClusterList *pClusterList = NULL;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(*this, pClusterList));
     if(pClusterList->empty())
       return pandora::STATUS_CODE_SUCCESS;
     for(pandora::ClusterList::const_iterator clusterIter = pClusterList->begin(), clusterEndIter = pClusterList->end() ;
         clusterEndIter != clusterIter ; ++clusterIter)
     {
       const pandora::Cluster *const pCluster = *clusterIter;
       if(!this->CanMergeCluster(pCluster))
         continue;
       if(m_discriminatePhotonPid && pCluster->IsPhotonFast(this->GetPandora()))
         continue;
       clusterVector.push_back(pCluster);
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::PointingClusterAssociationAlgorithm::ReadSettings (const pandora::TiXmlHandle xmlHandle) private
Definition at line 279 of file PointingClusterAssociationAlgorithm.cc.
References m_allowNeutralParentMerging, m_chi2AssociationCut, m_discriminatePhotonPid, m_maxBackwardAngle, m_maxBackwardDistanceCoarse, m_maxBackwardDistanceFine, m_maxBackwardPseudoLayer, m_maxClusterFitDca, m_maxNCaloHits, m_maxNPseudoLayers, m_minClusterCosOpeningAngle, m_minClusterFitCosOpeningAngle, m_minClusterFitCosOpeningAngle2, m_minNCaloHits, m_minNPseudoLayers, m_minParentClusterBackwardNHits, and m_nBackwardLayersFit.
   {
     m_discriminatePhotonPid = true;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "DiscriminatePhotonPid", m_discriminatePhotonPid));
     m_allowNeutralParentMerging = false;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "AllowNeutralParentMerging", m_allowNeutralParentMerging));
     m_minNCaloHits = 10;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinNCaloHits", m_minNCaloHits));
     m_maxNCaloHits = std::numeric_limits<unsigned int>::max();
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxNCaloHits", m_maxNCaloHits));
     m_minNPseudoLayers = 4;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinNPseudoLayers", m_minNPseudoLayers));
     m_maxNPseudoLayers = std::numeric_limits<unsigned int>::max();
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxNPseudoLayers", m_maxNPseudoLayers));
     m_chi2AssociationCut = 1.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "Chi2AssociationCut", m_chi2AssociationCut));
     m_nBackwardLayersFit = 6;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "NBackwardLayersFit", m_nBackwardLayersFit));
     m_maxBackwardAngle = 0.4;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxBackwardAngle", m_maxBackwardAngle));
     m_maxBackwardDistanceFine = 300.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxBackwardDistanceFine", m_maxBackwardDistanceFine));
     m_maxBackwardDistanceCoarse = 1000.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxBackwardDistanceCoarse", m_maxBackwardDistanceCoarse));
     m_maxBackwardPseudoLayer = 20;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxBackwardPseudoLayer", m_maxBackwardPseudoLayer));
     m_minParentClusterBackwardNHits = 5;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinParentClusterBackwardNHits", m_minParentClusterBackwardNHits));
     m_maxClusterFitDca = 25.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxClusterFitDca", m_maxClusterFitDca));
     m_minClusterCosOpeningAngle = 0.7;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinClusterCosOpeningAngle", m_minClusterCosOpeningAngle));
     m_minClusterFitCosOpeningAngle = 0.7;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinClusterFitCosOpeningAngle", m_minClusterFitCosOpeningAngle));
     m_minClusterFitCosOpeningAngle2 = 0.8;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinClusterFitCosOpeningAngle2", m_minClusterFitCosOpeningAngle2));
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::PointingClusterAssociationAlgorithm::Run () private
Definition at line 43 of file PointingClusterAssociationAlgorithm.cc.
References FindClustersToMerge(), GetEligibleClusters(), arbor_content::ClusterHelper::MergeClusters(), and arbor_content::SortingHelper::SortClustersByInnerLayer().
   {
     // get candidate clusters for association
     pandora::ClusterVector clusterVector;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->GetEligibleClusters(clusterVector));
     // sort them by inner layer
     std::sort(clusterVector.begin(), clusterVector.end(), SortingHelper::SortClustersByInnerLayer);
     ClusterToClusterMap clusterToClusterMap;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->FindClustersToMerge(clusterVector, clusterToClusterMap));
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::MergeClusters(*this, clusterToClusterMap));
     return pandora::STATUS_CODE_SUCCESS;
   }
Member Data Documentation
bool arbor_content::PointingClusterAssociationAlgorithm::m_allowNeutralParentMerging private
Definition at line 105 of file PointingClusterAssociationAlgorithm.h.
Referenced by ReadSettings().
float arbor_content::PointingClusterAssociationAlgorithm::m_chi2AssociationCut private
Definition at line 110 of file PointingClusterAssociationAlgorithm.h.
Referenced by FindBestParentCluster(), and ReadSettings().
bool arbor_content::PointingClusterAssociationAlgorithm::m_discriminatePhotonPid private
Whether to discriminate photons.
Definition at line 104 of file PointingClusterAssociationAlgorithm.h.
Referenced by CanMergeCluster(), GetEligibleClusters(), and ReadSettings().
float arbor_content::PointingClusterAssociationAlgorithm::m_maxBackwardAngle private
Definition at line 112 of file PointingClusterAssociationAlgorithm.h.
Referenced by ReadSettings().
float arbor_content::PointingClusterAssociationAlgorithm::m_maxBackwardDistanceCoarse private
Definition at line 114 of file PointingClusterAssociationAlgorithm.h.
Referenced by FindBestParentCluster(), and ReadSettings().
float arbor_content::PointingClusterAssociationAlgorithm::m_maxBackwardDistanceFine private
Definition at line 113 of file PointingClusterAssociationAlgorithm.h.
Referenced by FindBestParentCluster(), and ReadSettings().
unsigned int arbor_content::PointingClusterAssociationAlgorithm::m_maxBackwardPseudoLayer private
Definition at line 115 of file PointingClusterAssociationAlgorithm.h.
Referenced by FindBestParentCluster(), and ReadSettings().
float arbor_content::PointingClusterAssociationAlgorithm::m_maxClusterFitDca private
Definition at line 117 of file PointingClusterAssociationAlgorithm.h.
Referenced by ReadSettings().
unsigned int arbor_content::PointingClusterAssociationAlgorithm::m_maxNCaloHits private
Definition at line 107 of file PointingClusterAssociationAlgorithm.h.
Referenced by CanMergeCluster(), and ReadSettings().
unsigned int arbor_content::PointingClusterAssociationAlgorithm::m_maxNPseudoLayers private
Definition at line 109 of file PointingClusterAssociationAlgorithm.h.
Referenced by CanMergeCluster(), and ReadSettings().
float arbor_content::PointingClusterAssociationAlgorithm::m_minClusterCosOpeningAngle private
Definition at line 118 of file PointingClusterAssociationAlgorithm.h.
Referenced by FindBestParentCluster(), and ReadSettings().
float arbor_content::PointingClusterAssociationAlgorithm::m_minClusterFitCosOpeningAngle private
Definition at line 119 of file PointingClusterAssociationAlgorithm.h.
Referenced by FindBestParentCluster(), and ReadSettings().
float arbor_content::PointingClusterAssociationAlgorithm::m_minClusterFitCosOpeningAngle2 private
Definition at line 120 of file PointingClusterAssociationAlgorithm.h.
Referenced by FindBestParentCluster(), and ReadSettings().
unsigned int arbor_content::PointingClusterAssociationAlgorithm::m_minNCaloHits private
Definition at line 106 of file PointingClusterAssociationAlgorithm.h.
Referenced by CanMergeCluster(), and ReadSettings().
unsigned int arbor_content::PointingClusterAssociationAlgorithm::m_minNPseudoLayers private
Definition at line 108 of file PointingClusterAssociationAlgorithm.h.
Referenced by ReadSettings().
unsigned int arbor_content::PointingClusterAssociationAlgorithm::m_minParentClusterBackwardNHits private
Definition at line 116 of file PointingClusterAssociationAlgorithm.h.
Referenced by ReadSettings().
unsigned int arbor_content::PointingClusterAssociationAlgorithm::m_nBackwardLayersFit private
Definition at line 111 of file PointingClusterAssociationAlgorithm.h.
Referenced by FindBestParentCluster(), GetClusterBackwardDirection(), and ReadSettings().
The documentation for this class was generated from the following files:
PointingClusterAssociationAlgorithm.h
PointingClusterAssociationAlgorithm.cc