ArborContent: arbor_content::PfoCreationAlgorithm Class Reference
arbor_content::PfoCreationAlgorithm Class Reference
PfoCreationAlgorithm class.
#include <PfoCreationAlgorithm.h>
Classes
class Factory
Factory class for instantiating algorithm.
Public Member Functions
PfoCreationAlgorithm ()
Default constructor.
Private Types
typedef
PandoraContentApi::ParticleFlowObject::Parameters PfoParameters
Private Member Functions
pandora::StatusCode Run ()
pandora::StatusCode ReadSettings (const pandora::TiXmlHandle xmlHandle)
pandora::StatusCode CreateTrackBasedPfos () const
Create particle flow objects starting from tracks in the main tracker.
pandora::StatusCode PopulateTrackBasedPfo (const pandora::Track *const pTrack, PfoParameters &pfoParameters, const bool readSiblingInfo=true) const
Add relevant tracks and clusters to a track-based pfo.
pandora::StatusCode SetTrackBasedPfoParameters (const pandora::Track *const pTrack, PfoParameters &pfoParameters) const
Set the basic parameters for a track-based pfo.
pandora::StatusCode SetSiblingTrackBasedPfoParameters (const pandora::Track *const pTrack, PfoParameters &pfoParameters) const
Set the parameters for a track-based pfo, where pfo target consists of two or more sibling tracks.
pandora::StatusCode SetDaughterTrackBasedPfoParameters (const pandora::Track *const pTrack, PfoParameters &pfoParameters) const
Set the parameters for a track-based pfo, where the pfo target has one or more daughter tracks.
pandora::StatusCode SetSimpleTrackBasedPfoParameters (const pandora::Track *const pTrack, PfoParameters &pfoParameters) const
Set the parameters for a simple track-based pfo, where the track has no associations with other tracks.
pandora::StatusCode CreateNeutralPfos () const
Create particle flow objects corresponding to neutral particles, These pfos consist only of clusters that have no associated tracks.
const pandora::CartesianVector GetEnergyWeightedCentroid (const pandora::Cluster *const pCluster, const unsigned int innerPseudoLayer, const unsigned int outerPseudoLayer) const
Get the energy-weighted centroid for a specified cluster, calculated over a particular pseudo layer range.
Private Attributes
std::string m_outputPfoListName
The output pfo list name.
bool m_shouldCreateTrackBasedPfos
Whether to create track-based (charged) pfos.
bool m_shouldCreateNeutralPfos
Whether to create neutral pfos.
float m_minClusterHadronicEnergy
Min hadronic energy for neutral (non-photon) clusters to be added to pfos.
float m_minClusterElectromagneticEnergy
Min electromagnetic energy for neutral (photon) clusters to be added to pfos.
unsigned int m_minHitsInCluster
Min number of calo hits for neutral cluster to be added to pfos.
bool m_allowSingleLayerClusters
Whether to allow neutral clusters spanning only a single pseudolayer.
unsigned int m_photonPositionAlgorithm
Identifies the algorithm used to calculate photon pfo position vectors.
Detailed Description
PfoCreationAlgorithm class.
Definition at line 41 of file PfoCreationAlgorithm.h.
Member Typedef Documentation
typedef PandoraContentApi::ParticleFlowObject::Parameters arbor_content::PfoCreationAlgorithm::PfoParameters private
Definition at line 59 of file PfoCreationAlgorithm.h.
Constructor & Destructor Documentation
arbor_content::PfoCreationAlgorithm::PfoCreationAlgorithm ()
Default constructor.
Definition at line 34 of file PfoCreationAlgorithm.cc.
Referenced by arbor_content::PfoCreationAlgorithm::Factory::CreateAlgorithm().
                                            :
     m_shouldCreateTrackBasedPfos(true),
     m_shouldCreateNeutralPfos(true),
     m_minClusterHadronicEnergy(0.1f),
     m_minClusterElectromagneticEnergy(0.1f),
     m_minHitsInCluster(5),
     m_allowSingleLayerClusters(false),
     m_photonPositionAlgorithm(2)
 {
 }
Member Function Documentation
pandora::StatusCode arbor_content::PfoCreationAlgorithm::CreateNeutralPfos () const private
Create particle flow objects corresponding to neutral particles, These pfos consist only of clusters that have no associated tracks.
Definition at line 241 of file PfoCreationAlgorithm.cc.
References GetEnergyWeightedCentroid(), m_allowSingleLayerClusters, m_minClusterElectromagneticEnergy, m_minClusterHadronicEnergy, m_minHitsInCluster, and m_photonPositionAlgorithm.
Referenced by Run().
 {
     const pandora::ClusterList *pClusterList = NULL;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(*this, pClusterList));
     // Examine clusters with no associated tracks to form neutral pfos
     for (pandora::ClusterList::const_iterator iter = pClusterList->begin(), iterEnd = pClusterList->end(); iter != iterEnd; ++iter)
     {
         const pandora::Cluster *const pCluster = *iter;
         if (!pCluster->GetAssociatedTrackList().empty())
             continue;
         if (pCluster->GetNCaloHits() < m_minHitsInCluster)
             continue;
         const bool isPhoton(pCluster->IsPhotonFast(this->GetPandora()));
         float clusterEnergy(isPhoton ? pCluster->GetCorrectedElectromagneticEnergy(this->GetPandora()) : pCluster->GetCorrectedHadronicEnergy(this->GetPandora()));
         // Veto non-photon clusters below hadronic energy threshold and those occupying a single layer
         if (!isPhoton)
         {
             if (clusterEnergy < m_minClusterHadronicEnergy)
                 continue;
             if (!m_allowSingleLayerClusters && (pCluster->GetInnerPseudoLayer() == pCluster->GetOuterPseudoLayer()))
                 continue;
         }
         else
         {
             if (clusterEnergy < m_minClusterElectromagneticEnergy)
                 continue;
         }
         // Specify the pfo parameters
         PandoraContentApi::ParticleFlowObject::Parameters pfoParameters;
         pfoParameters.m_particleId = (isPhoton ? pandora::PHOTON : pandora::NEUTRON);
         pfoParameters.m_charge = 0;
         pfoParameters.m_mass = (isPhoton ? pandora::PdgTable::GetParticleMass(pandora::PHOTON) : pandora::PdgTable::GetParticleMass(pandora::NEUTRON));
         pfoParameters.m_energy = clusterEnergy;
         pfoParameters.m_clusterList.insert(pCluster);
         // Photon position: 0) unweighted inner centroid, 1) energy-weighted inner centroid, 2+) energy-weighted centroid for all layers
         pandora::CartesianVector positionVector(0.f, 0.f, 0.f);
         const unsigned int clusterInnerLayer(pCluster->GetInnerPseudoLayer());
         if (!isPhoton || (0 == m_photonPositionAlgorithm))
         {
             positionVector = pCluster->GetCentroid(clusterInnerLayer);
         }
         else if (1 == m_photonPositionAlgorithm)
         {
             positionVector = this->GetEnergyWeightedCentroid(pCluster, clusterInnerLayer, clusterInnerLayer);
         }
         else
         {
             positionVector = this->GetEnergyWeightedCentroid(pCluster, clusterInnerLayer, pCluster->GetOuterPseudoLayer());
         }
         const pandora::CartesianVector momentum(positionVector.GetUnitVector() * clusterEnergy);
         pfoParameters.m_momentum = momentum;
         const pandora::ParticleFlowObject *pPfo(NULL);
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::ParticleFlowObject::Create(*this, pfoParameters, pPfo));
     }
     return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode arbor_content::PfoCreationAlgorithm::CreateTrackBasedPfos () const private
Create particle flow objects starting from tracks in the main tracker.
The pfos will account for associated daughter/sibling tracks and associated calorimeter clusters.
Definition at line 69 of file PfoCreationAlgorithm.cc.
References PopulateTrackBasedPfo(), and SetTrackBasedPfoParameters().
Referenced by Run().
 {
     // Current track list should contain those tracks selected as "good" by the track preparation algorithm
     const pandora::TrackList *pTrackList = NULL;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList<pandora::TrackList>(*this, pTrackList));
     for (pandora::TrackList::const_iterator iter = pTrackList->begin(), iterEnd = pTrackList->end(); iter != iterEnd; ++iter)
     {
         const pandora::Track *const pTrack = *iter;
         PandoraContentApi::ParticleFlowObject::Parameters pfoParameters;
         // Walk along list of associated daughter/sibling tracks and their cluster associations
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->PopulateTrackBasedPfo(pTrack, pfoParameters));
         // Specify the pfo parameters
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->SetTrackBasedPfoParameters(pTrack, pfoParameters));
         // Create the pfo
         const pandora::ParticleFlowObject *pPfo(NULL);
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::ParticleFlowObject::Create(*this, pfoParameters, pPfo));
     }
     return pandora::STATUS_CODE_SUCCESS;
 }
const pandora::CartesianVector arbor_content::PfoCreationAlgorithm::GetEnergyWeightedCentroid (const pandora::Cluster *const pCluster, const unsigned int innerPseudoLayer, const unsigned int outerPseudoLayer) const private
Get the energy-weighted centroid for a specified cluster, calculated over a particular pseudo layer range.
Parameters
pCluster address of the cluster to consider
pseudoLayer the inner pseudo layer of interest
pseudoLayer the outer pseudo layer of interest
Returns
The energy-weighted centroid, returned by value
Definition at line 312 of file PfoCreationAlgorithm.cc.
Referenced by CreateNeutralPfos().
 {
     float energySum(0.f);
     pandora::CartesianVector energyPositionSum(0.f, 0.f, 0.f);
     const pandora::OrderedCaloHitList &orderedCaloHitList(pCluster->GetOrderedCaloHitList());
     for (pandora::OrderedCaloHitList::const_iterator iter = orderedCaloHitList.begin(), iterEnd = orderedCaloHitList.end(); iter != iterEnd; ++iter)
     {
         if (iter->first > outerPseudoLayer)
             break;
         if (iter->first < innerPseudoLayer)
             continue;
         for (pandora::CaloHitList::const_iterator hitIter = iter->second->begin(), hitIterEnd = iter->second->end(); hitIter != hitIterEnd; ++hitIter)
         {
             const float electromagneticEnergy((*hitIter)->GetElectromagneticEnergy());
             energySum += electromagneticEnergy;
             energyPositionSum += ((*hitIter)->GetPositionVector() * electromagneticEnergy);
         }
     }
     if (energySum < std::numeric_limits<float>::epsilon())
         throw pandora::StatusCodeException(pandora::STATUS_CODE_NOT_INITIALIZED);
     return (energyPositionSum * (1.f / energySum));
 }
pandora::StatusCode arbor_content::PfoCreationAlgorithm::PopulateTrackBasedPfo (const pandora::Track *const pTrack, PfoParameters & pfoParameters, const bool readSiblingInfo = true) const private
Add relevant tracks and clusters to a track-based pfo.
Parameters
pTrack address of the track to consider
pfoParameters the pfo parameters to populate
readSiblingInfo whether to read sibling track information (set to false to avoid multiple counting)
Definition at line 96 of file PfoCreationAlgorithm.cc.
Referenced by CreateTrackBasedPfos().
 {
     // Add track to the pfo
     pfoParameters.m_trackList.insert(pTrack);
     // Add any cluster associated with this track to the pfo
     try
     {
         const pandora::Cluster *const pAssociatedCluster(pTrack->GetAssociatedCluster());
         pfoParameters.m_clusterList.insert(pAssociatedCluster);
     }
     catch (pandora::StatusCodeException &)
     {
     }
     // Consider any sibling tracks
     if (readSiblingInfo)
     {
         const pandora::TrackList &siblingTrackList(pTrack->GetSiblingTrackList());
         for (pandora::TrackList::const_iterator iter = siblingTrackList.begin(), iterEnd = siblingTrackList.end(); iter != iterEnd; ++iter)
         {
             PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->PopulateTrackBasedPfo(*iter, pfoParameters, false));
         }
     }
     // Consider any daughter tracks
     const pandora::TrackList &daughterTrackList(pTrack->GetDaughterTrackList());
     for (pandora::TrackList::const_iterator iter = daughterTrackList.begin(), iterEnd = daughterTrackList.end(); iter != iterEnd; ++iter)
     {
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->PopulateTrackBasedPfo(*iter, pfoParameters));
     }
     return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode arbor_content::PfoCreationAlgorithm::ReadSettings (const pandora::TiXmlHandle xmlHandle) private
Definition at line 343 of file PfoCreationAlgorithm.cc.
References m_allowSingleLayerClusters, m_minClusterElectromagneticEnergy, m_minClusterHadronicEnergy, m_minHitsInCluster, m_outputPfoListName, m_photonPositionAlgorithm, m_shouldCreateNeutralPfos, and m_shouldCreateTrackBasedPfos.
 {
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "OutputPfoListName", m_outputPfoListName));
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "ShouldCreateTrackBasedPfos", m_shouldCreateTrackBasedPfos));
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "ShouldCreateNeutralPfos", m_shouldCreateNeutralPfos));
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinClusterHadronicEnergy", m_minClusterHadronicEnergy));
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinClusterElectromagneticEnergy", m_minClusterElectromagneticEnergy));
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinHitsInCluster", m_minHitsInCluster));
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "AllowSingleLayerClusters", m_allowSingleLayerClusters));
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "PhotonPositionAlgorithm", m_photonPositionAlgorithm));
     return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode arbor_content::PfoCreationAlgorithm::Run () private
Definition at line 47 of file PfoCreationAlgorithm.cc.
References CreateNeutralPfos(), CreateTrackBasedPfos(), m_outputPfoListName, m_shouldCreateNeutralPfos, and m_shouldCreateTrackBasedPfos.
 {
     const pandora::PfoList *pPfoList = NULL; std::string pfoListName;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::CreateTemporaryListAndSetCurrent(*this, pPfoList, pfoListName));
     if (m_shouldCreateTrackBasedPfos)
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->CreateTrackBasedPfos());
     if (m_shouldCreateNeutralPfos)
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->CreateNeutralPfos());
     if (!pPfoList->empty())
     {
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::SaveList<pandora::Pfo>(*this, m_outputPfoListName));
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::ReplaceCurrentList<pandora::Pfo>(*this, m_outputPfoListName));
     }
     return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode arbor_content::PfoCreationAlgorithm::SetDaughterTrackBasedPfoParameters (const pandora::Track *const pTrack, PfoParameters & pfoParameters) const private
Set the parameters for a track-based pfo, where the pfo target has one or more daughter tracks.
Parameters
pTrack address of the track to consider
pfoParameters the pfo parameters to populate
Definition at line 196 of file PfoCreationAlgorithm.cc.
Referenced by SetTrackBasedPfoParameters().
 {
     int daughterCharge(0);
     float energy(0.f);
     pandora::CartesianVector momentum(0.f, 0.f, 0.f);
     const pandora::TrackList &daughterTrackList(pTrack->GetDaughterTrackList());
     const unsigned int nDaughters(daughterTrackList.size());
     for (pandora::TrackList::const_iterator iter = daughterTrackList.begin(), iterEnd = daughterTrackList.end(); iter != iterEnd; ++iter)
     {
         const pandora::Track *const pDaughterTrack = *iter;
         if (!pDaughterTrack->CanFormPfo() && !pDaughterTrack->CanFormClusterlessPfo())
             continue;
         daughterCharge += pDaughterTrack->GetCharge();
         energy += pDaughterTrack->GetEnergyAtDca();
         momentum += pDaughterTrack->GetMomentumAtDca();
     }
     pfoParameters.m_energy = energy;
     pfoParameters.m_momentum = momentum;
     pfoParameters.m_mass = std::sqrt(std::max(energy * energy - momentum.GetDotProduct(momentum), 0.f));
     pfoParameters.m_charge = (nDaughters > 1) ? pTrack->GetCharge() : daughterCharge;
     pfoParameters.m_particleId = (pfoParameters.m_charge.Get() > 0) ? pandora::PI_PLUS : pandora::PI_MINUS;
     return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode arbor_content::PfoCreationAlgorithm::SetSiblingTrackBasedPfoParameters (const pandora::Track *const pTrack, PfoParameters & pfoParameters) const private
Set the parameters for a track-based pfo, where pfo target consists of two or more sibling tracks.
Parameters
pTrack address of the track to consider
pfoParameters the pfo parameters to populate
Definition at line 159 of file PfoCreationAlgorithm.cc.
Referenced by SetTrackBasedPfoParameters().
 {
     int charge(0);
     float energy(0.f);
     pandora::CartesianVector momentum(0.f, 0.f, 0.f);
     pandora::TrackList fullSiblingTrackList(pTrack->GetSiblingTrackList());
     fullSiblingTrackList.insert(pTrack);
     for (pandora::TrackList::const_iterator iter = fullSiblingTrackList.begin(), iterEnd = fullSiblingTrackList.end(); iter != iterEnd; ++iter)
     {
         const pandora::Track *const pSiblingTrack = *iter;
         charge += pSiblingTrack->GetCharge();
         if (!pSiblingTrack->CanFormPfo() && !pSiblingTrack->CanFormClusterlessPfo())
             continue;
         // ATTN Assume sibling-track-based pfos represent pair-production
         const float electronMass(pandora::PdgTable::GetParticleMass(pandora::E_MINUS));
         energy += std::sqrt(electronMass * electronMass + pSiblingTrack->GetMomentumAtDca().GetMagnitudeSquared());
         momentum += pSiblingTrack->GetMomentumAtDca();
     }
     if (energy < std::numeric_limits<float>::epsilon())
         return pandora::STATUS_CODE_NOT_INITIALIZED;
     pfoParameters.m_energy = energy;
     pfoParameters.m_momentum = momentum;
     pfoParameters.m_mass = std::sqrt(std::max(energy * energy - momentum.GetDotProduct(momentum), 0.f));
     pfoParameters.m_charge = charge;
     pfoParameters.m_particleId = pandora::PHOTON;
     return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode arbor_content::PfoCreationAlgorithm::SetSimpleTrackBasedPfoParameters (const pandora::Track *const pTrack, PfoParameters & pfoParameters) const private
Set the parameters for a simple track-based pfo, where the track has no associations with other tracks.
Parameters
pTrack address of the track to consider
pfoParameters the pfo parameters to populate
Definition at line 228 of file PfoCreationAlgorithm.cc.
Referenced by SetTrackBasedPfoParameters().
 {
     pfoParameters.m_energy = pTrack->GetEnergyAtDca();
     pfoParameters.m_momentum = pTrack->GetMomentumAtDca();
     pfoParameters.m_mass = pTrack->GetMass();
     pfoParameters.m_charge = pTrack->GetCharge();
     pfoParameters.m_particleId = (pTrack->GetCharge() > 0) ? pandora::PI_PLUS : pandora::PI_MINUS;
     return pandora::STATUS_CODE_SUCCESS;
 }
pandora::StatusCode arbor_content::PfoCreationAlgorithm::SetTrackBasedPfoParameters (const pandora::Track *const pTrack, PfoParameters & pfoParameters) const private
Set the basic parameters for a track-based pfo.
Parameters
pTrack address of the track to consider
pfoParameters the pfo parameters to populate
Definition at line 135 of file PfoCreationAlgorithm.cc.
References SetDaughterTrackBasedPfoParameters(), SetSiblingTrackBasedPfoParameters(), and SetSimpleTrackBasedPfoParameters().
Referenced by CreateTrackBasedPfos().
 {
     const bool hasParent(!pTrack->GetParentTrackList().empty());
     if (hasParent)
         return pandora::STATUS_CODE_NOT_ALLOWED;
     const bool hasSibling(!pTrack->GetSiblingTrackList().empty());
     const bool hasDaughter(!pTrack->GetDaughterTrackList().empty());
     if (hasSibling && hasDaughter)
         return pandora::STATUS_CODE_NOT_ALLOWED;
     if (hasSibling)
         return this->SetSiblingTrackBasedPfoParameters(pTrack, pfoParameters);
     if (hasDaughter)
         return this->SetDaughterTrackBasedPfoParameters(pTrack, pfoParameters);
     return this->SetSimpleTrackBasedPfoParameters(pTrack, pfoParameters);
 }
Member Data Documentation
bool arbor_content::PfoCreationAlgorithm::m_allowSingleLayerClusters private
Whether to allow neutral clusters spanning only a single pseudolayer.
Definition at line 135 of file PfoCreationAlgorithm.h.
Referenced by CreateNeutralPfos(), and ReadSettings().
float arbor_content::PfoCreationAlgorithm::m_minClusterElectromagneticEnergy private
Min electromagnetic energy for neutral (photon) clusters to be added to pfos.
Definition at line 133 of file PfoCreationAlgorithm.h.
Referenced by CreateNeutralPfos(), and ReadSettings().
float arbor_content::PfoCreationAlgorithm::m_minClusterHadronicEnergy private
Min hadronic energy for neutral (non-photon) clusters to be added to pfos.
Definition at line 132 of file PfoCreationAlgorithm.h.
Referenced by CreateNeutralPfos(), and ReadSettings().
unsigned int arbor_content::PfoCreationAlgorithm::m_minHitsInCluster private
Min number of calo hits for neutral cluster to be added to pfos.
Definition at line 134 of file PfoCreationAlgorithm.h.
Referenced by CreateNeutralPfos(), and ReadSettings().
std::string arbor_content::PfoCreationAlgorithm::m_outputPfoListName private
The output pfo list name.
Definition at line 129 of file PfoCreationAlgorithm.h.
Referenced by ReadSettings(), and Run().
unsigned int arbor_content::PfoCreationAlgorithm::m_photonPositionAlgorithm private
Identifies the algorithm used to calculate photon pfo position vectors.
Definition at line 136 of file PfoCreationAlgorithm.h.
Referenced by CreateNeutralPfos(), and ReadSettings().
bool arbor_content::PfoCreationAlgorithm::m_shouldCreateNeutralPfos private
Whether to create neutral pfos.
Definition at line 131 of file PfoCreationAlgorithm.h.
Referenced by ReadSettings(), and Run().
bool arbor_content::PfoCreationAlgorithm::m_shouldCreateTrackBasedPfos private
Whether to create track-based (charged) pfos.
Definition at line 130 of file PfoCreationAlgorithm.h.
Referenced by ReadSettings(), and Run().
The documentation for this class was generated from the following files:
PfoCreationAlgorithm.h
PfoCreationAlgorithm.cc