PandoraSDK: pandora::StatusCodeException Class Reference
pandora::StatusCodeException Class Reference
StatusCodeException class.
#include <StatusCodes.h>
Public Member Functions
StatusCodeException (const StatusCode statusCode)
Constructor.
~StatusCodeException () throw ()
Constructor.
StatusCode GetStatusCode () const
Get status code.
std::string ToString () const
Get status code as a string.
const std::string & GetBackTrace () const
Get back trace at point of exception construction (gcc only)
Detailed Description
StatusCodeException class.
Constructor & Destructor Documentation
pandora::StatusCodeException::StatusCodeException (const StatusCode statusCode) inline
Constructor.
Parameters
statusCode the status code
Member Function Documentation
const std::string & pandora::StatusCodeException::GetBackTrace () const inline
Get back trace at point of exception construction (gcc only)
Returns
The back trace
StatusCode pandora::StatusCodeException::GetStatusCode () const inline
Get status code.
Returns
the status code
Referenced by pandora::ClusterFitHelper::FitLayerCentroids(), and pandora::ClusterFitHelper::FitPoints().
std::string pandora::StatusCodeException::ToString () const inline
Get status code as a string.
Returns
The status code string
Referenced by pandora::Pandora::Pandora(), pandora::PluginManager::PluginManager(), pandora::FileReader::ReadEvent(), and pandora::FileReader::ReadGeometry().
The documentation for this class was generated from the following file:
StatusCodes.h