PandoraSDK: pandora::PluginManager Class Reference
pandora::PluginManager Class Reference
PluginManager class.
#include <PluginManager.h>
Public Member Functions
PluginManager (const Pandora *const pPandora)
Constructor.
~PluginManager ()
Destructor.
const BFieldPlugin * GetBFieldPlugin () const
Get the address of the b field plugin.
const PseudoLayerPlugin * GetPseudoLayerPlugin () const
Get the address of the pseudo layer plugin.
const ShowerProfilePlugin * GetShowerProfilePlugin () const
Get the shower profile plugin.
const EnergyCorrections * GetEnergyCorrections () const
Get the pandora energy corrections instance.
const ParticleId * GetParticleId () const
Get the address of the pandora particle id instance.
Friends
class PandoraApiImpl
class PandoraImpl
Detailed Description
PluginManager class.
Constructor & Destructor Documentation
pandora::PluginManager::PluginManager (const Pandora *const pPandora)
Constructor.
Parameters
pPandora address of the associated pandora object
References pandora::StatusCodeException::ToString().
Member Function Documentation
const BFieldPlugin * pandora::PluginManager::GetBFieldPlugin () const
Get the address of the b field plugin.
Returns
the address of the b field plugin
const EnergyCorrections * pandora::PluginManager::GetEnergyCorrections () const
Get the pandora energy corrections instance.
Returns
the address of the pandora energy corrections instance
Referenced by pandora::Cluster::PerformEnergyCorrections().
const ParticleId * pandora::PluginManager::GetParticleId () const
Get the address of the pandora particle id instance.
Returns
the address of the pandora particle id instance
Referenced by pandora::Cluster::CalculateFastPhotonFlag(), and pandora::Cluster::PerformEnergyCorrections().
const PseudoLayerPlugin * pandora::PluginManager::GetPseudoLayerPlugin () const
Get the address of the pseudo layer plugin.
Returns
the address of the pseudo layer plugin
const ShowerProfilePlugin * pandora::PluginManager::GetShowerProfilePlugin () const
Get the shower profile plugin.
Returns
address of the shower profile plugin
Referenced by pandora::Cluster::CalculateShowerProfile(), and pandora::Cluster::CalculateShowerStartLayer().
The documentation for this class was generated from the following files:
PluginManager.h
PluginManager.cc