PandoraSDK: pandora::AlgorithmObjectManager< T > Singleton Reference
pandora::AlgorithmObjectManager< T > Singleton Reference
AlgorithmObjectManager class.
#include <AlgorithmObjectManager.h>
Public Member Functions
AlgorithmObjectManager (const Pandora *const pPandora)
Constructor.
virtual ~AlgorithmObjectManager ()
Destructor.
Public Member Functions inherited from pandora::Manager< T >
Manager (const Pandora *const pPandora)
Constructor.
virtual ~Manager ()
Destructor.
Protected Types
typedef Manager< T >::ObjectList ObjectList
Protected Types inherited from pandora::Manager< T >
typedef std::MANAGED_CONTAINER
< const T * > ObjectList
typedef std::map< std::string,
ObjectList * > NameToListMap
typedef std::map< const
Algorithm *, AlgorithmInfo > AlgorithmInfoMap
Protected Member Functions
virtual StatusCode CreateTemporaryListAndSetCurrent (const Algorithm *const pAlgorithm, std::string &temporaryListName)
Make a temporary list and set it to be the current list.
virtual StatusCode MoveObjectsToTemporaryListAndSetCurrent (const Algorithm *const pAlgorithm, const std::string &originalListName, std::string &temporaryListName, const ObjectList &objectsToMove)
Move objects to a new temporary object list and set it to be the current object list.
virtual StatusCode SaveObjects (const std::string &targetListName, const std::string &sourceListName)
Save a list of objects.
virtual StatusCode SaveObjects (const std::string &targetListName, const std::string &sourceListName, const ObjectList &objectsToSave)
Save a list of objects.
virtual StatusCode MoveObjectsBetweenLists (const std::string &targetListName, const std::string &sourceListName, const ObjectList *pObjectSubset=NULL)
Move (a subset of) objects between two lists.
virtual StatusCode TemporarilyReplaceCurrentList (const std::string &listName)
Temporarily replace the current list with another list, which may only be a temporary list.
virtual StatusCode DeleteObject (const T *const pT, const std::string &listName)
Delete an object from a specified list.
virtual StatusCode DeleteObjects (const ObjectList &objectList, const std::string &listName)
Delete a list of objects from a specified list.
virtual StatusCode DeleteTemporaryObjects (const Algorithm *const pAlgorithm, const std::string &temporaryListName)
Delete the contents of a temporary list.
virtual StatusCode GetResetDeletionObjects (const Algorithm *const pAlgorithm, ObjectList &objectList) const
Get the list of objects that will be deleted when the algorithm info is reset.
virtual StatusCode ResetCurrentListToAlgorithmInputList (const Algorithm *const pAlgorithm)
Reset the current list to the algorithm input list.
virtual StatusCode ReplaceCurrentAndAlgorithmInputLists (const Algorithm *const pAlgorithm, const std::string &listName)
Replace the current and algorithm input lists with a pre-existing list.
virtual StatusCode DropCurrentList (const Algorithm *const pAlgorithm)
Drop the current list, returning the current list to its default empty/null state.
virtual StatusCode ResetAlgorithmInfo (const Algorithm *const pAlgorithm, bool isAlgorithmFinished)
Remove temporary lists and reset the current cluster list to that when algorithm was initialized.
virtual StatusCode EraseAllContent ()
Erase all manager content.
Protected Member Functions inherited from pandora::Manager< T >
virtual StatusCode GetList (const std::string &listName, const ObjectList *&pObjectList) const
Get a list.
virtual StatusCode GetCurrentList (const ObjectList *&pObjectList, std::string &listName) const
Get the current list.
virtual StatusCode GetCurrentListName (std::string &listName) const
Get the current list name.
virtual StatusCode GetAlgorithmInputList (const Algorithm *const pAlgorithm, const ObjectList *&pObjectList, std::string &listName) const
Get the algorithm input list.
virtual StatusCode GetAlgorithmInputListName (const Algorithm *const pAlgorithm, std::string &listName) const
Get the algorithm track list name.
virtual StatusCode RegisterAlgorithm (const Algorithm *const pAlgorithm)
Register an algorithm with the manager.
virtual StatusCode ResetForNextEvent ()
Reset the manager.
virtual StatusCode CreateInitialLists ()
Create initial lists.
virtual T * Modifiable (const T *const pT) const
Access a modifiable object, when provided with address to const object.
Protected Attributes
bool m_canMakeNewObjects
Whether the manager is allowed to make new objects when requested by algorithms.
Protected Attributes inherited from pandora::Manager< T >
NameToListMap m_nameToListMap
The name to list map.
AlgorithmInfoMap m_algorithmInfoMap
The algorithm info map.
std::string m_currentListName
The name of the current list.
StringSet m_savedLists
The set of saved lists.
const Pandora *const m_pPandora
The associated pandora object.
Additional Inherited Members
Static Protected Attributes inherited from pandora::Manager< T >
static const std::string NULL_LIST_NAME = "NullList"
The name of the default empty (NULL) list.
Detailed Description
template<typename T>
singleton pandora::AlgorithmObjectManager< T >
AlgorithmObjectManager class.
Constructor & Destructor Documentation
template<typename T > pandora::AlgorithmObjectManager< T >::AlgorithmObjectManager (const Pandora *const pPandora)
Constructor.
Parameters
pPandora address of the associated pandora object
Member Function Documentation
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::CreateTemporaryListAndSetCurrent (const Algorithm *const pAlgorithm, std::string & temporaryListName) protected virtual
Make a temporary list and set it to be the current list.
Parameters
pAlgorithm address of the algorithm requesting a temporary list
temporaryListName to receive the name of the temporary list
Reimplemented from pandora::Manager< T >.
References pandora::Manager< T >::CreateTemporaryListAndSetCurrent().
template<typename T> StatusCode pandora::AlgorithmObjectManager< T >::DeleteObject (const T *const pT, const std::string & listName) protected virtual
Delete an object from a specified list.
Parameters
pCluster address of the object to delete
listName the name of the list containing the object
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::DeleteObjects (const ObjectList & objectList, const std::string & listName) protected virtual
Delete a list of objects from a specified list.
Parameters
objectList the list of objects to delete
listName the name of the list containing the objects
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::DeleteTemporaryObjects (const Algorithm *const pAlgorithm, const std::string & temporaryListName) protected virtual
Delete the contents of a temporary list.
Parameters
pAlgorithm address of the algorithm calling this function
temporaryListName the name of the temporary list
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::DropCurrentList (const Algorithm *const pAlgorithm) protected virtual
Drop the current list, returning the current list to its default empty/null state.
Parameters
pAlgorithm address of the algorithm altering the lists
Reimplemented from pandora::Manager< T >.
References pandora::Manager< T >::DropCurrentList().
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::GetResetDeletionObjects (const Algorithm *const pAlgorithm, ObjectList & objectList) const protected virtual
Get the list of objects that will be deleted when the algorithm info is reset.
Parameters
pAlgorithm address of the algorithm
objectList to receive the list of objects that will be deleted when the algorithm info is reset
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::MoveObjectsBetweenLists (const std::string & targetListName, const std::string & sourceListName, const ObjectList * pObjectSubset = NULL) protected virtual
Move (a subset of) objects between two lists.
Parameters
targetListName the name of the target object list, which will be created if it doesn't currently exist
sourceListName the name of the object list containing objects to save
pObjectSubset if specified, only objects in both this and the source list will be moved
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::MoveObjectsToTemporaryListAndSetCurrent (const Algorithm *const pAlgorithm, const std::string & originalListName, std::string & temporaryListName, const ObjectList & objectsToMove) protected virtual
Move objects to a new temporary object list and set it to be the current object list.
Parameters
pAlgorithm address of the algorithm requesting a temporary list
originalListName the list in which the object currently exist
temporaryListName to receive the name of the temporary list
objectsToMove only objects in both this and the current list will be moved
other object in the current list will remain in original list
an empty object list will be rejected
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::ReplaceCurrentAndAlgorithmInputLists (const Algorithm *const pAlgorithm, const std::string & listName) protected virtual
Replace the current and algorithm input lists with a pre-existing list.
Parameters
pAlgorithm address of the algorithm changing the current list
listName the name of the new current (and algorithm input) list
Reimplemented from pandora::Manager< T >.
References pandora::Manager< T >::ReplaceCurrentAndAlgorithmInputLists().
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::ResetAlgorithmInfo (const Algorithm *const pAlgorithm, bool isAlgorithmFinished) protected virtual
Remove temporary lists and reset the current cluster list to that when algorithm was initialized.
Parameters
pAlgorithm the algorithm associated with the temporary objects
isAlgorithmFinished whether the algorithm has completely finished and the algorithm info should be entirely removed
Reimplemented from pandora::Manager< T >.
References pandora::Manager< T >::ResetAlgorithmInfo().
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::ResetCurrentListToAlgorithmInputList (const Algorithm *const pAlgorithm) protected virtual
Reset the current list to the algorithm input list.
Parameters
pAlgorithm address of the algorithm changing the current track list
Reimplemented from pandora::Manager< T >.
References pandora::Manager< T >::ResetCurrentListToAlgorithmInputList().
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::SaveObjects (const std::string & targetListName, const std::string & sourceListName) protected virtual
Save a list of objects.
Parameters
targetListName the name of the target object list, which will be created if it doesn't currently exist
sourceListName the name of the (typically temporary) object list to save
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::SaveObjects (const std::string & targetListName, const std::string & sourceListName, const ObjectList & objectsToSave) protected virtual
Save a list of objects.
Parameters
targetListName the name of the target object list, which will be created if it doesn't currently exist
sourceListName the name of the (typically temporary) object list containing objects to save
objectToSave only objects in both this and the temporary list will be stored
other object will remain in the temporary list and will be deleted when the parent algorithm exits
an empty object list will be rejected
template<typename T > StatusCode pandora::AlgorithmObjectManager< T >::TemporarilyReplaceCurrentList (const std::string & listName) protected virtual
Temporarily replace the current list with another list, which may only be a temporary list.
This switch will persist only for the duration of the algorithm and its daughters; unless otherwise specified, the list will revert to the algorithm input list upon algorithm completion.
Parameters
listName the name of the new current (and algorithm input) list
The documentation for this singleton was generated from the following files:
AlgorithmObjectManager.h
AlgorithmObjectManager.cc