PandoraSDK: pandora::CaloHit Class Reference
pandora::CaloHit Class Reference
CaloHit class.
#include <CaloHit.h>
Public Member Functions
const CartesianVector & GetPositionVector () const
Get the position vector of center of calorimeter cell, units mm.
const CartesianVector & GetExpectedDirection () const
Get the unit vector in direction of expected hit propagation.
const CartesianVector & GetCellNormalVector () const
Get the unit vector normal to the sampling layer, pointing outwards from the origin.
CellGeometry GetCellGeometry () const
Get the cell geometry.
float GetCellSize0 () const
Get the cell size 0 [pointing: eta, rectangular: up in ENDCAP, along beam in BARREL, units mm].
float GetCellSize1 () const
Get the cell size 1 [pointing: phi, rectangular: perpendicular to size 0 and thickness, units mm].
float GetCellThickness () const
Get the thickness of cell, units mm.
float GetNCellRadiationLengths () const
Get the absorber material in front of cell, units radiation lengths.
float GetNCellInteractionLengths () const
Get the absorber material in front of cell, units interaction lengths.
float GetInputEnergy () const
Get the corrected energy of the calorimeter cell, units GeV, as supplied by the user.
float GetTime () const
Get the time of (earliest) energy deposition in this cell, units ns.
bool IsDigital () const
Whether cell should be treated as digital.
HitType GetHitType () const
Get the calorimeter hit type.
HitRegion GetHitRegion () const
Get the region of the detector in which the calo hit is located.
unsigned int GetLayer () const
Get the subdetector readout layer number.
unsigned int GetPseudoLayer () const
Get pseudo layer for the calo hit.
bool IsInOuterSamplingLayer () const
Whether cell is in one of the outermost detector sampling layers.
float GetMipEquivalentEnergy () const
Get the calibrated mip equivalent energy.
float GetElectromagneticEnergy () const
Get the calibrated electromagnetic energy measure.
float GetHadronicEnergy () const
Get the calibrated hadronic energy measure.
float GetCellLengthScale () const
Get the typical length scale of cell, units mm.
bool IsPossibleMip () const
Whether the calo hit is flagged as a possible mip hit.
bool IsIsolated () const
Whether the calo hit is flagged as isolated.
float GetWeight () const
Get the calo hit weight, which may not be unity if the hit has been fragmented.
const MCParticleWeightMap & GetMCParticleWeightMap () const
Get mc particle weight map for the calo hit.
const void * GetParentCaloHitAddress () const
Get the address of the parent calo hit in the user framework.
void GetCellCorners (CartesianPointList &cartesianPointList) const
Get the list of cartesian coordinates for the cell corners.
Protected Member Functions
CaloHit (const PandoraApi::CaloHit::Parameters &parameters)
Constructor.
CaloHit (const PandoraContentApi::CaloHitFragment::Parameters &parameters)
Weighted copy constructor.
virtual ~CaloHit ()
Destructor.
StatusCode SetPseudoLayer (const unsigned int pseudoLayer)
Set the mc pseudo layer for the calo hit.
StatusCode AlterMetadata (const PandoraContentApi::CaloHit::Metadata &metadata)
Alter the metadata information stored in a calo hit.
void SetMCParticleWeightMap (const MCParticleWeightMap &mcParticleWeightMap)
Set the mc particles associated with the calo hit.
void RemoveMCParticles ()
Remove the mc particles associated with the calo hit.
float CalculateCellLengthScale () const
Calculate the typical length scale of the cell, units mm.
void GetRectangularCellCorners (CartesianPointList &cartesianPointList) const
Get the list of cartesian coordinates for rectangular cell corners.
void GetPointingCellCorners (CartesianPointList &cartesianPointList) const
Get the list of cartesian coordinates for pointing cell corners.
bool IsAvailable () const
Whether the calo hit is available to be added to a cluster (access this function via PandoraContentAPI)
void SetAvailability (bool isAvailable)
Set availability of calo hit to be added to a cluster.
Protected Attributes
const CartesianVector m_positionVector
Position vector of center of calorimeter cell, units mm.
const CartesianVector m_expectedDirection
Unit vector in direction of expected hit propagation.
const CartesianVector m_cellNormalVector
Unit normal to the sampling layer, pointing outwards from the origin.
const CellGeometry m_cellGeometry
The cell geometry type, pointing or rectangular.
const float m_cellSize0
Cell size 0 [pointing: pseudo rapidity, eta, rectangular: up in ENDCAP, along beam in BARREL, units mm].
const float m_cellSize1
Cell size 1 [pointing: azimuthal angle, phi, rectangular: perpendicular to size 0 and thickness, units mm].
const float m_cellThickness
Thickness of cell, units mm.
const float m_nCellRadiationLengths
Absorber material in front of cell, units radiation lengths.
const float m_nCellInteractionLengths
Absorber material in front of cell, units interaction lengths.
const float m_time
Time of (earliest) energy deposition in this cell, units ns.
const float m_inputEnergy
Corrected energy of calorimeter cell in user framework, units GeV.
const float m_mipEquivalentEnergy
The calibrated mip equivalent energy, units mip.
const float m_electromagneticEnergy
The calibrated electromagnetic energy measure, units GeV.
const float m_hadronicEnergy
The calibrated hadronic energy measure, units GeV.
const bool m_isDigital
Whether cell should be treated as digital (implies constant cell energy)
const HitType m_hitType
The type of calorimeter hit.
const HitRegion m_hitRegion
Region of the detector in which the calo hit is located.
const unsigned int m_layer
The subdetector readout layer number.
InputUInt m_pseudoLayer
The pseudo layer to which the calo hit has been assigned.
const bool m_isInOuterSamplingLayer
Whether cell is in one of the outermost detector sampling layers.
float m_cellLengthScale
Typical length scale [pointing: measured at cell mid-point, rectangular: std::sqrt(cellSize0 * cellSize1), units mm ].
bool m_isPossibleMip
Whether the calo hit is a possible mip hit.
bool m_isIsolated
Whether the calo hit is isolated.
bool m_isAvailable
Whether the calo hit is available to be added to a cluster.
float m_weight
The calo hit weight, which may not be unity if the hit has been fragmented.
MCParticleWeightMap m_mcParticleWeightMap
The mc particle weight map.
const void * m_pParentAddress
The address of the parent calo hit in the user framework.
Friends
class CaloHitMetadata
class CaloHitManager
class InputObjectManager< CaloHit >
class PandoraObjectFactory< PandoraApi::CaloHit::Parameters, CaloHit >
class PandoraObjectFactory< PandoraContentApi::CaloHitFragment::Parameters, CaloHit >
Detailed Description
CaloHit class.
Constructor & Destructor Documentation
pandora::CaloHit::CaloHit (const PandoraApi::CaloHit::Parameters & parameters) protected
Constructor.
Parameters
parameters the calo hit parameters
References CalculateCellLengthScale(), and m_cellLengthScale.
pandora::CaloHit::CaloHit (const PandoraContentApi::CaloHitFragment::Parameters & parameters) protected
Weighted copy constructor.
Parameters
parameters the calo hit fragmentation parameters
Member Function Documentation
StatusCode pandora::CaloHit::AlterMetadata (const PandoraContentApi::CaloHit::Metadata & metadata) protected
Alter the metadata information stored in a calo hit.
Parameters
metaData the metadata (only populated metadata fields will be propagated to the object)
References m_isIsolated, and m_isPossibleMip.
float pandora::CaloHit::CalculateCellLengthScale () const protected
Calculate the typical length scale of the cell, units mm.
Returns
the typical length scale of cell
References GetCellGeometry(), GetCellSize0(), GetCellSize1(), GetPositionVector(), and pandora::CartesianVector::GetSphericalCoordinates().
Referenced by CaloHit().
void pandora::CaloHit::GetCellCorners (CartesianPointList & cartesianPointList) const
Get the list of cartesian coordinates for the cell corners.
Parameters
cartesianPointList to receive the cartesian coordinates of the cell corners
References GetCellGeometry(), GetPointingCellCorners(), and GetRectangularCellCorners().
CellGeometry pandora::CaloHit::GetCellGeometry () const inline
Get the cell geometry.
Returns
the cell geometry
Referenced by CalculateCellLengthScale(), and GetCellCorners().
float pandora::CaloHit::GetCellLengthScale () const inline
Get the typical length scale of cell, units mm.
Returns
the typical length scale of cell
const CartesianVector & pandora::CaloHit::GetCellNormalVector () const inline
Get the unit vector normal to the sampling layer, pointing outwards from the origin.
Returns
the normal vector
Referenced by GetRectangularCellCorners().
float pandora::CaloHit::GetCellSize0 () const inline
Get the cell size 0 [pointing: eta, rectangular: up in ENDCAP, along beam in BARREL, units mm].
Returns
the cell size 0
Referenced by CalculateCellLengthScale(), GetPointingCellCorners(), and GetRectangularCellCorners().
float pandora::CaloHit::GetCellSize1 () const inline
Get the cell size 1 [pointing: phi, rectangular: perpendicular to size 0 and thickness, units mm].
Returns
the cell size 1
Referenced by CalculateCellLengthScale(), GetPointingCellCorners(), and GetRectangularCellCorners().
float pandora::CaloHit::GetCellThickness () const inline
Get the thickness of cell, units mm.
Returns
the thickness of cell
Referenced by GetPointingCellCorners(), and GetRectangularCellCorners().
float pandora::CaloHit::GetElectromagneticEnergy () const inline
Get the calibrated electromagnetic energy measure.
Returns
the calibrated electromagnetic energy
Referenced by pandora::Cluster::AddCaloHit(), pandora::Cluster::AddIsolatedCaloHit(), pandora::Cluster::RemoveCaloHit(), and pandora::Cluster::RemoveIsolatedCaloHit().
const CartesianVector & pandora::CaloHit::GetExpectedDirection () const inline
Get the unit vector in direction of expected hit propagation.
Returns
the expected direction
float pandora::CaloHit::GetHadronicEnergy () const inline
Get the calibrated hadronic energy measure.
Returns
the calibrated hadronic energy
Referenced by pandora::Cluster::AddCaloHit(), pandora::Cluster::AddIsolatedCaloHit(), pandora::Cluster::RemoveCaloHit(), and pandora::Cluster::RemoveIsolatedCaloHit().
HitRegion pandora::CaloHit::GetHitRegion () const inline
Get the region of the detector in which the calo hit is located.
Returns
the detector region
Referenced by GetPointingCellCorners(), and GetRectangularCellCorners().
HitType pandora::CaloHit::GetHitType () const inline
Get the calorimeter hit type.
Returns
the calorimeter hit type
float pandora::CaloHit::GetInputEnergy () const inline
Get the corrected energy of the calorimeter cell, units GeV, as supplied by the user.
Returns
the corrected energy of the calorimeter cell
unsigned int pandora::CaloHit::GetLayer () const inline
Get the subdetector readout layer number.
Returns
the subdetector readout layer number
const MCParticleWeightMap & pandora::CaloHit::GetMCParticleWeightMap () const inline
Get mc particle weight map for the calo hit.
Returns
the mc particle weight map
float pandora::CaloHit::GetMipEquivalentEnergy () const inline
Get the calibrated mip equivalent energy.
Returns
the calibrated mip equivalent energy
float pandora::CaloHit::GetNCellInteractionLengths () const inline
Get the absorber material in front of cell, units interaction lengths.
Returns
the absorber material in front of cell in interaction lengths
float pandora::CaloHit::GetNCellRadiationLengths () const inline
Get the absorber material in front of cell, units radiation lengths.
Returns
the absorber material in front of cell in radiation lengths
void pandora::CaloHit::GetPointingCellCorners (CartesianPointList & cartesianPointList) const protected
Get the list of cartesian coordinates for pointing cell corners.
Parameters
cartesianPointList to receive the cartesian coordinates of the cell corners
References GetCellSize0(), GetCellSize1(), GetCellThickness(), GetHitRegion(), GetPositionVector(), and pandora::CartesianVector::GetSphericalCoordinates().
Referenced by GetCellCorners().
const CartesianVector & pandora::CaloHit::GetPositionVector () const inline
Get the position vector of center of calorimeter cell, units mm.
Returns
the position vector
Referenced by pandora::Cluster::AddCaloHit(), CalculateCellLengthScale(), GetPointingCellCorners(), GetRectangularCellCorners(), and pandora::Cluster::RemoveCaloHit().
unsigned int pandora::CaloHit::GetPseudoLayer () const inline
Get pseudo layer for the calo hit.
Returns
the pseudo layer
Referenced by pandora::OrderedCaloHitList::Add(), pandora::Cluster::AddCaloHit(), pandora::OrderedCaloHitList::Remove(), and pandora::Cluster::RemoveCaloHit().
void pandora::CaloHit::GetRectangularCellCorners (CartesianPointList & cartesianPointList) const protected
Get the list of cartesian coordinates for rectangular cell corners.
Parameters
cartesianPointList to receive the cartesian coordinates of the cell corners
References GetCellNormalVector(), GetCellSize0(), GetCellSize1(), GetCellThickness(), pandora::CartesianVector::GetCrossProduct(), GetHitRegion(), and GetPositionVector().
Referenced by GetCellCorners().
float pandora::CaloHit::GetTime () const inline
Get the time of (earliest) energy deposition in this cell, units ns.
Returns
the time of (earliest) energy deposition in this cell
float pandora::CaloHit::GetWeight () const inline
Get the calo hit weight, which may not be unity if the hit has been fragmented.
Returns
the calo hit weight
bool pandora::CaloHit::IsAvailable () const inline protected
Whether the calo hit is available to be added to a cluster (access this function via PandoraContentAPI)
Returns
boolean
bool pandora::CaloHit::IsDigital () const inline
Whether cell should be treated as digital.
Returns
boolean
bool pandora::CaloHit::IsInOuterSamplingLayer () const inline
Whether cell is in one of the outermost detector sampling layers.
Returns
boolean
Referenced by pandora::Cluster::AddCaloHit(), and pandora::Cluster::RemoveCaloHit().
bool pandora::CaloHit::IsIsolated () const inline
Whether the calo hit is flagged as isolated.
Returns
boolean
bool pandora::CaloHit::IsPossibleMip () const inline
Whether the calo hit is flagged as a possible mip hit.
Returns
boolean
Referenced by pandora::Cluster::AddCaloHit(), and pandora::Cluster::RemoveCaloHit().
void pandora::CaloHit::SetAvailability (bool isAvailable) inline protected
Set availability of calo hit to be added to a cluster.
Parameters
isAvailable the calo hit availability
void pandora::CaloHit::SetMCParticleWeightMap (const MCParticleWeightMap & mcParticleWeightMap) protected
Set the mc particles associated with the calo hit.
Parameters
mcParticleWeightMap the mc particle weight map
References m_mcParticleWeightMap.
StatusCode pandora::CaloHit::SetPseudoLayer (const unsigned int pseudoLayer) protected
Set the mc pseudo layer for the calo hit.
Parameters
pseudoLayer the pseudo layer
References m_pseudoLayer.
The documentation for this class was generated from the following files:
CaloHit.h
CaloHit.cc