ArborContent: arbor_content::Connector Class Reference
arbor_content::Connector Class Reference
Connector class.
#include <Connector.h>
Public Member Functions
const arbor_content::CaloHit * GetFrom () const
Get the 'from' calo hit.
const arbor_content::CaloHit * GetTo () const
Get the 'to' calo hit.
const arbor_content::CaloHit * Get (ConnectorDirection direction) const
Get the 'to' or 'from' calo hit (from (to) for BACKWARD_DIRECTION (FORWARD_DIRECTION))
float GetLength () const
Get the connector length.
float GetReferenceLength () const
Get the reference length.
float GetNormalizedLength () const
Get the normalized length.
pandora::CartesianVector GetVector (ConnectorDirection direction=FORWARD_DIRECTION) const
Get the connector vector depending on the asked direction.
bool IsFrom (const arbor_content::CaloHit *const pCaloHit) const
Whether the calo hit is the 'from' calo hit of this connector.
bool IsTo (const arbor_content::CaloHit *const pCaloHit) const
Whether the calo hit is the 'to' calo hit of this connector.
float GetOpeningAngle (const Connector *const pConnector) const
Get the opening angle with an other connector (radian)
Private Member Functions
Connector (const arbor_content::CaloHit *const pFromCaloHit, const arbor_content::CaloHit *const pToCaloHit, float referenceLength=1.f)
Constructor with two calo hits and a reference length.
~Connector ()
Destructor.
Private Attributes
const CaloHit * m_pFromCaloHit
The 'from' calo hit of this connector.
const CaloHit * m_pToCaloHit
The 'to' calo hit of this connector.
float m_referenceLength
The reference length on connector creation.
Friends
class CaloHit
class ::ArborContentApi
Detailed Description
Connector class.
Definition at line 43 of file Connector.h.
Constructor & Destructor Documentation
arbor_content::Connector::Connector (const arbor_content::CaloHit *const pFromCaloHit, const arbor_content::CaloHit *const pToCaloHit, float referenceLength = 1.f) private
Constructor with two calo hits and a reference length.
Definition at line 34 of file Connector.cc.
                                                                                                                                           :
       m_pFromCaloHit(pFromCaloHit),
       m_pToCaloHit(pToCaloHit),
       m_referenceLength(referenceLength)
   {
     /* nop */
   }
arbor_content::Connector::~Connector () private
Destructor.
Definition at line 44 of file Connector.cc.
References m_pFromCaloHit, and m_pToCaloHit.
   {
     m_pFromCaloHit = NULL;
     m_pToCaloHit = NULL;
   }
Member Function Documentation
const arbor_content::CaloHit * arbor_content::Connector::Get (ConnectorDirection direction) const
Get the 'to' or 'from' calo hit (from (to) for BACKWARD_DIRECTION (FORWARD_DIRECTION))
Definition at line 66 of file Connector.cc.
References arbor_content::BACKWARD_DIRECTION, GetFrom(), and GetTo().
Referenced by arbor_content::CaloHitHelper::BuildCaloHitList(), and arbor_content::CaloHitHelper::GetMeanDirection().
   {
     return direction == BACKWARD_DIRECTION ? this->GetFrom() : this->GetTo();
   }
const CaloHit * arbor_content::Connector::GetFrom () const
Get the 'from' calo hit.
Definition at line 52 of file Connector.cc.
References m_pFromCaloHit.
Referenced by arbor_content::ConnectorCleaningTool::CleanCaloHits(), arbor_content::ConnectorAlignmentTool::ConnectBackward(), Get(), GetLength(), GetOpeningAngle(), GetVector(), arbor_content::CaloHitMetaData::IsConnected(), IsFrom(), arbor_content::ConnectorAlignmentTool::Process(), arbor_content::CaloHitMetaData::RemoveConnector(), and ArborContentApi::RemoveConnector().
   {
     return m_pFromCaloHit;
   }
float arbor_content::Connector::GetLength () const
Get the connector length.
Definition at line 73 of file Connector.cc.
References GetFrom(), and GetTo().
Referenced by GetNormalizedLength().
   {
     return (this->GetFrom()->GetPositionVector() - this->GetTo()->GetPositionVector()).GetMagnitude();
   }
float arbor_content::Connector::GetNormalizedLength () const
Get the normalized length.
Definition at line 87 of file Connector.cc.
References GetLength(), and m_referenceLength.
Referenced by arbor_content::ConnectorCleaningTool::GetOrderParameter().
   {
     return (this->GetLength() / m_referenceLength);
   }
float arbor_content::Connector::GetOpeningAngle (const Connector *const pConnector) const
Get the opening angle with an other connector (radian)
Definition at line 116 of file Connector.cc.
References GetFrom(), and GetTo().
   {
     const pandora::CartesianVector direction(GetTo()->GetPositionVector() - GetFrom()->GetPositionVector());
     const pandora::CartesianVector otherDirection(pConnector->GetTo()->GetPositionVector() - pConnector->GetTo()->GetPositionVector());
     return direction.GetOpeningAngle(otherDirection);
   }
float arbor_content::Connector::GetReferenceLength () const
Get the reference length.
Definition at line 80 of file Connector.cc.
References m_referenceLength.
   {
     return m_referenceLength;
   }
const CaloHit * arbor_content::Connector::GetTo () const
Get the 'to' calo hit.
Definition at line 59 of file Connector.cc.
References m_pToCaloHit.
Referenced by arbor_content::ConnectorAlignmentTool::ConnectForward(), Get(), GetLength(), GetOpeningAngle(), GetVector(), arbor_content::CaloHitMetaData::IsConnected(), IsTo(), arbor_content::ConnectorAlignmentTool::Process(), arbor_content::CaloHitMetaData::RemoveConnector(), and ArborContentApi::RemoveConnector().
   {
     return m_pToCaloHit;
   }
pandora::CartesianVector arbor_content::Connector::GetVector (ConnectorDirection direction = FORWARD_DIRECTION) const
Get the connector vector depending on the asked direction.
Definition at line 94 of file Connector.cc.
References arbor_content::FORWARD_DIRECTION, GetFrom(), and GetTo().
Referenced by arbor_content::ConnectorAlignmentTool::ConnectBackward(), arbor_content::ConnectorAlignmentTool::ConnectForward(), and arbor_content::ConnectorCleaningTool::GetOrderParameter().
   {
     pandora::CartesianVector vector = GetTo()->GetPositionVector() - GetFrom()->GetPositionVector();
     return direction == FORWARD_DIRECTION ? vector : vector * -1.f;
   }
bool arbor_content::Connector::IsFrom (const arbor_content::CaloHit *const pCaloHit) const
Whether the calo hit is the 'from' calo hit of this connector.
Definition at line 102 of file Connector.cc.
References GetFrom().
   {
     return (pCaloHit == this->GetFrom());
   }
bool arbor_content::Connector::IsTo (const arbor_content::CaloHit *const pCaloHit) const
Whether the calo hit is the 'to' calo hit of this connector.
Definition at line 109 of file Connector.cc.
References GetTo().
   {
     return (pCaloHit == this->GetTo());
   }
Friends And Related Function Documentation
friend class ::ArborContentApi friend
Definition at line 115 of file Connector.h.
friend class CaloHit friend
Definition at line 114 of file Connector.h.
Member Data Documentation
const CaloHit* arbor_content::Connector::m_pFromCaloHit private
The 'from' calo hit of this connector.
Definition at line 109 of file Connector.h.
Referenced by GetFrom(), and ~Connector().
const CaloHit* arbor_content::Connector::m_pToCaloHit private
The 'to' calo hit of this connector.
Definition at line 110 of file Connector.h.
Referenced by GetTo(), and ~Connector().
float arbor_content::Connector::m_referenceLength private
The reference length on connector creation.
Definition at line 111 of file Connector.h.
Referenced by GetNormalizedLength(), and GetReferenceLength().
The documentation for this class was generated from the following files:
Connector.h
Connector.cc