ArborContent: arbor_content::NearbyTrackPhotonRemovalAlg Class Reference
arbor_content::NearbyTrackPhotonRemovalAlg Class Reference
NearbyTrackPhotonRemovalAlg class.
#include <NearbyTrackPhotonRemovalAlg.h>
Classes
class Factory
Factory class for instantiating algorithm.
Private Member Functions
pandora::StatusCode Run ()
pandora::StatusCode ReadSettings (const pandora::TiXmlHandle xmlHandle)
pandora::StatusCode GetContents (pandora::ClusterVector &clusterVector, pandora::TrackVector &trackVector) const
Get the contents for the algorithm.
pandora::StatusCode RemoveNearbyPhotonHits (const pandora::ClusterVector &clusterVector, const pandora::TrackVector &trackVector, pandora::ClusterVector &photonFragmentVector) const
Remove photon hits nearby tracks and get all photon fragments with too less hits.
pandora::StatusCode RemovePhotonFragments (const pandora::ClusterVector &photonFragmentVector) const
Delete the provided list of photon fragments.
Private Attributes
std::string m_photonClusterListName
float m_maxTrackHitDistance
float m_maxOmegaTrack
float m_minRemainingPhotonEnergy
unsigned int m_minRemainingPhotonNHits
Detailed Description
NearbyTrackPhotonRemovalAlg class.
Definition at line 41 of file NearbyTrackPhotonRemovalAlg.h.
Member Function Documentation
pandora::StatusCode arbor_content::NearbyTrackPhotonRemovalAlg::GetContents (pandora::ClusterVector & clusterVector, pandora::TrackVector & trackVector) const private
Get the contents for the algorithm.
Parameters
clusterVector the cluster vector to receive
trackVector the track vector to receive
Definition at line 59 of file NearbyTrackPhotonRemovalAlg.cc.
References m_maxOmegaTrack, and m_photonClusterListName.
Referenced by Run().
   {
     // Get photon cluster list
     const pandora::ClusterList *pClusterList = NULL;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetList(*this, m_photonClusterListName, pClusterList));
     clusterVector.insert(clusterVector.end(), pClusterList->begin(), pClusterList->end());
     // Get the track list to be used as veto
     const pandora::TrackList *pTrackList = NULL;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentList(*this, pTrackList));
     const float bField(PandoraContentApi::GetPlugins(*this)->GetBFieldPlugin()->GetBField(pandora::CartesianVector(0.f, 0.f, 0.f)));
     for(pandora::TrackList::const_iterator trackIter = pTrackList->begin(), trackEndIter = pTrackList->end() ;
         trackEndIter != trackIter ; ++trackIter)
     {
       const pandora::Track *const pTrack(*trackIter);
       if(!pTrack->CanFormPfo())
         continue;
       if(!pTrack->ReachesCalorimeter())
         continue;
       if(!pTrack->GetDaughterTrackList().empty())
         continue;
       const pandora::Helix helix(pTrack->GetTrackStateAtCalorimeter().GetPosition(),
           pTrack->GetTrackStateAtCalorimeter().GetMomentum(), pTrack->GetCharge(), bField);
       if(fabs(helix.GetOmega()) > m_maxOmegaTrack)
         continue;
       trackVector.push_back(pTrack);
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::NearbyTrackPhotonRemovalAlg::ReadSettings (const pandora::TiXmlHandle xmlHandle) private
Definition at line 194 of file NearbyTrackPhotonRemovalAlg.cc.
References m_maxOmegaTrack, m_maxTrackHitDistance, m_minRemainingPhotonEnergy, m_minRemainingPhotonNHits, and m_photonClusterListName.
   {
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "PhotonClusterListName", m_photonClusterListName));
     m_maxTrackHitDistance = 8.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxTrackHitDistance", m_maxTrackHitDistance));
     m_maxOmegaTrack = 0.002;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxOmegaTrack", m_maxOmegaTrack));
     m_minRemainingPhotonEnergy = 0.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinRemainingPhotonEnergy", m_minRemainingPhotonEnergy));
     m_minRemainingPhotonNHits = 5;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MinRemainingPhotonNHits", m_minRemainingPhotonNHits));
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::NearbyTrackPhotonRemovalAlg::RemoveNearbyPhotonHits (const pandora::ClusterVector & clusterVector, const pandora::TrackVector & trackVector, pandora::ClusterVector & photonFragmentVector) const private
Remove photon hits nearby tracks and get all photon fragments with too less hits.
Parameters
clusterVector the input photon cluster vector
trackVector the input track vector
photonFragmentVector the list of photon fragments to receive
Definition at line 101 of file NearbyTrackPhotonRemovalAlg.cc.
References ARBOR_LOG, arbor_content::GeometryHelper::GetProjectionOnHelix(), m_maxTrackHitDistance, m_minRemainingPhotonEnergy, m_minRemainingPhotonNHits, and ArborContentApi::RemoveAndDeleteAllConnections().
Referenced by Run().
   {
     const float bField(PandoraContentApi::GetPlugins(*this)->GetBFieldPlugin()->GetBField(pandora::CartesianVector(0.f, 0.f, 0.f)));
     unsigned int totalRemovedNHits(0); // just for logging
     for(pandora::ClusterVector::const_iterator clusterIter = clusterVector.begin(), clusterEndIter = clusterVector.end() ; clusterEndIter != clusterIter ; ++clusterIter)
     {
       const pandora::Cluster *const pCluster(*clusterIter);
       pandora::CaloHitList clusterCaloHits;
       pCluster->GetOrderedCaloHitList().GetCaloHitList(clusterCaloHits);
       pandora::CaloHitList caloHitListRemoval;
       for(pandora::TrackVector::const_iterator trackIter = trackVector.begin(), trackEndIter = trackVector.end() ;
           trackEndIter != trackIter ; ++trackIter)
       {
         const pandora::Track *const pTrack(*trackIter);
         const pandora::CartesianVector &trackProjection(pTrack->GetTrackStateAtCalorimeter().GetPosition());
         const pandora::Helix helix(pTrack->GetTrackStateAtCalorimeter().GetPosition(),
             pTrack->GetTrackStateAtCalorimeter().GetMomentum(), pTrack->GetCharge(), bField);
         for(pandora::CaloHitList::const_iterator iter = clusterCaloHits.begin(), endIter = clusterCaloHits.end() ;
             endIter != iter ; ++iter)
         {
           const pandora::CaloHit *const pCaloHit(*iter);
           const float trackHitAngle(pCaloHit->GetPositionVector().GetOpeningAngle(trackProjection));
           // cut needed for discriminate track opposite direction
           if(trackHitAngle > M_PI/2.f)
             continue;
           pandora::CartesianVector projectionOnHelix(0.f, 0.f, 0.f);
           if(pandora::STATUS_CODE_SUCCESS != GeometryHelper::GetProjectionOnHelix(helix, pCaloHit->GetPositionVector(), projectionOnHelix))
             continue;
           const float distanceToHelix((projectionOnHelix-pCaloHit->GetPositionVector()).GetMagnitude());
           if(distanceToHelix > m_maxTrackHitDistance)
             continue;
           caloHitListRemoval.insert(pCaloHit);
           ++totalRemovedNHits;
         }
       }
       for(pandora::CaloHitList::const_iterator iter = caloHitListRemoval.begin(), endIter = caloHitListRemoval.end() ;
           endIter != iter ; ++iter)
       {
         const arbor_content::CaloHit *const pCaloHit(dynamic_cast<const arbor_content::CaloHit *const>(*iter));
         if(NULL != pCaloHit)
         {
           PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::RemoveAndDeleteAllConnections(pCaloHit));
         }
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::RemoveFromCluster(*this, pCluster, *iter));
       }
       const unsigned int nRemainingCaloHits(pCluster->GetNCaloHits());
       const float remainingEnergy(pCluster->GetElectromagneticEnergy());
       if(nRemainingCaloHits < m_minRemainingPhotonNHits || remainingEnergy < m_minRemainingPhotonEnergy)
       {
         photonFragmentVector.push_back(pCluster);
       }
     }
     ARBOR_LOG( "NearbyTrackPhotonRemovalAlg: Will remove " << photonFragmentVector.size() << " photons" << std::endl);
     ARBOR_LOG( "NearbyTrackPhotonRemovalAlg: Removed " << totalRemovedNHits << " hits from photon clusters" << std::endl);
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::NearbyTrackPhotonRemovalAlg::RemovePhotonFragments (const pandora::ClusterVector & photonFragmentVector) const private
Delete the provided list of photon fragments.
Parameters
photonFragmentVector the list of photon fragments to remove
Definition at line 181 of file NearbyTrackPhotonRemovalAlg.cc.
References m_photonClusterListName.
Referenced by Run().
   {
     for(pandora::ClusterVector::const_iterator iter = photonFragmentVector.begin(), endIter = photonFragmentVector.end() ; endIter != iter ; ++iter)
     {
       const pandora::Cluster *const pCluster(*iter);
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::Delete(*this, pCluster, m_photonClusterListName));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::NearbyTrackPhotonRemovalAlg::Run () private
Definition at line 41 of file NearbyTrackPhotonRemovalAlg.cc.
References GetContents(), RemoveNearbyPhotonHits(), and RemovePhotonFragments().
   {
     // get algorithm contents
     pandora::ClusterVector clusterVector; pandora::TrackVector trackVector;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->GetContents(clusterVector, trackVector));
     if(clusterVector.empty() || trackVector.empty())
       return pandora::STATUS_CODE_SUCCESS;
     pandora::ClusterVector photonFragmentVector;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->RemoveNearbyPhotonHits(clusterVector, trackVector, photonFragmentVector));
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->RemovePhotonFragments(photonFragmentVector));
     return pandora::STATUS_CODE_SUCCESS;
   }
Member Data Documentation
float arbor_content::NearbyTrackPhotonRemovalAlg::m_maxOmegaTrack private
Definition at line 85 of file NearbyTrackPhotonRemovalAlg.h.
Referenced by GetContents(), and ReadSettings().
float arbor_content::NearbyTrackPhotonRemovalAlg::m_maxTrackHitDistance private
Definition at line 84 of file NearbyTrackPhotonRemovalAlg.h.
Referenced by ReadSettings(), and RemoveNearbyPhotonHits().
float arbor_content::NearbyTrackPhotonRemovalAlg::m_minRemainingPhotonEnergy private
Definition at line 86 of file NearbyTrackPhotonRemovalAlg.h.
Referenced by ReadSettings(), and RemoveNearbyPhotonHits().
unsigned int arbor_content::NearbyTrackPhotonRemovalAlg::m_minRemainingPhotonNHits private
Definition at line 87 of file NearbyTrackPhotonRemovalAlg.h.
Referenced by ReadSettings(), and RemoveNearbyPhotonHits().
std::string arbor_content::NearbyTrackPhotonRemovalAlg::m_photonClusterListName private
Definition at line 83 of file NearbyTrackPhotonRemovalAlg.h.
Referenced by GetContents(), ReadSettings(), and RemovePhotonFragments().
The documentation for this class was generated from the following files:
NearbyTrackPhotonRemovalAlg.h
NearbyTrackPhotonRemovalAlg.cc