ArborContent: arbor_content::CaloHitMergingTool Class Reference
arbor_content::CaloHitMergingTool Class Reference
CaloHitMergingTool class.
#include <CaloHitMergingTool.h>
Classes
class Factory
Factory class for instantiating algorithm tool.
Public Member Functions
virtual pandora::StatusCode ReadSettings (const pandora::TiXmlHandle xmlHandle)
Read settings from the xml handle.
virtual pandora::StatusCode MergeCaloHits (const pandora::Algorithm &algorithm, const pandora::CaloHitList &caloHitList, const pandora::ClusterVector &clusterVector)
Merge the calo hit list in provided cluster list.
Private Types
typedef std::map< int, float > PidToDistanceMap
The pid flag to max merging distance map typedef.
Private Member Functions
pandora::StatusCode FindCaloHitClusterMerging (const pandora::Algorithm &algorithm, const pandora::CaloHitList &caloHitList, const pandora::ClusterVector &clusterVector, CaloHitToClusterMap &caloHitToClusterMap) const
Find a possible parent cluster for each hit.
pandora::StatusCode MergeCaloHits (const pandora::Algorithm &algorithm, const CaloHitToClusterMap &caloHitToClusterMap) const
Merge the calo hits in their target cluster.
float GetMaxCaloHitDistance (const pandora::Algorithm &algorithm, const pandora::CaloHit *const pCaloHit, const pandora::Cluster *const pCluster) const
Get the maximum distance to merge the calo hit into that cluster.
Private Attributes
float m_maxCaloHitDistanceFine
The max distance to merge a hit in a cluster (fine granularity)
float m_maxCaloHitDistanceCoarse
The max distance to merge a hit in a cluster (coarse granularity)
PidToDistanceMap m_maxCaloHitDistanceFineMap
The map of cluster pid -> max distance to merge a hit in a cluster (fine granularity)
PidToDistanceMap m_maxCaloHitDistanceCoarseMap
The map of cluster pid -> max distance to merge a hit in a cluster (coarse granularity)
Detailed Description
CaloHitMergingTool class.
Definition at line 42 of file CaloHitMergingTool.h.
Member Typedef Documentation
typedef std::map<int, float> arbor_content::CaloHitMergingTool::PidToDistanceMap private
The pid flag to max merging distance map typedef.
Definition at line 101 of file CaloHitMergingTool.h.
Member Function Documentation
pandora::StatusCode arbor_content::CaloHitMergingTool::FindCaloHitClusterMerging (const pandora::Algorithm & algorithm, const pandora::CaloHitList & caloHitList, const pandora::ClusterVector & clusterVector, CaloHitToClusterMap & caloHitToClusterMap) const private
Find a possible parent cluster for each hit.
Parameters
algorithm the algorithm calling this function
caloHitList the input calo hit list
clusterVector the input cluster list
caloHitToClusterMap the map of calo hit to cluster to merge
Definition at line 54 of file CaloHitMergingTool.cc.
References arbor_content::ClusterHelper::GetClosestDistanceApproach(), and GetMaxCaloHitDistance().
Referenced by MergeCaloHits().
   {
     for(pandora::CaloHitList::const_iterator hitIter = caloHitList.begin(), hitEndIter = caloHitList.end() ;
         hitEndIter != hitIter ; ++hitIter)
     {
       const pandora::CaloHit *const pCaloHit(*hitIter);
       float bestDistanceToHit(std::numeric_limits<float>::max());
       const pandora::Cluster *pBestCluster = NULL;
       for(pandora::ClusterVector::const_iterator clusterIter = clusterVector.begin(), clusterEndIter = clusterVector.end() ;
           clusterEndIter != clusterIter ; ++clusterIter)
       {
         const pandora::Cluster *const pCluster(*clusterIter);
         // Get calo hit closest distance approach
         float caloHitDistance(std::numeric_limits<float>::max());
         if(pandora::STATUS_CODE_SUCCESS != ClusterHelper::GetClosestDistanceApproach(pCluster, pCaloHit->GetPositionVector(), caloHitDistance))
           continue;
         const float maxCaloHitDistance(this->GetMaxCaloHitDistance(algorithm, pCaloHit, pCluster));
         if(caloHitDistance < maxCaloHitDistance && caloHitDistance < bestDistanceToHit)
         {
           bestDistanceToHit = caloHitDistance;
           pBestCluster = pCluster;
         }
       }
       if(NULL != pBestCluster)
         caloHitToClusterMap[pCaloHit] = pBestCluster;
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
float arbor_content::CaloHitMergingTool::GetMaxCaloHitDistance (const pandora::Algorithm & algorithm, const pandora::CaloHit *const pCaloHit, const pandora::Cluster *const pCluster) const private
Get the maximum distance to merge the calo hit into that cluster.
Parameters
algorithm the algorithm calling this function
pCaloHit the calo hit to merge
pCluster the potential cluster to merge the calo hit in
Returns
float the maximum distance to merge the calo hit into that cluster
Definition at line 109 of file CaloHitMergingTool.cc.
References m_maxCaloHitDistanceCoarse, m_maxCaloHitDistanceCoarseMap, m_maxCaloHitDistanceFine, and m_maxCaloHitDistanceFineMap.
Referenced by FindCaloHitClusterMerging().
   {
     const pandora::Granularity &granularity(PandoraContentApi::GetGeometry(algorithm)->GetHitTypeGranularity(pCaloHit->GetHitType()));
     const int pidFlag(pCluster->IsPhotonFast(algorithm.GetPandora()) ? pandora::PHOTON : pCluster->GetParticleIdFlag());
     // default distance for all clusters
     float maxCaloHitDistance((granularity <= pandora::FINE) ? m_maxCaloHitDistanceFine : m_maxCaloHitDistanceCoarse);
     // then proceed by particle flag
     if(pidFlag != 0)
     {
       if(granularity <= pandora::FINE)
       {
         PidToDistanceMap::const_iterator findIter = m_maxCaloHitDistanceFineMap.find(pidFlag);
         if(m_maxCaloHitDistanceFineMap.end() != findIter)
           maxCaloHitDistance = findIter->second;
       }
       else
       {
         PidToDistanceMap::const_iterator findIter = m_maxCaloHitDistanceCoarseMap.find(pidFlag);
         if(m_maxCaloHitDistanceCoarseMap.end() != findIter)
           maxCaloHitDistance = findIter->second;
       }
     }
     return maxCaloHitDistance;
   }
pandora::StatusCode arbor_content::CaloHitMergingTool::MergeCaloHits (const pandora::Algorithm & algorithm, const pandora::CaloHitList & caloHitList, const pandora::ClusterVector & clusterVector) virtual
Merge the calo hit list in provided cluster list.
Parameters
algorithm the algorithm calling this function
caloHitList the calo hits to merge
clusterVector the cluster list to enlarge with calo hits
Definition at line 43 of file CaloHitMergingTool.cc.
References FindCaloHitClusterMerging().
Referenced by arbor_content::FragmentRemovalAlgorithm::Run(), and arbor_content::SurroundingHitsMergingAlgorithm::Run().
   {
     CaloHitToClusterMap caloHitToClusterMap;
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->FindCaloHitClusterMerging(algorithm, caloHitList, clusterVector, caloHitToClusterMap));
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->MergeCaloHits(algorithm, caloHitToClusterMap));
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::CaloHitMergingTool::MergeCaloHits (const pandora::Algorithm & algorithm, const CaloHitToClusterMap & caloHitToClusterMap) const private
Merge the calo hits in their target cluster.
Parameters
algorithm the algorithm calling this function
caloHitToClusterMap the calo hit to cluster map to perform the merging
Definition at line 93 of file CaloHitMergingTool.cc.
   {
     for(CaloHitToClusterMap::const_iterator iter = caloHitToClusterMap.begin(), endIter = caloHitToClusterMap.end() ;
         endIter != iter ; ++iter)
     {
       const pandora::CaloHit *const pCaloHit(iter->first);
       const pandora::Cluster *const pCluster(iter->second);
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::AddToCluster(algorithm, pCluster, pCaloHit));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::CaloHitMergingTool::ReadSettings (const pandora::TiXmlHandle xmlHandle) virtual
Read settings from the xml handle.
Parameters
xmlHandle the xml handle to settings
Definition at line 141 of file CaloHitMergingTool.cc.
References m_maxCaloHitDistanceCoarse, m_maxCaloHitDistanceCoarseMap, m_maxCaloHitDistanceFine, and m_maxCaloHitDistanceFineMap.
   {
     m_maxCaloHitDistanceFine = 200.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxCaloHitDistanceFine", m_maxCaloHitDistanceFine));
     m_maxCaloHitDistanceCoarse = 500.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "MaxCaloHitDistanceCoarse", m_maxCaloHitDistanceCoarse));
     pandora::StringVector stringVector;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadVectorOfValues(xmlHandle,
         "MaxPidCaloHitDistanceFine", stringVector));
     for(pandora::StringVector::const_iterator iter = stringVector.begin(), endIter = stringVector.end() ; endIter != iter ; ++iter)
     {
       pandora::StringVector pidDistanceSeparated;
       const std::string delimiter = ":";
       pandora::XmlHelper::TokenizeString(*iter, pidDistanceSeparated, delimiter);
       if (pidDistanceSeparated.size() != 2)
         return pandora::STATUS_CODE_INVALID_PARAMETER;
       int pid(0);
       float distance(0.f);
       if (!pandora::StringToType(pidDistanceSeparated.at(0), pid) || !pandora::StringToType(pidDistanceSeparated.at(1), distance))
         return pandora::STATUS_CODE_INVALID_PARAMETER;
       m_maxCaloHitDistanceFineMap.insert(PidToDistanceMap::value_type(pid, distance));
     }
     stringVector.clear();
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadVectorOfValues(xmlHandle,
         "MaxPidCaloHitDistanceCoarse", stringVector));
     for(pandora::StringVector::const_iterator iter = stringVector.begin(), endIter = stringVector.end() ; endIter != iter ; ++iter)
     {
       pandora::StringVector pidDistanceSeparated;
       const std::string delimiter = ":";
       pandora::XmlHelper::TokenizeString(*iter, pidDistanceSeparated, delimiter);
       if (pidDistanceSeparated.size() != 2)
         return pandora::STATUS_CODE_INVALID_PARAMETER;
       int pid(0);
       float distance(0.f);
       if (!pandora::StringToType(pidDistanceSeparated.at(0), pid) || !pandora::StringToType(pidDistanceSeparated.at(1), distance))
         return pandora::STATUS_CODE_INVALID_PARAMETER;
       m_maxCaloHitDistanceCoarseMap.insert(PidToDistanceMap::value_type(pid, distance));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
Member Data Documentation
float arbor_content::CaloHitMergingTool::m_maxCaloHitDistanceCoarse private
The max distance to merge a hit in a cluster (coarse granularity)
Definition at line 103 of file CaloHitMergingTool.h.
Referenced by GetMaxCaloHitDistance(), and ReadSettings().
PidToDistanceMap arbor_content::CaloHitMergingTool::m_maxCaloHitDistanceCoarseMap private
The map of cluster pid -> max distance to merge a hit in a cluster (coarse granularity)
Definition at line 105 of file CaloHitMergingTool.h.
Referenced by GetMaxCaloHitDistance(), and ReadSettings().
float arbor_content::CaloHitMergingTool::m_maxCaloHitDistanceFine private
The max distance to merge a hit in a cluster (fine granularity)
Definition at line 102 of file CaloHitMergingTool.h.
Referenced by GetMaxCaloHitDistance(), and ReadSettings().
PidToDistanceMap arbor_content::CaloHitMergingTool::m_maxCaloHitDistanceFineMap private
The map of cluster pid -> max distance to merge a hit in a cluster (fine granularity)
Definition at line 104 of file CaloHitMergingTool.h.
Referenced by GetMaxCaloHitDistance(), and ReadSettings().
The documentation for this class was generated from the following files:
CaloHitMergingTool.h
CaloHitMergingTool.cc