PandoraMonitoring: pandora_monitoring::PandoraMonitoring Class Reference
pandora_monitoring::PandoraMonitoring Class Reference
PandoraMonitoring singleton class.
#include <PandoraMonitoring.h>
Public Member Functions
template<typename T >
void SetTreeVariable (const std::string &treeName, const std::string &variableName, T t)
Set a variable in a tree (create the tree and the branch if not yet existing)
void FillTree (const std::string &treeName)
Fill the tree with the variables which have been set before with SetTreeVariable.
void PrintTree (const std::string &treeName)
Print the tree.
void ScanTree (const std::string &treeName)
Scan the tree (print the values of all branches)
void SaveTree (const std::string &treeName, const std::string &fileName, const std::string &fileOptions)
Save the tree to a file.
template<typename T >
void DrawPandoraHistogram (const T &t, const std::string &options)
Draw a pandora histogram.
void SetEveDisplayParameters (const bool showDetectors, const DetectorView detectorView, const float transparencyThresholdE, const float energyScaleThresholdE, const float scalingFactor)
Set TEve display parameters.
TEveElement * VisualizeMCParticles (const pandora::MCParticleList *const pMCParticleList, const std::string &name, TEveElement *parent, const Color color, const PandoraMonitoringApi::PdgCodeToEnergyMap *pParticleSuppressionMap)
Add MC particles to the Eve event-display.
TEveElement * VisualizeTracks (const pandora::TrackList *const pTrackList, const std::string &name, TEveElement *parent, const Color color)
Add Tracks to the Eve event-display.
TEveElement * VisualizeCaloHits (const pandora::CaloHitList *const pCaloHitList, const std::string &name, TEveElement *parent, const Color color)
Add CaloHits to the Eve event-display.
TEveElement * VisualizeClusters (const pandora::ClusterList *const pClusterList, const std::string &name, TEveElement *parent, const Color color, bool showAssociatedTracks)
Add Clusters to the Eve event-display.
TEveElement * VisualizeParticleFlowObjects (const pandora::PfoList *const pPfoList, const std::string &name, TEveElement *parent, const Color color, bool showVertices, bool displayPfoHierarchy)
Add Particle flow objects to the Eve event-display.
TEveElement * VisualizeVertices (const pandora::VertexList *const pVertexList, const std::string &name, TEveElement *parent, const Color color)
Add vertices to the Eve event-display.
TEveElement * AddMarkerToVisualization (const pandora::CartesianVector *const pMarkerPoint, const std::string &name, TEveElement *parent, const Color color, const unsigned int markerSize)
Add marker to visualization.
void ViewEvent ()
Show the Eve Event-display and pause.
void Pause () const
Pause thread until user enters 'return'.
template<typename VariableType >
void SetTreeVariable (const std::string &treeName, const std::string &variableName, VariableType variable)
template<>
void DrawPandoraHistogram (const pandora::Histogram &histogram, const std::string &options)
template<>
void DrawPandoraHistogram (const pandora::TwoDHistogram &twoDHistogram, const std::string &options)
Static Public Member Functions
static PandoraMonitoring * GetInstance (const pandora::Pandora &pandora)
Get the relevant pandora monitoring instance.
static void DeleteInstance (const pandora::Pandora &pandora)
Delete instance of PandoraMonitoring.
static bool SortClustersByHadronicEnergy (const pandora::Cluster *const pLhs, const pandora::Cluster *const pRhs)
Sort clusters by descending hadronic energy.
static bool SortMCParticlesByEnergy (const pandora::MCParticle *const pLhs, const pandora::MCParticle *const pRhs)
Sort MCParticles by descending energy.
static bool SortTracksByMomentum (const pandora::Track *const pLhs, const pandora::Track *const pRhs)
Sort tracks by descending momentum.
static bool SortPfosByEnergy (const pandora::ParticleFlowObject *const pLhs, const pandora::ParticleFlowObject *const pRhs)
Sort pfos by descending energy.
Detailed Description
PandoraMonitoring singleton class.
Member Function Documentation
TEveElement * pandora_monitoring::PandoraMonitoring::AddMarkerToVisualization (const pandora::CartesianVector *const pMarkerPoint, const std::string & name, TEveElement * parent, const Color color, const unsigned int markerSize)
Add marker to visualization.
Parameters
pMarkerPoint address of the marker point
name of the marker
color the marker color
showAssociatedTracks draw the tracks associated to the cluster
Referenced by PandoraMonitoringApi::AddMarkerToVisualization().
void pandora_monitoring::PandoraMonitoring::DeleteInstance (const pandora::Pandora & pandora) static
Delete instance of PandoraMonitoring.
Parameters
pandora the calling pandora instance
Referenced by PandoraMonitoringApi::Delete().
template<typename T > void pandora_monitoring::PandoraMonitoring::DrawPandoraHistogram (const T & t, const std::string & options)
Draw a pandora histogram.
Parameters
name the name associated with the histogram
options the drawing options
Referenced by PandoraMonitoringApi::DrawPandoraHistogram().
void pandora_monitoring::PandoraMonitoring::FillTree (const std::string & treeName)
Fill the tree with the variables which have been set before with SetTreeVariable.
Parameters
treeName name of the tree to be filled
Referenced by PandoraMonitoringApi::FillTree().
PandoraMonitoring * pandora_monitoring::PandoraMonitoring::GetInstance (const pandora::Pandora & pandora) static
Get the relevant pandora monitoring instance.
Parameters
pandora the calling pandora instance
Referenced by PandoraMonitoringApi::AddMarkerToVisualization(), PandoraMonitoringApi::Create(), PandoraMonitoringApi::Delete(), PandoraMonitoringApi::DrawPandoraHistogram(), PandoraMonitoringApi::FillTree(), PandoraMonitoringApi::Pause(), PandoraMonitoringApi::PrintTree(), PandoraMonitoringApi::SaveTree(), PandoraMonitoringApi::ScanTree(), PandoraMonitoringApi::SetEveDisplayParameters(), PandoraMonitoringApi::SetTreeVariable(), PandoraMonitoringApi::ViewEvent(), PandoraMonitoringApi::VisualizeCaloHits(), PandoraMonitoringApi::VisualizeClusters(), PandoraMonitoringApi::VisualizeMCParticles(), PandoraMonitoringApi::VisualizeParticleFlowObjects(), PandoraMonitoringApi::VisualizeTracks(), and PandoraMonitoringApi::VisualizeVertices().
void pandora_monitoring::PandoraMonitoring::PrintTree (const std::string & treeName)
Print the tree.
Parameters
treeName name of the tree to be printed
Referenced by PandoraMonitoringApi::PrintTree().
void pandora_monitoring::PandoraMonitoring::SaveTree (const std::string & treeName, const std::string & fileName, const std::string & fileOptions)
Save the tree to a file.
Parameters
fileName the file name under which to save the histogram
fileOptions the options associated with opening/recreating a file
treeName name of the tree to be written to a file
Referenced by PandoraMonitoringApi::SaveTree().
void pandora_monitoring::PandoraMonitoring::ScanTree (const std::string & treeName)
Scan the tree (print the values of all branches)
Parameters
treeName name of the tree to be scanned
Referenced by PandoraMonitoringApi::ScanTree().
void pandora_monitoring::PandoraMonitoring::SetEveDisplayParameters (const bool showDetectors, const DetectorView detectorView, const float transparencyThresholdE, const float energyScaleThresholdE, const float scalingFactor)
Set TEve display parameters.
Parameters
showDetectors turns the visibility of the detector geometry on or off
detectorView the detector view
transparencyThresholdE cell energy for which transparency is saturated (0%, fully opaque)
energyScaleThresholdE cell energy for which color is at top end of continous color palette
scalingFactor TEve works with [cm], Pandora works with [mm] (unless user has decided to use alternative units)
Referenced by PandoraMonitoringApi::SetEveDisplayParameters().
template<typename T > void pandora_monitoring::PandoraMonitoring::SetTreeVariable (const std::string & treeName, const std::string & variableName, T t)
Set a variable in a tree (create the tree and the branch if not yet existing)
Parameters
treeName name of the tree (is created if it does not exist yet)
variableName name of the branch in the tree (the branch is created if it does not exist yet)
t sets value of the variable (permitted types are float/double/int and std::vector<float>*,std::vector<double>*,std::vector<int>*
Referenced by PandoraMonitoringApi::SetTreeVariable().
bool pandora_monitoring::PandoraMonitoring::SortClustersByHadronicEnergy (const pandora::Cluster *const pLhs, const pandora::Cluster *const pRhs) static
Sort clusters by descending hadronic energy.
Parameters
pLhs address of first cluster
pRhs address of second cluster
bool pandora_monitoring::PandoraMonitoring::SortMCParticlesByEnergy (const pandora::MCParticle *const pLhs, const pandora::MCParticle *const pRhs) static
Sort MCParticles by descending energy.
Parameters
pLhs address of first MCParticle
pRhs address of second MCParticle
bool pandora_monitoring::PandoraMonitoring::SortPfosByEnergy (const pandora::ParticleFlowObject *const pLhs, const pandora::ParticleFlowObject *const pRhs) static
Sort pfos by descending energy.
Parameters
pLhs address of first pfo
pRhs address of second pfo
bool pandora_monitoring::PandoraMonitoring::SortTracksByMomentum (const pandora::Track *const pLhs, const pandora::Track *const pRhs) static
Sort tracks by descending momentum.
Parameters
pLhs address of first track
pRhs address of second track
TEveElement * pandora_monitoring::PandoraMonitoring::VisualizeCaloHits (const pandora::CaloHitList *const pCaloHitList, const std::string & name, TEveElement * parent, const Color color)
Add CaloHits to the Eve event-display.
Parameters
pCaloHitList list of calohits to be added to the event display
parent name of the calohitlist
parent pointer to the parent TEveElement. If NULL, the cluster will be parent element
color The color the cluster elements are drawn with
Returns
pointer to created TEveElement
Referenced by PandoraMonitoringApi::VisualizeCaloHits().
TEveElement * pandora_monitoring::PandoraMonitoring::VisualizeClusters (const pandora::ClusterList *const pClusterList, const std::string & name, TEveElement * parent, const Color color, bool showAssociatedTracks)
Add Clusters to the Eve event-display.
Parameters
pClusterList list of clusters to be added to the event display
name of the cluster list
parent pointer to the parent TEveElement. If NULL, the cluster will be parent element
color The color the cluster elements are drawn with
showAssociatedTracks draw the tracks associated to the cluster
Returns
pointer to created TEveElement
Referenced by PandoraMonitoringApi::VisualizeClusters().
TEveElement * pandora_monitoring::PandoraMonitoring::VisualizeMCParticles (const pandora::MCParticleList *const pMCParticleList, const std::string & name, TEveElement * parent, const Color color, const PandoraMonitoringApi::PdgCodeToEnergyMap * pParticleSuppressionMap)
Add MC particles to the Eve event-display.
Parameters
pMCParticleList list of tracks to be added to the event display
name of the MC particle list
parent pointer to the parent TEveElement. If NULL, the track will be parent element
color The color the track elements are drawn with
pParticleSuppressionMap map from pdg-codes to energy for suppression of particles types below specific energies
Returns
pointer to created TEveElement
Referenced by PandoraMonitoringApi::VisualizeMCParticles().
TEveElement * pandora_monitoring::PandoraMonitoring::VisualizeParticleFlowObjects (const pandora::PfoList *const pPfoList, const std::string & name, TEveElement * parent, const Color color, bool showVertices, bool displayPfoHierarchy)
Add Particle flow objects to the Eve event-display.
Parameters
pPfoList list of particle flow objects to be added to the event display
name of the pfo list
parent pointer to the parent TEveElement. If NULL, the cluster will be parent element
color The color the cluster elements are drawn with
showAssociatedTracks draw the tracks associated to the cluster
showVertices whether to draw markers to represent the pfo vertices
displayPfoHierarchy whether to draw daughter particles (only) within parent elements
Referenced by PandoraMonitoringApi::VisualizeParticleFlowObjects().
TEveElement * pandora_monitoring::PandoraMonitoring::VisualizeTracks (const pandora::TrackList *const pTrackList, const std::string & name, TEveElement * parent, const Color color)
Add Tracks to the Eve event-display.
Parameters
pTrackList list of tracks to be added to the event display
name of the track list
parent pointer to the parent TEveElement. If NULL, the track will be parent element
color The color the track elements are drawn with
Returns
pointer to created TEveElement
Referenced by PandoraMonitoringApi::VisualizeTracks().
TEveElement * pandora_monitoring::PandoraMonitoring::VisualizeVertices (const pandora::VertexList *const pVertexList, const std::string & name, TEveElement * parent, const Color color)
Add vertices to the Eve event-display.
Parameters
pVertexList list of vertices to be added to the event display
parent name of the vertexlist
parent pointer to the parent TEveElement. If NULL, the vertex will be parent element
color The color the vertex elements are drawn with
Returns
pointer to created TEveElement
Referenced by PandoraMonitoringApi::VisualizeVertices().
The documentation for this class was generated from the following files:
PandoraMonitoring.h
PandoraMonitoring.cc