ArborContent: arbor_content::ConnectorCleaningTool Class Reference
arbor_content::ConnectorCleaningTool Class Reference
ConnectorCleaningTool class.
#include <ConnectorCleaningTool.h>
Classes
class Factory
Factory class for instantiating algorithm tool.
Public Member Functions
~ConnectorCleaningTool ()
Destructor.
pandora::StatusCode Process (const pandora::Algorithm &algorithm, const pandora::CaloHitList *const pCaloHitList)
Clean the connectors of the calo hit list.
pandora::StatusCode ReadSettings (const pandora::TiXmlHandle xmlHandle)
Read settings from the xml handle.
Public Member Functions inherited from arbor_content::ConnectorAlgorithmTool
virtual ~ConnectorAlgorithmTool ()
Destructor.
Private Types
typedef std::map< const
arbor_content::CaloHit
*, pandora::CaloHitList > CaloHitCleaningMap
Private Member Functions
float GetOrderParameter (const arbor_content::Connector *const pConnector, const pandora::CartesianVector &referenceDirection) const
Get the order parameter of the connector in the backward direction.
pandora::CartesianVector GetReferenceVector (const arbor_content::CaloHit *const pCaloHit) const
Get the reference vector of the calo hit.
pandora::StatusCode CleanCaloHits (const pandora::CaloHitList *const pCaloHitList) const
Clean the connectors of the calo hits, ending with a tree structure.
pandora::StatusCode CleanCaloHits (const pandora::OrderedCaloHitList &orderedCaloHitList) const
Clean the connectors of the ordered calo hit list, ending with a tree structure.
Private Attributes
unsigned int m_strategy
float m_backwardConnectorWeight
float m_forwardConnectorWeight
unsigned int m_backwardReferenceDirectionDepth
unsigned int m_forwardReferenceDirectionDepth
float m_orderParameterAnglePower
float m_orderParameterDistancePower
Detailed Description
ConnectorCleaningTool class.
Definition at line 43 of file ConnectorCleaningTool.h.
Member Typedef Documentation
typedef std::map<const arbor_content::CaloHit*, pandora::CaloHitList> arbor_content::ConnectorCleaningTool::CaloHitCleaningMap private
Definition at line 45 of file ConnectorCleaningTool.h.
Constructor & Destructor Documentation
arbor_content::ConnectorCleaningTool::~ConnectorCleaningTool () inline
Destructor.
Definition at line 130 of file ConnectorCleaningTool.h.
 {
 }
Member Function Documentation
pandora::StatusCode arbor_content::ConnectorCleaningTool::CleanCaloHits (const pandora::CaloHitList *const pCaloHitList) const private
Clean the connectors of the calo hits, ending with a tree structure.
Parameters
pCaloHitList the calo hit list to clean
Definition at line 105 of file ConnectorCleaningTool.cc.
References arbor_content::BACKWARD_DIRECTION, ArborContentApi::GetConnectorList(), arbor_content::Connector::GetFrom(), GetOrderParameter(), GetReferenceVector(), and ArborContentApi::RemoveConnectionBetween().
Referenced by CleanCaloHits(), and Process().
   {
     CaloHitCleaningMap caloHitCleaningMap;
     for(pandora::CaloHitList::const_iterator iter = pCaloHitList->begin(), endIter = pCaloHitList->end() ;
         endIter != iter ; ++iter)
     {
       const arbor_content::CaloHit *pCaloHit = dynamic_cast<const arbor_content::CaloHit *>(*iter);
       if(NULL == pCaloHit)
         return pandora::STATUS_CODE_FAILURE;
       const ConnectorList &backwardConnectorList(ArborContentApi::GetConnectorList(pCaloHit, BACKWARD_DIRECTION));
       if(backwardConnectorList.size() < 2)
         continue;
       pandora::CartesianVector referenceVector(this->GetReferenceVector(pCaloHit));
       // undefined reference vector ?
       if(referenceVector == pandora::CartesianVector(0.f, 0.f, 0.f))
         return pandora::STATUS_CODE_FAILURE;
       const CaloHit *pBestCaloHit = NULL;
       float bestOrderParameter = std::numeric_limits<float>::max();
       pandora::CaloHitList deleteConnectionCaloHitList;
       // find the best connector with the smallest order parameter
       for(ConnectorList::const_iterator connectorIter = backwardConnectorList.begin(), connectorEndIter = backwardConnectorList.end() ;
           connectorEndIter != connectorIter ; ++connectorIter)
       {
         const Connector *pConnector = *connectorIter;
         const CaloHit *pFromCaloHit = pConnector->GetFrom();
         const float orderParameter(this->GetOrderParameter(pConnector, referenceVector));
         if(orderParameter< bestOrderParameter)
         {
           if(NULL != pBestCaloHit)
             deleteConnectionCaloHitList.insert(pBestCaloHit);
           bestOrderParameter = orderParameter;
           pBestCaloHit = pFromCaloHit;
         }
         else
         {
           deleteConnectionCaloHitList.insert(pFromCaloHit);
         }
       }
       if(NULL != pBestCaloHit)
         caloHitCleaningMap[pCaloHit] = deleteConnectionCaloHitList;
     }
     // remove all un-needed connections
     for(CaloHitCleaningMap::const_iterator iter = caloHitCleaningMap.begin(), endIter = caloHitCleaningMap.end() ;
         endIter != iter ; ++iter)
     {
       for(pandora::CaloHitList::const_iterator hitIter = iter->second.begin(), hitEndIter = iter->second.end() ;
           hitEndIter != hitIter ; ++hitIter)
       {
         const arbor_content::CaloHit *const pCaloHit = dynamic_cast<const arbor_content::CaloHit *const>(*hitIter);
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::RemoveConnectionBetween(iter->first, pCaloHit));
       }
     }
     caloHitCleaningMap.clear();
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ConnectorCleaningTool::CleanCaloHits (const pandora::OrderedCaloHitList & orderedCaloHitList) const private
Clean the connectors of the ordered calo hit list, ending with a tree structure.
Parameters
orderedCaloHitList the ordered calo hit list to clean
Definition at line 177 of file ConnectorCleaningTool.cc.
References CleanCaloHits(), and m_strategy.
   {
     if(1 == m_strategy)
     {
       for(pandora::OrderedCaloHitList::const_iterator iter = orderedCaloHitList.begin(), endIter = orderedCaloHitList.end() ;
           endIter != iter ; ++iter)
       {
         if(iter->second->empty())
           continue;
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->CleanCaloHits(iter->second));
       }
     }
     else
     {
       for(pandora::OrderedCaloHitList::const_reverse_iterator iter = orderedCaloHitList.rbegin(), endIter = orderedCaloHitList.rend() ;
           endIter != iter ; ++iter)
       {
         if(iter->second->empty())
           continue;
         PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->CleanCaloHits(iter->second));
       }
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
float arbor_content::ConnectorCleaningTool::GetOrderParameter (const arbor_content::Connector *const pConnector, const pandora::CartesianVector & referenceDirection) const private
Get the order parameter of the connector in the backward direction.
Parameters
pConnector the connector to compute the order parameter
referenceDirection the reference direction to compare with the connector
Returns
the order parameter
Definition at line 62 of file ConnectorCleaningTool.cc.
References arbor_content::BACKWARD_DIRECTION, arbor_content::Connector::GetNormalizedLength(), arbor_content::Connector::GetVector(), m_orderParameterAnglePower, and m_orderParameterDistancePower.
Referenced by CleanCaloHits().
   {
     const pandora::CartesianVector connectorVector = pConnector->GetVector(BACKWARD_DIRECTION);
     const float angle = referenceDirection.GetOpeningAngle(connectorVector)/M_PI;
     const float distance = pConnector->GetNormalizedLength();
     return (std::pow(angle, m_orderParameterAnglePower) * std::pow(distance, m_orderParameterDistancePower));
   }
pandora::CartesianVector arbor_content::ConnectorCleaningTool::GetReferenceVector (const arbor_content::CaloHit *const pCaloHit) const private
Get the reference vector of the calo hit.
The vector is oriented backwardly.
Parameters
pCaloHit the calo hit to evaluate the reference vector
Returns
the reference vector
Definition at line 73 of file ConnectorCleaningTool.cc.
References arbor_content::BACKWARD_DIRECTION, arbor_content::FORWARD_DIRECTION, arbor_content::CaloHitHelper::GetMeanDirection(), m_backwardConnectorWeight, m_backwardReferenceDirectionDepth, m_forwardConnectorWeight, and m_forwardReferenceDirectionDepth.
Referenced by CleanCaloHits().
   {
     pandora::CartesianVector referenceVector = pandora::CartesianVector(0, 0, 0);
     try
     {
       pandora::CartesianVector meanForwardDirection(0, 0, 0);
       pandora::CartesianVector meanBackwardDirection(0, 0, 0);
       PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, CaloHitHelper::GetMeanDirection(pCaloHit, FORWARD_DIRECTION,
           meanForwardDirection, m_forwardReferenceDirectionDepth));
       meanForwardDirection *= m_forwardConnectorWeight;
       PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, CaloHitHelper::GetMeanDirection(pCaloHit, BACKWARD_DIRECTION,
           meanBackwardDirection, m_backwardReferenceDirectionDepth));
       meanBackwardDirection *= m_backwardConnectorWeight;
       if(meanForwardDirection == meanBackwardDirection)
         throw pandora::StatusCodeException(pandora::STATUS_CODE_FAILURE);
       referenceVector = meanBackwardDirection - meanForwardDirection;
     }
     catch(pandora::StatusCodeException &exception)
     {
     }
     return referenceVector;
   }
pandora::StatusCode arbor_content::ConnectorCleaningTool::Process (const pandora::Algorithm & algorithm, const pandora::CaloHitList *const pCaloHitList) virtual
Clean the connectors of the calo hit list.
Parameters
algorithm the parent algorithm to access pandora content
pCaloHitList the calo hit list to process
Implements arbor_content::ConnectorAlgorithmTool.
Definition at line 40 of file ConnectorCleaningTool.cc.
References CleanCaloHits(), and m_strategy.
   {
     if(pCaloHitList->empty())
       return pandora::STATUS_CODE_SUCCESS;
     if(0 == m_strategy)
     {
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->CleanCaloHits(pCaloHitList));
     }
     else
     {
       pandora::OrderedCaloHitList orderedCaloHitList;
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, orderedCaloHitList.Add(*pCaloHitList));
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, this->CleanCaloHits(orderedCaloHitList));
     }
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ConnectorCleaningTool::ReadSettings (const pandora::TiXmlHandle xmlHandle)
Read settings from the xml handle.
Parameters
xmlHandle the xml handle to settings
Definition at line 207 of file ConnectorCleaningTool.cc.
References m_backwardConnectorWeight, m_backwardReferenceDirectionDepth, m_forwardConnectorWeight, m_forwardReferenceDirectionDepth, m_orderParameterAnglePower, m_orderParameterDistancePower, and m_strategy.
   {
     m_backwardConnectorWeight = 1.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "BackwardConnectorWeight", m_backwardConnectorWeight));
     m_forwardConnectorWeight = 3.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "ForwardConnectorWeight", m_forwardConnectorWeight));
     m_backwardReferenceDirectionDepth = 1;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "BackwardReferenceDirectionDepth", m_backwardReferenceDirectionDepth));
     m_forwardReferenceDirectionDepth = 2;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "ForwardReferenceDirectionDepth", m_forwardReferenceDirectionDepth));
     if(m_backwardReferenceDirectionDepth == 0 || m_forwardReferenceDirectionDepth == 0)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     m_orderParameterAnglePower = 1.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "OrderParameterAnglePower", m_orderParameterAnglePower));
     m_orderParameterDistancePower = 5.f;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "OrderParameterDistancePower", m_orderParameterDistancePower));
     m_strategy = 2;
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
         "Strategy", m_strategy));
     if(2 < m_strategy)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     return pandora::STATUS_CODE_SUCCESS;
   }
Member Data Documentation
float arbor_content::ConnectorCleaningTool::m_backwardConnectorWeight private
Definition at line 113 of file ConnectorCleaningTool.h.
Referenced by GetReferenceVector(), and ReadSettings().
unsigned int arbor_content::ConnectorCleaningTool::m_backwardReferenceDirectionDepth private
Definition at line 115 of file ConnectorCleaningTool.h.
Referenced by GetReferenceVector(), and ReadSettings().
float arbor_content::ConnectorCleaningTool::m_forwardConnectorWeight private
Definition at line 114 of file ConnectorCleaningTool.h.
Referenced by GetReferenceVector(), and ReadSettings().
unsigned int arbor_content::ConnectorCleaningTool::m_forwardReferenceDirectionDepth private
Definition at line 116 of file ConnectorCleaningTool.h.
Referenced by GetReferenceVector(), and ReadSettings().
float arbor_content::ConnectorCleaningTool::m_orderParameterAnglePower private
Definition at line 117 of file ConnectorCleaningTool.h.
Referenced by GetOrderParameter(), and ReadSettings().
float arbor_content::ConnectorCleaningTool::m_orderParameterDistancePower private
Definition at line 118 of file ConnectorCleaningTool.h.
Referenced by GetOrderParameter(), and ReadSettings().
unsigned int arbor_content::ConnectorCleaningTool::m_strategy private
Definition at line 112 of file ConnectorCleaningTool.h.
Referenced by CleanCaloHits(), Process(), and ReadSettings().
The documentation for this class was generated from the following files:
ConnectorCleaningTool.h
ConnectorCleaningTool.cc