ArborContent: arbor_content::ReclusterHelper Class Reference
arbor_content::ReclusterHelper Class Reference
ReclusterHelper class.
#include <ReclusterHelper.h>
Static Public Member Functions
static float GetTrackClusterCompatibility (const pandora::Pandora &pandora, const pandora::Cluster *const pCluster, const pandora::TrackList &trackList, float energyResolutionFactor=1.f)
Evaluate the compatibility of a cluster with its associated tracks.
static float GetTrackClusterCompatibility (const pandora::Pandora &pandora, const float clusterEnergy, const float trackEnergy, float energyResolutionFactor=1.f)
Evaluate the compatibility of a cluster with its associated tracks.
static pandora::StatusCode ExtractReclusterResults (const pandora::Pandora &pandora, const pandora::ClusterList &clusterList, ReclusterResult &reclusterResult)
Extract the recluster result.
static pandora::StatusCode SplitTreeFromCluster (const pandora::Algorithm &algorithm, const arbor_content::CaloHit *const pSeedCaloHit, const pandora::Cluster *const pOriginalCluster, const pandora::Cluster *&pSeparatedTreeCluster, const std::string &originalClusterListName="")
Create a separated tree cluster from a seed calo hit contained in an original cluster.
static pandora::StatusCode SplitClusterIntoTreeClusters (const pandora::Algorithm &algorithm, const pandora::Cluster *const pCluster, pandora::ClusterVector &treeClusterVector)
Create a cluster list for each tree contained in the cluster Possible only if the cluster contains more than one tree (more than one seed calo hit)
Detailed Description
ReclusterHelper class.
Definition at line 128 of file ReclusterHelper.h.
Member Function Documentation
pandora::StatusCode arbor_content::ReclusterHelper::ExtractReclusterResults (const pandora::Pandora & pandora, const pandora::ClusterList & clusterList, ReclusterResult & reclusterResult) static
Extract the recluster result.
Parameters
pandora the pandora instance to access content
clusterList the newly created clusters after a reclustering step
reclusterResult the recluster results
Definition at line 72 of file ReclusterHelper.cc.
References GetTrackClusterCompatibility(), arbor_content::ReclusterResult::SetChargedEnergy(), arbor_content::ReclusterResult::SetChi(), arbor_content::ReclusterResult::SetChi2(), arbor_content::ReclusterResult::SetChi2PerDof(), arbor_content::ReclusterResult::SetChiPerDof(), arbor_content::ReclusterResult::SetChiWorstAssociation(), and arbor_content::ReclusterResult::SetNeutralEnergy().
Referenced by arbor_content::MissingEnergyReclusteringAlgorithm::Run().
   {
     if(clusterList.empty())
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     unsigned int nDof(0);
     float chi(0.f), chi2(0.f), neutralEnergy(0.f), chargedEnergy(0.f), chiWorstAssociation(0.f);
     for(pandora::ClusterList::const_iterator iter = clusterList.begin(), endIter = clusterList.end() ; endIter != iter ; ++iter)
     {
       const pandora::Cluster *const pCluster = *iter;
       const float clusterEnergy(pCluster->GetCorrectedHadronicEnergy(pandora));
       const pandora::TrackList &trackList(pCluster->GetAssociatedTrackList());
       const unsigned int nTracks(trackList.size());
       if(nTracks == 0)
       {
         neutralEnergy += clusterEnergy;
         continue;
       }
       chargedEnergy += clusterEnergy;
       const float newChi(ReclusterHelper::GetTrackClusterCompatibility(pandora, pCluster, trackList));
       chi += newChi;
       chi2 += newChi * newChi;
       ++nDof;
       if( (newChi * newChi) > chiWorstAssociation*chiWorstAssociation )
         chiWorstAssociation = newChi;
     }
     if(0 == nDof)
       return pandora::STATUS_CODE_FAILURE;
     reclusterResult.SetChi(chi);
     reclusterResult.SetChi2(chi2);
     reclusterResult.SetChiPerDof(chi / nDof);
     reclusterResult.SetChi2PerDof(chi2 / nDof);
     reclusterResult.SetNeutralEnergy(neutralEnergy);
     reclusterResult.SetChargedEnergy(chargedEnergy);
     reclusterResult.SetChiWorstAssociation(chiWorstAssociation);
     return pandora::STATUS_CODE_SUCCESS;
   }
float arbor_content::ReclusterHelper::GetTrackClusterCompatibility (const pandora::Pandora & pandora, const pandora::Cluster *const pCluster, const pandora::TrackList & trackList, float energyResolutionFactor = 1.f) static
Evaluate the compatibility of a cluster with its associated tracks.
Reclustering can be used to split up a cluster and produce more favourable track/cluster matches.
Parameters
pandora the associated pandora instance
pCluster address of the cluster
trackList address of the list of tracks associated with the cluster
energyResolutionFactory the number of sigmas of resolution in the chi computation
Returns
the chi value for the suitability of the track/cluster associations
Definition at line 35 of file ReclusterHelper.cc.
Referenced by arbor_content::TrackClusterAssociationAlgorithm::BuildPossibleAssociations(), arbor_content::TrackClusterAssociationAlgorithm::CalculateAssociationConstraints(), ExtractReclusterResults(), arbor_content::ClusterHelper::GetChiClusterMerging(), arbor_content::SortingHelper::SortByTrackClusterCompatibility::operator()(), arbor_content::UnassociatedTrackRecoveryAlg::PerformPossibleTrackClusterAssociations(), arbor_content::PerformanceMonitoringAlgorithm::Run(), arbor_content::ClusterFragmentMergingAlgorithm::Run(), arbor_content::LoopingTrackAssociationAlgorithm::Run(), arbor_content::EnergyExcessReclusteringAlgorithm::Run(), and arbor_content::MissingEnergyReclusteringAlgorithm::Run().
   {
     float trackEnergySum(0.);
     for (pandora::TrackList::const_iterator trackIter = trackList.begin(), trackIterEnd = trackList.end(); trackIter != trackIterEnd; ++trackIter)
       trackEnergySum += (*trackIter)->GetEnergyAtDca();
     const float hadronicEnergyResolution(pandora.GetSettings()->GetHadronicEnergyResolution());
     if ((trackEnergySum < std::numeric_limits<float>::epsilon()) || (hadronicEnergyResolution < std::numeric_limits<float>::epsilon()))
       throw pandora::StatusCodeException(pandora::STATUS_CODE_FAILURE);
     const float sigmaE(hadronicEnergyResolution * trackEnergySum / std::sqrt(trackEnergySum));
     const float chi((pCluster->GetTrackComparisonEnergy(pandora) - trackEnergySum) / (energyResolutionFactor * sigmaE));
     return chi;
   }
float arbor_content::ReclusterHelper::GetTrackClusterCompatibility (const pandora::Pandora & pandora, const float clusterEnergy, const float trackEnergy, float energyResolutionFactor = 1.f) static
Evaluate the compatibility of a cluster with its associated tracks.
Reclustering can be used to split up a cluster and produce more favourable track/cluster matches.
Parameters
pandora the associated pandora instance
clusterEnergy the cluster energy
trackEnergy the sum of the energies of the associated tracks
energyResolutionFactory the number of sigmas of resolution in the chi computation
Returns
the chi value for the suitability of the track/cluster associations
Definition at line 56 of file ReclusterHelper.cc.
   {
     const float hadronicEnergyResolution(pandora.GetSettings()->GetHadronicEnergyResolution());
     if ((trackEnergy < std::numeric_limits<float>::epsilon()) || (hadronicEnergyResolution < std::numeric_limits<float>::epsilon()))
       throw pandora::StatusCodeException(pandora::STATUS_CODE_FAILURE);
     const float sigmaE(hadronicEnergyResolution * trackEnergy / std::sqrt(trackEnergy));
     const float chi((clusterEnergy - trackEnergy) / (energyResolutionFactor * sigmaE));
     return chi;
   }
pandora::StatusCode arbor_content::ReclusterHelper::SplitClusterIntoTreeClusters (const pandora::Algorithm & algorithm, const pandora::Cluster *const pCluster, pandora::ClusterVector & treeClusterVector) static
Create a cluster list for each tree contained in the cluster Possible only if the cluster contains more than one tree (more than one seed calo hit)
Parameters
algorithm the algorithm instance used to access pandora content
pCluster the cluster to split
treeClusterVector the split list of tree clusters
Definition at line 187 of file ReclusterHelper.cc.
References arbor_content::CaloHitHelper::BuildCaloHitList(), arbor_content::CaloHitHelper::ExtractSeedCaloHitList(), and arbor_content::FORWARD_DIRECTION.
   {
     if(NULL == pCluster)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     pandora::CaloHitList clusterCaloHitList;
     pandora::CaloHitList seedCaloHitList;
     pCluster->GetOrderedCaloHitList().GetCaloHitList(clusterCaloHitList);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, CaloHitHelper::ExtractSeedCaloHitList(&clusterCaloHitList, seedCaloHitList, false));
     // if only one seed in the original cluster, can't create a separate tree from this cluster
     if(seedCaloHitList.size() <= 1)
       return pandora::STATUS_CODE_NOT_ALLOWED;
     pandora::ClusterList reclusterClusterList;
     reclusterClusterList.insert(pCluster);
     std::string originalClusterListName;
     std::string fragmentsClustersListName;
     // fragment the cluster
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::InitializeFragmentation(algorithm, reclusterClusterList, originalClusterListName, fragmentsClustersListName));
     for(pandora::CaloHitList::const_iterator iter = seedCaloHitList.begin(), endIter = seedCaloHitList.end() ;
         endIter != iter ; ++iter)
     {
       const arbor_content::CaloHit *const pCaloHit = dynamic_cast<const arbor_content::CaloHit *const>(*iter);
       if(NULL == pCaloHit)
         return pandora::STATUS_CODE_FAILURE;
       pandora::CaloHitList treeCaloHitList;
       treeCaloHitList.insert(pCaloHit);
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, CaloHitHelper::BuildCaloHitList(pCaloHit, FORWARD_DIRECTION, treeCaloHitList));
       // create a separated tree cluster
       PandoraContentApi::ClusterParameters clusterParameters;
       clusterParameters.m_caloHitList = treeCaloHitList;
       const pandora::Cluster *pTreeCluster = NULL;
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::Cluster::Create(algorithm, clusterParameters, pTreeCluster));
       treeClusterVector.push_back(pTreeCluster);
     }
     // save fragmented clusters
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::EndFragmentation(algorithm, fragmentsClustersListName, originalClusterListName));
     return pandora::STATUS_CODE_SUCCESS;
   }
pandora::StatusCode arbor_content::ReclusterHelper::SplitTreeFromCluster (const pandora::Algorithm & algorithm, const arbor_content::CaloHit *const pSeedCaloHit, const pandora::Cluster *const pOriginalCluster, const pandora::Cluster *& pSeparatedTreeCluster, const std::string & originalClusterListName = "") static
Create a separated tree cluster from a seed calo hit contained in an original cluster.
Possible only if the original cluster contains more than one tree (more than one seed calo hit). Calo hits of the newly created tree cluster are removed from the original one
Parameters
algorithm the algorithm instance used to access pandora content
pSeedCaloHit the seed calo hit pointer to build the separated tree from
pOriginalCluster the original cluster pointer from which to separate the tree
Definition at line 123 of file ReclusterHelper.cc.
References arbor_content::CaloHitHelper::BuildCaloHitList(), arbor_content::CaloHitHelper::ExtractSeedCaloHitList(), arbor_content::FORWARD_DIRECTION, and ArborContentApi::IsSeed().
   {
     if(NULL == pOriginalCluster || NULL == pSeedCaloHit)
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     if(!ArborContentApi::IsSeed(pSeedCaloHit))
       return pandora::STATUS_CODE_INVALID_PARAMETER;
     pandora::CaloHitList clusterCaloHitList;
     pandora::CaloHitList seedCaloHitList;
     pOriginalCluster->GetOrderedCaloHitList().GetCaloHitList(clusterCaloHitList);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, CaloHitHelper::ExtractSeedCaloHitList(&clusterCaloHitList, seedCaloHitList, false));
     // if only one seed in the original cluster, can't create a separate tree from this cluster
     if(seedCaloHitList.size() <= 1)
       return pandora::STATUS_CODE_NOT_ALLOWED;
     // seed calo hit must be contained in the original cluster
     if(seedCaloHitList.end() == seedCaloHitList.find(pSeedCaloHit))
       return pandora::STATUS_CODE_FAILURE;
     pandora::CaloHitList treeCaloHitList;
     treeCaloHitList.insert(pSeedCaloHit);
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, CaloHitHelper::BuildCaloHitList(pSeedCaloHit, FORWARD_DIRECTION, treeCaloHitList));
     // remove all the hits from the original cluster
     for(pandora::CaloHitList::const_iterator iter = treeCaloHitList.begin(), endIter = treeCaloHitList.end() ;
         endIter != iter ; ++iter)
     {
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::RemoveFromCluster(algorithm, pOriginalCluster, *iter));
     }
     // create the separated tree cluster
     PandoraContentApi::ClusterParameters clusterParameters;
     clusterParameters.m_caloHitList = treeCaloHitList;
     pSeparatedTreeCluster = NULL;
     std::string clusterListName;
     std::string temporaryClusterListName;
     const pandora::ClusterList *pTemporaryClusterList = NULL;
     // in order to create a separate tree cluster, cluster creation must be enabled by pandora sdk first
     if(originalClusterListName.empty())
     {
       PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::GetCurrentListName<pandora::Cluster>(algorithm, clusterListName));
     }
     else
     {
       clusterListName = originalClusterListName;
     }
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::CreateTemporaryListAndSetCurrent(algorithm, pTemporaryClusterList, temporaryClusterListName));
     // create the tree cluster and save it
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::Cluster::Create(algorithm, clusterParameters, pSeparatedTreeCluster));
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::SaveList<pandora::Cluster>(algorithm, temporaryClusterListName, clusterListName));
     return pandora::STATUS_CODE_SUCCESS;
   }
The documentation for this class was generated from the following files:
ReclusterHelper.h
ReclusterHelper.cc