MarlinArbor: marlin_arbor::MCParticleCreator Class Reference
marlin_arbor::MCParticleCreator Class Reference
MCParticleCreator class.
#include <MCParticleCreator.h>
Classes
class Settings
Settings class.
Public Types
typedef std::vector< std::string > StringVector
Public Member Functions
MCParticleCreator (const Settings &settings, const pandora::Pandora *const pPandora)
Constructor.
~MCParticleCreator ()
Destructor.
pandora::StatusCode CreateMCParticles (const EVENT::LCEvent *const pLCEvent) const
Create MCParticles.
pandora::StatusCode CreateTrackToMCParticleRelationships (const EVENT::LCEvent *const pLCEvent, const TrackVector &trackVector) const
Create Track to mc particle relationships.
pandora::StatusCode CreateCaloHitToMCParticleRelationships (const EVENT::LCEvent *const pLCEvent, const CalorimeterHitVector &calorimeterHitVector) const
Create calo hit to mc particle relationships.
Detailed Description
MCParticleCreator class.
Constructor & Destructor Documentation
marlin_arbor::MCParticleCreator::MCParticleCreator (const Settings & settings, const pandora::Pandora *const pPandora)
Constructor.
Parameters
settings the creator settings
pPandora address of the relevant pandora instance
Member Function Documentation
pandora::StatusCode marlin_arbor::MCParticleCreator::CreateCaloHitToMCParticleRelationships (const EVENT::LCEvent *const pLCEvent, const CalorimeterHitVector & calorimeterHitVector) const
Create calo hit to mc particle relationships.
Parameters
pLCEvent the lcio event
calorimeterHitVector the vector containing all calorimeter hits successfully passed to pandora
References marlin_arbor::MCParticleCreator::Settings::m_lcCaloHitRelationCollections.
Referenced by marlin_arbor::ArborPFAProcessor::processEvent().
pandora::StatusCode marlin_arbor::MCParticleCreator::CreateMCParticles (const EVENT::LCEvent *const pLCEvent) const
Create MCParticles.
Parameters
pLCEvent the lcio event
References marlin_arbor::MCParticleCreator::Settings::m_mcParticleCollections.
Referenced by marlin_arbor::ArborPFAProcessor::processEvent().
pandora::StatusCode marlin_arbor::MCParticleCreator::CreateTrackToMCParticleRelationships (const EVENT::LCEvent *const pLCEvent, const TrackVector & trackVector) const
Create Track to mc particle relationships.
Parameters
pLCEvent the lcio event
trackVector the vector containing all tracks successfully passed to pandora
References marlin_arbor::MCParticleCreator::Settings::m_lcTrackRelationCollections.
Referenced by marlin_arbor::ArborPFAProcessor::processEvent().
The documentation for this class was generated from the following files:
MCParticleCreator.h
MCParticleCreator.cc