PandoraSDK: pandora::CaloHitMetadata Class Reference
pandora::CaloHitMetadata Class Reference
CaloHitMetadata class.
#include <Metadata.h>
Public Member Functions
CaloHitMetadata (CaloHitList *const pCaloHitList, const std::string &caloHitListName, const bool initialHitAvailability)
Constructor.
~CaloHitMetadata ()
Destructor.
template<typename T >
bool IsAvailable (const T *const pT) const
Is a calo hit, or a list of calo hits, available to add to a cluster.
template<typename T >
StatusCode SetAvailability (const T *const pT, bool isAvailable)
Set availability of a calo hit, or a list of calo hits, to be added to a cluster.
StatusCode Update (const CaloHitMetadata &caloHitMetadata)
Update metadata to account for changes by daughter recluster processes.
StatusCode Update (const CaloHitReplacement &caloHitReplacement)
Update metadata to account for a specific calo hit replacement.
void Clear ()
Clear all metadata content.
const CaloHitUsageMap & GetCaloHitUsageMap () const
Get the calo hit usage map.
const CaloHitReplacementList & GetCaloHitReplacementList () const
Get the calo hit replacement list.
template<>
bool IsAvailable (const CaloHit *const pCaloHit) const
template<>
bool IsAvailable (const CaloHitList *const pCaloHitList) const
template<>
StatusCode SetAvailability (const CaloHit *const pCaloHit, bool isAvailable)
template<>
StatusCode SetAvailability (const CaloHitList *const pCaloHitList, bool isAvailable)
Detailed Description
CaloHitMetadata class.
Constructor & Destructor Documentation
pandora::CaloHitMetadata::CaloHitMetadata (CaloHitList *const pCaloHitList, const std::string & caloHitListName, const bool initialHitAvailability)
Constructor.
Parameters
pCaloHitList address of the associated calo hit list
caloHitListName name of the associated calo hit list
initialHitAvailability the initial availability of the calo hits
Member Function Documentation
const CaloHitReplacementList & pandora::CaloHitMetadata::GetCaloHitReplacementList () const inline
Get the calo hit replacement list.
Returns
the calo hit replacement list
Referenced by Update().
const CaloHitUsageMap & pandora::CaloHitMetadata::GetCaloHitUsageMap () const inline
Get the calo hit usage map.
Returns
the calo hit usage map
Referenced by Update().
template<typename T > bool pandora::CaloHitMetadata::IsAvailable (const T *const pT) const
Is a calo hit, or a list of calo hits, available to add to a cluster.
Parameters
pT address of the object or object list
Returns
boolean
template<typename T > StatusCode pandora::CaloHitMetadata::SetAvailability (const T *const pT, bool isAvailable)
Set availability of a calo hit, or a list of calo hits, to be added to a cluster.
Parameters
pT the address of the object or object list
isAvailable the availability
StatusCode pandora::CaloHitMetadata::Update (const CaloHitMetadata & caloHitMetadata)
Update metadata to account for changes by daughter recluster processes.
Parameters
caloHitMetadata description of the changes made by daughter reclustering processes
References GetCaloHitReplacementList(), and GetCaloHitUsageMap().
StatusCode pandora::CaloHitMetadata::Update (const CaloHitReplacement & caloHitReplacement)
Update metadata to account for a specific calo hit replacement.
Parameters
caloHitReplacement the calo hit replacement
References pandora::CaloHitReplacement::m_newCaloHits, and pandora::CaloHitReplacement::m_oldCaloHits.
The documentation for this class was generated from the following files:
Metadata.h
Metadata.cc