PandoraSDK: pandora::Process Class Reference
pandora::Process Class Reference abstract
Process class.
#include <Process.h>
Public Member Functions
Process ()
Default constructor.
const std::string & GetType () const
Get the type.
const Pandora & GetPandora () const
Get the associated pandora instance.
Protected Member Functions
virtual StatusCode ReadSettings (const TiXmlHandle xmlHandle)=0
Read the algorithm settings.
virtual StatusCode Initialize ()
Perform any operations that must occur after reading settings, but before running the process.
virtual ~Process ()
Destructor.
StatusCode RegisterDetails (const Pandora *const pPandora, const std::string &type)
Register i) the pandora instance that will run the process and ii) the process type.
Protected Attributes
const Pandora * m_pPandora
The pandora object that will run the process.
std::string m_type
The process type.
Detailed Description
Process class.
Member Function Documentation
const Pandora & pandora::Process::GetPandora () const inline
Get the associated pandora instance.
Returns
the associated pandora instance
References m_pPandora.
Referenced by PandoraContentApi::AddIsolatedToCluster(), PandoraContentApi::AddToCluster(), PandoraContentApi::AddToPfo(), PandoraContentApi::AddTrackClusterAssociation(), PandoraContentApi::AlterMetadata(), PandoraContentApi::ObjectCreationHelper< PARAMETERS, METADATA, OBJECT >::Create(), PandoraContentApi::CreateAlgorithmTool(), PandoraContentApi::CreateDaughterAlgorithm(), PandoraContentApi::CreateTemporaryListAndSetCurrent(), PandoraContentApi::Delete(), PandoraContentApi::DropCurrentList(), PandoraContentApi::EndFragmentation(), PandoraContentApi::EndReclustering(), PandoraContentApi::Fragment(), PandoraContentApi::GetCurrentList(), PandoraContentApi::GetCurrentListName(), PandoraContentApi::GetGeometry(), PandoraContentApi::GetList(), PandoraContentApi::GetPlugins(), PandoraContentApi::GetSettings(), PandoraContentApi::InitializeFragmentation(), PandoraContentApi::InitializeReclustering(), PandoraContentApi::IsAvailable(), PandoraContentApi::MergeAndDeleteClusters(), PandoraContentApi::MergeFragments(), PandoraContentApi::RemoveAllMCParticleRelationships(), PandoraContentApi::RemoveAllTrackClusterAssociations(), PandoraContentApi::RemoveCurrentTrackClusterAssociations(), PandoraContentApi::RemoveFromCluster(), PandoraContentApi::RemoveFromPfo(), PandoraContentApi::RemoveIsolatedFromCluster(), PandoraContentApi::RemovePfoParentDaughterRelationship(), PandoraContentApi::RemoveTrackClusterAssociation(), PandoraContentApi::RepeatEventPreparation(), PandoraContentApi::ReplaceCurrentList(), PandoraContentApi::RunClusteringAlgorithm(), PandoraContentApi::RunDaughterAlgorithm(), PandoraContentApi::SaveList(), PandoraContentApi::SetPfoParentDaughterRelationship(), and PandoraContentApi::TemporarilyReplaceCurrentList().
const std::string & pandora::Process::GetType () const inline
Get the type.
Returns
The type
References m_type.
virtual StatusCode pandora::Process::ReadSettings (const TiXmlHandle xmlHandle) protected pure virtual
Read the algorithm settings.
Parameters
xmlHandle the relevant xml handle
StatusCode pandora::Process::RegisterDetails (const Pandora *const pPandora, const std::string & type) inline protected
Register i) the pandora instance that will run the process and ii) the process type.
Parameters
pPandora address of the pandora object that will run the process
type the process type
References m_pPandora, and m_type.
The documentation for this class was generated from the following file:
Process.h