PandoraSDK: PandoraApi Class Reference
PandoraApi Class Reference
PandoraApi class.
#include <PandoraApi.h>
Classes
class CaloHitParameters
CaloHitParameters class.
class Geometry
Geometry class.
class MCParticleParameters
MCParticleParameters class.
class ObjectCreationHelper
Object creation helper class.
class TrackParameters
TrackParameters class.
Public Types
typedef ObjectCreationHelper
< CaloHitParameters,
pandora::CaloHit > CaloHit
typedef ObjectCreationHelper
< MCParticleParameters,
pandora::MCParticle > MCParticle
typedef ObjectCreationHelper
< TrackParameters,
pandora::Track > Track
Static Public Member Functions
static pandora::StatusCode ProcessEvent (const pandora::Pandora &pandora)
Process an event.
static pandora::StatusCode ReadSettings (const pandora::Pandora &pandora, const std::string &xmlFileName)
Read pandora settings.
static pandora::StatusCode RegisterAlgorithmFactory (const pandora::Pandora &pandora, const std::string &algorithmType, pandora::AlgorithmFactory *const pAlgorithmFactory)
Register an algorithm factory with pandora.
static pandora::StatusCode RegisterAlgorithmToolFactory (const pandora::Pandora &pandora, const std::string &algorithmToolType, pandora::AlgorithmToolFactory *const pAlgorithmToolFactory)
Register an algorithm tool factory with pandora.
static pandora::StatusCode SetMCParentDaughterRelationship (const pandora::Pandora &pandora, const void *const pParentAddress, const void *const pDaughterAddress)
Set parent-daughter mc particle relationship.
static pandora::StatusCode SetTrackParentDaughterRelationship (const pandora::Pandora &pandora, const void *const pParentAddress, const void *const pDaughterAddress)
Set parent-daughter track relationship.
static pandora::StatusCode SetTrackSiblingRelationship (const pandora::Pandora &pandora, const void *const pFirstSiblingAddress, const void *const pSecondSiblingAddress)
Set sibling track relationship.
static pandora::StatusCode SetCaloHitToMCParticleRelationship (const pandora::Pandora &pandora, const void *const pCaloHitParentAddress, const void *const pMCParticleParentAddress, const float mcParticleWeight=1)
Set calo hit to mc particle relationship.
static pandora::StatusCode SetTrackToMCParticleRelationship (const pandora::Pandora &pandora, const void *const pTrackParentAddress, const void *const pMCParticleParentAddress, const float mcParticleWeight=1)
Set track to mc particle relationship.
static pandora::StatusCode GetCurrentPfoList (const pandora::Pandora &pandora, const pandora::PfoList *&pPfoList)
Get the current pfo list.
static pandora::StatusCode GetPfoList (const pandora::Pandora &pandora, const std::string &pfoListName, const pandora::PfoList *&pPfoList)
Get a named pfo list.
static pandora::StatusCode SetHitTypeGranularity (const pandora::Pandora &pandora, const pandora::HitType hitType, const pandora::Granularity granularity)
Set the granularity level to be associated with a specified hit type.
static pandora::StatusCode SetBFieldPlugin (const pandora::Pandora &pandora, pandora::BFieldPlugin *const pBFieldPlugin)
Set the bfield plugin used by pandora.
static pandora::StatusCode SetPseudoLayerPlugin (const pandora::Pandora &pandora, pandora::PseudoLayerPlugin *const pPseudoLayerPlugin)
Set the pseudo layer plugin used by pandora.
static pandora::StatusCode SetShowerProfilePlugin (const pandora::Pandora &pandora, pandora::ShowerProfilePlugin *const pShowerProfilePlugin)
Set the shower profile plugin used by pandora.
static pandora::StatusCode RegisterEnergyCorrectionPlugin (const pandora::Pandora &pandora, const std::string &name, const pandora::EnergyCorrectionType energyCorrectionType, pandora::EnergyCorrectionPlugin *const pEnergyCorrectionPlugin)
Register an energy correction plugin.
static pandora::StatusCode RegisterParticleIdPlugin (const pandora::Pandora &pandora, const std::string &name, pandora::ParticleIdPlugin *const pParticleIdPlugin)
Register a particle id plugin.
static pandora::StatusCode Reset (const pandora::Pandora &pandora)
Reset pandora to process another event.
Detailed Description
PandoraApi class.
Member Function Documentation
pandora::StatusCode PandoraApi::GetCurrentPfoList (const pandora::Pandora & pandora, const pandora::PfoList *& pPfoList) static
Get the current pfo list.
Parameters
pandora the pandora instance to get the objects from
pPfoList to receive the address of the particle flow objects
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::GetPfoList (const pandora::Pandora & pandora, const std::string & pfoListName, const pandora::PfoList *& pPfoList) static
Get a named pfo list.
Parameters
pandora the pandora instance to get the objects from
pfoListName the name of the pfo list
pPfoList to receive the address of the pfo list
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::ProcessEvent (const pandora::Pandora & pandora) static
Process an event.
Parameters
pandora the pandora instance to process event
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::ReadSettings (const pandora::Pandora & pandora, const std::string & xmlFileName) static
Read pandora settings.
Parameters
pandora the pandora instance to run the algorithms initialize
xmlFileName the name of the xml file containing the settings
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::RegisterAlgorithmFactory (const pandora::Pandora & pandora, const std::string & algorithmType, pandora::AlgorithmFactory *const pAlgorithmFactory) static
Register an algorithm factory with pandora.
Parameters
pandora the pandora instance to register the algorithm factory with
algorithmType the type of algorithm that the factory will create
pAlgorithmFactory the address of an algorithm factory instance
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::RegisterAlgorithmToolFactory (const pandora::Pandora & pandora, const std::string & algorithmToolType, pandora::AlgorithmToolFactory *const pAlgorithmToolFactory) static
Register an algorithm tool factory with pandora.
Parameters
pandora the pandora instance to register the algorithm tool factory with
algorithmTool Type the type of algorithm tool that the factory will create
pAlgorithmToolFactory the address of an algorithm tool factory instance
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::RegisterEnergyCorrectionPlugin (const pandora::Pandora & pandora, const std::string & name, const pandora::EnergyCorrectionType energyCorrectionType, pandora::EnergyCorrectionPlugin *const pEnergyCorrectionPlugin) static
Register an energy correction plugin.
Parameters
pandora the pandora instance with which to register the energy correction plugin
name the name/label associated with the energy correction plugin
energyCorrectionType the energy correction type
pEnergyCorrectionPlugin address of the energy correction plugin (will pass ownership to pandora)
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::RegisterParticleIdPlugin (const pandora::Pandora & pandora, const std::string & name, pandora::ParticleIdPlugin *const pParticleIdPlugin) static
Register a particle id plugin.
Parameters
pandora the pandora instance with which to register the particle id plugin
functionName the name/label associated with the particle id plugin
pParticleIdPlugin address of the particle id plugin (will pass ownership to pandora)
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::Reset (const pandora::Pandora & pandora) static
Reset pandora to process another event.
Parameters
pandora the pandora instance to reset
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::SetBFieldPlugin (const pandora::Pandora & pandora, pandora::BFieldPlugin *const pBFieldPlugin) static
Set the bfield plugin used by pandora.
Parameters
pandora the pandora instance to register the bfield calculator with
pBFieldPlugin address of the bfield plugin (will pass ownership to pandora)
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::SetCaloHitToMCParticleRelationship (const pandora::Pandora & pandora, const void *const pCaloHitParentAddress, const void *const pMCParticleParentAddress, const float mcParticleWeight = 1) static
Set calo hit to mc particle relationship.
Parameters
pandora the pandora instance to register the relationship with
pCaloHitParentAddress address of calo hit in the user framework
pMCParticleParentAddress address of mc particle in the user framework
mcParticleWeight weighting to assign to the mc particle
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::SetHitTypeGranularity (const pandora::Pandora & pandora, const pandora::HitType hitType, const pandora::Granularity granularity) static
Set the granularity level to be associated with a specified hit type.
Parameters
pandora the pandora instance to register the hit type to granularity relationship
hitType the specified hit type
granularity the specified granularity
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::SetMCParentDaughterRelationship (const pandora::Pandora & pandora, const void *const pParentAddress, const void *const pDaughterAddress) static
Set parent-daughter mc particle relationship.
Parameters
pandora the pandora instance to register the relationship with
pParentAddress address of parent mc particle in the user framework
pDaughterAddress address of daughter mc particle in the user framework
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::SetPseudoLayerPlugin (const pandora::Pandora & pandora, pandora::PseudoLayerPlugin *const pPseudoLayerPlugin) static
Set the pseudo layer plugin used by pandora.
Parameters
pandora the pandora instance to register the pseudo layer calculator with
pPseudoLayerPlugin address of the pseudo layer plugin (will pass ownership to pandora)
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::SetShowerProfilePlugin (const pandora::Pandora & pandora, pandora::ShowerProfilePlugin *const pShowerProfilePlugin) static
Set the shower profile plugin used by pandora.
Parameters
pandora the pandora instance to register the shower profile calculator with
pPseudoLayerPlugin address of the pseudo layer plugin (will pass ownership to pandora)
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::SetTrackParentDaughterRelationship (const pandora::Pandora & pandora, const void *const pParentAddress, const void *const pDaughterAddress) static
Set parent-daughter track relationship.
Parameters
pandora the pandora instance to register the relationship with
pParentAddress address of parent track in the user framework
pDaughterAddress address of daughter track in the user framework
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::SetTrackSiblingRelationship (const pandora::Pandora & pandora, const void *const pFirstSiblingAddress, const void *const pSecondSiblingAddress) static
Set sibling track relationship.
Parameters
pandora the pandora instance to register the relationship with
pFirstSiblingAddress address of first sibling track in the user framework
pSecondSiblingAddress address of second sibling track in the user framework
References pandora::Pandora::GetPandoraApiImpl().
pandora::StatusCode PandoraApi::SetTrackToMCParticleRelationship (const pandora::Pandora & pandora, const void *const pTrackParentAddress, const void *const pMCParticleParentAddress, const float mcParticleWeight = 1) static
Set track to mc particle relationship.
Parameters
pandora the pandora instance to register the relationship with
pTrackParentAddress address of track in the user framework
pMCParticleParentAddress address of mc particle in the user framework
mcParticleWeight weighting to assign to the mc particle
References pandora::Pandora::GetPandoraApiImpl().
The documentation for this class was generated from the following files:
PandoraApi.h
PandoraApi.cc