PandoraSDK: pandora::Manager< T > Class Template Reference
pandora::Manager< T > Class Template Reference
Manager class.
#include <Manager.h>
Classes
class AlgorithmInfo
AlgorithmInfo class.
Public Member Functions
Manager (const Pandora *const pPandora)
Constructor.
virtual ~Manager ()
Destructor.
Protected Types
typedef std::MANAGED_CONTAINER
< const T * > ObjectList
typedef std::map< std::string,
ObjectList * > NameToListMap
typedef std::map< const
Algorithm *, AlgorithmInfo > AlgorithmInfoMap
Protected Member Functions
virtual StatusCode GetList (const std::string &listName, const ObjectList *&pObjectList) const
Get a list.
virtual StatusCode GetCurrentList (const ObjectList *&pObjectList, std::string &listName) const
Get the current list.
virtual StatusCode GetCurrentListName (std::string &listName) const
Get the current list name.
virtual StatusCode GetAlgorithmInputList (const Algorithm *const pAlgorithm, const ObjectList *&pObjectList, std::string &listName) const
Get the algorithm input list.
virtual StatusCode GetAlgorithmInputListName (const Algorithm *const pAlgorithm, std::string &listName) const
Get the algorithm track list name.
virtual StatusCode ResetCurrentListToAlgorithmInputList (const Algorithm *const pAlgorithm)
Reset the current list to the algorithm input list.
virtual StatusCode ReplaceCurrentAndAlgorithmInputLists (const Algorithm *const pAlgorithm, const std::string &listName)
Replace the current and algorithm input lists with a pre-existing list.
virtual StatusCode DropCurrentList (const Algorithm *const pAlgorithm)
Drop the current list, returning the current list to its default empty/null state.
virtual StatusCode CreateTemporaryListAndSetCurrent (const Algorithm *const pAlgorithm, std::string &temporaryListName)
Create a temporary list associated with a particular algorithm.
virtual StatusCode RegisterAlgorithm (const Algorithm *const pAlgorithm)
Register an algorithm with the manager.
virtual StatusCode ResetAlgorithmInfo (const Algorithm *const pAlgorithm, bool isAlgorithmFinished)
Remove temporary lists and reset the current list to that when algorithm was initialized.
virtual StatusCode ResetForNextEvent ()
Reset the manager.
virtual StatusCode EraseAllContent ()
Erase all manager content.
virtual StatusCode CreateInitialLists ()
Create initial lists.
virtual T * Modifiable (const T *const pT) const
Access a modifiable object, when provided with address to const object.
Protected Attributes
NameToListMap m_nameToListMap
The name to list map.
AlgorithmInfoMap m_algorithmInfoMap
The algorithm info map.
std::string m_currentListName
The name of the current list.
StringSet m_savedLists
The set of saved lists.
const Pandora *const m_pPandora
The associated pandora object.
Static Protected Attributes
static const std::string NULL_LIST_NAME = "NullList"
The name of the default empty (NULL) list.
Detailed Description
template<typename T>
class pandora::Manager< T >
Manager class.
Constructor & Destructor Documentation
template<typename T > pandora::Manager< T >::Manager (const Pandora *const pPandora)
Constructor.
Parameters
pPandora address of the associated pandora object
Member Function Documentation
template<typename T > StatusCode pandora::Manager< T >::CreateTemporaryListAndSetCurrent (const Algorithm *const pAlgorithm, std::string & temporaryListName) protected virtual
Create a temporary list associated with a particular algorithm.
Parameters
pAlgorithm address of the algorithm
temporaryListName to receive the name of the temporary list
Reimplemented in pandora::AlgorithmObjectManager< T >, pandora::AlgorithmObjectManager< Vertex >, pandora::AlgorithmObjectManager< Cluster >, and pandora::AlgorithmObjectManager< ParticleFlowObject >.
Referenced by pandora::AlgorithmObjectManager< T >::CreateTemporaryListAndSetCurrent().
template<typename T > StatusCode pandora::Manager< T >::DropCurrentList (const Algorithm *const pAlgorithm) protected virtual
Drop the current list, returning the current list to its default empty/null state.
Parameters
pAlgorithm address of the algorithm altering the lists
Reimplemented in pandora::AlgorithmObjectManager< T >, pandora::AlgorithmObjectManager< Vertex >, pandora::AlgorithmObjectManager< Cluster >, and pandora::AlgorithmObjectManager< ParticleFlowObject >.
Referenced by pandora::AlgorithmObjectManager< T >::DropCurrentList().
template<typename T > StatusCode pandora::Manager< T >::GetAlgorithmInputList (const Algorithm *const pAlgorithm, const ObjectList *& pObjectList, std::string & listName) const protected virtual
Get the algorithm input list.
Parameters
pAlgorithm address of the algorithm
pObjectList to receive the algorithm input list
listName to receive the name of the algorithm input list
template<typename T > StatusCode pandora::Manager< T >::GetAlgorithmInputListName (const Algorithm *const pAlgorithm, std::string & listName) const inline protected virtual
Get the algorithm track list name.
Parameters
pAlgorithm address of the algorithm
listName to receive the algorithm input list name
template<typename T > StatusCode pandora::Manager< T >::GetCurrentList (const ObjectList *& pObjectList, std::string & listName) const protected virtual
Get the current list.
Parameters
pObjectList to receive the current list
listName to receive the name of the current list
template<typename T > StatusCode pandora::Manager< T >::GetCurrentListName (std::string & listName) const inline protected virtual
Get the current list name.
Parameters
listName to receive the current list name
template<typename T > StatusCode pandora::Manager< T >::GetList (const std::string & listName, const ObjectList *& pObjectList) const protected virtual
Get a list.
Parameters
listName the name of the list
pObjectList to receive the list
template<typename T> T * pandora::Manager< T >::Modifiable (const T *const pT) const protected virtual
Access a modifiable object, when provided with address to const object.
Parameters
pT the address of the const object
Returns
address of the modifiable object
template<typename T > StatusCode pandora::Manager< T >::RegisterAlgorithm (const Algorithm *const pAlgorithm) protected virtual
Register an algorithm with the manager.
Parameters
pAlgorithm address of the algorithm
References pandora::Manager< T >::AlgorithmInfo::m_numberOfListsCreated, and pandora::Manager< T >::AlgorithmInfo::m_parentListName.
template<typename T > StatusCode pandora::Manager< T >::ReplaceCurrentAndAlgorithmInputLists (const Algorithm *const pAlgorithm, const std::string & listName) protected virtual
Replace the current and algorithm input lists with a pre-existing list.
Parameters
pAlgorithm address of the algorithm changing the current list
listName the name of the new current (and algorithm input) list
Reimplemented in pandora::AlgorithmObjectManager< T >, pandora::AlgorithmObjectManager< Vertex >, pandora::AlgorithmObjectManager< Cluster >, and pandora::AlgorithmObjectManager< ParticleFlowObject >.
Referenced by pandora::AlgorithmObjectManager< T >::ReplaceCurrentAndAlgorithmInputLists().
template<typename T > StatusCode pandora::Manager< T >::ResetAlgorithmInfo (const Algorithm *const pAlgorithm, bool isAlgorithmFinished) protected virtual
Remove temporary lists and reset the current list to that when algorithm was initialized.
Parameters
pAlgorithm address of the algorithm altering the lists
isAlgorithmFinished whether the algorithm has completely finished and the algorithm info should be entirely removed
Reimplemented in pandora::AlgorithmObjectManager< T >, pandora::AlgorithmObjectManager< Vertex >, pandora::AlgorithmObjectManager< Cluster >, and pandora::AlgorithmObjectManager< ParticleFlowObject >.
Referenced by pandora::AlgorithmObjectManager< T >::ResetAlgorithmInfo().
template<typename T > StatusCode pandora::Manager< T >::ResetCurrentListToAlgorithmInputList (const Algorithm *const pAlgorithm) protected virtual
Reset the current list to the algorithm input list.
Parameters
pAlgorithm address of the algorithm changing the current track list
Reimplemented in pandora::AlgorithmObjectManager< T >, pandora::AlgorithmObjectManager< Vertex >, pandora::AlgorithmObjectManager< Cluster >, and pandora::AlgorithmObjectManager< ParticleFlowObject >.
Referenced by pandora::AlgorithmObjectManager< T >::ResetCurrentListToAlgorithmInputList().
The documentation for this class was generated from the following files:
Manager.h
Manager.cc