PandoraSDK: pandora::FileReader Class Reference
pandora::FileReader Class Reference abstract
FileReader class.
#include <FileReader.h>
Public Member Functions
FileReader (const pandora::Pandora &pandora, const std::string &fileName)
Constructor.
virtual ~FileReader ()
Destructor.
StatusCode ReadGeometry ()
Read the current geometry information from the file.
StatusCode ReadEvent ()
Read an entire pandora event from the file, recreating the stored objects.
StatusCode GoToNextGeometry ()
Skip to next geometry container in the file.
StatusCode GoToNextEvent ()
Skip to next event container in the file.
virtual StatusCode GoToGeometry (const unsigned int geometryNumber)=0
Skip to a specified geometry number in the file.
virtual StatusCode GoToEvent (const unsigned int eventNumber)=0
Skip to a specified event number in the file.
Public Member Functions inherited from pandora::Persistency
Persistency (const pandora::Pandora &pandora, const std::string &fileName)
Constructor.
virtual ~Persistency ()
Destructor.
const std::string & GetFileName () const
Get the file name.
FileType GetFileType () const
Get the file type.
template<typename PARAMETERS , typename OBJECT >
StatusCode SetFactory (ObjectFactory< PARAMETERS, OBJECT > *const pFactory)
Set the factory to use for all instantiations and parameter persistence.
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::CaloHit::Parameters, CaloHit > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::Track::Parameters, Track > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::MCParticle::Parameters, MCParticle > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::Geometry::SubDetector::Parameters, SubDetector > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::Geometry::LineGap::Parameters, LineGap > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::Geometry::BoxGap::Parameters, BoxGap > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::Geometry::ConcentricGap::Parameters, ConcentricGap > *const pFactory)
Protected Member Functions
virtual StatusCode ReadHeader ()=0
Read the container header from the current position in the file, checking for properly written container.
virtual StatusCode GoToNextContainer ()=0
Skip to next container in the file.
virtual ContainerId GetNextContainerId ()=0
Get the id of the next container in the file without changing the current position in the file.
virtual StatusCode ReadNextGeometryComponent ()=0
Read the next pandora geometry component from the current position in the file, recreating the stored component.
virtual StatusCode ReadNextEventComponent ()=0
Read the next pandora event component from the current position in the file, recreating the stored component.
Protected Member Functions inherited from pandora::Persistency
template<typename PARAMETERS , typename OBJECT >
void ReplaceCurrentFactory (ObjectFactory< PARAMETERS, OBJECT > *const pFactory)
Replace the current factory with the provided instance.
Additional Inherited Members
Protected Attributes inherited from pandora::Persistency
const Pandora *const m_pPandora
Address of pandora instance to be used alongside the file writer.
std::string m_fileName
The file name.
FileType m_fileType
The file type.
ContainerId m_containerId
The type of container currently being written to file.
ObjectFactory
< PandoraApi::CaloHit::Parameters,
CaloHit > * m_pCaloHitFactory
Address of the calo hit factory.
ObjectFactory
< PandoraApi::Track::Parameters,
Track > * m_pTrackFactory
Address of the track factory.
ObjectFactory
< PandoraApi::MCParticle::Parameters,
MCParticle > * m_pMCParticleFactory
Address of the mc particle factory.
ObjectFactory
< PandoraApi::Geometry::SubDetector::Parameters,
SubDetector > * m_pSubDetectorFactory
Address of the sub detector factory.
ObjectFactory
< PandoraApi::Geometry::LineGap::Parameters,
LineGap > * m_pLineGapFactory
Address of the line gap factory.
ObjectFactory
< PandoraApi::Geometry::BoxGap::Parameters,
BoxGap > * m_pBoxGapFactory
Address of the box gap factory.
ObjectFactory
< PandoraApi::Geometry::ConcentricGap::Parameters,
ConcentricGap > * m_pConcentricGapFactory
Address of the concentric gap factory.
Detailed Description
FileReader class.
Constructor & Destructor Documentation
pandora::FileReader::FileReader (const pandora::Pandora & pandora, const std::string & fileName)
Constructor.
Parameters
pandora the pandora instance to be used alongside the file reader
fileName the name of the file containing the pandora objects
Member Function Documentation
virtual ContainerId pandora::FileReader::GetNextContainerId () protected pure virtual
Get the id of the next container in the file without changing the current position in the file.
Returns
The id of the next container in the file
Referenced by GoToNextEvent(), GoToNextGeometry(), ReadEvent(), and ReadGeometry().
virtual StatusCode pandora::FileReader::GoToEvent (const unsigned int eventNumber) pure virtual
Skip to a specified event number in the file.
Parameters
eventNumber the event number
virtual StatusCode pandora::FileReader::GoToGeometry (const unsigned int geometryNumber) pure virtual
Skip to a specified geometry number in the file.
Parameters
geometryNumber the geometry number
The documentation for this class was generated from the following files:
FileReader.h
FileReader.cc