PandoraSDK: pandora::ClusterFitResult Class Reference
pandora::ClusterFitResult Class Reference
ClusterFitResult class.
#include <ClusterFitHelper.h>
Public Member Functions
ClusterFitResult ()
Default constructor.
bool IsFitSuccessful () const
Query whether fit was successful.
const CartesianVector & GetDirection () const
Get the fit direction.
const CartesianVector & GetIntercept () const
Get the fit intercept.
float GetChi2 () const
Get the fit ch2.
float GetRms () const
Get the fit rms.
float GetRadialDirectionCosine () const
Get the fit direction cosine w.r.t.
void SetSuccessFlag (const bool successFlag)
Set the fit success flag.
void SetDirection (const CartesianVector &direction)
Set the fit direction.
void SetIntercept (const CartesianVector &intercept)
Set the fit intercept.
void SetChi2 (const float chi2)
Set the fit chi2.
void SetRms (const float rms)
Set the fit rms.
void SetRadialDirectionCosine (const float radialDirectionCosine)
Set the fit direction cosine w.r.t.
void Reset ()
Reset the cluster fit result.
Detailed Description
ClusterFitResult class.
Member Function Documentation
float pandora::ClusterFitResult::GetChi2 () const inline
Get the fit ch2.
Returns
the fit chi2
References pandora::PandoraInputType< T >::Get().
const CartesianVector & pandora::ClusterFitResult::GetDirection () const inline
Get the fit direction.
Returns
the fit direction
const CartesianVector & pandora::ClusterFitResult::GetIntercept () const inline
Get the fit intercept.
Returns
the fit intercept
float pandora::ClusterFitResult::GetRadialDirectionCosine () const inline
Get the fit direction cosine w.r.t.
the radial direction
Returns
the fit direction cosine w.r.t. the radial direction
References pandora::PandoraInputType< T >::Get().
float pandora::ClusterFitResult::GetRms () const inline
Get the fit rms.
Returns
the fit rms
References pandora::PandoraInputType< T >::Get().
bool pandora::ClusterFitResult::IsFitSuccessful () const inline
Query whether fit was successful.
Returns
boolean
void pandora::ClusterFitResult::SetChi2 (const float chi2) inline
Set the fit chi2.
Parameters
chi2 the fit chi2
void pandora::ClusterFitResult::SetDirection (const CartesianVector & direction) inline
Set the fit direction.
Parameters
direction the fit direction
void pandora::ClusterFitResult::SetIntercept (const CartesianVector & intercept) inline
Set the fit intercept.
Parameters
intercept the fit intercept
void pandora::ClusterFitResult::SetRadialDirectionCosine (const float radialDirectionCosine) inline
Set the fit direction cosine w.r.t.
the radial direction
Parameters
radialDirectionCosine the fit direction cosine w.r.t. the radial direction
void pandora::ClusterFitResult::SetRms (const float rms) inline
Set the fit rms.
Parameters
rms the fit rms
void pandora::ClusterFitResult::SetSuccessFlag (const bool successFlag) inline
Set the fit success flag.
Parameters
successFlag the fit success flag
Referenced by pandora::ClusterFitHelper::FitLayerCentroids(), and pandora::ClusterFitHelper::FitPoints().
The documentation for this class was generated from the following file:
ClusterFitHelper.h