PandoraSDK: pandora::PandoraInputType< T > Class Template Reference
pandora::PandoraInputType< T > Class Template Reference
PandoraInputType template class.
#include <PandoraInputTypes.h>
Public Member Functions
PandoraInputType ()
Default constructor.
~PandoraInputType ()
Destructor.
PandoraInputType (const T &t)
Constructor.
PandoraInputType (const PandoraInputType< T > &rhs)
Copy constructor (EXPENSIVE WITH LARGE OBJECTS)
void Set (const T &t)
Set the value held by the pandora type.
const T & Get () const
Get the value held by the pandora type.
void Reset ()
Reset the pandora type.
bool IsInitialized () const
Whether the pandora type is initialized.
bool operator= (const T &rhs)
Assignment operator for the pandora type.
bool operator= (const PandoraInputType< T > &rhs)
Assignment operator for parent pandora type (EXPENSIVE WITH LARGE OBJECTS)
Detailed Description
template<typename T>
class pandora::PandoraInputType< T >
PandoraInputType template class.
Constructor & Destructor Documentation
template<typename T> pandora::PandoraInputType< T >::PandoraInputType (const T & t) inline
Constructor.
Parameters
t the initial value
template<typename T> pandora::PandoraInputType< T >::PandoraInputType (const PandoraInputType< T > & rhs) inline
Copy constructor (EXPENSIVE WITH LARGE OBJECTS)
Parameters
rhs the initial pandora type
Member Function Documentation
template<typename T > const T & pandora::PandoraInputType< T >::Get () const inline
Get the value held by the pandora type.
Returns
the value
Referenced by pandora::Cluster::AddCaloHit(), pandora::ClusterFitResult::GetChi2(), pandora::Cluster::GetCorrectedElectromagneticEnergy(), pandora::Cluster::GetCorrectedHadronicEnergy(), pandora::Cluster::GetInnerLayerHitType(), pandora::Cluster::GetInnerPseudoLayer(), pandora::Cluster::GetOuterLayerHitType(), pandora::Cluster::GetOuterPseudoLayer(), pandora::ClusterFitResult::GetRadialDirectionCosine(), pandora::ClusterFitResult::GetRms(), pandora::Cluster::GetShowerProfileDiscrepancy(), pandora::Cluster::GetShowerProfileStart(), pandora::Cluster::GetShowerStartLayer(), pandora::Cluster::GetTrackComparisonEnergy(), pandora::Cluster::IsPhotonFast(), and pandora::Cluster::RemoveCaloHit().
template<typename T > bool pandora::PandoraInputType< T >::IsInitialized () const inline
Whether the pandora type is initialized.
Returns
boolean
Referenced by pandora::Cluster::AddCaloHit(), pandora::Cluster::GetCorrectedElectromagneticEnergy(), pandora::Cluster::GetCorrectedHadronicEnergy(), pandora::Cluster::GetInnerLayerHitType(), pandora::Cluster::GetOuterLayerHitType(), pandora::Cluster::GetShowerProfileDiscrepancy(), pandora::Cluster::GetShowerProfileStart(), pandora::Cluster::GetShowerStartLayer(), pandora::Cluster::GetTrackComparisonEnergy(), and pandora::Cluster::IsPhotonFast().
template<typename T> bool pandora::PandoraInputType< T >::operator= (const T & rhs) inline
Assignment operator for the pandora type.
Returns
whether assignment succeeded
template<typename T> bool pandora::PandoraInputType< T >::operator= (const PandoraInputType< T > & rhs) inline
Assignment operator for parent pandora type (EXPENSIVE WITH LARGE OBJECTS)
Exceptions
status code exception
template<typename T> void pandora::PandoraInputType< T >::Set (const T & t) inline
Set the value held by the pandora type.
Parameters
t the value
The documentation for this class was generated from the following file:
PandoraInputTypes.h