MarlinArbor: marlin_arbor::TrackCreator Class Reference
marlin_arbor::TrackCreator Class Reference
TrackCreator class.
#include <TrackCreator.h>
Classes
class Settings
Settings class.
Public Types
typedef std::vector< double > DoubleVector
typedef std::vector< std::string > StringVector
Public Member Functions
TrackCreator (const Settings &settings, const pandora::Pandora *const pPandora)
Constructor.
~TrackCreator ()
Destructor.
pandora::StatusCode CreateTrackAssociations (const EVENT::LCEvent *const pLCEvent)
Create associations between tracks, V0s, kinks, etc.
pandora::StatusCode CreateTracks (EVENT::LCEvent *pLCEvent)
Create tracks, insert user code here.
const TrackVector & GetTrackVector () const
Get the track vector.
void Reset ()
Reset the track creator.
Detailed Description
TrackCreator class.
Constructor & Destructor Documentation
marlin_arbor::TrackCreator::TrackCreator (const Settings & settings, const pandora::Pandora *const pPandora)
Constructor.
Parameters
settings the creator settings
pPandora address of the relevant pandora instance
Member Function Documentation
pandora::StatusCode marlin_arbor::TrackCreator::CreateTrackAssociations (const EVENT::LCEvent *const pLCEvent)
Create associations between tracks, V0s, kinks, etc.
Parameters
pLCEvent the lcio event
Referenced by marlin_arbor::ArborPFAProcessor::processEvent().
pandora::StatusCode marlin_arbor::TrackCreator::CreateTracks (EVENT::LCEvent * pLCEvent)
Create tracks, insert user code here.
Parameters
pLCEvent the lcio event
References marlin_arbor::TrackCreator::Settings::m_maxTrackHits, marlin_arbor::TrackCreator::Settings::m_minFtdTrackHits, marlin_arbor::TrackCreator::Settings::m_minTrackHits, and marlin_arbor::TrackCreator::Settings::m_trackCollections.
Referenced by marlin_arbor::ArborPFAProcessor::processEvent().
const TrackVector & marlin_arbor::TrackCreator::GetTrackVector () const inline
Get the track vector.
Returns
The track vector
Referenced by marlin_arbor::ArborPFAProcessor::processEvent().
The documentation for this class was generated from the following files:
TrackCreator.h
TrackCreator.cc