PandoraSDK: pandora::ParticleIdPlugin Class Reference
pandora::ParticleIdPlugin Class Reference abstract
ParticleIdPlugin class.
#include <ParticleIdPlugin.h>
Public Member Functions
virtual bool IsMatch (const Cluster *const pCluster) const =0
Whether the cluster matches the specific particle hypothesis.
Public Member Functions inherited from pandora::Process
Process ()
Default constructor.
const std::string & GetType () const
Get the type.
const Pandora & GetPandora () const
Get the associated pandora instance.
Friends
class ParticleId
Additional Inherited Members
Protected Member Functions inherited from pandora::Process
virtual StatusCode ReadSettings (const TiXmlHandle xmlHandle)=0
Read the algorithm settings.
virtual StatusCode Initialize ()
Perform any operations that must occur after reading settings, but before running the process.
virtual ~Process ()
Destructor.
StatusCode RegisterDetails (const Pandora *const pPandora, const std::string &type)
Register i) the pandora instance that will run the process and ii) the process type.
Protected Attributes inherited from pandora::Process
const Pandora * m_pPandora
The pandora object that will run the process.
std::string m_type
The process type.
Detailed Description
ParticleIdPlugin class.
Member Function Documentation
virtual bool pandora::ParticleIdPlugin::IsMatch (const Cluster *const pCluster) const pure virtual
Whether the cluster matches the specific particle hypothesis.
Parameters
pCluster address of the cluster
Returns
boolean
Referenced by pandora::ParticleId::IsElectron(), pandora::ParticleId::IsEmShower(), pandora::ParticleId::IsMuon(), and pandora::ParticleId::IsPhoton().
The documentation for this class was generated from the following file:
ParticleIdPlugin.h