PandoraSDK: pandora::TwoDHistogram Class Reference
pandora::TwoDHistogram Class Reference
TwoDHistogram class.
#include <Histograms.h>
Public Member Functions
TwoDHistogram (const unsigned int nBinsX, const float xLow, const float xHigh, const unsigned int nBinsY, const float yLow, const float yHigh)
Constructor.
TwoDHistogram (const TiXmlHandle *const pXmlHandle, const std::string &xmlElementName)
Constructor.
TwoDHistogram (const TwoDHistogram &rhs)
Copy constructor.
int GetNBinsX () const
Get the number of x bins.
float GetXLow () const
Get the min binned x value.
float GetXHigh () const
Get the max binned x value.
float GetXBinWidth () const
Get the x bin width.
int GetNBinsY () const
Get the number of y bins.
float GetYLow () const
Get the min binned y value.
float GetYHigh () const
Get the max binned y value.
float GetYBinWidth () const
Get the y bin width.
float GetBinContent (const int binX, const int binY) const
Get the content of a specified bin.
int GetBinNumberX (const float valueX) const
Get the x bin number for a specified x value.
int GetMinBinNumberX () const
Get the min x bin number of the histogram (ignores overflow and underflow bins)
int GetMaxBinNumberX () const
Get the max x bin number of the histogram (ignores overflow and underflow bins)
int GetUnderflowBinNumberX () const
Get the underflow x bin number of the histogram.
int GetOverflowBinNumberX () const
Get the overflow x bin number of the histogram.
int GetBinNumberY (const float valueY) const
Get the y bin number for a specified value.
int GetMinBinNumberY () const
Get the min y bin number of the histogram (ignores overflow and underflow bins)
int GetMaxBinNumberY () const
Get the max y bin number of the histogram (ignores overflow and underflow bins)
int GetUnderflowBinNumberY () const
Get the underflow y bin number of the histogram.
int GetOverflowBinNumberY () const
Get the overflow y bin number of the histogram.
float GetCumulativeSum () const
Get the cumulative sum of bin entries in the histogram (ignores overflow and underflow bins)
float GetCumulativeSum (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin) const
Get the cumulative sum of bin entries in a specified range of the histogram (includes overflow and underflow bins if specified)
void GetMaximum (float &maximumValue, int &maximumBinX, int &maximumBinY) const
Get the maximum value in the histogram and the corresponding bin numbers (ignores overflow and underflow bins)
void GetMaximum (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin, float &maximumValue, int &maximumBinX, int &maximumBinY) const
Get the maximum value in a specified range of the histogram and the corresponding bin numbers (includes overflow and underflow bins if specified)
float GetMeanX () const
Get the mean x value of entries in the histogram (ignores overflow and underflow bins)
float GetMeanX (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin) const
Get the mean x value of entries in a specified range of the histogram (ignores overflow and underflow bins)
float GetStandardDeviationX () const
Get the standard deviation of x entries in the histogram (ignores overflow and underflow bins)
float GetStandardDeviationX (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin) const
Get the standard deviation of x entries in a specified range of the histogram (ignores overflow and underflow bins)
float GetMeanY () const
Get the mean y value of entries in the histogram (ignores overflow and underflow bins)
float GetMeanY (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin) const
Get the mean y value of entries in a specified range of the histogram (ignores overflow and underflow bins)
float GetStandardDeviationY () const
Get the standard deviation of y entries in the histogram (ignores overflow and underflow bins)
float GetStandardDeviationY (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin) const
Get the standard deviation of y entries in a specified range of the histogram (ignores overflow and underflow bins)
void SetBinContent (const int binX, const int binY, const float value)
Set the contents of a specified bin.
void Fill (const float valueX, const float valueY, const float weight=1.f)
Add an entry to the histogram.
void Scale (const float scaleFactor)
Scale contents of all histogram bins by a specified factor.
void WriteToXml (TiXmlDocument *const pTiXmlDocument, const std::string &xmlElementName) const
Write the histogram to an xml document.
Detailed Description
TwoDHistogram class.
Constructor & Destructor Documentation
pandora::TwoDHistogram::TwoDHistogram (const unsigned int nBinsX, const float xLow, const float xHigh, const unsigned int nBinsY, const float yLow, const float yHigh)
Constructor.
Parameters
nBinsX number of x bins
xLow min binned x value
xHigh max binned x value
nBinsY number of y bins
yLow min binned y value
yHigh max binned y value
pandora::TwoDHistogram::TwoDHistogram (const TiXmlHandle *const pXmlHandle, const std::string & xmlElementName)
Constructor.
Parameters
pXmlHandle address of the handle for the xml element describing the histogram
xmlElementName the xml element name for the histogram
References pandora::TiXmlHandle::Element(), pandora::TiXmlHandle::FirstChild(), GetOverflowBinNumberX(), GetOverflowBinNumberY(), GetUnderflowBinNumberX(), GetUnderflowBinNumberY(), pandora::XmlHelper::Read2DVectorOfValues(), and pandora::XmlHelper::ReadValue().
pandora::TwoDHistogram::TwoDHistogram (const TwoDHistogram & rhs)
Copy constructor.
Parameters
rhs the histogram to copy
Member Function Documentation
void pandora::TwoDHistogram::Fill (const float valueX, const float valueY, const float weight = 1.f)
Add an entry to the histogram.
Parameters
valueX the x value for the entry
valueY the y value for the entry
weight the weight associated with this entry
References GetBinNumberX(), and GetBinNumberY().
float pandora::TwoDHistogram::GetBinContent (const int binX, const int binY) const
Get the content of a specified bin.
Parameters
binX the specified x bin number
binY the specified y bin number
Returns
The content of the specified bin
Referenced by WriteToXml().
int pandora::TwoDHistogram::GetBinNumberX (const float valueX) const
Get the x bin number for a specified x value.
Parameters
valueX the specified x value
Returns
The x bin number
References GetOverflowBinNumberX(), and GetUnderflowBinNumberX().
Referenced by Fill().
int pandora::TwoDHistogram::GetBinNumberY (const float valueY) const
Get the y bin number for a specified value.
Parameters
valueY the specified y value
Returns
The y bin number
References GetOverflowBinNumberY(), and GetUnderflowBinNumberY().
Referenced by Fill().
float pandora::TwoDHistogram::GetCumulativeSum () const inline
Get the cumulative sum of bin entries in the histogram (ignores overflow and underflow bins)
Returns
The cumulative sum
References GetMaxBinNumberX(), GetMaxBinNumberY(), GetMinBinNumberX(), and GetMinBinNumberY().
float pandora::TwoDHistogram::GetCumulativeSum (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin) const
Get the cumulative sum of bin entries in a specified range of the histogram (includes overflow and underflow bins if specified)
Parameters
xLowBin bin at start of specified x range
xHighBin bin at end of specified x range
yLowBin bin at start of specified y range
yHighBin bin at end of specified y range
Returns
The cumulative sum
References GetOverflowBinNumberX(), GetOverflowBinNumberY(), GetUnderflowBinNumberX(), and GetUnderflowBinNumberY().
int pandora::TwoDHistogram::GetMaxBinNumberX () const inline
Get the max x bin number of the histogram (ignores overflow and underflow bins)
Returns
The max x bin number
Referenced by GetCumulativeSum(), GetMaximum(), GetMeanX(), GetMeanY(), GetOverflowBinNumberX(), GetStandardDeviationX(), and GetStandardDeviationY().
int pandora::TwoDHistogram::GetMaxBinNumberY () const inline
Get the max y bin number of the histogram (ignores overflow and underflow bins)
Returns
The max y bin number
Referenced by GetCumulativeSum(), GetMaximum(), GetMeanX(), GetMeanY(), GetOverflowBinNumberY(), GetStandardDeviationX(), and GetStandardDeviationY().
void pandora::TwoDHistogram::GetMaximum (float & maximumValue, int & maximumBinX, int & maximumBinY) const inline
Get the maximum value in the histogram and the corresponding bin numbers (ignores overflow and underflow bins)
Parameters
maximumValue to receive the maximum value
maximumBinX to receive the x coordinate of the bin containing the maximum value
maximumBinY to receive the y coordinate of the bin containing the maximum value
References GetMaxBinNumberX(), GetMaxBinNumberY(), GetMinBinNumberX(), and GetMinBinNumberY().
void pandora::TwoDHistogram::GetMaximum (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin, float & maximumValue, int & maximumBinX, int & maximumBinY) const
Get the maximum value in a specified range of the histogram and the corresponding bin numbers (includes overflow and underflow bins if specified)
Parameters
xLowBin bin at start of specified x range
xHighBin bin at end of specified x range
yLowBin bin at start of specified y range
yHighBin bin at end of specified y range
maximumValue to receive the maximum value
maximumBinX to receive the x coordinate of the bin containing the maximum value
maximumBinY to receive the y coordinate of the bin containing the maximum value
References GetOverflowBinNumberX(), GetOverflowBinNumberY(), GetUnderflowBinNumberX(), and GetUnderflowBinNumberY().
float pandora::TwoDHistogram::GetMeanX () const inline
Get the mean x value of entries in the histogram (ignores overflow and underflow bins)
Returns
The mean x value
References GetMaxBinNumberX(), GetMaxBinNumberY(), GetMinBinNumberX(), and GetMinBinNumberY().
float pandora::TwoDHistogram::GetMeanX (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin) const
Get the mean x value of entries in a specified range of the histogram (ignores overflow and underflow bins)
Parameters
xLowBin bin at start of specified x range
xHighBin bin at end of specified x range
yLowBin bin at start of specified y range
yHighBin bin at end of specified y range
Returns
The mean x value
References GetMaxBinNumberX(), GetMaxBinNumberY(), GetMinBinNumberX(), and GetMinBinNumberY().
float pandora::TwoDHistogram::GetMeanY () const inline
Get the mean y value of entries in the histogram (ignores overflow and underflow bins)
Returns
The mean y value
References GetMaxBinNumberX(), GetMaxBinNumberY(), GetMinBinNumberX(), and GetMinBinNumberY().
float pandora::TwoDHistogram::GetMeanY (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin) const
Get the mean y value of entries in a specified range of the histogram (ignores overflow and underflow bins)
Parameters
xLowBin bin at start of specified x range
xHighBin bin at end of specified x range
yLowBin bin at start of specified y range
yHighBin bin at end of specified y range
Returns
The mean y value
References GetMaxBinNumberX(), GetMaxBinNumberY(), GetMinBinNumberX(), and GetMinBinNumberY().
int pandora::TwoDHistogram::GetMinBinNumberX () const inline
Get the min x bin number of the histogram (ignores overflow and underflow bins)
Returns
The min x bin number
Referenced by GetCumulativeSum(), GetMaximum(), GetMeanX(), GetMeanY(), GetStandardDeviationX(), GetStandardDeviationY(), and GetUnderflowBinNumberX().
int pandora::TwoDHistogram::GetMinBinNumberY () const inline
Get the min y bin number of the histogram (ignores overflow and underflow bins)
Returns
The min y bin number
Referenced by GetCumulativeSum(), GetMaximum(), GetMeanX(), GetMeanY(), GetStandardDeviationX(), GetStandardDeviationY(), and GetUnderflowBinNumberY().
int pandora::TwoDHistogram::GetNBinsX () const inline
Get the number of x bins.
Returns
The number of x bins
int pandora::TwoDHistogram::GetNBinsY () const inline
Get the number of y bins.
Returns
The number of y bins
int pandora::TwoDHistogram::GetOverflowBinNumberX () const inline
Get the overflow x bin number of the histogram.
Returns
The overflow x bin number
References GetMaxBinNumberX().
Referenced by GetBinNumberX(), GetCumulativeSum(), GetMaximum(), SetBinContent(), TwoDHistogram(), and WriteToXml().
int pandora::TwoDHistogram::GetOverflowBinNumberY () const inline
Get the overflow y bin number of the histogram.
Returns
The overflow y bin number
References GetMaxBinNumberY().
Referenced by GetBinNumberY(), GetCumulativeSum(), GetMaximum(), SetBinContent(), TwoDHistogram(), and WriteToXml().
float pandora::TwoDHistogram::GetStandardDeviationX () const inline
Get the standard deviation of x entries in the histogram (ignores overflow and underflow bins)
Returns
The standard deviation of x entries
References GetMaxBinNumberX(), GetMaxBinNumberY(), GetMinBinNumberX(), and GetMinBinNumberY().
float pandora::TwoDHistogram::GetStandardDeviationX (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin) const
Get the standard deviation of x entries in a specified range of the histogram (ignores overflow and underflow bins)
Parameters
xLowBin bin at start of specified x range
xHighBin bin at end of specified x range
yLowBin bin at start of specified y range
yHighBin bin at end of specified y range
Returns
The standard deviation of x entries
References GetMaxBinNumberX(), GetMaxBinNumberY(), GetMinBinNumberX(), and GetMinBinNumberY().
float pandora::TwoDHistogram::GetStandardDeviationY () const inline
Get the standard deviation of y entries in the histogram (ignores overflow and underflow bins)
Returns
The standard deviation of y entries
References GetMaxBinNumberX(), GetMaxBinNumberY(), GetMinBinNumberX(), and GetMinBinNumberY().
float pandora::TwoDHistogram::GetStandardDeviationY (const int xLowBin, const int xHighBin, const int yLowBin, const int yHighBin) const
Get the standard deviation of y entries in a specified range of the histogram (ignores overflow and underflow bins)
Parameters
xLowBin bin at start of specified x range
xHighBin bin at end of specified x range
yLowBin bin at start of specified y range
yHighBin bin at end of specified y range
Returns
The standard deviation of y entries
References GetMaxBinNumberX(), GetMaxBinNumberY(), GetMinBinNumberX(), and GetMinBinNumberY().
int pandora::TwoDHistogram::GetUnderflowBinNumberX () const inline
Get the underflow x bin number of the histogram.
Returns
The underflow x bin number
References GetMinBinNumberX().
Referenced by GetBinNumberX(), GetCumulativeSum(), GetMaximum(), SetBinContent(), TwoDHistogram(), and WriteToXml().
int pandora::TwoDHistogram::GetUnderflowBinNumberY () const inline
Get the underflow y bin number of the histogram.
Returns
The underflow y bin number
References GetMinBinNumberY().
Referenced by GetBinNumberY(), GetCumulativeSum(), GetMaximum(), SetBinContent(), TwoDHistogram(), and WriteToXml().
float pandora::TwoDHistogram::GetXBinWidth () const inline
Get the x bin width.
Returns
The x bin width
float pandora::TwoDHistogram::GetXHigh () const inline
Get the max binned x value.
Returns
The max binned x value
float pandora::TwoDHistogram::GetXLow () const inline
Get the min binned x value.
Returns
The min binned x value
float pandora::TwoDHistogram::GetYBinWidth () const inline
Get the y bin width.
Returns
The y bin width
float pandora::TwoDHistogram::GetYHigh () const inline
Get the max binned y value.
Returns
The max binned y value
float pandora::TwoDHistogram::GetYLow () const inline
Get the min binned y value.
Returns
The min binned y value
void pandora::TwoDHistogram::Scale (const float scaleFactor)
Scale contents of all histogram bins by a specified factor.
Parameters
scaleFactor the scale factor
void pandora::TwoDHistogram::SetBinContent (const int binX, const int binY, const float value)
Set the contents of a specified bin.
Parameters
binX the specified x bin number
binY the specified y bin number
value the new value for the specified bin
References GetOverflowBinNumberX(), GetOverflowBinNumberY(), GetUnderflowBinNumberX(), and GetUnderflowBinNumberY().
void pandora::TwoDHistogram::WriteToXml (TiXmlDocument *const pTiXmlDocument, const std::string & xmlElementName) const
Write the histogram to an xml document.
Parameters
pTiXmlDocument address of the xml document
xmlElementName the xml element name for the histogram
References GetBinContent(), GetOverflowBinNumberX(), GetOverflowBinNumberY(), GetUnderflowBinNumberX(), GetUnderflowBinNumberY(), and pandora::TiXmlNode::LinkEndChild().
The documentation for this class was generated from the following files:
Histograms.h
Histograms.cc