PandoraSDK: pandora::Pandora Class Reference
pandora::Pandora Class Reference
Pandora class.
#include <Pandora.h>
Public Member Functions
Pandora ()
Default constructor.
~Pandora ()
Destructor.
const PandoraApiImpl * GetPandoraApiImpl () const
Get the pandora api impl.
const PandoraContentApiImpl * GetPandoraContentApiImpl () const
Get the pandora content api impl.
const PandoraSettings * GetSettings () const
Get the pandora settings instance.
const GeometryManager * GetGeometry () const
Get the pandora geometry instance.
const PluginManager * GetPlugins () const
Get the pandora plugin instance, providing access to user registered functions and calculators.
Friends
class PandoraApiImpl
class PandoraContentApiImpl
class PandoraImpl
Detailed Description
Pandora class.
Member Function Documentation
const GeometryManager * pandora::Pandora::GetGeometry () const
Get the pandora geometry instance.
Returns
the address of the pandora geometry instance
const PandoraApiImpl * pandora::Pandora::GetPandoraApiImpl () const
Get the pandora api impl.
Returns
Address of the pandora api impl
Referenced by PandoraApi::ObjectCreationHelper< PARAMETERS, OBJECT >::Create(), PandoraApi::GetCurrentPfoList(), PandoraApi::GetPfoList(), PandoraApi::ProcessEvent(), PandoraApi::ReadSettings(), PandoraApi::RegisterAlgorithmFactory(), PandoraApi::RegisterAlgorithmToolFactory(), PandoraApi::RegisterEnergyCorrectionPlugin(), PandoraApi::RegisterParticleIdPlugin(), PandoraApi::Reset(), PandoraApi::SetBFieldPlugin(), PandoraApi::SetCaloHitToMCParticleRelationship(), PandoraApi::SetHitTypeGranularity(), PandoraApi::SetMCParentDaughterRelationship(), PandoraApi::SetPseudoLayerPlugin(), PandoraApi::SetShowerProfilePlugin(), PandoraApi::SetTrackParentDaughterRelationship(), PandoraApi::SetTrackSiblingRelationship(), and PandoraApi::SetTrackToMCParticleRelationship().
const PandoraContentApiImpl * pandora::Pandora::GetPandoraContentApiImpl () const
Get the pandora content api impl.
Returns
Address of the pandora content api impl
Referenced by PandoraContentApi::AddIsolatedToCluster(), PandoraContentApi::AddToCluster(), PandoraContentApi::AddToPfo(), PandoraContentApi::AddTrackClusterAssociation(), PandoraContentApi::AlterMetadata(), PandoraContentApi::ObjectCreationHelper< PARAMETERS, METADATA, OBJECT >::Create(), PandoraContentApi::CreateAlgorithmTool(), PandoraContentApi::CreateDaughterAlgorithm(), PandoraContentApi::CreateTemporaryListAndSetCurrent(), PandoraContentApi::Delete(), PandoraContentApi::DropCurrentList(), PandoraContentApi::EndFragmentation(), PandoraContentApi::EndReclustering(), PandoraContentApi::Fragment(), PandoraContentApi::GetCurrentList(), PandoraContentApi::GetCurrentListName(), PandoraContentApi::GetGeometry(), PandoraContentApi::GetList(), PandoraContentApi::GetPlugins(), PandoraContentApi::GetSettings(), PandoraContentApi::InitializeFragmentation(), PandoraContentApi::InitializeReclustering(), PandoraContentApi::IsAvailable(), PandoraContentApi::MergeAndDeleteClusters(), PandoraContentApi::MergeFragments(), PandoraContentApi::RemoveAllMCParticleRelationships(), PandoraContentApi::RemoveAllTrackClusterAssociations(), PandoraContentApi::RemoveCurrentTrackClusterAssociations(), PandoraContentApi::RemoveFromCluster(), PandoraContentApi::RemoveFromPfo(), PandoraContentApi::RemoveIsolatedFromCluster(), PandoraContentApi::RemovePfoParentDaughterRelationship(), PandoraContentApi::RemoveTrackClusterAssociation(), PandoraContentApi::RepeatEventPreparation(), PandoraContentApi::ReplaceCurrentList(), PandoraContentApi::RunClusteringAlgorithm(), PandoraContentApi::RunDaughterAlgorithm(), PandoraContentApi::SaveList(), PandoraContentApi::SetPfoParentDaughterRelationship(), and PandoraContentApi::TemporarilyReplaceCurrentList().
const PluginManager * pandora::Pandora::GetPlugins () const
Get the pandora plugin instance, providing access to user registered functions and calculators.
Returns
the address of the pandora plugin instance
Referenced by pandora::Cluster::CalculateFastPhotonFlag(), pandora::Cluster::CalculateShowerProfile(), pandora::Cluster::CalculateShowerStartLayer(), and pandora::Cluster::PerformEnergyCorrections().
const PandoraSettings * pandora::Pandora::GetSettings () const
Get the pandora settings instance.
Returns
the address of the pandora settings instance
The documentation for this class was generated from the following files:
Pandora.h
Pandora.cc