PandoraSDK: pandora::FileWriter Class Reference
pandora::FileWriter Class Reference abstract
FileWriter class.
#include <FileWriter.h>
Public Member Functions
FileWriter (const pandora::Pandora &pandora, const std::string &fileName)
Constructor.
virtual ~FileWriter ()
Destructor.
StatusCode WriteGeometry ()
Write the current geometry information to the file.
StatusCode WriteEvent (const CaloHitList &caloHitList, const TrackList &trackList, const MCParticleList &mcParticleList, const bool writeMCRelationships=true, const bool writeTrackRelationships=true)
Write the specified event components to the file.
Public Member Functions inherited from pandora::Persistency
Persistency (const pandora::Pandora &pandora, const std::string &fileName)
Constructor.
virtual ~Persistency ()
Destructor.
const std::string & GetFileName () const
Get the file name.
FileType GetFileType () const
Get the file type.
template<typename PARAMETERS , typename OBJECT >
StatusCode SetFactory (ObjectFactory< PARAMETERS, OBJECT > *const pFactory)
Set the factory to use for all instantiations and parameter persistence.
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::CaloHit::Parameters, CaloHit > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::Track::Parameters, Track > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::MCParticle::Parameters, MCParticle > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::Geometry::SubDetector::Parameters, SubDetector > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::Geometry::LineGap::Parameters, LineGap > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::Geometry::BoxGap::Parameters, BoxGap > *const pFactory)
template<>
void ReplaceCurrentFactory (ObjectFactory< PandoraApi::Geometry::ConcentricGap::Parameters, ConcentricGap > *const pFactory)
Protected Member Functions
virtual StatusCode WriteHeader (const ContainerId containerId)=0
Write the container header to the file.
virtual StatusCode WriteFooter ()=0
Write the container footer to the file.
virtual StatusCode WriteSubDetector (const SubDetector *const pSubDetector)=0
Write a sub detector to the current position in the file.
virtual StatusCode WriteDetectorGap (const DetectorGap *const pDetectorGap)=0
Write the detector gap parameters to the file.
virtual StatusCode WriteCaloHit (const CaloHit *const pCaloHit)=0
Write a calo hit to the current position in the file.
virtual StatusCode WriteTrack (const Track *const pTrack)=0
Write a track to the current position in the file.
virtual StatusCode WriteMCParticle (const MCParticle *const pMCParticle)=0
Write a mc particle to the current position in the file.
virtual StatusCode WriteRelationship (const RelationshipId relationshipId, const void *address1, const void *address2, const float weight=1.f)=0
Write a relationship between two objects with specified addresses.
Protected Member Functions inherited from pandora::Persistency
template<typename PARAMETERS , typename OBJECT >
void ReplaceCurrentFactory (ObjectFactory< PARAMETERS, OBJECT > *const pFactory)
Replace the current factory with the provided instance.
Additional Inherited Members
Protected Attributes inherited from pandora::Persistency
const Pandora *const m_pPandora
Address of pandora instance to be used alongside the file writer.
std::string m_fileName
The file name.
FileType m_fileType
The file type.
ContainerId m_containerId
The type of container currently being written to file.
ObjectFactory
< PandoraApi::CaloHit::Parameters,
CaloHit > * m_pCaloHitFactory
Address of the calo hit factory.
ObjectFactory
< PandoraApi::Track::Parameters,
Track > * m_pTrackFactory
Address of the track factory.
ObjectFactory
< PandoraApi::MCParticle::Parameters,
MCParticle > * m_pMCParticleFactory
Address of the mc particle factory.
ObjectFactory
< PandoraApi::Geometry::SubDetector::Parameters,
SubDetector > * m_pSubDetectorFactory
Address of the sub detector factory.
ObjectFactory
< PandoraApi::Geometry::LineGap::Parameters,
LineGap > * m_pLineGapFactory
Address of the line gap factory.
ObjectFactory
< PandoraApi::Geometry::BoxGap::Parameters,
BoxGap > * m_pBoxGapFactory
Address of the box gap factory.
ObjectFactory
< PandoraApi::Geometry::ConcentricGap::Parameters,
ConcentricGap > * m_pConcentricGapFactory
Address of the concentric gap factory.
Detailed Description
FileWriter class.
Constructor & Destructor Documentation
pandora::FileWriter::FileWriter (const pandora::Pandora & pandora, const std::string & fileName)
Constructor.
Parameters
algorithm the pandora instance to be used alongside the file writer
fileName the name of the output file
fileMode the mode for file writing
Member Function Documentation
virtual StatusCode pandora::FileWriter::WriteCaloHit (const CaloHit *const pCaloHit) protected pure virtual
Write a calo hit to the current position in the file.
Parameters
pCaloHit address of the calo hit
virtual StatusCode pandora::FileWriter::WriteDetectorGap (const DetectorGap *const pDetectorGap) protected pure virtual
Write the detector gap parameters to the file.
Parameters
pDetectorGap address of the detector gap
StatusCode pandora::FileWriter::WriteEvent (const CaloHitList & caloHitList, const TrackList & trackList, const MCParticleList & mcParticleList, const bool writeMCRelationships = true, const bool writeTrackRelationships = true)
Write the specified event components to the file.
Parameters
caloHitList the list of calo hits to write to the file
trackList the list of tracks to write to the file
mcParticleList the list of mc particles to write to the file
writeMCRelationships whether to write mc relationship information to the file
writeTrackRelationships whether to write track relationship information to the file
References WriteFooter(), and WriteHeader().
virtual StatusCode pandora::FileWriter::WriteHeader (const ContainerId containerId) protected pure virtual
Write the container header to the file.
Parameters
containerId the container id
Referenced by WriteEvent(), and WriteGeometry().
virtual StatusCode pandora::FileWriter::WriteMCParticle (const MCParticle *const pMCParticle) protected pure virtual
Write a mc particle to the current position in the file.
Parameters
pMCParticle address of the mc particle
virtual StatusCode pandora::FileWriter::WriteRelationship (const RelationshipId relationshipId, const void * address1, const void * address2, const float weight = 1.f) protected pure virtual
Write a relationship between two objects with specified addresses.
Parameters
relationshipId the relationship id
address1 first address to write
address2 second address to write
virtual StatusCode pandora::FileWriter::WriteSubDetector (const SubDetector *const pSubDetector) protected pure virtual
Write a sub detector to the current position in the file.
Parameters
subDetectorName the sub detector name
pSubDetector address of the sub detector
virtual StatusCode pandora::FileWriter::WriteTrack (const Track *const pTrack) protected pure virtual
Write a track to the current position in the file.
Parameters
pTrack address of the track
The documentation for this class was generated from the following files:
FileWriter.h
FileWriter.cc