PandoraSDK: pandora::XmlHelper Class Reference
pandora::XmlHelper Class Reference
XmlHelper class.
#include <XmlHelper.h>
Public Member Functions
template<>
StatusCode ReadValue (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, CartesianVector &t)
template<>
StatusCode ReadValue (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, TrackState &t)
template<>
StatusCode ReadValue (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, bool &t)
Static Public Member Functions
template<typename T >
static StatusCode ReadValue (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, T &t)
Read a value from an xml element.
template<typename T >
static StatusCode ReadVectorOfValues (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, std::vector< T > &vector)
Read a vector of values from a (space separated) list in an xml element.
template<typename T >
static StatusCode Read2DVectorOfValues (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, const std::string &rowName, std::vector< std::vector< T > > &vector)
Read a two-dimensional array of values into a vector of vectors.
static StatusCode ProcessAlgorithm (const Algorithm &algorithm, const TiXmlHandle &xmlHandle, const std::string &description, std::string &algorithmName)
Process an algorithm described in an xml element with a matching "description = ..." attribute.
static StatusCode ProcessFirstAlgorithm (const Algorithm &algorithm, const TiXmlHandle &xmlHandle, std::string &algorithmName)
Process a single algorithm described in an xml file (the first found by the xml handle)
static StatusCode ProcessAlgorithmList (const Algorithm &algorithm, const TiXmlHandle &xmlHandle, const std::string &listName, StringVector &algorithmNames)
Process a list of daughter algorithms in an xml file.
static StatusCode ProcessAlgorithmTool (const Algorithm &algorithm, const TiXmlHandle &xmlHandle, const std::string &description, AlgorithmTool *&pAlgorithmTool)
Process an algorithm tool described in an xml element with a matching "description = ..." attribute.
static StatusCode ProcessFirstAlgorithmTool (const Algorithm &algorithm, const TiXmlHandle &xmlHandle, AlgorithmTool *&pAlgorithmTool)
Process a single algorithm tool described in an xml file (the first found by the xml handle)
static StatusCode ProcessAlgorithmToolList (const Algorithm &algorithm, const TiXmlHandle &xmlHandle, const std::string &listName, AlgorithmToolList &algorithmToolList)
Process a list of algorithms tools in an xml file.
static void TokenizeString (const std::string &inputString, StringVector &tokens, const std::string &delimiter=" ")
Tokenize a string.
Detailed Description
XmlHelper class.
Member Function Documentation
StatusCode pandora::XmlHelper::ProcessAlgorithm (const Algorithm & algorithm, const TiXmlHandle & xmlHandle, const std::string & description, std::string & algorithmName) static
Process an algorithm described in an xml element with a matching "description = ..." attribute.
Parameters
algorithm the parent algorithm calling this function
xmlHandle the relevant xml handle
description the description attribute of the algorithm xml element
algorithmName to receive the name of the algorithm instance
References PandoraContentApi::CreateDaughterAlgorithm(), pandora::TiXmlHandle::Element(), pandora::TiXmlHandle::FirstChild(), pandora::TiXmlNode::NextSiblingElement(), pandora::TiXmlHandle::ToNode(), and pandora::TiXmlNode::ValueStr().
Referenced by ProcessFirstAlgorithm().
StatusCode pandora::XmlHelper::ProcessAlgorithmList (const Algorithm & algorithm, const TiXmlHandle & xmlHandle, const std::string & listName, StringVector & algorithmNames) static
Process a list of daughter algorithms in an xml file.
Parameters
algorithm the parent algorithm calling this function
xmlHandle the relevant xml handle
listName the name of the algorithm list
algorithmNames to receive the names of the algorithm instances
References PandoraContentApi::CreateDaughterAlgorithm(), pandora::TiXmlHandle::Element(), pandora::TiXmlHandle::FirstChild(), pandora::TiXmlNode::NextSiblingElement(), pandora::TiXmlHandle::ToNode(), and pandora::TiXmlNode::ValueStr().
StatusCode pandora::XmlHelper::ProcessAlgorithmTool (const Algorithm & algorithm, const TiXmlHandle & xmlHandle, const std::string & description, AlgorithmTool *& pAlgorithmTool) static
Process an algorithm tool described in an xml element with a matching "description = ..." attribute.
Parameters
algorithm the parent algorithm calling this function
xmlHandle the relevant xml handle
description the description attribute of the algorithm tool xml element
pAlgorithmTool to receive the address of the algorithm tool instance
References PandoraContentApi::CreateAlgorithmTool(), pandora::TiXmlHandle::Element(), pandora::TiXmlHandle::FirstChild(), pandora::TiXmlNode::NextSiblingElement(), pandora::TiXmlHandle::ToNode(), and pandora::TiXmlNode::ValueStr().
Referenced by ProcessFirstAlgorithmTool().
StatusCode pandora::XmlHelper::ProcessAlgorithmToolList (const Algorithm & algorithm, const TiXmlHandle & xmlHandle, const std::string & listName, AlgorithmToolList & algorithmToolList) static
Process a list of algorithms tools in an xml file.
Parameters
algorithm the parent algorithm calling this function
xmlHandle the relevant xml handle
listName the name of the algorithm tool list
algorithmToolList to receive the list of addresses of the algorithm tool instances
References PandoraContentApi::CreateAlgorithmTool(), pandora::TiXmlHandle::Element(), pandora::TiXmlHandle::FirstChild(), pandora::TiXmlNode::NextSiblingElement(), pandora::TiXmlHandle::ToNode(), and pandora::TiXmlNode::ValueStr().
StatusCode pandora::XmlHelper::ProcessFirstAlgorithm (const Algorithm & algorithm, const TiXmlHandle & xmlHandle, std::string & algorithmName) inline static
Process a single algorithm described in an xml file (the first found by the xml handle)
Parameters
algorithm the parent algorithm calling this function
xmlHandle the relevant xml handle
algorithmName to receive the name of the algorithm instance
References ProcessAlgorithm().
StatusCode pandora::XmlHelper::ProcessFirstAlgorithmTool (const Algorithm & algorithm, const TiXmlHandle & xmlHandle, AlgorithmTool *& pAlgorithmTool) inline static
Process a single algorithm tool described in an xml file (the first found by the xml handle)
Parameters
algorithm the parent algorithm calling this function
xmlHandle the relevant xml handle
pAlgorithmTool to receive the address of the algorithm tool instance
References ProcessAlgorithmTool().
template<typename T > StatusCode pandora::XmlHelper::Read2DVectorOfValues (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, const std::string & rowName, std::vector< std::vector< T > > & vector) inline static
Read a two-dimensional array of values into a vector of vectors.
Each row of values must be contained within <rowname></rowname> xml tags, whilst the values in the row must be space separated
Parameters
xmlHandle the relevant xml handle
xmlElementName the name of the xml element to examine
rowName the row name
vector to receive the 2d vector of values
References pandora::TiXmlHandle::Element(), pandora::TiXmlHandle::FirstChild(), pandora::TiXmlElement::GetText(), pandora::TiXmlNode::NextSiblingElement(), and TokenizeString().
Referenced by pandora::TwoDHistogram::TwoDHistogram().
template<typename T > StatusCode pandora::XmlHelper::ReadValue (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, T & t) inline static
Read a value from an xml element.
Parameters
xmlHandle the relevant xml handle
xmlElementName the name of the xml element to examine
t to receive the value
References pandora::TiXmlHandle::Element(), pandora::TiXmlHandle::FirstChild(), and pandora::TiXmlElement::GetText().
Referenced by pandora::Histogram::Histogram(), pandora::XmlFileReader::ReadVariable(), and pandora::TwoDHistogram::TwoDHistogram().
template<typename T > StatusCode pandora::XmlHelper::ReadVectorOfValues (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, std::vector< T > & vector) inline static
Read a vector of values from a (space separated) list in an xml element.
Parameters
xmlHandle the relevant xml handle
xmlElementName the name of the xml element to examine
vector to receive the vector of values
References pandora::TiXmlHandle::Element(), pandora::TiXmlHandle::FirstChild(), pandora::TiXmlElement::GetText(), and TokenizeString().
Referenced by pandora::Histogram::Histogram().
void pandora::XmlHelper::TokenizeString (const std::string & inputString, StringVector & tokens, const std::string & delimiter = " ") static
Tokenize a string.
Parameters
inputString the input string
tokens to receive the resulting tokens
delimiter the specified delimeter
Referenced by Read2DVectorOfValues(), and ReadVectorOfValues().
The documentation for this class was generated from the following files:
XmlHelper.h
XmlHelper.cc