PandoraSDK: pandora::ParticleId Class Reference
pandora::ParticleId Class Reference
ParticleId class.
#include <ParticleIdPlugin.h>
Public Member Functions
bool IsEmShower (const Cluster *const pCluster) const
Provide identification of whether a cluster is an electromagnetic shower.
bool IsPhoton (const Cluster *const pCluster) const
Provide identification of whether a cluster is a photon.
bool IsElectron (const Cluster *const pCluster) const
Provide identification of whether a cluster is an electron.
bool IsMuon (const Cluster *const pCluster) const
Provide identification of whether a cluster is a muon.
Friends
class PandoraApiImpl
class PluginManager
Detailed Description
ParticleId class.
Member Function Documentation
bool pandora::ParticleId::IsElectron (const Cluster *const pCluster) const
Provide identification of whether a cluster is an electron.
Parameters
pCluster address of the cluster
Returns
boolean
References pandora::Cluster::GetParticleIdFlag(), and pandora::ParticleIdPlugin::IsMatch().
bool pandora::ParticleId::IsEmShower (const Cluster *const pCluster) const
Provide identification of whether a cluster is an electromagnetic shower.
Parameters
pCluster address of the cluster
Returns
boolean
References pandora::ParticleIdPlugin::IsMatch().
bool pandora::ParticleId::IsMuon (const Cluster *const pCluster) const
Provide identification of whether a cluster is a muon.
Parameters
pCluster address of the cluster
Returns
boolean
References pandora::Cluster::GetParticleIdFlag(), and pandora::ParticleIdPlugin::IsMatch().
bool pandora::ParticleId::IsPhoton (const Cluster *const pCluster) const
Provide identification of whether a cluster is a photon.
Parameters
pCluster address of the cluster
Returns
boolean
References pandora::Cluster::GetParticleIdFlag(), and pandora::ParticleIdPlugin::IsMatch().
Referenced by pandora::Cluster::CalculateFastPhotonFlag().
The documentation for this class was generated from the following files:
ParticleIdPlugin.h
ParticleIdPlugin.cc