PandoraSDK: pandora::Histogram Class Reference
pandora::Histogram Class Reference
Histogram class.
#include <Histograms.h>
Public Member Functions
Histogram (const unsigned int nBinsX, const float xLow, const float xHigh)
Constructor.
Histogram (const TiXmlHandle *const pXmlHandle, const std::string &xmlElementName)
Constructor.
Histogram (const Histogram &rhs)
Copy constructor.
int GetNBinsX () const
Get the number of x bins.
float GetXLow () const
Get the min binned x value.
float GetXHigh () const
Get the max binned x value.
float GetXBinWidth () const
Get the x bin width.
float GetBinContent (const int binX) const
Get the content of a specified bin.
int GetBinNumber (const float valueX) const
Get the bin number for a specified value.
int GetMinBinNumber () const
Get the min bin number of the histogram (ignores overflow and underflow bins)
int GetMaxBinNumber () const
Get the max bin number of the histogram (ignores overflow and underflow bins)
int GetUnderflowBinNumber () const
Get the underflow bin number of the histogram.
int GetOverflowBinNumber () const
Get the overflow bin number of the histogram.
float GetCumulativeSum () const
Get the cumulative sum of bin entries in the histogram (ignores overflow and underflow bins)
float GetCumulativeSum (const int xLowBin, const int xHighBin) const
Get the cumulative sum of bin entries in a specified range of the histogram (includes overflow and underflow bins if specified)
void GetMaximum (float &maximumValue, int &maximumBinX) const
Get the maximum value in the histogram and the corresponding bin number (ignores overflow and underflow bins)
void GetMaximum (const int xLowBin, const int xHighBin, float &maximumValue, int &maximumBinX) const
Get the maximum value in a specified range of the histogram and the corresponding bin numbers (includes overflow and underflow bins if specified)
float GetMeanX () const
Get the mean x value of entries in the histogram (ignores overflow and underflow bins)
float GetMeanX (const int xLowBin, const int xHighBin) const
Get the mean x value of entries in a specified range of the histogram (ignores overflow and underflow bins)
float GetStandardDeviationX () const
Get the standard deviation of entries in the histogram (ignores overflow and underflow bins)
float GetStandardDeviationX (const int xLowBin, const int xHighBin) const
Get the standard deviation of x entries in a specified range of the histogram (ignores overflow and underflow bins)
void SetBinContent (const int binX, const float value)
Set the contents of a specified bin.
void Fill (const float valueX, const float weight=1.f)
Add an entry to the histogram.
void Scale (const float scaleFactor)
Scale contents of all histogram bins by a specified factor.
void WriteToXml (TiXmlDocument *const pTiXmlDocument, const std::string &xmlElementName) const
Write the histogram to an xml document.
Detailed Description
Histogram class.
Constructor & Destructor Documentation
pandora::Histogram::Histogram (const unsigned int nBinsX, const float xLow, const float xHigh)
Constructor.
Parameters
nBinsX number of x bins
xLow min binned x value
xHigh max binned x value
pandora::Histogram::Histogram (const TiXmlHandle *const pXmlHandle, const std::string & xmlElementName)
Constructor.
Parameters
pXmlHandle address of the handle for the xml element describing the histogram
xmlElementName the xml element name for the histogram
References pandora::TiXmlHandle::Element(), pandora::TiXmlHandle::FirstChild(), GetOverflowBinNumber(), GetUnderflowBinNumber(), pandora::XmlHelper::ReadValue(), and pandora::XmlHelper::ReadVectorOfValues().
pandora::Histogram::Histogram (const Histogram & rhs)
Copy constructor.
Parameters
rhs the histogram to copy
Member Function Documentation
void pandora::Histogram::Fill (const float valueX, const float weight = 1.f)
Add an entry to the histogram.
Parameters
valueX the value for the entry
weight the weight associated with this entry
References GetBinNumber().
float pandora::Histogram::GetBinContent (const int binX) const
Get the content of a specified bin.
Parameters
binX the specified bin number
Returns
The content of the specified bin
Referenced by WriteToXml().
int pandora::Histogram::GetBinNumber (const float valueX) const
Get the bin number for a specified value.
Parameters
valueX the specified value
Returns
The bin number
References GetOverflowBinNumber(), and GetUnderflowBinNumber().
Referenced by Fill().
float pandora::Histogram::GetCumulativeSum () const inline
Get the cumulative sum of bin entries in the histogram (ignores overflow and underflow bins)
Returns
The cumulative sum
References GetMaxBinNumber(), and GetMinBinNumber().
float pandora::Histogram::GetCumulativeSum (const int xLowBin, const int xHighBin) const
Get the cumulative sum of bin entries in a specified range of the histogram (includes overflow and underflow bins if specified)
Parameters
xLowBin bin at start of specified x range
xHighBin bin at end of specified x range
Returns
The cumulative sum
References GetOverflowBinNumber(), and GetUnderflowBinNumber().
int pandora::Histogram::GetMaxBinNumber () const inline
Get the max bin number of the histogram (ignores overflow and underflow bins)
Returns
The max bin number
Referenced by GetCumulativeSum(), GetMaximum(), GetMeanX(), GetOverflowBinNumber(), and GetStandardDeviationX().
void pandora::Histogram::GetMaximum (float & maximumValue, int & maximumBinX) const inline
Get the maximum value in the histogram and the corresponding bin number (ignores overflow and underflow bins)
Parameters
maximumValue to receive the maximum value
maximumBinX to receive the coordinate of the bin containing the maximum value
References GetMaxBinNumber(), and GetMinBinNumber().
void pandora::Histogram::GetMaximum (const int xLowBin, const int xHighBin, float & maximumValue, int & maximumBinX) const
Get the maximum value in a specified range of the histogram and the corresponding bin numbers (includes overflow and underflow bins if specified)
Parameters
xLowBin bin at start of specified x range
xHighBin bin at end of specified x range
maximumValue to receive the maximum value
maximumBinX to receive the coordinate of the bin containing the maximum value
References GetOverflowBinNumber(), and GetUnderflowBinNumber().
float pandora::Histogram::GetMeanX () const inline
Get the mean x value of entries in the histogram (ignores overflow and underflow bins)
Returns
The mean x value
References GetMaxBinNumber(), and GetMinBinNumber().
float pandora::Histogram::GetMeanX (const int xLowBin, const int xHighBin) const
Get the mean x value of entries in a specified range of the histogram (ignores overflow and underflow bins)
Parameters
xLowBin bin at start of specified x range
xHighBin bin at end of specified x range
Returns
The mean x value
References GetMaxBinNumber(), and GetMinBinNumber().
int pandora::Histogram::GetMinBinNumber () const inline
Get the min bin number of the histogram (ignores overflow and underflow bins)
Returns
The min bin number
Referenced by GetCumulativeSum(), GetMaximum(), GetMeanX(), GetStandardDeviationX(), and GetUnderflowBinNumber().
int pandora::Histogram::GetNBinsX () const inline
Get the number of x bins.
Returns
The number of x bins
int pandora::Histogram::GetOverflowBinNumber () const inline
Get the overflow bin number of the histogram.
Returns
The overflow bin number
References GetMaxBinNumber().
Referenced by GetBinNumber(), GetCumulativeSum(), GetMaximum(), Histogram(), SetBinContent(), and WriteToXml().
float pandora::Histogram::GetStandardDeviationX () const inline
Get the standard deviation of entries in the histogram (ignores overflow and underflow bins)
Returns
The standard deviation of x entries
References GetMaxBinNumber(), and GetMinBinNumber().
float pandora::Histogram::GetStandardDeviationX (const int xLowBin, const int xHighBin) const
Get the standard deviation of x entries in a specified range of the histogram (ignores overflow and underflow bins)
Parameters
xLowBin bin at start of specified x range
xHighBin bin at end of specified x range
Returns
The standard deviation of x entries
References GetMaxBinNumber(), and GetMinBinNumber().
int pandora::Histogram::GetUnderflowBinNumber () const inline
Get the underflow bin number of the histogram.
Returns
The underflow bin number
References GetMinBinNumber().
Referenced by GetBinNumber(), GetCumulativeSum(), GetMaximum(), Histogram(), SetBinContent(), and WriteToXml().
float pandora::Histogram::GetXBinWidth () const inline
Get the x bin width.
Returns
The x bin width
float pandora::Histogram::GetXHigh () const inline
Get the max binned x value.
Returns
The max binned x value
float pandora::Histogram::GetXLow () const inline
Get the min binned x value.
Returns
The min binned x value
void pandora::Histogram::Scale (const float scaleFactor)
Scale contents of all histogram bins by a specified factor.
Parameters
scaleFactor the scale factor
void pandora::Histogram::SetBinContent (const int binX, const float value)
Set the contents of a specified bin.
Parameters
binX the specified bin number
value the new value for the specified bin
References GetOverflowBinNumber(), and GetUnderflowBinNumber().
void pandora::Histogram::WriteToXml (TiXmlDocument *const pTiXmlDocument, const std::string & xmlElementName) const
Write the histogram to an xml document.
Parameters
pTiXmlDocument address of the xml document
xmlElementName the xml element name for the histogram
References GetBinContent(), GetOverflowBinNumber(), GetUnderflowBinNumber(), and pandora::TiXmlNode::LinkEndChild().
The documentation for this class was generated from the following files:
Histograms.h
Histograms.cc