PandoraSDK: pandora::ConcentricGap Class Reference
pandora::ConcentricGap Class Reference
ConcentricGap class, associated with all 3D hit types.
#include <DetectorGap.h>
Public Member Functions
bool IsInGap (const CartesianVector &positionVector, const HitType hitType, const float gapTolerance) const
Whether a specified position lies within the gap.
float GetMinZCoordinate () const
Get the min cylindrical polar z coordinate, origin interaction point.
float GetMaxZCoordinate () const
Get the max cylindrical polar z coordinate, origin interaction point.
float GetInnerRCoordinate () const
Get the inner cylindrical polar r coordinate, origin interaction point.
float GetInnerPhiCoordinate () const
Get the inner cylindrical polar phi coordinate.
unsigned int GetInnerSymmetryOrder () const
Get the order of symmetry of the innermost edge of gap.
float GetOuterRCoordinate () const
Get the outer cylindrical polar r coordinate, origin interaction point.
float GetOuterPhiCoordinate () const
Get the outer cylindrical polar phi coordinate.
unsigned int GetOuterSymmetryOrder () const
Get the order of symmetry of the outermost edge of gap.
Public Member Functions inherited from pandora::DetectorGap
virtual ~DetectorGap ()
Destructor.
Friends
class PandoraObjectFactory< PandoraApi::Geometry::ConcentricGap::Parameters, ConcentricGap >
Detailed Description
ConcentricGap class, associated with all 3D hit types.
Member Function Documentation
float pandora::ConcentricGap::GetInnerPhiCoordinate () const inline
Get the inner cylindrical polar phi coordinate.
Parameters
the inner cylindrical polar phi coordinate
float pandora::ConcentricGap::GetInnerRCoordinate () const inline
Get the inner cylindrical polar r coordinate, origin interaction point.
Parameters
the inner cylindrical polar r coordinate
unsigned int pandora::ConcentricGap::GetInnerSymmetryOrder () const inline
Get the order of symmetry of the innermost edge of gap.
Parameters
the order of symmetry of the innermost edge of gap
float pandora::ConcentricGap::GetMaxZCoordinate () const inline
Get the max cylindrical polar z coordinate, origin interaction point.
Parameters
the max cylindrical polar z coordinate
float pandora::ConcentricGap::GetMinZCoordinate () const inline
Get the min cylindrical polar z coordinate, origin interaction point.
Parameters
the min cylindrical polar z coordinate
float pandora::ConcentricGap::GetOuterPhiCoordinate () const inline
Get the outer cylindrical polar phi coordinate.
Parameters
the outer cylindrical polar phi coordinate
float pandora::ConcentricGap::GetOuterRCoordinate () const inline
Get the outer cylindrical polar r coordinate, origin interaction point.
Parameters
the outer cylindrical polar r coordinate
unsigned int pandora::ConcentricGap::GetOuterSymmetryOrder () const inline
Get the order of symmetry of the outermost edge of gap.
Parameters
the order of symmetry of the outermost edge of gap
bool pandora::ConcentricGap::IsInGap (const CartesianVector & positionVector, const HitType hitType, const float gapTolerance) const virtual
Whether a specified position lies within the gap.
Parameters
positionVector the position vector
hitType the hit type, providing context to aid interpretation of provided position vector
gapTolerance tolerance allowed when declaring a point to be "in" a gap region, units mm
Returns
boolean
Implements pandora::DetectorGap.
References pandora::CartesianVector::GetX(), pandora::CartesianVector::GetY(), and pandora::CartesianVector::GetZ().
The documentation for this class was generated from the following files:
DetectorGap.h
DetectorGap.cc