PandoraSDK: pandora::OrderedCaloHitList Class Reference
pandora::OrderedCaloHitList Class Reference
Calo hit lists arranged by pseudo layer.
#include <OrderedCaloHitList.h>
Public Types
typedef std::map< unsigned int,
CaloHitList * > TheList
typedef TheList::const_iterator const_iterator
typedef
TheList::const_reverse_iterator const_reverse_iterator
Public Member Functions
OrderedCaloHitList ()
Default constructor.
OrderedCaloHitList (const OrderedCaloHitList &rhs)
Copy constructor.
~OrderedCaloHitList ()
Destructor.
StatusCode Add (const OrderedCaloHitList &rhs)
Add the hits from a second ordered calo hit list to this list.
StatusCode Remove (const OrderedCaloHitList &rhs)
Remove the hits in a second ordered calo hit list from this list.
StatusCode Add (const CaloHitList &caloHitList)
Add a list of calo hits to the ordered calo hit list.
StatusCode Remove (const CaloHitList &caloHitList)
Remove a list of calo hits from the ordered calo hit list.
StatusCode Add (const CaloHit *const pCaloHit)
Add a calo hit to the ordered calo hit list.
StatusCode Remove (const CaloHit *const pCaloHit)
Remove a calo hit from the ordered calo hit list.
StatusCode GetCaloHitsInPseudoLayer (const unsigned int pseudoLayer, CaloHitList *&pCaloHitList) const
Get calo hits in specified pseudo layer.
unsigned int GetNCaloHitsInPseudoLayer (const unsigned int pseudoLayer) const
Get the number of calo hits in a specified pseudo layer.
void Reset ()
Reset the ordered calo hit list, emptying its contents.
void GetCaloHitList (CaloHitList &caloHitList) const
Get a simple list of all the calo hits in the ordered calo hit list (no ordering by pseudolayer)
const_iterator begin () const
Returns a const iterator referring to the first element in the ordered calo hit list.
const_iterator end () const
Returns a const iterator referring to the past-the-end element in the ordered calo hit list.
const_reverse_iterator rbegin () const
Returns a const reverse iterator referring to the first element in the ordered calo hit list.
const_reverse_iterator rend () const
Returns a const reverse iterator referring to the past-the-end element in the ordered calo hit list.
const_iterator find (const unsigned int index) const
Searches the container for an element with specified layer and returns an iterator to it if found, otherwise it returns an iterator to the past-the-end element.
unsigned int size () const
Returns the number of elements in the container.
bool empty () const
Returns whether the map container is empty (i.e.
bool operator= (const OrderedCaloHitList &rhs)
Assignment operator.
Detailed Description
Calo hit lists arranged by pseudo layer.
Constructor & Destructor Documentation
pandora::OrderedCaloHitList::OrderedCaloHitList (const OrderedCaloHitList & rhs)
Copy constructor.
Parameters
rhs the ordered calo hit list to copy
References Add().
Member Function Documentation
StatusCode pandora::OrderedCaloHitList::Add (const OrderedCaloHitList & rhs)
Add the hits from a second ordered calo hit list to this list.
Parameters
rhs the source ordered calo hit list
References begin(), and end().
Referenced by Add(), pandora::Cluster::AddCaloHit(), pandora::Cluster::AddHitsFromSecondCluster(), operator=(), and OrderedCaloHitList().
StatusCode pandora::OrderedCaloHitList::Add (const CaloHitList & caloHitList)
Add a list of calo hits to the ordered calo hit list.
Parameters
caloHitList the calo hit list
References Add().
StatusCode pandora::OrderedCaloHitList::Add (const CaloHit *const pCaloHit) inline
Add a calo hit to the ordered calo hit list.
Parameters
pCaloHit the address of the calo hit
References Add(), and pandora::CaloHit::GetPseudoLayer().
bool pandora::OrderedCaloHitList::empty () const inline
Returns whether the map container is empty (i.e.
whether its size is 0)
Referenced by pandora::Cluster::CalculateInitialDirection(), operator=(), pandora::Cluster::RemoveCaloHit(), Reset(), and pandora::Cluster::ResetProperties().
void pandora::OrderedCaloHitList::GetCaloHitList (CaloHitList & caloHitList) const
Get a simple list of all the calo hits in the ordered calo hit list (no ordering by pseudolayer)
Parameters
caloHitList to receive the simple list of calo hits
References begin(), and end().
StatusCode pandora::OrderedCaloHitList::GetCaloHitsInPseudoLayer (const unsigned int pseudoLayer, CaloHitList *& pCaloHitList) const
Get calo hits in specified pseudo layer.
Parameters
pseudoLayer the pseudo layer
pCaloHitList to receive the address of the relevant calo hit list
References end(), and find().
unsigned int pandora::OrderedCaloHitList::GetNCaloHitsInPseudoLayer (const unsigned int pseudoLayer) const
Get the number of calo hits in a specified pseudo layer.
Parameters
pseudoLayer the pseudo layer
Returns
The number of calo hits in the specified pseudo layer
References end(), and find().
bool pandora::OrderedCaloHitList::operator= (const OrderedCaloHitList & rhs)
Assignment operator.
Parameters
rhs the ordered calo hit list to assign
References Add(), empty(), and Reset().
StatusCode pandora::OrderedCaloHitList::Remove (const OrderedCaloHitList & rhs)
Remove the hits in a second ordered calo hit list from this list.
Parameters
rhs the source ordered calo hit list
References begin(), and end().
Referenced by Remove(), and pandora::Cluster::RemoveCaloHit().
StatusCode pandora::OrderedCaloHitList::Remove (const CaloHitList & caloHitList)
Remove a list of calo hits from the ordered calo hit list.
Parameters
caloHitList the calo hit list
References Remove().
StatusCode pandora::OrderedCaloHitList::Remove (const CaloHit *const pCaloHit) inline
Remove a calo hit from the ordered calo hit list.
Parameters
pCaloHit the address of the calo hit
References pandora::CaloHit::GetPseudoLayer(), and Remove().
The documentation for this class was generated from the following files:
OrderedCaloHitList.h
OrderedCaloHitList.cc