PandoraSDK: pandora::CartesianVector Class Reference
pandora::CartesianVector Class Reference
CartesianVector class.
#include <CartesianVector.h>
Public Member Functions
CartesianVector (float x, float y, float z)
Constructor, create a vector from the cartesian coordinates of the end point, origin at (0,0,0,)
CartesianVector (const CartesianVector &rhs)
Copy constructor.
void SetValues (float x, float y, float z)
Set the values of cartesian vector components.
float GetX () const
Get the cartesian x coordinate.
float GetY () const
Get the cartesian y coordinate.
float GetZ () const
Get the cartesian z coordinate.
float GetMagnitude () const
Get the magnitude.
float GetMagnitudeSquared () const
Get the magnitude squared.
float GetDotProduct (const CartesianVector &rhs) const
Get the dot product of the cartesian vector with a second cartesian vector.
CartesianVector GetCrossProduct (const CartesianVector &rhs) const
Get the cross product of the cartesian vector with a second cartesian vector.
float GetCosOpeningAngle (const CartesianVector &rhs) const
Get the cosine of the opening angle of the cartesian vector with respect to a second cartesian vector.
float GetOpeningAngle (const CartesianVector &rhs) const
Get the opening angle of the cartesian vector with respect to a second cartesian vector.
void GetSphericalCoordinates (float &radius, float &phi, float &theta) const
Get the spherical coordinates of the cartesian vector.
void GetCylindricalCoordinates (float &radius, float &phi, float &z) const
Get the cylindrical coordinates of the cartesian vector (x/y .
CartesianVector GetUnitVector () const
Get a unit vector in the direction of the cartesian vector.
CartesianVector & operator= (const CartesianVector &rhs)
Cartesian vector assignment operator.
CartesianVector & operator+= (const CartesianVector &rhs)
Cartesian vector += operator.
CartesianVector & operator-= (const CartesianVector &rhs)
Cartesian vector -= operator.
CartesianVector & operator*= (const double scalar)
Cartesian vector *= operator.
bool operator== (const CartesianVector &rhs) const
Cartesian vector == operator.
Detailed Description
CartesianVector class.
Constructor & Destructor Documentation
pandora::CartesianVector::CartesianVector (float x, float y, float z) inline
Constructor, create a vector from the cartesian coordinates of the end point, origin at (0,0,0,)
Parameters
x the end point x coordinate
y the end point y coordinate
z the end point z coordinate
Referenced by GetCrossProduct(), and GetUnitVector().
pandora::CartesianVector::CartesianVector (const CartesianVector & rhs) inline
Copy constructor.
Parameters
rhs the cartesian vector to copy
Member Function Documentation
float pandora::CartesianVector::GetCosOpeningAngle (const CartesianVector & rhs) const
Get the cosine of the opening angle of the cartesian vector with respect to a second cartesian vector.
Parameters
rhs the second cartesian vector
Returns
The cosine of the opening angle
References GetDotProduct(), and GetMagnitudeSquared().
Referenced by GetOpeningAngle().
CartesianVector pandora::CartesianVector::GetCrossProduct (const CartesianVector & rhs) const inline
Get the cross product of the cartesian vector with a second cartesian vector.
Parameters
rhs the second cartesian vector
Returns
The cross product
References CartesianVector().
Referenced by pandora::CaloHit::GetRectangularCellCorners().
void pandora::CartesianVector::GetCylindricalCoordinates (float & radius, float & phi, float & z) const
Get the cylindrical coordinates of the cartesian vector (x/y .
. radius, z .. z)
Parameters
radius the radius (x,y-plane) of the vector
phi the azimuth of the vector
z the z position of the vector
References GetMagnitude().
float pandora::CartesianVector::GetDotProduct (const CartesianVector & rhs) const inline
Get the dot product of the cartesian vector with a second cartesian vector.
Parameters
rhs the second cartesian vector
Returns
The dot product
Referenced by GetCosOpeningAngle(), and pandora::BoxGap::IsInGap().
float pandora::CartesianVector::GetMagnitude () const inline
Get the magnitude.
Returns
The magnitude
References GetMagnitudeSquared().
Referenced by GetCylindricalCoordinates(), GetSphericalCoordinates(), GetUnitVector(), and pandora::BoxGap::IsInGap().
float pandora::CartesianVector::GetMagnitudeSquared () const inline
Get the magnitude squared.
Returns
The magnitude squared
Referenced by GetCosOpeningAngle(), and GetMagnitude().
float pandora::CartesianVector::GetOpeningAngle (const CartesianVector & rhs) const inline
Get the opening angle of the cartesian vector with respect to a second cartesian vector.
Parameters
rhs the second cartesian vector
Returns
The opening angle
References GetCosOpeningAngle().
void pandora::CartesianVector::GetSphericalCoordinates (float & radius, float & phi, float & theta) const
Get the spherical coordinates of the cartesian vector.
Parameters
radius the magnitude of the vector
phi the azimuth of the vector
theta the inclination of the vector
References GetMagnitude().
Referenced by pandora::CaloHit::CalculateCellLengthScale(), and pandora::CaloHit::GetPointingCellCorners().
CartesianVector pandora::CartesianVector::GetUnitVector () const
Get a unit vector in the direction of the cartesian vector.
Returns
The unit vector
References CartesianVector(), and GetMagnitude().
Referenced by pandora::Cluster::CalculateInitialDirection(), pandora::Cluster::Cluster(), pandora::ClusterFitHelper::FitLayerCentroids(), pandora::ClusterFitHelper::FitPoints(), and pandora::BoxGap::IsInGap().
float pandora::CartesianVector::GetX () const inline
Get the cartesian x coordinate.
Returns
The cartesian x coordinate
Referenced by pandora::Cluster::AddCaloHit(), pandora::Helix::GetDistanceToHelix(), pandora::Helix::GetDistanceToPoint(), pandora::Helix::GetExtrapolatedMomentum(), pandora::Helix::GetPointInXY(), pandora::Helix::GetPointInZ(), pandora::Helix::GetPointOnCircle(), pandora::Helix::Helix(), pandora::ConcentricGap::IsInGap(), and pandora::Cluster::RemoveCaloHit().
float pandora::CartesianVector::GetY () const inline
Get the cartesian y coordinate.
Returns
The cartesian y coordinate
Referenced by pandora::Cluster::AddCaloHit(), pandora::Helix::GetDistanceToHelix(), pandora::Helix::GetDistanceToPoint(), pandora::Helix::GetExtrapolatedMomentum(), pandora::Helix::GetPointInXY(), pandora::Helix::GetPointInZ(), pandora::Helix::GetPointOnCircle(), pandora::Helix::Helix(), pandora::ConcentricGap::IsInGap(), and pandora::Cluster::RemoveCaloHit().
float pandora::CartesianVector::GetZ () const inline
Get the cartesian z coordinate.
Returns
The cartesian z coordinate
Referenced by pandora::Cluster::AddCaloHit(), pandora::Helix::GetDistanceToHelix(), pandora::Helix::GetDistanceToPoint(), pandora::Helix::GetExtrapolatedMomentum(), pandora::Helix::GetPointInXY(), pandora::Helix::GetPointInZ(), pandora::Helix::GetPointOnCircle(), pandora::Helix::Helix(), pandora::LineGap::IsInGap(), pandora::ConcentricGap::IsInGap(), and pandora::Cluster::RemoveCaloHit().
CartesianVector & pandora::CartesianVector::operator*= (const double scalar) inline
Cartesian vector *= operator.
Parameters
scalar the scalar to multiply
References SetValues().
CartesianVector & pandora::CartesianVector::operator+= (const CartesianVector & rhs) inline
Cartesian vector += operator.
Parameters
rhs the cartesian vector to add
References SetValues().
CartesianVector & pandora::CartesianVector::operator-= (const CartesianVector & rhs) inline
Cartesian vector -= operator.
Parameters
rhs the cartesian vector to subtract
References SetValues().
CartesianVector & pandora::CartesianVector::operator= (const CartesianVector & rhs) inline
Cartesian vector assignment operator.
Parameters
rhs the cartesian vector to assign
References SetValues().
bool pandora::CartesianVector::operator== (const CartesianVector & rhs) const inline
Cartesian vector == operator.
Parameters
rhs the cartesian vector to compare
void pandora::CartesianVector::SetValues (float x, float y, float z) inline
Set the values of cartesian vector components.
Parameters
x the x coordinate
y the y coordinate
z the z coordinate
Referenced by pandora::Cluster::CalculateInitialDirection(), pandora::Helix::GetDistanceToPoint(), pandora::Helix::GetPointInXY(), pandora::Helix::GetPointInZ(), pandora::Helix::GetPointOnCircle(), pandora::Helix::Helix(), operator*=(), operator+=(), operator-=(), operator=(), pandora::ClusterFitResult::Reset(), and pandora::Cluster::ResetOutdatedProperties().
The documentation for this class was generated from the following files:
CartesianVector.h
CartesianVector.cc