PandoraSDK: pandora::ClusterFitHelper Class Reference
pandora::ClusterFitHelper Class Reference
ClusterFitHelper class.
#include <ClusterFitHelper.h>
Static Public Member Functions
static StatusCode FitStart (const Cluster *const pCluster, const unsigned int maxOccupiedLayers, ClusterFitResult &clusterFitResult)
Fit points in first n occupied pseudolayers of a cluster.
static StatusCode FitEnd (const Cluster *const pCluster, const unsigned int maxOccupiedLayers, ClusterFitResult &clusterFitResult)
Fit points in last n occupied pseudolayers of a cluster.
static StatusCode FitFullCluster (const Cluster *const pCluster, ClusterFitResult &clusterFitResult)
Fit all points in a cluster.
static StatusCode FitLayers (const Cluster *const pCluster, const unsigned int startLayer, const unsigned int endLayer, ClusterFitResult &clusterFitResult)
Fit all cluster points within the specified (inclusive) pseudolayer range.
static StatusCode FitLayerCentroids (const Cluster *const pCluster, const unsigned int startLayer, const unsigned int endLayer, ClusterFitResult &clusterFitResult)
Fit all cluster centroids within the specified (inclusive) pseudolayer range.
static StatusCode FitPoints (const ClusterFitPointList &clusterFitPointList, ClusterFitResult &clusterFitResult)
Perform linear regression of x vs d and y vs d and z vs d (assuming same error on all hits)
Detailed Description
ClusterFitHelper class.
Member Function Documentation
StatusCode pandora::ClusterFitHelper::FitEnd (const Cluster *const pCluster, const unsigned int maxOccupiedLayers, ClusterFitResult & clusterFitResult) static
Fit points in last n occupied pseudolayers of a cluster.
Parameters
pCluster the cluster containing the ordered list of calo hits to fit
maxOccupiedLayers the maximum number of occupied pseudo layers to consider
clusterFitResult to receive the cluster fit result
References FitPoints(), pandora::Cluster::GetOrderedCaloHitList(), pandora::OrderedCaloHitList::rbegin(), pandora::OrderedCaloHitList::rend(), and pandora::OrderedCaloHitList::size().
StatusCode pandora::ClusterFitHelper::FitFullCluster (const Cluster *const pCluster, ClusterFitResult & clusterFitResult) static
Fit all points in a cluster.
Parameters
pCluster the cluster containing the ordered list of calo hits to fit
clusterFitResult to receive the cluster fit result
References pandora::OrderedCaloHitList::begin(), pandora::OrderedCaloHitList::end(), FitPoints(), pandora::Cluster::GetOrderedCaloHitList(), and pandora::OrderedCaloHitList::size().
Referenced by pandora::Cluster::CalculateFitToAllHitsResult().
StatusCode pandora::ClusterFitHelper::FitLayerCentroids (const Cluster *const pCluster, const unsigned int startLayer, const unsigned int endLayer, ClusterFitResult & clusterFitResult) static
Fit all cluster centroids within the specified (inclusive) pseudolayer range.
Parameters
pCluster the cluster containing the ordered list of calo hits to fit
startLayer the start of the pseudolayer range
endLayer the end of the pseudolayer range
clusterFitResult to receive the cluster fit result
References pandora::OrderedCaloHitList::begin(), pandora::OrderedCaloHitList::end(), FitPoints(), pandora::Cluster::GetCentroid(), pandora::Cluster::GetOrderedCaloHitList(), pandora::StatusCodeException::GetStatusCode(), pandora::CartesianVector::GetUnitVector(), pandora::ClusterFitResult::SetSuccessFlag(), and pandora::OrderedCaloHitList::size().
StatusCode pandora::ClusterFitHelper::FitLayers (const Cluster *const pCluster, const unsigned int startLayer, const unsigned int endLayer, ClusterFitResult & clusterFitResult) static
Fit all cluster points within the specified (inclusive) pseudolayer range.
Parameters
pCluster the cluster containing the ordered list of calo hits to fit
startLayer the start of the pseudolayer range
endLayer the end of the pseudolayer range
clusterFitResult to receive the cluster fit result
References pandora::OrderedCaloHitList::begin(), pandora::OrderedCaloHitList::end(), FitPoints(), pandora::Cluster::GetOrderedCaloHitList(), and pandora::OrderedCaloHitList::size().
StatusCode pandora::ClusterFitHelper::FitPoints (const ClusterFitPointList & clusterFitPointList, ClusterFitResult & clusterFitResult) static
Perform linear regression of x vs d and y vs d and z vs d (assuming same error on all hits)
Parameters
clusterFitPointList list of cluster fit points
clusterFitResult to receive the cluster fit result
References pandora::StatusCodeException::GetStatusCode(), pandora::CartesianVector::GetUnitVector(), pandora::ClusterFitResult::Reset(), and pandora::ClusterFitResult::SetSuccessFlag().
Referenced by FitEnd(), FitFullCluster(), FitLayerCentroids(), FitLayers(), and FitStart().
StatusCode pandora::ClusterFitHelper::FitStart (const Cluster *const pCluster, const unsigned int maxOccupiedLayers, ClusterFitResult & clusterFitResult) static
Fit points in first n occupied pseudolayers of a cluster.
Parameters
pCluster the cluster containing the ordered list of calo hits to fit
maxOccupiedLayers the maximum number of occupied pseudo layers to consider
clusterFitResult to receive the cluster fit result
References pandora::OrderedCaloHitList::begin(), pandora::OrderedCaloHitList::end(), FitPoints(), pandora::Cluster::GetOrderedCaloHitList(), and pandora::OrderedCaloHitList::size().
The documentation for this class was generated from the following files:
ClusterFitHelper.h
ClusterFitHelper.cc