PandoraSDK: pandora::BoxGap Class Reference
pandora::BoxGap Class Reference
BoxGap class, associated with all 3D hit types.
#include <DetectorGap.h>
Public Member Functions
bool IsInGap (const CartesianVector &positionVector, const HitType hitType, const float gapTolerance) const
Whether a specified position lies within the gap.
const CartesianVector & GetVertex () const
Get the gap vertex.
const CartesianVector & GetSide1 () const
Get the vector describing first side meeting vertex.
const CartesianVector & GetSide2 () const
Get the vector describing second side meeting vertex.
const CartesianVector & GetSide3 () const
Get the vector describing third side meeting vertex.
Public Member Functions inherited from pandora::DetectorGap
virtual ~DetectorGap ()
Destructor.
Friends
class PandoraObjectFactory< PandoraApi::Geometry::BoxGap::Parameters, BoxGap >
Detailed Description
BoxGap class, associated with all 3D hit types.
Member Function Documentation
const CartesianVector & pandora::BoxGap::GetSide1 () const inline
Get the vector describing first side meeting vertex.
Parameters
the vector describing first side meeting vertex
const CartesianVector & pandora::BoxGap::GetSide2 () const inline
Get the vector describing second side meeting vertex.
Parameters
the vector describing second side meeting vertex
const CartesianVector & pandora::BoxGap::GetSide3 () const inline
Get the vector describing third side meeting vertex.
Parameters
the vector describing third side meeting vertex
const CartesianVector & pandora::BoxGap::GetVertex () const inline
Get the gap vertex.
Parameters
the gap vertex
bool pandora::BoxGap::IsInGap (const CartesianVector & positionVector, const HitType hitType, const float gapTolerance) const virtual
Whether a specified position lies within the gap.
Parameters
positionVector the position vector
hitType the hit type, providing context to aid interpretation of provided position vector
gapTolerance tolerance allowed when declaring a point to be "in" a gap region, units mm
Returns
boolean
Implements pandora::DetectorGap.
References pandora::CartesianVector::GetDotProduct(), pandora::CartesianVector::GetMagnitude(), and pandora::CartesianVector::GetUnitVector().
The documentation for this class was generated from the following files:
DetectorGap.h
DetectorGap.cc