PandoraSDK: pandora::Cluster Class Reference
pandora::Cluster Class Reference
Cluster class.
#include <Cluster.h>
Classes
class SimplePoint
SimplePoint class.
Public Member Functions
const OrderedCaloHitList & GetOrderedCaloHitList () const
Get the ordered calo hit list.
const CaloHitList & GetIsolatedCaloHitList () const
Get the isolated calo hit list.
unsigned int GetNCaloHits () const
Get the number of calo hits in the cluster.
unsigned int GetNIsolatedCaloHits () const
Get the number of isolated calo hits in the cluster.
unsigned int GetNPossibleMipHits () const
Get the number of calo hits in the cluster that have been flagged as possible mip hits.
float GetMipFraction () const
Get fraction of constituent calo hits that have been flagged as possible mip hits.
unsigned int GetNHitsInOuterLayer () const
Get the number of hits in the outer sampling layers.
float GetElectromagneticEnergy () const
Get the sum of electromagnetic energy measures of all constituent calo hits, units GeV.
float GetHadronicEnergy () const
Get the sum of hadronic energy measures of all constituent calo hits, units GeV.
float GetIsolatedElectromagneticEnergy () const
Get the sum of electromagnetic energy measures of isolated constituent calo hits, units GeV.
float GetIsolatedHadronicEnergy () const
Get the sum of hadronic energy measures of isolated constituent calo hits, units GeV.
int GetParticleIdFlag () const
Get the particle id flag.
bool IsTrackSeeded () const
Whether the cluster is track seeded.
const Track * GetTrackSeed () const
Get the address of the track with which the cluster is seeded.
unsigned int GetInnerPseudoLayer () const
Get the innermost pseudo layer in the cluster.
unsigned int GetOuterPseudoLayer () const
Get the outermost pseudo layer in the cluster.
const CartesianVector GetCentroid (const unsigned int pseudoLayer) const
Get unweighted centroid for cluster at a particular pseudo layer, calculated using cached values of hit coordinate sums.
const CartesianVector & GetInitialDirection () const
Get the initial direction of the cluster.
const ClusterFitResult & GetFitToAllHitsResult () const
Get the result of a linear fit to all calo hits in the cluster.
HitType GetInnerLayerHitType () const
Get the typical inner layer hit type.
HitType GetOuterLayerHitType () const
Get the typical outer layer hit type.
const TrackList & GetAssociatedTrackList () const
Get the list of tracks associated with the cluster.
bool IsAvailable () const
Whether the cluster is available to be added to a particle flow object.
float GetCorrectedElectromagneticEnergy (const Pandora &pandora) const
Get the corrected electromagnetic estimate of the cluster energy, units GeV.
float GetCorrectedHadronicEnergy (const Pandora &pandora) const
Get the corrected hadronic estimate of the cluster energy, units GeV.
float GetTrackComparisonEnergy (const Pandora &pandora) const
Get the best energy estimate to use when comparing cluster energy to associated track momentum, units GeV.
bool IsPhotonFast (const Pandora &pandora) const
Whether the cluster has been flagged as a photon by photon id function.
unsigned int GetShowerStartLayer (const Pandora &pandora) const
Get the pseudo layer at which shower commences.
float GetShowerProfileStart (const Pandora &pandora) const
Get the cluster shower profile start, units radiation lengths.
float GetShowerProfileDiscrepancy (const Pandora &pandora) const
Get the cluster shower profile discrepancy.
Protected Types
typedef std::map< unsigned int,
SimplePoint > PointByPseudoLayerMap
The point by pseudo layer typedef.
typedef std::map< HitType, float > HitTypeToEnergyMap
The hit type to energy map typedef.
Protected Member Functions
Cluster (const PandoraContentApi::Cluster::Parameters &parameters)
Constructor.
virtual ~Cluster ()
Destructor.
StatusCode AlterMetadata (const PandoraContentApi::Cluster::Metadata &metadata)
Alter the metadata information stored in a cluster.
StatusCode AddCaloHit (const CaloHit *const pCaloHit)
Add a calo hit to the cluster.
StatusCode RemoveCaloHit (const CaloHit *const pCaloHit)
Remove a calo hit from the cluster.
StatusCode AddIsolatedCaloHit (const CaloHit *const pCaloHit)
Add an isolated calo hit to the cluster.
StatusCode RemoveIsolatedCaloHit (const CaloHit *const pCaloHit)
Remove an isolated calo hit from the cluster.
void CalculateFitToAllHitsResult () const
Calculate result of a linear fit to all calo hits in the cluster.
void CalculateInitialDirection () const
Calculate cluster initial direction.
void CalculateLayerHitType (const unsigned int pseudoLayer, InputHitType &layerHitType) const
Calculate the typical hit type for a specified layer.
void PerformEnergyCorrections (const Pandora &pandora) const
PerformClusterEnergyCorrections.
void CalculateFastPhotonFlag (const Pandora &pandora) const
Calculate the fast photon flag.
void CalculateShowerStartLayer (const Pandora &pandora) const
Calculate the pseudo layer at which shower commences.
void CalculateShowerProfile (const Pandora &pandora) const
Calculate shower profile and compare it with the expected profile for a photon.
StatusCode ResetProperties ()
Reset all cluster properties.
void ResetOutdatedProperties ()
Reset those cluster properties that must be recalculated upon addition/removal of a calo hit.
StatusCode AddHitsFromSecondCluster (const Cluster *const pCluster)
Add the calo hits from a second cluster to this.
StatusCode AddTrackAssociation (const Track *const pTrack)
Add an association between the cluster and a track.
StatusCode RemoveTrackAssociation (const Track *const pTrack)
Remove an association between the cluster and a track.
void RemoveTrackSeed ()
Remove the track seed, changing the initial direction measurement.
void SetAvailability (bool isAvailable)
Set availability of cluster to be added to a particle flow object.
Protected Attributes
OrderedCaloHitList m_orderedCaloHitList
The ordered calo hit list.
CaloHitList m_isolatedCaloHitList
The list of isolated hits, which contribute only towards cluster energy.
unsigned int m_nCaloHits
The number of calo hits.
unsigned int m_nPossibleMipHits
The number of calo hits that have been flagged as possible mip hits.
unsigned int m_nCaloHitsInOuterLayer
Keep track of the number of calo hits in the outermost layers.
double m_electromagneticEnergy
The sum of electromagnetic energy measures of constituent calo hits, units GeV.
double m_hadronicEnergy
The sum of hadronic energy measures of constituent calo hits, units GeV.
double m_isolatedElectromagneticEnergy
Sum of electromagnetic energy measures of isolated calo hits, units GeV.
double m_isolatedHadronicEnergy
Sum of hadronic energy measures of isolated calo hits, units GeV.
int m_particleId
The particle id flag.
const Track * m_pTrackSeed
Address of the track with which the cluster is seeded.
PointByPseudoLayerMap m_sumXYZByPseudoLayer
Construct to allow rapid calculation of centroid in each pseudolayer.
InputUInt m_innerPseudoLayer
The innermost pseudo layer in the cluster.
InputUInt m_outerPseudoLayer
The outermost pseudo layer in the cluster.
CartesianVector m_initialDirection
The initial direction of the cluster.
bool m_isDirectionUpToDate
Whether the initial direction of the cluster is up to date.
ClusterFitResult m_fitToAllHitsResult
The result of a linear fit to all calo hits in the cluster.
bool m_isFitUpToDate
Whether the fit to all calo hits is up to date.
InputFloat m_correctedElectromagneticEnergy
The corrected electromagnetic estimate of the cluster energy, units GeV.
InputFloat m_correctedHadronicEnergy
The corrected hadronic estimate of the cluster energy, units GeV.
InputFloat m_trackComparisonEnergy
The appropriate corrected energy to use in comparisons with track momentum, units GeV.
InputBool m_isPhotonFast
Whether the cluster is flagged as a photon by fast photon id function.
InputUInt m_showerStartLayer
The pseudo layer at which shower commences.
InputFloat m_showerProfileStart
The cluster shower profile start, units radiation lengths.
InputFloat m_showerProfileDiscrepancy
The cluster shower profile discrepancy.
InputHitType m_innerLayerHitType
The typical inner layer hit type.
InputHitType m_outerLayerHitType
The typical outer layer hit type.
TrackList m_associatedTrackList
The list of tracks associated with the cluster.
bool m_isAvailable
Whether the cluster is available to be added to a particle flow object.
Friends
class ClusterManager
class AlgorithmObjectManager< Cluster >
class PandoraObjectFactory< PandoraContentApi::Cluster::Parameters, Cluster >
Detailed Description
Cluster class.
Constructor & Destructor Documentation
pandora::Cluster::Cluster (const PandoraContentApi::Cluster::Parameters & parameters) protected
Constructor.
Parameters
parameters the cluster parameters
References AddCaloHit(), AddIsolatedCaloHit(), pandora::CartesianVector::GetUnitVector(), m_initialDirection, and m_isDirectionUpToDate.
Member Function Documentation
StatusCode pandora::Cluster::AddCaloHit (const CaloHit *const pCaloHit) protected
Add a calo hit to the cluster.
Parameters
pCaloHit the address of the calo hit
References pandora::OrderedCaloHitList::Add(), pandora::OrderedCaloHitList::end(), pandora::OrderedCaloHitList::find(), pandora::PandoraInputType< T >::Get(), pandora::CaloHit::GetElectromagneticEnergy(), pandora::CaloHit::GetHadronicEnergy(), pandora::CaloHit::GetPositionVector(), pandora::CaloHit::GetPseudoLayer(), pandora::CartesianVector::GetX(), pandora::CartesianVector::GetY(), pandora::CartesianVector::GetZ(), pandora::PandoraInputType< T >::IsInitialized(), pandora::CaloHit::IsInOuterSamplingLayer(), pandora::CaloHit::IsPossibleMip(), m_electromagneticEnergy, m_hadronicEnergy, m_innerPseudoLayer, m_nCaloHits, m_nCaloHitsInOuterLayer, pandora::Cluster::SimplePoint::m_nHits, m_nPossibleMipHits, m_orderedCaloHitList, m_outerPseudoLayer, m_sumXYZByPseudoLayer, pandora::Cluster::SimplePoint::m_xyzPositionSums, and ResetOutdatedProperties().
Referenced by Cluster().
StatusCode pandora::Cluster::AddHitsFromSecondCluster (const Cluster *const pCluster) protected
Add the calo hits from a second cluster to this.
Parameters
pCluster the address of the second cluster
References pandora::OrderedCaloHitList::Add(), pandora::OrderedCaloHitList::begin(), pandora::OrderedCaloHitList::end(), pandora::OrderedCaloHitList::find(), GetElectromagneticEnergy(), GetHadronicEnergy(), GetIsolatedCaloHitList(), GetNCaloHits(), GetNHitsInOuterLayer(), GetNPossibleMipHits(), GetOrderedCaloHitList(), m_electromagneticEnergy, m_hadronicEnergy, m_innerPseudoLayer, m_isolatedCaloHitList, m_nCaloHits, m_nCaloHitsInOuterLayer, pandora::Cluster::SimplePoint::m_nHits, m_nPossibleMipHits, m_orderedCaloHitList, m_outerPseudoLayer, m_sumXYZByPseudoLayer, pandora::Cluster::SimplePoint::m_xyzPositionSums, pandora::OrderedCaloHitList::rbegin(), and ResetOutdatedProperties().
StatusCode pandora::Cluster::AddIsolatedCaloHit (const CaloHit *const pCaloHit) protected
Add an isolated calo hit to the cluster.
Parameters
pCaloHit the address of the isolated calo hit
References pandora::CaloHit::GetElectromagneticEnergy(), pandora::CaloHit::GetHadronicEnergy(), m_electromagneticEnergy, m_hadronicEnergy, m_isolatedCaloHitList, m_isolatedElectromagneticEnergy, and m_isolatedHadronicEnergy.
Referenced by Cluster().
StatusCode pandora::Cluster::AddTrackAssociation (const Track *const pTrack) protected
Add an association between the cluster and a track.
Parameters
pTrack the address of the track with which the cluster is associated
References m_associatedTrackList.
StatusCode pandora::Cluster::AlterMetadata (const PandoraContentApi::Cluster::Metadata & metadata) protected
Alter the metadata information stored in a cluster.
Parameters
metaData the metadata (only populated metadata fields will be propagated to the object)
References m_isPhotonFast, m_particleId, and pandora::PandoraInputType< T >::Reset().
void pandora::Cluster::CalculateFastPhotonFlag (const Pandora & pandora) const protected
Calculate the fast photon flag.
Parameters
pandora the associated pandora instance
References pandora::PluginManager::GetParticleId(), pandora::Pandora::GetPlugins(), pandora::ParticleId::IsPhoton(), and m_isPhotonFast.
Referenced by IsPhotonFast().
void pandora::Cluster::CalculateLayerHitType (const unsigned int pseudoLayer, InputHitType & layerHitType) const protected
Calculate the typical hit type for a specified layer.
Parameters
pseudoLayer the pseudo layer
layerHitType to receive the typical layer hit type
References pandora::OrderedCaloHitList::end(), pandora::OrderedCaloHitList::find(), and m_orderedCaloHitList.
Referenced by GetInnerLayerHitType(), and GetOuterLayerHitType().
void pandora::Cluster::CalculateShowerProfile (const Pandora & pandora) const protected
Calculate shower profile and compare it with the expected profile for a photon.
Parameters
pandora the associated pandora instance
References pandora::Pandora::GetPlugins(), pandora::PluginManager::GetShowerProfilePlugin(), m_showerProfileDiscrepancy, and m_showerProfileStart.
Referenced by GetShowerProfileDiscrepancy(), and GetShowerProfileStart().
void pandora::Cluster::CalculateShowerStartLayer (const Pandora & pandora) const protected
Calculate the pseudo layer at which shower commences.
Parameters
pandora the associated pandora instance
References pandora::Pandora::GetPlugins(), pandora::PluginManager::GetShowerProfilePlugin(), and m_showerStartLayer.
Referenced by GetShowerStartLayer().
const TrackList & pandora::Cluster::GetAssociatedTrackList () const inline
Get the list of tracks associated with the cluster.
Returns
Address of the list of associated tracks
References m_associatedTrackList.
const CartesianVector pandora::Cluster::GetCentroid (const unsigned int pseudoLayer) const
Get unweighted centroid for cluster at a particular pseudo layer, calculated using cached values of hit coordinate sums.
Parameters
pseudoLayer the pseudo layer of interest
Returns
The unweighted centroid, returned by value
References pandora::Cluster::SimplePoint::m_nHits, m_sumXYZByPseudoLayer, and pandora::Cluster::SimplePoint::m_xyzPositionSums.
Referenced by pandora::ClusterFitHelper::FitLayerCentroids().
float pandora::Cluster::GetCorrectedElectromagneticEnergy (const Pandora & pandora) const inline
Get the corrected electromagnetic estimate of the cluster energy, units GeV.
Parameters
pandora the associated pandora instance
Returns
The corrected electromagnetic energy estimate
References pandora::PandoraInputType< T >::Get(), pandora::PandoraInputType< T >::IsInitialized(), and PerformEnergyCorrections().
float pandora::Cluster::GetCorrectedHadronicEnergy (const Pandora & pandora) const inline
Get the corrected hadronic estimate of the cluster energy, units GeV.
Parameters
pandora the associated pandora instance
Returns
The corrected hadronic energy estimate
References pandora::PandoraInputType< T >::Get(), pandora::PandoraInputType< T >::IsInitialized(), and PerformEnergyCorrections().
float pandora::Cluster::GetElectromagneticEnergy () const inline
Get the sum of electromagnetic energy measures of all constituent calo hits, units GeV.
Returns
The electromagnetic energy measure
References m_electromagneticEnergy.
Referenced by AddHitsFromSecondCluster(), and pandora::EnergyCorrections::MakeEnergyCorrections().
const ClusterFitResult & pandora::Cluster::GetFitToAllHitsResult () const inline
Get the result of a linear fit to all calo hits in the cluster.
Returns
The cluster fit result
References CalculateFitToAllHitsResult(), and m_fitToAllHitsResult.
float pandora::Cluster::GetHadronicEnergy () const inline
Get the sum of hadronic energy measures of all constituent calo hits, units GeV.
Returns
The hadronic energy measure
References m_hadronicEnergy.
Referenced by AddHitsFromSecondCluster(), and pandora::EnergyCorrections::MakeEnergyCorrections().
const CartesianVector & pandora::Cluster::GetInitialDirection () const inline
Get the initial direction of the cluster.
Returns
The initial direction of the cluster
References CalculateInitialDirection(), and m_initialDirection.
HitType pandora::Cluster::GetInnerLayerHitType () const inline
Get the typical inner layer hit type.
Returns
The typical inner layer hit type
References CalculateLayerHitType(), pandora::PandoraInputType< T >::Get(), pandora::PandoraInputType< T >::IsInitialized(), and m_innerLayerHitType.
unsigned int pandora::Cluster::GetInnerPseudoLayer () const inline
Get the innermost pseudo layer in the cluster.
Returns
The innermost pseudo layer in the cluster
References pandora::PandoraInputType< T >::Get().
const CaloHitList & pandora::Cluster::GetIsolatedCaloHitList () const inline
Get the isolated calo hit list.
Returns
The isolated calo hit list by reference
References m_isolatedCaloHitList.
Referenced by AddHitsFromSecondCluster().
float pandora::Cluster::GetIsolatedElectromagneticEnergy () const inline
Get the sum of electromagnetic energy measures of isolated constituent calo hits, units GeV.
Returns
The electromagnetic energy measure
References m_isolatedElectromagneticEnergy.
float pandora::Cluster::GetIsolatedHadronicEnergy () const inline
Get the sum of hadronic energy measures of isolated constituent calo hits, units GeV.
Returns
The hadronic energy measure
References m_isolatedHadronicEnergy.
float pandora::Cluster::GetMipFraction () const inline
Get fraction of constituent calo hits that have been flagged as possible mip hits.
Returns
The mip fraction
unsigned int pandora::Cluster::GetNCaloHits () const inline
Get the number of calo hits in the cluster.
Returns
The number of calo hits
References m_nCaloHits.
Referenced by AddHitsFromSecondCluster().
unsigned int pandora::Cluster::GetNHitsInOuterLayer () const inline
Get the number of hits in the outer sampling layers.
Returns
The number of hits in this cluster in the outermost sampling layer
References m_nCaloHitsInOuterLayer.
Referenced by AddHitsFromSecondCluster().
unsigned int pandora::Cluster::GetNIsolatedCaloHits () const inline
Get the number of isolated calo hits in the cluster.
Returns
The number of isolated calo hits
unsigned int pandora::Cluster::GetNPossibleMipHits () const inline
Get the number of calo hits in the cluster that have been flagged as possible mip hits.
Returns
The number of possible mip hits
References m_nPossibleMipHits.
Referenced by AddHitsFromSecondCluster().
const OrderedCaloHitList & pandora::Cluster::GetOrderedCaloHitList () const inline
Get the ordered calo hit list.
Returns
The ordered calo hit list by reference
References m_orderedCaloHitList.
Referenced by AddHitsFromSecondCluster(), pandora::ClusterFitHelper::FitEnd(), pandora::ClusterFitHelper::FitFullCluster(), pandora::ClusterFitHelper::FitLayerCentroids(), pandora::ClusterFitHelper::FitLayers(), and pandora::ClusterFitHelper::FitStart().
HitType pandora::Cluster::GetOuterLayerHitType () const inline
Get the typical outer layer hit type.
Returns
The typical outer layer hit type
References CalculateLayerHitType(), pandora::PandoraInputType< T >::Get(), pandora::PandoraInputType< T >::IsInitialized(), and m_outerLayerHitType.
unsigned int pandora::Cluster::GetOuterPseudoLayer () const inline
Get the outermost pseudo layer in the cluster.
Returns
The outermost pseudo layer in the cluster
References pandora::PandoraInputType< T >::Get().
int pandora::Cluster::GetParticleIdFlag () const inline
Get the particle id flag.
Returns
The particle id flag
References m_particleId.
Referenced by pandora::ParticleId::IsElectron(), pandora::ParticleId::IsMuon(), and pandora::ParticleId::IsPhoton().
float pandora::Cluster::GetShowerProfileDiscrepancy (const Pandora & pandora) const inline
Get the cluster shower profile discrepancy.
Parameters
pandora the associated pandora instance
Returns
The cluster shower profile discrepancy
References CalculateShowerProfile(), pandora::PandoraInputType< T >::Get(), and pandora::PandoraInputType< T >::IsInitialized().
float pandora::Cluster::GetShowerProfileStart (const Pandora & pandora) const inline
Get the cluster shower profile start, units radiation lengths.
Parameters
pandora the associated pandora instance
Returns
The cluster shower profile start
References CalculateShowerProfile(), pandora::PandoraInputType< T >::Get(), and pandora::PandoraInputType< T >::IsInitialized().
unsigned int pandora::Cluster::GetShowerStartLayer (const Pandora & pandora) const inline
Get the pseudo layer at which shower commences.
Parameters
pandora the associated pandora instance
Returns
The pseudo layer at which shower commences
References CalculateShowerStartLayer(), pandora::PandoraInputType< T >::Get(), and pandora::PandoraInputType< T >::IsInitialized().
float pandora::Cluster::GetTrackComparisonEnergy (const Pandora & pandora) const inline
Get the best energy estimate to use when comparing cluster energy to associated track momentum, units GeV.
For clusters identified as electromagnetic showers, the corrected electromagnetic energy will be returned. For all other clusters, the corrected hadronic energy will be returned.
Parameters
pandora the associated pandora instance
Returns
The track comparison energy estimate
References pandora::PandoraInputType< T >::Get(), pandora::PandoraInputType< T >::IsInitialized(), and PerformEnergyCorrections().
const Track * pandora::Cluster::GetTrackSeed () const inline
Get the address of the track with which the cluster is seeded.
Returns
address of the track seed
References m_pTrackSeed.
bool pandora::Cluster::IsAvailable () const inline
Whether the cluster is available to be added to a particle flow object.
Returns
boolean
References m_isAvailable.
bool pandora::Cluster::IsPhotonFast (const Pandora & pandora) const inline
Whether the cluster has been flagged as a photon by photon id function.
Parameters
pandora the associated pandora instance
Returns
boolean
References CalculateFastPhotonFlag(), pandora::PandoraInputType< T >::Get(), and pandora::PandoraInputType< T >::IsInitialized().
bool pandora::Cluster::IsTrackSeeded () const inline
Whether the cluster is track seeded.
Returns
boolean
void pandora::Cluster::PerformEnergyCorrections (const Pandora & pandora) const protected
PerformClusterEnergyCorrections.
Parameters
pandora the associated pandora instance
References pandora::PluginManager::GetEnergyCorrections(), pandora::PluginManager::GetParticleId(), pandora::Pandora::GetPlugins(), m_correctedElectromagneticEnergy, m_correctedHadronicEnergy, and m_trackComparisonEnergy.
Referenced by GetCorrectedElectromagneticEnergy(), GetCorrectedHadronicEnergy(), and GetTrackComparisonEnergy().
StatusCode pandora::Cluster::RemoveCaloHit (const CaloHit *const pCaloHit) protected
Remove a calo hit from the cluster.
Parameters
pCaloHit the address of the calo hit
References pandora::OrderedCaloHitList::begin(), pandora::OrderedCaloHitList::empty(), pandora::OrderedCaloHitList::end(), pandora::OrderedCaloHitList::find(), pandora::PandoraInputType< T >::Get(), pandora::CaloHit::GetElectromagneticEnergy(), pandora::CaloHit::GetHadronicEnergy(), pandora::CaloHit::GetPositionVector(), pandora::CaloHit::GetPseudoLayer(), pandora::CartesianVector::GetX(), pandora::CartesianVector::GetY(), pandora::CartesianVector::GetZ(), pandora::CaloHit::IsInOuterSamplingLayer(), pandora::CaloHit::IsPossibleMip(), m_electromagneticEnergy, m_hadronicEnergy, m_innerPseudoLayer, m_nCaloHits, m_nCaloHitsInOuterLayer, pandora::Cluster::SimplePoint::m_nHits, m_nPossibleMipHits, m_orderedCaloHitList, m_outerPseudoLayer, m_sumXYZByPseudoLayer, pandora::Cluster::SimplePoint::m_xyzPositionSums, pandora::OrderedCaloHitList::rbegin(), pandora::OrderedCaloHitList::Remove(), ResetOutdatedProperties(), and ResetProperties().
StatusCode pandora::Cluster::RemoveIsolatedCaloHit (const CaloHit *const pCaloHit) protected
Remove an isolated calo hit from the cluster.
Parameters
pCaloHit the address of the isolated calo hit
References pandora::CaloHit::GetElectromagneticEnergy(), pandora::CaloHit::GetHadronicEnergy(), m_electromagneticEnergy, m_hadronicEnergy, m_isolatedCaloHitList, m_isolatedElectromagneticEnergy, and m_isolatedHadronicEnergy.
StatusCode pandora::Cluster::RemoveTrackAssociation (const Track *const pTrack) protected
Remove an association between the cluster and a track.
Parameters
pTrack the address of the track with which the cluster is no longer associated
References m_associatedTrackList.
void pandora::Cluster::SetAvailability (bool isAvailable) inline protected
Set availability of cluster to be added to a particle flow object.
Parameters
isAvailable the cluster availability
The documentation for this class was generated from the following files:
Cluster.h
Cluster.cc