PandoraSDK: pandora::Helix Class Reference
pandora::Helix Class Reference
Helix class.
#include <Helix.h>
Public Member Functions
Helix (const float phi0, const float d0, const float z0, const float omega, const float tanlambda, const float bField)
Constructor using canonical (LEP-wise) parameterisation.
Helix (const CartesianVector &position, const CartesianVector &momentum, const float charge, const float bField)
Constructor.
StatusCode GetPointInXY (const float x0, const float y0, const float ax, const float ay, const CartesianVector &referencePoint, CartesianVector &intersectionPoint) const
Get helix intersection point with a plane parallel to z axis.
StatusCode GetPointInXY (const float x0, const float y0, const float ax, const float ay, const CartesianVector &referencePoint, CartesianVector &intersectionPoint, float &genericTime) const
Get helix intersection point with a plane parallel to z axis.
StatusCode GetPointInZ (const float zPlane, const CartesianVector &referencePoint, CartesianVector &intersectionPoint) const
Get helix intersection point with a plane perpendicular to z axis.
StatusCode GetPointInZ (const float zPlane, const CartesianVector &referencePoint, CartesianVector &intersectionPoint, float &genericTime) const
Get helix intersection point with a plane perpendicular to z axis.
StatusCode GetPointOnCircle (const float radius, const CartesianVector &referencePoint, CartesianVector &intersectionPoint) const
Get coordinates of helix intersection with cylinder, aligned along z-axis.
StatusCode GetPointOnCircle (const float radius, const CartesianVector &referencePoint, CartesianVector &intersectionPoint, float &genericTime) const
Get coordinates of helix intersection with cylinder, aligned along z-axis.
StatusCode GetDistanceToPoint (const CartesianVector &point, CartesianVector &distance) const
Get distance of the closest approach of helix to an arbitrary point in space.
StatusCode GetDistanceToPoint (const CartesianVector &point, CartesianVector &distance, float &genericTime) const
Get distance of the closest approach of helix to an arbitrary point in space.
StatusCode GetDistanceToHelix (const Helix *const pHelix, CartesianVector &positionOfClosestApproach, CartesianVector &v0momentum, float &helixDistance) const
Get distance between two helices.
CartesianVector GetExtrapolatedMomentum (const CartesianVector &position) const
const CartesianVector & GetMomentum () const
Get momentum of particle at the point of closest approach to IP.
const CartesianVector & GetReferencePoint () const
Get reference point of track.
float GetPhi0 () const
Get phi angle of the momentum vector at the point of closest approach to IP.
float GetD0 () const
Get z signed distance of closest approach to IP in the R-Phi plane.
float GetZ0 () const
Get z coordinate of the point of closest approach to IP in the R-Phi plane.
float GetOmega () const
Get signed curvature of the track.
float GetTanLambda () const
Get tangent of dip angle of the track.
float GetPxy () const
Get transverse momentum of the track.
float GetCharge () const
Get charge.
float GetXCentre () const
Get x coordinate of circumference.
float GetYCentre () const
Get y coordinate of circumference.
float GetRadius () const
Get radius of circumference.
Detailed Description
Helix class.
Constructor & Destructor Documentation
pandora::Helix::Helix (const float phi0, const float d0, const float z0, const float omega, const float tanlambda, const float bField)
Constructor using canonical (LEP-wise) parameterisation.
Parameters
phi0 phi angle of momentum vector at the point of closest approach to IP in R-Phi plane
d0 signed distance of closest approach in R-Phi plane
z0 z coordinate of the point of closest approach to IP in R-Phi plane
omega signed curvature
tanLambda tangent of dip angle
bField magnetic field (in Tesla)
References pandora::CartesianVector::GetX(), pandora::CartesianVector::GetY(), and pandora::CartesianVector::SetValues().
pandora::Helix::Helix (const CartesianVector & position, const CartesianVector & momentum, const float charge, const float bField)
Constructor.
Parameters
position position of the reference point
momentum momentum vector at the reference point
charge particle charge
bField magnetic field (in Tesla)
References pandora::CartesianVector::GetX(), pandora::CartesianVector::GetY(), and pandora::CartesianVector::GetZ().
Member Function Documentation
float pandora::Helix::GetCharge () const inline
Get charge.
Returns
the charge
Referenced by GetDistanceToHelix().
float pandora::Helix::GetD0 () const inline
Get z signed distance of closest approach to IP in the R-Phi plane.
Returns
the signed distance of closest approach
StatusCode pandora::Helix::GetDistanceToHelix (const Helix *const pHelix, CartesianVector & positionOfClosestApproach, CartesianVector & v0momentum, float & helixDistance) const
Get distance between two helices.
Parameters
pHelix address of a second helix
positionOfClosestApproach to receive position of the point of closest approach
v0momentum to receive the v0 momentum
helixDistance to receive the distance between the two helices
References GetCharge(), GetExtrapolatedMomentum(), GetMomentum(), GetPointOnCircle(), GetPxy(), GetRadius(), GetReferencePoint(), pandora::CartesianVector::GetX(), GetXCentre(), pandora::CartesianVector::GetY(), GetYCentre(), and pandora::CartesianVector::GetZ().
StatusCode pandora::Helix::GetDistanceToPoint (const CartesianVector & point, CartesianVector & distance) const inline
Get distance of the closest approach of helix to an arbitrary point in space.
Parameters
point coordinates of the specified point
distance to receive a vector of distances from helix to point in the following projections: x component: distance in R-Phi plane y-component: distance along Z axis z-component: 3D distance magnitude
StatusCode pandora::Helix::GetDistanceToPoint (const CartesianVector & point, CartesianVector & distance, float & genericTime) const
Get distance of the closest approach of helix to an arbitrary point in space.
Parameters
point coordinates of the specified point
distance to receive a vector of distances from helix to point in the following projections: x component: distance in R-Phi plane y-component: distance along Z axis z-component: 3D distance magnitude
genericTime to receive the generic time (helix length, from reference point to intersection, divided by particle momentum)
References pandora::CartesianVector::GetX(), pandora::CartesianVector::GetY(), pandora::CartesianVector::GetZ(), and pandora::CartesianVector::SetValues().
CartesianVector pandora::Helix::GetExtrapolatedMomentum (const CartesianVector & position) const
Parameters
Get extrapolated momentum at a specified position
position the specified position
Returns
the extrapolated momentum
References pandora::CartesianVector::GetX(), pandora::CartesianVector::GetY(), and pandora::CartesianVector::GetZ().
Referenced by GetDistanceToHelix().
const CartesianVector & pandora::Helix::GetMomentum () const inline
Get momentum of particle at the point of closest approach to IP.
Returns
the momentum of particle
Referenced by GetDistanceToHelix().
float pandora::Helix::GetOmega () const inline
Get signed curvature of the track.
Returns
the signed curvature of the track
float pandora::Helix::GetPhi0 () const inline
Get phi angle of the momentum vector at the point of closest approach to IP.
Returns
the phi angle of the momentum vector
StatusCode pandora::Helix::GetPointInXY (const float x0, const float y0, const float ax, const float ay, const CartesianVector & referencePoint, CartesianVector & intersectionPoint) const inline
Get helix intersection point with a plane parallel to z axis.
The plane is defined by two coordinates in the plane (x0,y0) and a normal vector (ax,ay).
Parameters
x0 x coordinate in the specified plane
y0 y coordinate in the specified plane
ax x component of vector normal to specified plane
ay y component of vector normal to specified plane
referencePoint the reference point of the helix
intersectionPoint to receive the coordinates of the intersection point
StatusCode pandora::Helix::GetPointInXY (const float x0, const float y0, const float ax, const float ay, const CartesianVector & referencePoint, CartesianVector & intersectionPoint, float & genericTime) const
Get helix intersection point with a plane parallel to z axis.
The plane is defined by two coordinates in the plane (x0,y0) and a normal vector (ax,ay).
Parameters
x0 x coordinate in the specified plane
y0 y coordinate in the specified plane
ax x component of vector normal to specified plane
ay y component of vector normal to specified plane
referencePoint the reference point of the helix
intersectionPoint to receive the coordinates of the intersection point
genericTime to receive the generic time (helix length, from reference point to intersection, divided by particle momentum)
References pandora::CartesianVector::GetX(), pandora::CartesianVector::GetY(), pandora::CartesianVector::GetZ(), and pandora::CartesianVector::SetValues().
StatusCode pandora::Helix::GetPointInZ (const float zPlane, const CartesianVector & referencePoint, CartesianVector & intersectionPoint) const inline
Get helix intersection point with a plane perpendicular to z axis.
Parameters
zPlane the z coordinate for the specified plane
referencePoint the reference point of the helix
intersectionPoint to receive the coordinates of the intersection point
StatusCode pandora::Helix::GetPointInZ (const float zPlane, const CartesianVector & referencePoint, CartesianVector & intersectionPoint, float & genericTime) const
Get helix intersection point with a plane perpendicular to z axis.
Parameters
zPlane the z coordinate for the specified plane
referencePoint the reference point of the helix
intersectionPoint to receive the coordinates of the intersection point
genericTime to receive the generic time (helix length, from reference point to intersection, divided by particle momentum)
References pandora::CartesianVector::GetX(), pandora::CartesianVector::GetY(), pandora::CartesianVector::GetZ(), and pandora::CartesianVector::SetValues().
StatusCode pandora::Helix::GetPointOnCircle (const float radius, const CartesianVector & referencePoint, CartesianVector & intersectionPoint) const inline
Get coordinates of helix intersection with cylinder, aligned along z-axis.
Parameters
radius the radius of the cylinder
referencePoint the reference point of the helix
intersectionPoint to receive the coordinates of the intersection point
Referenced by GetDistanceToHelix().
StatusCode pandora::Helix::GetPointOnCircle (const float radius, const CartesianVector & referencePoint, CartesianVector & intersectionPoint, float & genericTime) const
Get coordinates of helix intersection with cylinder, aligned along z-axis.
Parameters
radius the radius of the cylinder
referencePoint the reference point of the helix
intersectionPoint to receive the coordinates of the intersection point
genericTime to receive the generic time (helix length, from reference point to intersection, divided by particle momentum)
References pandora::CartesianVector::GetX(), pandora::CartesianVector::GetY(), pandora::CartesianVector::GetZ(), and pandora::CartesianVector::SetValues().
float pandora::Helix::GetPxy () const inline
Get transverse momentum of the track.
Returns
the transverse momentum of the track
Referenced by GetDistanceToHelix().
float pandora::Helix::GetRadius () const inline
Get radius of circumference.
Returns
the radius of circumference
Referenced by GetDistanceToHelix().
const CartesianVector & pandora::Helix::GetReferencePoint () const inline
Get reference point of track.
Returns
the reference point of track
Referenced by GetDistanceToHelix().
float pandora::Helix::GetTanLambda () const inline
Get tangent of dip angle of the track.
Returns
the tangent of dip angle of the track
float pandora::Helix::GetXCentre () const inline
Get x coordinate of circumference.
Returns
the x coordinate of circumference
Referenced by GetDistanceToHelix().
float pandora::Helix::GetYCentre () const inline
Get y coordinate of circumference.
Returns
the y coordinate of circumference
Referenced by GetDistanceToHelix().
float pandora::Helix::GetZ0 () const inline
Get z coordinate of the point of closest approach to IP in the R-Phi plane.
Returns
the z coordinate of the point of closest approach
The documentation for this class was generated from the following files:
Helix.h
Helix.cc