MarlinArbor: marlin_arbor::ArborPFAProcessor Class Reference
marlin_arbor::ArborPFAProcessor Class Reference
ArborPFAProcessor class.
#include <ArborPFAProcessor.h>
Classes
class Settings
Settings class.
Public Types
typedef std::vector< float > FloatVector
typedef std::vector< std::string > StringVector
Public Member Functions
ArborPFAProcessor ()
Default constructor.
virtual Processor * newProcessor ()
Create new processor.
virtual void init ()
Initialize, called at startup.
virtual void processRunHeader (lcio::LCRunHeader *pLCRunHeader)
Process run header.
virtual void processEvent (EVENT::LCEvent *pLCEvent)
Process event, main entry point.
virtual void check (EVENT::LCEvent *pLCEvent)
Checks for event.
virtual void end ()
End, called at shutdown.
const pandora::Pandora * GetPandora () const
Get address of the pandora instance.
Static Public Member Functions
static const EVENT::LCEvent * GetCurrentEvent (const pandora::Pandora *const pPandora)
Get address of the current lcio event.
Detailed Description
ArborPFAProcessor class.
Member Function Documentation
void marlin_arbor::ArborPFAProcessor::check (EVENT::LCEvent * pLCEvent) virtual
Checks for event.
Parameters
pLCEvent the lc event
const EVENT::LCEvent * marlin_arbor::ArborPFAProcessor::GetCurrentEvent (const pandora::Pandora *const pPandora) static
Get address of the current lcio event.
Parameters
pPandora address of the relevant pandora instance
Returns
address of the current lcio event
const pandora::Pandora * marlin_arbor::ArborPFAProcessor::GetPandora () const
Get address of the pandora instance.
Returns
address of the pandora instance
void marlin_arbor::ArborPFAProcessor::processEvent (EVENT::LCEvent * pLCEvent) virtual
Process event, main entry point.
Parameters
pLCEvent the lc event
References marlin_arbor::CaloHitCreator::CreateCaloHits(), marlin_arbor::MCParticleCreator::CreateCaloHitToMCParticleRelationships(), marlin_arbor::MCParticleCreator::CreateMCParticles(), marlin_arbor::PfoCreator::CreateParticleFlowObjects(), marlin_arbor::TrackCreator::CreateTrackAssociations(), marlin_arbor::TrackCreator::CreateTracks(), marlin_arbor::MCParticleCreator::CreateTrackToMCParticleRelationships(), marlin_arbor::CaloHitCreator::GetCalorimeterHitVector(), and marlin_arbor::TrackCreator::GetTrackVector().
void marlin_arbor::ArborPFAProcessor::processRunHeader (lcio::LCRunHeader * pLCRunHeader) virtual
Process run header.
Parameters
pLCRunHeader the lc run header
The documentation for this class was generated from the following files:
ArborPFAProcessor.h
ArborPFAProcessor.cc